#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=rsync
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-openssl-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for stage/configure/install
if [ "${HOST_PROCESSOR}" = "x86_64" ]; then
    CONFIGURE_SIMD_CMD="--enable-simd"
else
    CONFIGURE_SIMD_CMD="--disable-simd"
fi

CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
DISABLE_AUTOUPDATE=TRUE \
MAKECMDGOALS=reconfigure \
package-stage-configure-install \
    rsync_cv_HAVE_BROKEN_READDIR=no \
    --disable-md2man \
    ${CONFIGURE_SIMD_CMD}
