#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Build the components
cd ${SOURCE_ROOT}
package-python-build
package-python-build --project tensorflow-io-gcs-filesystem

# Build and install the package
package-invoke-archive-install
