#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
copy-source-to-staging

COMMON_LDFLAGS="\
    -L${PACKAGE_PREFIX}/lib \
    ${COMMON_LDFLAGS} \
" \
export-compiler-environment

TOOL_LOG=builder-invocation \
tool-log ${STAGE_ROOT}/Configure \
    -d \
    -e \
    -s \
    -Dar="${AR}" \
    -Das="${AS}" \
    -Dcc="${CC}" \
    -Dccflags="${CFLAGS}" \
    -Dcpp="${CPP}" \
    -Dcppflags="${CPPFLAGS}" \
    -Dcxx="${CXX}" \
    -Dcxxflags="${CXXFLAGS}" \
    -Dincpth=${PACKAGE_PREFIX}/include \
    -Dld="${CCLD}" \
    -Dldflags="${CCLDFLAGS}" \
    -Dloclibpth="${PACKAGE_PREFIX}/lib ${SYSROOT}/usr/lib" \
    -Dnm="${NM}" \
    -Dprefix=${PACKAGE_PREFIX} \
    -Dranlib="${RANLIB}" \
    -Dsiteprefix=${PACKAGE_PREFIX}/local \
    -Dsysroot=${SYSROOT} \
    -Dusrinc=${PACKAGE_PREFIX}/include \
    -Dvendorprefix=${PACKAGE_PREFIX}

# Build the components
make-install

# Build and install the package
package-invoke-archive-install