#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# spice-protocol build
package-invoke-builder spice-protocol-cross 0

if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "macos" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    # spice build
    package-invoke-builder spice-cross 0

    # virglrenderer build
    package-invoke-builder virglrenderer-cross 0
fi

# qemu build
package-invoke-builder qemu-cross 6

if [ "${HOST_OS}" = "gnu" ]; then
    if [ "${HOST_PROCESSOR}" = "armv7a" ] ||
       [ "${HOST_PROCESSOR}" = "i686" ]; then
        # box86 build
        package-invoke-builder box86-cross 0
    elif [ "${HOST_PROCESSOR}" = "aarch64" ] ||
         [ "${HOST_PROCESSOR}" = "x86_64" ]; then
        # box64 build
        package-invoke-builder box64-cross 0
    fi
fi