#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libsecret
export SOURCE_PACKAGE_VERSION=0.20.4

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-gcrypt \
    --disable-static \
    --enable-gtk-doc=no \
    --enable-gtk-doc-html=no \
    --enable-gtk-doc-pdf=no \
    --enable-introspection=no \
    --enable-shared

# Build the components
TARGETS=" " \
make-build

make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
