#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=grep
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
if [ "${HOST_OS}" = "mingw32" ]; then
    export COMMON_CFLAGS="\
        -pthread \
        ${COMMON_CFLAGS} \
    "
fi

GREP= \
package-bootstrap-configure-install-archive
