#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=perl-xml-parser
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
copy-source-to-staging
export-compiler-environment
generate-compiler-tools

${PERL} ${SOURCE_ROOT}/Makefile.PL
make-install \
    AR=${AR} \
    CC=${CC} \
    CCFLAGS="${CFLAGS}" \
    LD=${CCLD} \
    LDFLAGS="${CCLDFLAGS}" \
    OPTIMIZE="-O${OPTIMIZATION_LEVEL}" \
    PREFIX=${INSTALL_PREFIX} \
    RANLIB=${RANLIB}

# Build and install the package
package-invoke-archive-install
