#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=gnutls
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
BOOTSTRAP_FILE=./autogen.sh \
CFLAGS="\
    -UNDEBUG \
    ${CFLAGS} \
" \
package-bootstrap-configure-install \
    --disable-doc \
    --disable-static \
    --enable-shared