#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=zlib
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
function package-install-completion-callback() {
    ${MV} ${INSTALL_PREFIX}/share/pkgconfig \
          ${INSTALL_PREFIX}/lib/pkgconfig
}

PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-cmake-install-archive