#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=freetype2
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
package-cmake \
    -DBUILD_SHARED_LIBS=true \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build the package
deb-package-build

# Install the package
deb-package-install
