#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
package-cmake-install-archive \
    -DALSA_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DALSA_LIBRARY=`package-get-path asound SHARED HOST` \
    -DBUILD_EXAMPLES=FALSE \
    -DBUILD_PROGRAMS=TRUE \
    -DBUILD_REGTEST=FALSE \
    -DBUILD_SHARED_LIBS=TRUE \
    -DBUILD_TESTING=FALSE \
    -DPYTHON_EXECUTABLE=${PYTHON} \
    -DSQLite3_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DSQLite3_LIBRARY=`package-get-path sqlite3 SHARED HOST`
