#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=texinfo
export SOURCE_PACKAGE_VERSION=6

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
BOOTSTRAP_FILE=./autogen.sh \
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
package-bootstrap-configure-install-archive
