#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=tcl
export SOURCE_PACKAGE_VERSION=8

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

if [ "${HOST_OS}" = "macos" ]; then
    CONFIGURE_FILE_DIR=macosx
elif [ "${HOST_OS}" = "mingw32" ]; then
    CONFIGURE_FILE_DIR=win
else
    CONFIGURE_FILE_DIR=unix
fi

# Invoke one-shot template for stage/configure/install
CONFIGURE_FILE_ROOT=${STAGE_ROOT}/${CONFIGURE_FILE_DIR} \
package-stage-configure-install-archive
