#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install

COMMON_CFLAGS="\
    -L${PACKAGE_PREFIX}/lib \
    ${COMMON_CFLAGS} \
" \
CONFIGURE_FILE=autogen.sh \
package-configure-install-archive \
    ac_cv_gssapi_supports_spnego=yes \
    --disable-sample \
    --disable-static \
    --enable-shared \
    --with-gss_impl=mit