#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-cmark
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-llvm-project-13-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Invoke one-shot template for cmake/install
DISABLE_BUILD_DEB=TRUE \
DISABLE_INSTALL_DEB=TRUE \
package-cmake-install-archive
