#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=wine
export SOURCE_PACKAGE_VERSION=6

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
if [ "${HOST_TRIPLE}" != "${BUILD_TRIPLE}" ]; then
    CROSS_CMD="--with-wine-tools=${STAGE_ROOT_BASE}/${SOURCE_PACKAGE_NAME}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}"
fi

package-stage-configure-install \
    --disable-static \
    --enable-shared \
    --enable-win64 \
    ${CROSS_CMD}

# Build and install the package
package-invoke-artifact-install
