#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Build the components
cd ${STAGE_ROOT}
copy-source-to-staging
export-compiler-environment
make-install \
    prefix=${PACKAGE_PREFIX}

# Build and install the package
package-invoke-archive-install
