#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=egl-headers
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
${MKDIR} -p ${INSTALL_PREFIX}/include
package-rsync -ax \
              ${SOURCE_ROOT}/api/EGL \
              ${INSTALL_PREFIX}/include/

# Build the package
deb-package-build

# Install the package
deb-package-install
