#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-swift-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU}-${QUALIFIED_HOST_PROCESSOR} (>=1.0.0) \
"

if [ "${HOST_OS}" != "macos" ]; then
    export DEPENDS="\
        ${DEPENDS}, \
        ${PACKAGE_BASE_NAME}-swift-corelibs-foundation-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU}-${QUALIFIED_HOST_PROCESSOR} (>=1.0.0), \
        ${PACKAGE_BASE_NAME}-swift-corelibs-libdispatch-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU}-${QUALIFIED_HOST_PROCESSOR} (>=1.0.0) \
    "
fi

# Configure the build components
cd ${SOURCE_ROOT}

if [ "${HOST_OS}" = "android" ]; then
    export MAINLINE_BRANCH=val-verde-android-mainline
fi

SWIFT_BUILD_FLAGS="\
    -Xcxx -fno-modules \
    -Xlinker -lc++ \
    -Xlinker -licuucswift \
    -Xlinker -lm \
    -Xlinker -lunwind \
    ${SWIFT_BUILD_FLAGS} \
" \
package-swift-build

cd ${STAGE_ROOT}
${MKDIR} -p ${INSTALL_PREFIX}/bin
package-rsync -ax \
              `${FIND} release/baikonur* -executable -type f` \
              ${INSTALL_PREFIX}/bin

# RPATH fixups
RPATH_COMPONENTS="\
    ${INSTALL_PREFIX}/bin/baikonur \
" \
rpath-fixup

# Build and install the package
package-invoke-archive-install
