#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
if [ "${HOST_OS}" = "macos" ]; then
    ENABLE_OR_DISABLE_ASSEMBLY=disable
elif [ "${HOST_OS}" = "mingw32" ]; then
    if [ "${HOST_PROCESSOR}" = "x86_64" ]; then
        ENABLE_OR_DISABLE_ASSEMBLY=enable
    else
        ENABLE_OR_DISABLE_ASSEMBLY=disable
    fi
else
    ENABLE_OR_DISABLE_ASSEMBLY=enable
fi

DISABLE_AUTOUPDATE=TRUE \
GCC=yes \
GXX=yes \
package-stage-configure-install-archive \
    --${ENABLE_OR_DISABLE_ASSEMBLY}-assembly \
    --disable-static \
    --enable-shared
