#!/bin/bash

set -e


# Set all environment vars
export SOURCE_PACKAGE_NAME=zlib
export SOURCE_PACKAGE_VERSION=1.2.11

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}
package-cmake \
    ${SOURCE_ROOT}

# Build the components
ninja-install

${MV} ${INSTALL_PREFIX}/share/pkgconfig \
      ${INSTALL_PREFIX}/lib/pkgconfig

# Build the package
deb-package-build

# Install the package
deb-package-install
