#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libdb
export SOURCE_PACKAGE_VERSION=5

export DEPENDS="${PACKAGE_BASE_NAME}-gmp-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
CONFIGURE_FILE_ROOT=${STAGE_ROOT}/dist \
INSTALL_TARGET="install_include install_lib install_utilities" \
package-stage-configure-install \
    cross_compiling=yes \
    --disable-doc \
    --disable-static \
    --enable-shared