#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
BOOTSTRAP_ARGS="--force" \
DISABLE_AUTOUPDATE=TRUE \
package-bootstrap-configure-install-archive \
    --disable-doc \
    --disable-gtk-doc \
    --disable-gtk-doc-html \
    --disable-gtk-doc-pdf \
    --disable-static \
    --enable-shared
