#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=opencl-icd-loader
export SOURCE_PACKAGE_VERSION=2020
export PACKAGE_INSTALL_FLAG='build'

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
package-cmake \
    -DOPENCL_ICD_LOADER_DISABLE_OPENCLON12=TRUE

# Build the components
ninja-install

# Build and install the package
package-invoke-archive-install
