#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=gperf
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}

CXXFLAGS="\
    -std=c++11 \
    ${CXXFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure

# Build the components
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
