#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=dpkg
export SOURCE_PACKAGE_VERSION=1.20.5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-bzip2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-tar-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure

if [ "${BUILD_TRIPLE}" != "${HOST_TRIPLE}" ]; then
    CROSS_COMPILING=yes
else
    CROSS_COMPILING=no
fi

if [ "${HOST_OS}" = "android" ]; then
    ADMIN_DIR=/data/local/tmp
    CONFIGURE_HOST_KERNEL=unknown
elif [ "${HOST_OS}" = "mingw32" ]; then
    ADMIN_DIR=/
    CONFIGURE_HOST_KERNEL=unknown
else
    ADMIN_DIR=/var/lib/dpkg
    CONFIGURE_HOST_KERNEL=${HOST_KERNEL}
fi

cd ${STAGE_ROOT}
CONFIGURE_HOST_TRIPLE=${HOST_PROCESSOR}-${CONFIGURE_HOST_KERNEL}-gnu \
CXXFLAGS="\
    -std=c++14 \
    ${CXXFLAGS} \
" \
TAR=tar \
package-configure \
    ${SOURCE_ROOT}/configure \
    cross_compiling=${CROSS_COMPILING} \
    --disable-dselect \
    --with-admindir=${ADMIN_DIR}

# Build the components
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
