#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# spirv headers build
package-invoke-builder spirv-headers-cross 1

# spirv tools build
package-invoke-builder spirv-tools-cross 2020

# spirv cross build
package-invoke-builder spirv-cross-cross 2021

# spirv llvm translator build
package-invoke-builder spirv-llvm-translator-cross 12

# glslang build
package-invoke-builder glslang-cross 10-11

if [ "${HOST_OS}" = "macos" ]; then
    # moltenvk build
    package-invoke-builder moltenvk-cross 1
else
    # vulkan tools build
    package-invoke-builder vulkan-tools-cross 1
fi

# vulkan validation layers build
package-invoke-builder vulkan-validation-layers-cross 1

if [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "macos" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    # libclc build
    ENABLE_STAGE_ROOT_BUILD=TRUE \
    package-invoke-builder libclc-cross 13

    # mesa build
    package-invoke-builder mesa-cross 21
fi

if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "macos" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    # libepoxy build
    package-invoke-builder libepoxy-cross 1
fi

if [ "${HOST_OS}" = "macos" ]; then
    # libapplewm build
    package-invoke-builder libapplewm-cross 1
fi

if [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "macos" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    # xorg-xserver build
    package-invoke-builder xorg-xserver-cross 1

    # mesa glu build
    package-invoke-builder mesa-glu-cross 9

    # freeglut build
    package-invoke-builder freeglut-cross 3

    # glew build
    package-invoke-builder glew-cross 2

    # mesa demos build
    package-invoke-builder mesa-demos-cross 8
fi

# libsass build
package-invoke-builder libsass-cross

if [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "macos" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    # gtk build
    package-invoke-builder gtk-cross
fi

if [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    # mtdev build
    package-invoke-builder mtdev-cross

    # libgudev build
    package-invoke-builder libgudev-cross

    # libwacom build
    package-invoke-builder libwacom-cross

    # libevdev build
    package-invoke-builder libevdev-cross

    # libinput build
    package-invoke-builder libinput-cross

    # seatd build
    package-invoke-builder seatd-cross

    # wlroots build
    package-invoke-builder wlroots-cross

    # sway build
    package-invoke-builder sway-cross
fi

# sdl build
package-invoke-builder sdl-cross 2

# sdl-image build
package-invoke-builder sdl-image-cross 2

# sdl-mixer build
package-invoke-builder sdl-mixer-cross 2

# sdl-net build
package-invoke-builder sdl-net-cross 2

# sdl-ttf build
package-invoke-builder sdl-ttf-cross 2

# filament build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder filament-cross 1

if [ "{HOST_OS}" = "mingw32" ]; then
    # dxvk-cross build
    package-invoke-builder dxvk-cross 1
fi
