#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=argp-standalone
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
COMMON_CFLAGS="\
    -std=c89 \
    ${COMMON_CFLAGS} \
" \
package-stage-configure-install-archive \
    ac_cv_prog_cc_c11= \
    --disable-static \
    --enable-shared
