#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-kernel-builder
export SOURCE_ROOT=${SOURCE_ROOT_BASE}/linux-5

# Configure the build components
kernel-bootstrap-config

# Build and install the package
kernel-build headers_install
package-invoke-archive-install