#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=gettext
export SOURCE_PACKAGE_VERSION=0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for stage/configure/install
DEFAULT_VISIBILITY_HIDDEN=yes
WITH_INCLUDED_GETTEXT=yes

if [ "${HOST_OS}" = "gnu" ]; then
    WITH_INCLUDED_GETTEXT=no
elif [ "${HOST_OS}" = "macos" ]; then
    DEFAULT_VISIBILITY_HIDDEN=no
fi

if [ -n "${DISABLE_LIBXML2}" ]; then
    LIBXML2_CMD="--with-include-libxml"
else
    export DEPENDS="\
        ${PACKAGE_BASE_NAME}-libxml2-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
        ${DEPENDS} \
    "
fi

if [ -n "${DISABLE_XZ}" ]; then
    XZ_CMD="--without-xz"
fi

BOOTSTRAP_FILE=autogen.sh \
package-bootstrap-configure-install-archive \
    gl_cv_cc_visibility=${DEFAULT_VISIBILITY_HIDDEN} \
    gl_cv_type_wint_t_large_enough=yes \
    --with-included-gettext=${WITH_INCLUDED_GETTEXT} \
    ${LIBXML2_CMD} \
    ${XZ_CMD}
