#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-doc
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-swift-${SOURCE_PACKAGE_VERSION}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-swift-corelibs-foundation-${SOURCE_PACKAGE_VERSION}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
if [ "${HOST_OS}" = "android" ]; then
   SOURCE_ROOT=${SOURCE_ROOT}-android
else
   SOURCE_ROOT=${SOURCE_ROOT}
fi

# Build the components
cd ${SOURCE_ROOT}
package-swift-build

cd ${STAGE_ROOT}
${MKDIR} -p ${INSTALL_PREFIX}/bin
package-push-directory release
package-rsync -ax \
              `${FIND} -type f -name swift-doc\*` \
              ${INSTALL_PREFIX}/bin
package-pop-directory

# Build and install the package
package-invoke-archive-install
