#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
function package-install-completion-callback() {
    ${MKDIR} -p ${INSTALL_PREFIX}/bin
    ${CP} ${STAGE_ROOT}/jwasm* \
          ${INSTALL_PREFIX}/bin/
}

function tool-install-invocation() {
    return
}

PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
TOOL_INSTALL_INVOCATION=tool-install-invocation \
package-cmake-install-archive
