#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
CXX_STANDARD=14 \
package-cmake-install-archive \
    -Dopencv_core_lib=`package-get-path opencv_core SHARED HOST` \
    -Dopencv_imgproc_lib=`package-get-path opencv_imgproc SHARED HOST` \
    -Dopencv_videoio_lib=`package-get-path opencv_videoio SHARED HOST` \
    -Dpybind11_ROOT=${PACKAGE_PREFIX}/lib/python${PYTHON_VERSION}/site-packages/pybind11 \
    -DBoost_INCLUDE_DIRS=${PACKAGE_PREFIX}/include \
    -DBoost_LIBRARY_DIRS=${PACKAGE_PREFIX}/lib \
    -DBoost_LIBRARIES="-lboost_filesystem -lboost_thread" \
    -DBoost_VERSION=107700 \
    -DBOOST_CUSTOM=TRUE \
    -DBUILD_DOCS=FALSE \
    -DBUILD_ROBINMAP_FORCE=TRUE \
    -DBUILD_TESTING=FALSE \
    -DCOMPILER_SUPPORTS_ATOMIC_WITHOUT_LIBATOMIC_EXITCODE=0 \
    -DCOMPILER_SUPPORTS_ATOMIC_WITHOUT_LIBATOMIC_EXITCODE__TRYRUN_OUTPUT=0 \
    -DGIT_EXECUTABLE=${GIT} \
    -DOIIO_BUILD_TESTS=FALSE \
    -DPython_ROOT=${PACKAGE_PREFIX} \
    -DPYTHON=${PYTHON} \
    -DPYTHON_VERSION=${PYTHON_VERSION} \
    -DRT_LIBRARY=`package-get-path rt SHARED HOST` \
    -DUSE_PYTHON=FALSE
