#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libpng
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
package-cmake-install-archive \
    -DAWK=${GAWK} \
    -DPNG_ARM_NEON=on