#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libsecret
export SOURCE_PACKAGE_VERSION=0.20.4

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${SOURCE_ROOT}
package-meson-build \
    -Dgcrypt=false \
    -Dgtk_doc=false \
    -Dintrospection=false \
    -Dmanpages=false

# Build the components
cd ${STAGE_ROOT}
ninja-build

# Build the package
deb-package-build

# Install the package
deb-package-install
