#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=attr
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
BOOTSTRAP_FILE=./autogen.sh \
package-bootstrap-configure-install-archive
