#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=glibc-headers
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
SOURCE_ROOT=${SOURCE_ROOT_BASE}/glibc-${SOURCE_PACKAGE_VERSION}
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

copy-source-to-staging

# Configure the build components
cd ${STAGE_ROOT}

package-autoupdate
package-autoreconf -fi

${MKDIR} -p ${STAGE_ROOT}/build

cd ${STAGE_ROOT}/build
package-configure \
    ${STAGE_ROOT}/configure \
    libc_cv_gcc_builtin_redirection=yes

# Build the components
INSTALL_TARGET=install-headers \
make-install

# Build and install the package
package-invoke-artifact-install
