#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
copy-source-to-staging
export-compiler-environment

TOOL_LOG=builder-bootstrap \
tool-log ${PERL} ${STAGE_ROOT}/Makefile.PL \
    PREFIX=${PACKAGE_PREFIX}

INSTALL_TARGET=pure_install \
make-install

# Build and install the package
package-invoke-archive-install