#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=acl
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-attr-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Invoke one-shot template for bootstrap/configure/install
BOOTSTRAP_FILE=./autogen.sh \
package-bootstrap-configure-install-archive
