#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
package-cmake-install-archive \
    -Dgflags_DIR=${PACKAGE_PREFIX}/lib/cmake/gflags \
    -Dglog_DIR=${PACKAGE_PREFIX}/lib/cmake/glog \
    -DBUILD_BENCHMARKS=FALSE \
    -DBUILD_DOCUMENTATION=FALSE \
    -DBUILD_EXAMPLES=FALSE \
    -DBUILD_SHARED_LIBS=TRUE \
    -DBUILD_TESTING=FALSE \
    -DCUDA=FALSE \
    -DLIB_SUFFIX=