#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-swift-${SOURCE_PACKAGE_VERSION}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

if [ "${HOST_OS}" != "macos" ]; then
    export DEPENDS="\
        ${DEPENDS}, \
        ${PACKAGE_BASE_NAME}-swift-corelibs-foundation-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
        ${PACKAGE_BASE_NAME}-swift-corelibs-libdispatch-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
    "
fi

# Build the components
cd ${SOURCE_ROOT}

if [ "${HOST_OS}" = "macos" ]; then
    LIBTOOL=`package-get-path llvm-ar EXECUTABLE BUILD`
    USE_GNU_OVER_DARWIN_LIBTOOL=TRUE
fi

SWIFT_BUILD_FLAGS="\
    -Xlinker -lc++ \
    -Xlinker -licuucswift \
    -Xlinker -lncurses \
    ${SWIFT_BUILD_FLAGS} \
" \
SWIFTPM_USE_SWIFT_CRYPTO_V2=TRUE \
package-swift-build

cd ${STAGE_ROOT}
${MKDIR} -p ${INSTALL_PREFIX}/bin
package-rsync -ax \
              `${FIND} -type f -name sourcekit-lsp\*` \
              ${INSTALL_PREFIX}/bin

# Build and install the package
package-invoke-archive-install