#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# cython build
package-invoke-builder cython-cross

# pybind11 build
package-invoke-builder pybind11-cross

# pygments build
package-invoke-builder pygments-cross

# pyparsing build
package-invoke-builder pyparsing-cross

# python-jinja build
package-invoke-builder python-jinja-cross

# python-six build
package-invoke-builder python-six-cross

# python-toml build
package-invoke-builder python-toml-cross

# numpy build
package-invoke-builder numpy-cross

# mako build
package-invoke-builder mako-cross

# meson build
package-invoke-builder meson-cross
