#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=pcre
export SOURCE_PACKAGE_VERSION=8

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

copy-source-to-staging

# Configure the build components
cd ${STAGE_ROOT}
package-autoreconf -fi

sed -i \
    "s/'auto-import'/'ld'/g" \
    ${STAGE_ROOT}/configure

if [ "${HOST_OS}" = "mingw32" ]; then
    sed -i \
        "s/-nostdlib//g" \
        ${STAGE_ROOT}/configure
fi

package-configure \
    ${STAGE_ROOT}/configure \
    --disable-static \
    --enable-shared

# Build the components
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
