#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-glib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

# Invoke one-shot template for bootstrap/configure/install
CONFIGURE_FILE=autogen.sh \
package-configure-install-archive \
    ac_cv_func_posix_getgrgid_r=yes \
    ac_cv_func_posix_getpwuid_r=yes \
    glib_cv_stack_grows=no \
    glib_cv_uscore=no \
    --disable-define-prefix \
    --disable-host-tool \
    --with-libiconv=gnu