#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# remove host foundation and libdispatch to avoid module collisions
PACKAGE_ACTION=UNINSTALL
PACKAGES_TO_MANAGE=( 'swift-argument-parser-5'         'BUILD' \
                     'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-libdispatch-5'    'BUILD' \
                     'swift-corelibs-xctest-5'         'BUILD' \
                     'swift-crypto-5'                  'BUILD' \
                     'swift-driver-5'                  'BUILD' \
                     'swift-llbuild-5'                 'BUILD' \
                     'swift-package-manager-5'         'BUILD' \
                     'swift-tools-support-core-5'      'BUILD' \
                     'yams-3'                          'BUILD' )
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

if [ "${HOST_OS}" = "macos" ]; then
    # libdispatch build
    package-invoke-builder swift-corelibs-libdispatch-darwin

    # foundation build
    package-invoke-builder swift-corelibs-foundation-darwin
else
    # libdispatch build
    package-invoke-builder swift-corelibs-libdispatch-cross

    # foundation build
    package-invoke-builder swift-corelibs-foundation-cross
fi

# xctest build
package-invoke-builder swift-corelibs-xctest-cross

# reinstall swiftpm for build and host
PACKAGE_ACTION=INSTALL
PACKAGES_TO_MANAGE=( 'swift-argument-parser-5'         'BUILD' \
                     'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-libdispatch-5'    'BUILD' \
                     'swift-corelibs-xctest-5'         'BUILD' \
                     'swift-crypto-5'                  'BUILD' \
                     'swift-driver-5'                  'BUILD' \
                     'swift-llbuild-5'                 'BUILD' \
                     'swift-package-manager-5'         'BUILD' \
                     'swift-tools-support-core-5'      'BUILD' \
                     'yams-3'                          'BUILD' \
                     'swift-corelibs-foundation-5'     'HOST' \
                     'swift-corelibs-libdispatch-5'    'HOST' \
                     'swift-corelibs-xctest-5'         'HOST' )
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# swift argument parser build
package-invoke-builder swift-argument-parser-cross

# swift package manager build
package-invoke-builder swift-package-manager-cross
