#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-cmark
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-llvm-project-12-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
cd ${STAGE_ROOT}
package-cmake \
    ${SOURCE_ROOT}

# Build the components
ninja-install
