#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=jwasm
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}

package-cmake \
    ${SOURCE_ROOT}

# Build the components
ninja-build

${MKDIR} -p ${INSTALL_PREFIX}/bin
${CP} ${STAGE_ROOT}/jwasm* \
      ${INSTALL_PREFIX}/bin/

# Build and install the package
package-invoke-artifact-install
