#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=pkg-config
export SOURCE_PACKAGE_VERSION=0.29.2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-glib-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
copy-source-to-staging

sed -i \
    "s/'auto-import'/'ld'/g" \
    ${STAGE_ROOT}/configure

cd ${STAGE_ROOT}
package-configure \
    ${STAGE_ROOT}/configure \
    ac_cv_func_posix_getgrgid_r=yes \
    ac_cv_func_posix_getpwuid_r=yes \
    glib_cv_stack_grows=no \
    glib_cv_uscore=no \
    --with-libiconv=gnu

# Build the components
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
