#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
CONFIGURE_FILE=autogen.sh \
package-configure-install-archive \
    --enable-malloc0returnsnull \
    --disable-static \
    --enable-shared
