#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=gawk
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Invoke one-shot template for stage/configure/install
DISABLE_AUTOUPDATE=TRUE \
DISABLE_TOOL_BUILD=TRUE \
INSTALL_TARGET="AM_CFLAGS= install" \
package-stage-configure-install-archive
