#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=openssl
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment
generate-compiler-tools

# Configure the build components
cd ${STAGE_ROOT}

OPENSSL_DIR=/etc/ssl
OPENSSL_OS=${HOST_OS}
OPENSSL_PROCESSOR=${HOST_PROCESSOR}

if [ "${HOST_OS}" = "android" ]; then
    OPENSSL_DIR=/data/local/tmp${PACKAGE_PREFIX}/etc/ssl
    OPENSSL_OS=linux
elif [ "${HOST_OS}" = "gnu" ] || \
     [ "${HOST_OS}" = "musl" ]; then
    OPENSSL_OS=linux
elif [ "${HOST_OS}" = "macos" ]; then
    OPENSSL_OS=darwin64

    if [ "${HOST_PROCESSOR}" = "aarch64" ]; then
        OPENSSL_PROCESSOR=arm64
    fi
elif [ "${HOST_OS}" = "mingw32" ]; then
    OPENSSL_DIR=${PACKAGE_PREFIX}/etc/ssl
fi

OPENSSL_TARGET=${OPENSSL_OS}-${OPENSSL_PROCESSOR}

if [ "${HOST_OS}" = "macos" ]; then
    OPENSSL_TARGET=${OPENSSL_TARGET}-cc
elif [ "${HOST_OS}" = "mingw32" ]; then
    OPENSSL_TARGET=mingw64
fi

TOOL_LOG=${STAGE_ROOT}/builder-invocation \
tool-log ${SOURCE_ROOT}/Configure \
    --libdir=${PACKAGE_PREFIX}/lib \
    --openssldir=${OPENSSL_DIR} \
    --prefix=${PACKAGE_PREFIX} \
    ${OPENSSL_DEFINES} \
    ${OPENSSL_TARGET}

# Build the components
make-build

INSTALL_TARGET="install_sw install_ssldirs" \
make-install

# Build and install the package
package-invoke-archive-install
