#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=wayland-protocols
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
copy-source-to-staging

cd ${STAGE_ROOT}
package-configure \
    ${STAGE_ROOT}/autogen.sh \
    --disable-static \
    --enable-shared

# Build the components
make-install

${MKDIR} -p ${INSTALL_PREFIX}/lib
${MV} ${INSTALL_PREFIX}/share/pkgconfig \
      ${INSTALL_PREFIX}/lib/pkgconfig

# Build the package
deb-package-build

# Build the package
deb-package-install
