#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=python-numpy
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Build the components
cd ${SOURCE_ROOT}
NUMPY_VERSION="1.21.2" \
package-python-build

# Build and install the package
package-invoke-archive-install
