#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=guile
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-libunistring-0-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-gc-8-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for bootstrap/configure/install
BOOTSTRAP_FILE=./autogen.sh \
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
package-bootstrap-configure-install \
    --disable-static \
    --enable-shared