#!/bin/bash

set -e

# Source package build helper functions
SOURCE_ROOT=${SOURCE_ROOT_BASE}/openldap-${SOURCE_PACKAGE_VERSION}/libraries/liblmdb
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Build the components
copy-source-to-staging
export-compiler-environment

cd ${STAGE_ROOT}
make-install \
    prefix=${PACKAGE_PREFIX} \
    CC=${CC} \
    LDFLAGS="${CCLDFLAGS}" \
    XCFLAGS="${CFLAGS}"

# Build and install the package
package-invoke-archive-install