#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=util-linux
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for configure/install
DISABLE_AUTOUPDATE=TRUE \
package-configure-install \
    ac_cv_func_setns=yes \
    ac_cv_func_unshare=yes \
    ac_cv_prog_ac_ct_NCURSES6_CONFIG= \
    --disable-all-programs \
    --disable-bash-completion \
    --disable-static \
    --enable-libblkid \
    --enable-libmount \
    --enable-libuuid \
    --enable-shared
