#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
if [ "${HOST_OS}" = "mingw" ]; then
    COMMON_CFLAGS="\
        -fms-extensions \
        ${COMMON_CFLAGS} \
    "
fi

package-cmake-install-archive \
    -DENABLE_QRENDERDOC=FALSE \
    -DENABLE_PYRENDERDOC=FALSE