#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=glib
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

if [ "${HOST_OS}" = "gnu" ]; then
    ICONV_LIB=libc
else
    ICONV_LIB=external
fi

if [ "${HOST_OS}" != "mingw32" ]; then
    export DEPENDS="\
        ${PACKAGE_BASE_NAME}-util-linux-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
        ${DEPENDS} \
    "
fi

# Configure the build components
cd ${SOURCE_ROOT}
package-meson-build \
    -Diconv=${ICONV_LIB}

# Build the components
cd ${STAGE_ROOT}
ninja-install

# Build and install the package
package-invoke-archive-install
