#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=mpfr
export SOURCE_PACKAGE_VERSION=4

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
package-stage-configure-install \
    --disable-static \
    --enable-shared
