#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=zip
export SOURCE_PACKAGE_VERSION=30

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export-compiler-environment
generate-compiler-tools

# Configure the build components
if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    PLATFORM=unix
elif [ "${HOST_OS}" = "mingw32" ]; then
    PLATFORM=win32
fi

# Build the components
copy-source-to-staging

cd ${STAGE_ROOT}
${MAKE} \
    -f ${STAGE_ROOT}/${PLATFORM}/Makefile \
    prefix=${INSTALL_PREFIX} \
    CC=${CC} \
    install

# Build the package
deb-package-build

# Install the package
deb-package-install
