#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=icu4c
export SOURCE_PACKAGE_VERSION=68

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
CONFIGURE_FILE_ROOT=${STAGE_ROOT}/${SOURCE_PACKAGE_NAME}/source \
RPATH_COMPONENTS="\
    ${INSTALL_PREFIX}/lib/libicudataswift.so \
    ${INSTALL_PREFIX}/lib/libicui18nswift.so \
    ${INSTALL_PREFIX}/lib/libicuioswift.so \
    ${INSTALL_PREFIX}/lib/libicuucswift.so \
" \
package-stage-configure-install \
    --disable-extras \
    --disable-samples \
    --disable-static \
    --disable-tests \
    --disable-tools \
    --enable-shared \
    --with-cross-build=${STAGE_ROOT_BASE}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}/build \
    --with-library-suffix=swift