#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=xxhash
export SOURCE_PACKAGE_VERSION=0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
copy-source-to-staging
export-compiler-environment

SYSTEM=Linux

if [ "${HOST_OS}" = "macos" ]; then
    SYSTEM=Darwin
fi

make-install \
    AR=${AR} \
    CC=${CC} \
    CFLAGS="${CCLDFLAGS}" \
    LD=${CCLD} \
    LDFLAGS="-shared" \
    PREFIX=${PACKAGE_PREFIX} \
    RANLIB=${RANLIB} \
    UNAME=${SYSTEM}

# Build and install the package
package-invoke-archive-install
