#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Determine source branch
if [ "${HOST_OS}" = "mingw32" ]; then
    SOURCE_ROOT=${SOURCE_ROOT}-windows
else
    SOURCE_ROOT=${SOURCE_ROOT}
fi

# Configure the build components
cd ${STAGE_ROOT}
copy-source-to-staging
export-compiler-environment
make-install \
    AR=${AR} \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    LD=${CCLD} \
    LDFLAGS="${CCLDFLAGS}" \
    PREFIX=${INSTALL_PREFIX} \
    RANLIB=${RANLIB}

${MKDIR} -p ${INSTALL_PREFIX}/lib/pkgconfig
${ECHO} "
V=${SOURCE_PACKAGE_VERSION}
R=${SOURCE_PACKAGE_VERSION}

prefix=${PACKAGE_PREFIX}
INSTALL_INC=\${prefix}/include
INSTALL_LIB=\${prefix}/lib
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: bzip2
Description: bzip2 is a freely available, patent free (see below), high-quality data compressor.
Version: \${R}
Requires:
Libs: -L\${libdir} -lbz2
Cflags: -I\${includedir}
" > ${INSTALL_PREFIX}/lib/pkgconfig/bzip2.pc

# Build and install the package
package-invoke-archive-install
