#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=mesa
export SOURCE_PACKAGE_VERSION=20.3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment

export LLVM_NATIVE_STAGE_ROOT=${LLVM_NATIVE_STAGE_ROOT:-${STAGE_ROOT_BASE}/llvm-project-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}}

# Configure the build components
cd ${SOURCE_ROOT}
MESON_EXTRA_BINARIES="\
llvm-config = '${LLVM_NATIVE_STAGE_ROOT}/bin/llvm-config'
" \
package-meson-build \
    -Ddri-drivers= \
    -Dgallium-drivers="d3d12,freedreno,iris,lima,panfrost,nouveau,radeonsi,svga,swr,swrast,v3d,vc4,virgl,zink" \
    -Dgallium-nine=true \
    -Dgallium-opencl=disabled \
    -Dgallium-spirv=true \
    -Dglvnd=false \
    -Dglx=disabled \
    -Dllvm=enabled \
    -Dopencl-native=false \
    -Dplatforms="wayland" \
    -Dprefix=${PACKAGE_PREFIX} \
    -Dosmesa=true \
    -Dshared-llvm=enabled \
    -Dshared-swr=true \
    -Dvulkan-drivers="amd,broadcom,freedreno,intel,swrast" \
    -Dzstd=enabled

# Build the components
cd ${STAGE_ROOT}
ninja-install

# Build the package
deb-package-build

# Build the package
deb-package-install
