#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libtool
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
BOOTSTRAP_ARGS="\
    --force \
    --skip-git \
    --gnulib-srcdir=${STAGE_ROOT}/glib \
" \
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
ENABLE_GNULIB_OVERRIDE=TRUE \
package-bootstrap-configure-install
