#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libatomic-ops
export SOURCE_PACKAGE_VERSION=7

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
BOOTSTRAP_FILE=./autogen.sh \
package-bootstrap-configure-install \
    --disable-static \
    --enable-shared

# Build the components
make-install

# Build the package
deb-package-build

# Build the package
deb-package-install