#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=make
export SOURCE_PACKAGE_VERSION=4
export GNULIB_SRCDIR=${SOURCE_ROOT_BASE}/gnulib-0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
if [ "${HOST_OS}" = "mingw32" ]; then
    MAKE_FS_CMD="--enable-case-insensitive-file-system"
fi

# Invoke one-shot template for bootstrap/configure/install
package-bootstrap-configure-install-archive \
    "${MAKE_FS_CMD}"
