#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=m4
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
copy-source-to-staging

if [ "${HOST_OS}" = "gnu" ]; then
    export CFLAGS=`${ECHO} "\
        -D_IO_ftrylockfile=1 \
        -D_IO_IN_BACKUP=0x100 \
        ${CFLAGS} \
    " | ${XARGS}`
fi

cd ${STAGE_ROOT}
package-autoreconf -fi
package-configure \
    ${STAGE_ROOT}/configure

sed -i \
    "s|define _FORTIFY_SOURCE 2|define _FORTIFY_SOURCE 0|g" \
    ${STAGE_ROOT}/lib/config.h

# Build the components
make-install \
    HELP2MAN=${HELP2MAN}

# Build the package
deb-package-build

# Install the package
deb-package-install
