#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
package-cmake-install-archive \
    -DGETTEXT_MSGFMT_EXECUTABLE=`package-get-path msgfmt EXECUTABLE BUILD` \
    -DGETTEXT_MSGMERGE_EXECUTABLE=`package-get-path msgmerge EXECUTABLE BUILD` \
    -DPYTHON_DESIRED="3" \
    -DPYTHON_EXECUTABLE=${PYTHON} \
    -DWITH_MAN=0
