#!/bin/bash

set -x -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-argument-parser
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Build the components
cd ${SOURCE_ROOT}
package-swift-build

if [ "${HOST_OS}" = "gnu" ]; then
    SDK_PLATFORM_DIR="linux"
elif [ "${HOST_OS}" = "macos" ]; then
    SDK_PLATFORM_DIR="macosx"
elif [ "${HOST_OS}" = "mingw32" ]; then
    SDK_PLATFORM_DIR="windows"
else
    SDK_PLATFORM_DIR=${HOST_OS}
fi

cd ${STAGE_ROOT}
${MKDIR} -p ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/
package-rsync -ax \
              release/*.swiftdoc \
              ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/
package-rsync -ax \
              release/*.swiftmodule \
              ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/
package-rsync -ax \
              release/`package-get-filename ArgumentParser SHARED HOST` \
              ${INSTALL_PREFIX}/lib/

# Build and install the package
package-invoke-archive-install
