#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=apt
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-gnutls-3-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
HAVE_LIBC_RESOLV=TRUE

if [ "${HOST_OS}" = "gnu" ]; then
    HAVE_LIBC_RESOLV=FALSE
    RESOLV_LIBRARIES=`package-get-path resolv SHARED HOST`
    SYSTEMD_INCLUDE_DIRS=${PACKAGE_PREFIX}/include
    SYSTEMD_LIBRARIES=`package-get-path systemd SHARED HOST`
    UDEV_INCLUDE_DIRS=${PACKAGE_PREFIX}/include
    UDEV_LIBRARIES=`package-get-path udev SHARED HOST`
fi

package-cmake-install-archive \
    -DCONF_DIR=/etc/apt \
    -DCACHE_DIR=/var/cache/apt \
    -DHAVE_LIBC_RESOLV=${HAVE_LIBC_RESOLV} \
    -DLOG_DIR=/var/log/apt \
    -DRESOLV_LIBRARIES=${RESOLV_LIBRARIES} \
    -DSTATE_DIR=/var/lib/apt \
    -DSYSTEMD_INCLUDE_DIRS=${SYSTEMD_INCLUDE_DIRS} \
    -DSYSTEMD_LIBRARIES=${SYSTEM_LIBRARIES} \
    -DTRIEHASH_EXECUTABLE=${SOURCE_ROOT_BASE}/triehash-0/triehash.pl \
    -DUDEV_INCLUDE_DIRS=${UDEV_INCLUDE_DIRS} \
    -DUDEV_LIBRARIES=${UDEV_LIBRARIES} \
    -DWITH_DOC=FALSE \
    -DWITH_TESTS=FALSE