#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=xxhash
export SOURCE_PACKAGE_VERSION=0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment
generate-compiler-tools

# Configure the build components
copy-source-to-staging

# Build the components
SYSTEM=Linux

if [ "${HOST_OS}" = "macos" ]; then
    SYSTEM=Darwin
fi

cd ${STAGE_ROOT}
make-install \
    AR=${AR} \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    LD=${CCLD} \
    LDFLAGS="-shared ${CCLDFLAGS}" \
    PREFIX=${PACKAGE_PREFIX} \
    RANLIB=${RANLIB} \
    UNAME=${SYSTEM}

# Build and install the package
package-invoke-archive-install
