#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
ENABLE_GLX=true
ENABLE_LOGIND=false
ENABLE_UDEV=false

if [ "${HOST_OS}" = "gnu" ]; then
    ENABLE_UDEV=true
elif [ "${HOST_OS}" = "musl" ]; then
    ENABLE_UDEV=true
fi

MIGCC=${STAGE_ROOT}/host-clang \
package-meson-install-archive \
    -Dapple-applications-dir=${PACKAGE_PLATFORM_SYSROOT}/System/Applications \
    -Dglx=${ENABLE_GLX} \
    -Dsecure-rpc=false \
    -Dsystemd_logind=${ENABLE_LOGIND} \
    -Dudev=${ENABLE_UDEV} \
    -Dudev_kms=${ENABLE_UDEV}
