#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libuv
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd ${STAGE_ROOT}

if [ "${HOST_OS}" = "android" ]; then
    FORCE_ANDROID_CMD="-DFORCE_ANDROID=TRUE"
fi

package-cmake \
    -DBUILD_TESTING=FALSE \
    ${FORCE_ANDROID_CMD} \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build and install the package
package-invoke-artifact-install
