#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
${TOUCH} \
     ${STAGE_ROOT}/nasm.1 \
     ${STAGE_ROOT}/ndisasm.1

BOOTSTRAP_FILE=autogen.sh \
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
DISABLE_AUTOUPDATE=TRUE \
package-bootstrap-configure-install-archive