#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=isl
export SOURCE_PACKAGE_VERSION=0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
package-stage-configure-install \
    ac_cv_have_decl_ffs=yes \
    --disable-static \
    --enable-shared
