#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=gmp
export SOURCE_PACKAGE_VERSION=6

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
if [ "${HOST_OS}" = "macos" ]; then
    ENABLE_OR_DISABLE_ASSEMBLY=disable
else
    ENABLE_OR_DISABLE_ASSEMBLY=enable
fi

DISABLE_AUTOUPDATE=TRUE \
GCC=yes \
GXX=yes \
package-stage-configure-install-archive \
    --${ENABLE_OR_DISABLE_ASSEMBLY}-assembly \
    --disable-static \
    --enable-shared