#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

# Configure the build components
if [ "${HOST_OS}" = "android" ]; then
    FORCE_ANDROID_CMD="-DFORCE_ANDROID=TRUE"
elif [ "${HOST_OS}" = "mingw32" ]; then
    COMMON_CFLAGS="\
        -fms-extensions \
        ${COMMON_CFLAGS} \
    "
fi

package-cmake-install-archive \
    -DBUILD_TESTING=FALSE \
    ${FORCE_ANDROID_CMD}
