#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
function package-install-completion-callback() {
    ${MKDIR} -p ${INSTALL_PREFIX}/lib/cmake
    ${LN} -sf \
          ${INSTALL_PREFIX}/share/cmake/Modules/FindLibSolv.cmake \
          ${INSTALL_PREFIX}/lib/cmake/LibSolvConfig.cmake
}

PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-cmake-install-archive \
    -DENABLE_COMPLEX_DEPS=TRUE \
    -DENABLE_RPMDB=TRUE \
    -DENABLE_RPMMD=TRUE
