#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-lua-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-popt-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for configure/install
ENABLE_OR_DISABLE_DBUS=enable

if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    LIBS="\
        -lintl \
        ${LIBS} \
    "
fi

CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
CONFIGURE_FILE=autogen.sh \
DBUS_CFLAGS="-I${PACKAGE_PREFIX}/include/dbus-1.0 -I${PACKAGE_PREFIX}/lib/dbus-1.0/include" \
DBUS_LDFLAGS="-L${PACKAGE_PREFIX}/lib" \
DBUS_LIBS="-ldbus-1" \
DISABLE_AUTOUPDATE=TRUE \
package-configure-install-archive \
    --disable-static \
    --enable-shared \
    --${ENABLE_OR_DISABLE_DBUS}-dbus
