#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=pixman
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${SOURCE_ROOT}
package-meson-build \
    -Dtests=disabled

# Build the components
cd ${STAGE_ROOT}
ninja-build

# Build the package
deb-package-build

# Build the package
deb-package-install
