#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libcap
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment
generate-compiler-tools

# Configure the build components
copy-source-to-staging

cd ${STAGE_ROOT}

# Build the components
INSTALL_TARGET=`${ECHO} "\
    lib=lib \
    prefix=${INSTALL_PREFIX} \
    AR=${AR} \
    BUILD_CC=${BUILD_CC} \
    BUILD_COPTS="-O${OPTIMIZATION_LEVEL}" \
    BUILD_GPERF=${GPERF} \
    CC=${CC} \
    COPTS="-O${OPTIMIZATION_LEVEL}" \
    DYNAMIC=yes \
    GOLANG=yes \
    INDENT=${INDENT} \
    KERNEL_HEADERS=${PACKAGE_PREFIX}/include/uapi \
    PSXLINKFLAGS=-pthread \
    SYSTEM_HEADERS=${PACKAGE_PREFIX}/include \
    TESTS=no \
    install \
" | ${XARGS}` \
make-install \
    CFLAGS="${CFLAGS}" \
    LDFLAGS="${LDFLAGS}"

# Build and install the package
package-invoke-archive-install
