#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=re2c
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
package-cmake \
    -DBISON_EXECUTABLE=${BISON} \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build and install the package
package-invoke-archive-install