#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libmicrohttpd
export SOURCE_PACKAGE_VERSION=0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

if [ "${HOST_OS}" = "mingw32" ]; then
    ENABLE_OR_DISABLE_SHARED=disable
else
    ENABLE_OR_DISABLE_SHARED=enable
fi

# Invoke one-shot template for stage/configure/install
DISABLE_AUTOUPDATE=TRUE \
package-stage-configure-install-archive \
    --${ENABLE_OR_DISABLE_SHARED}-shared

