#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=mesa-demos
export SOURCE_PACKAGE_VERSION=8

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
package-cmake-install-archive \
    -DGLUT_glu_LIBRARY=`package-get-path glu SHARED HOST` \
    -DGLUT_glut_LIBRARY=`package-get-path glut SHARED HOST` \
    -DGLUT_INCLUDE_DIR=${PACKAGE_PREFIX}/include