#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=sed
export SOURCE_PACKAGE_VERSION=4

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-acl-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
cd ${STAGE_ROOT}

package-configure \
    ${SOURCE_ROOT}/configure

# Build the components
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
