#!/bin/bash

set -e

export SOURCE_ROOT=${SOURCE_ROOT_BASE}/egl-registry-1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
${MKDIR} -p ${INSTALL_PREFIX}/include
package-rsync -ax \
              ${SOURCE_ROOT}/api/KHR \
              ${INSTALL_PREFIX}/include/

# Build and install the package
package-invoke-archive-install
