#!/bin/bash

set -e

export SOURCE_ROOT=${SOURCE_ROOT_BASE}/linux-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-kernel-builder

# Configure the build components
${MKDIR} -p ${INSTALL_ROOT}/${PACKAGE_PLATFORM_SYSROOT}/boot

kernel-bootstrap-config
kernel-build all
kernel-build modules_install
kernel-build install

# Build and install the package
package-invoke-archive-install