#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
package-bootstrap-configure-install-archive \
    gl_cv_warn_c__Werror=no
