#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    LIBS="\
        -lintl \
        ${LIBS} \
    "
fi

DISABLE_AUTOUPDATE=TRUE \
SOURCE_ROOT=${SOURCE_ROOT}/src \
package-stage-configure-install-archive \
    ac_cv_func_regcomp=yes \
    ac_cv_printf_positional=yes \
    krb5_cv_attr_constructor_destructor=yes,yes \
    --disable-static \
    --enable-shared \
    --with-tcl=${PACKAGE_PREFIX}
