#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libedit
export SOURCE_PACKAGE_VERSION=20191231-3.1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure

cd ${STAGE_ROOT}
CFLAGS="\
    -D__STDC_ISO_10646__=201103L \
    -DNBBY=CHAR_BIT \
    -I${PACKAGE_PREFIX}/include/ncurses \
    ${CFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-static \
    --enable-shared

# Build the components
make-install

# RPATH fixups
COMPONENTS="\
    ${INSTALL_PREFIX}/lib/libedit.so \
" \
rpath-fixup

# Build the package
deb-package-build

# Install the package
deb-package-install
