#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=git
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-curl-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-expat-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-pcre-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

if [ "${HOST_OS}" != "android" ]; then
    NEEDS_LIBRT=1
fi

# Configure the build components
copy-source-to-staging

cd ${STAGE_ROOT}
package-autoreconf -fi
package-configure \
    ${STAGE_ROOT}/configure \
    ac_cv_fread_reads_directories=true \
    ac_cv_iconv_omits_bom=true \
    ac_cv_snprintf_returns_bogus=false \
    --with-curl=${PACKAGE_PREFIX} \
    --with-expat=${PACKAGE_PREFIX} \
    --with-openssl=${PACKAGE_PREFIX}

# Build the components
make-install NEEDS_LIBRT=${NEEDS_LIBRT}

# Build the package
deb-package-build

# Install the package
deb-package-install
