#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=lz4
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export-compiler-environment
generate-compiler-tools

# Configure the build components
copy-source-to-staging

# Build the components
if [ "${HOST_OS}" = "mingw32" ]; then
    TARGET_OS=Windows
else
    TARGET_OS=Linux
fi

cd ${STAGE_ROOT}
${MAKE} \
    AR=${AR} \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    PREFIX=${INSTALL_PREFIX} \
    RANLIB=${RANLIB} \
    TARGET_OS=${TARGET_OS} \
    WINDRES=${WINDRES} \
    install

# Build the package
deb-package-build

# Install the package
deb-package-install
