#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=cups
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
if [ "${HOST_OS}" = "gnu" ]; then
    ENABLE_OR_DISABLE_SYSTEMD=enable
else
    ENABLE_OR_DISABLE_SYSTEMD=disable
fi

CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
DISABLE_AUTORECONF=TRUE \
package-stage-configure-install-archive \
    --disable-static \
    --enable-shared \
    --${ENABLE_OR_DISABLE_SYSTEMD}-systemd
