#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
if [ "${HOST_OS}" = "musl" ]; then
    MEMFD_CREATE_AVAILABLE=yes
else
    MEMFD_CREATE_AVAILABLE=no
fi

CONFIGURE_FILE=autogen.sh \
package-configure-install-archive \
    ac_cv_func_memfd_create=${MEMFD_CREATE_AVAILABLE} \
    --disable-static \
    --enable-shared
