#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment
generate-compiler-tools

# Configure the build components
if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "macos" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    PLATFORM=unix
elif [ "${HOST_OS}" = "mingw32" ]; then
    PLATFORM=win32
fi

# Build the components
copy-source-to-staging

cd ${STAGE_ROOT}
make-build \
    -f ${STAGE_ROOT}/${PLATFORM}/Makefile \
    prefix=${INSTALL_PREFIX} \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    LD=${CCLD} \
    LFLAGS2="${CCLDFLAGS}" \
    generic
make-install \
    -f ${STAGE_ROOT}/${PLATFORM}/Makefile \
    prefix=${INSTALL_PREFIX} \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    LD=${CCLD} \
    LFLAGS2="${CCLDFLAGS}"

# Build and install the package
package-invoke-archive-install
