#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
if [ "${HOST_OS}" = "mingw32" ]; then
    COMMON_CFLAGS="\
        -lws2_32 \
        ${COMMON_CFLAGS} \
    "
fi

BOOTSTRAP_FILE=./autogen.sh \
package-bootstrap-configure-install-archive \
    --disable-static \
    --enable-shared
