#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# swift-protobuf build
package-invoke-builder swift-protobuf-cross

# swift-syntax build
package-invoke-builder swift-syntax-cross

# swift-syntax-highlighter build
package-invoke-builder swift-syntax-highlighter-cross

# swift-format build
package-invoke-builder swift-format-cross

# swift-semantics build
package-invoke-builder swift-semantics-cross

# swift-doc build
package-invoke-builder swift-doc-cross

# sourcekit-lsp build
package-invoke-builder sourcekit-lsp-cross

# baikonur build
package-invoke-builder baikonur-cross

# pythonkit build
package-invoke-builder pythonkit-cross

# swift tensorflows apis build
# package-invoke-builder swift-tensorflow-apis
