#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke post installation steps
function package-install-completion-callback() {
      ${MKDIR} -p ${INSTALL_PREFIX}/share/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}
      ${MV} ${INSTALL_PREFIX}/LICENSE \
      ${INSTALL_PREFIX}/NOTICE \
      ${INSTALL_PREFIX}/README.txt \
      ${INSTALL_PREFIX}/share/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}/
}

# Invoke one shot template for maven build install
package-push-directory ${SOURCE_ROOT}
    PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
    package-maven-build \
      -DdistributionTargetDir=${INSTALL_PREFIX} \
      clean \
      package
package-pop-directory
