#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=unbound
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
CFLAGS="\
    -pthread \
    ${CFLAGS} \
" \
package-stage-configure-install \
    --disable-static \
    --enable-shared \
    --with-libexpat=${PACKAGE_PREFIX} \
    --with-ssl=${PACKAGE_PREFIX}

# Build and install the package
package-invoke-artifact-install
