#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=strace
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
CFLAGS="\
    -Wno-macro-redefined \
    -Wno-unused-command-line-argument \
    ${CFLAGS} \
" \
DISABLE_AUTOUPDATE=TRUE \
package-bootstrap-configure-install \
    --enable-mpers=no

# Build and install the package
package-invoke-artifact-install
