#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libtasn1
export SOURCE_PACKAGE_VERSION=4

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
DISABLE_AUTOUPDATE=TRUE \
package-bootstrap-configure-install \
    --disable-doc \
    --disable-gtk-doc \
    --disable-gtk-doc-html \
    --disable-gtk-doc-pdf \
    --disable-static \
    --enable-shared

# Build and install the package
package-invoke-artifact-install
