#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-bzip2-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

if [ "${HOST_OS}" != "macos" ] &&
   [ "${HOST_OS}" != "mingw" ]; then
    export DEPENDS="\
        ${PACKAGE_BASE_NAME}-acl-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${DEPENDS} \
    "
fi

# Invoke one-shot template for stage/configure/install
DISABLE_AUTOUPDATE=TRUE \
FORCE_UNSAFE_CONFIGURE=1 \
package-stage-configure-install-archive
