#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
LIBS="\
    -lintl \
    ${LIBS} \
" \
DISABLE_AUTOUPDATE=TRUE \
package-stage-configure-install-archive \
    --disable-manpages \
    --disable-static \
    --enable-shared
