#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=openssl
export SOURCE_PACKAGE_VERSION=1.1.1i

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment
generate-compiler-tools

# Configure the build components
cd ${STAGE_ROOT}

OPENSSL_DIR=/etc/ssl
OPENSSL_OS=${HOST_OS}
OPENSSL_PROCESSOR=${HOST_PROCESSOR}

if [ "${HOST_OS}" = "android" ]; then
    OPENSSL_DIR=/data/local/tmp${PACKAGE_PREFIX}/etc/ssl
    OPENSSL_OS=linux
elif [ "${HOST_OS}" = "gnu" ] || \
     [ "${HOST_OS}" = "musl" ]; then
    OPENSSL_OS=linux
elif [ "${HOST_OS}" = "mingw32" ]; then
    OPENSSL_DIR=${PACKAGE_PREFIX}/etc/ssl
fi

OPENSSL_TARGET=${OPENSSL_OS}-${OPENSSL_PROCESSOR}

if [ "${HOST_OS}" = "mingw32" ]; then
    OPENSSL_TARGET=mingw64
fi

${SOURCE_ROOT}/Configure \
    --openssldir=${OPENSSL_DIR} \
    --prefix=${PACKAGE_PREFIX} \
    "${OPENSSL_DEFINES}" \
    ${OPENSSL_TARGET}

# Build the components
make-build

INSTALL_TARGET="install_sw install_ssldirs" \
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
