#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for python/build/install
if [ "${HOST_OS}" = "android" ]; then
    export MATHLIB="m"
fi

COMMON_CFLAGS="\
    -L${PACKAGE_PREFIX}/lib \
    ${COMMON_CFLAGS} \
" \
NUMPY_VERSION="1.23.1" \
package-python-install-archive