#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-libunistring-0-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-gc-8-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

# Invoke one-shot template for bootstrap/configure/install
ENABLE_JIT=yes
ENABLE_OR_DISABLE_NETWORKING=enable
ENABLE_OR_DISABLE_POSIX=enable
WITH_OR_WITHOUT_MODULES=with

if [ "${HOST_PROCESSOR}" = "aarch64" ]; then
    ENABLE_JIT=no
fi

if [ "${HOST_OS}" = "macos" ]; then
    COMMON_CFLAGS="\
        -U__nonnull \
	${COMMON_CFLAGS} \
    "
    LIBS="\
        -framework CoreFoundation \
	${LIBS} \
    "
elif [ "${HOST_OS}" = "mingw32" ]; then
    ENABLE_JIT=no
    ENABLE_OR_DISABLE_NETWORKING=disable
    ENABLE_OR_DISABLE_POSIX=disable
    WITH_OR_WITHOUT_MODULES=without
fi

BOOTSTRAP_FILE=./autogen.sh \
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
DISABLE_AUTOUPDATE=TRUE \
package-bootstrap-configure-install-archive \
    ac_cv_func_GC_is_heap_ptr=yes \
    ac_cv_func_GC_move_disappearing_link=yes \
    --disable-static \
    --enable-jit=${ENABLE_JIT} \
    --enable-shared \
    --${ENABLE_OR_DISABLE_NETWORKING}-networking \
    --${ENABLE_OR_DISABLE_POSIX}-posix \
    --${WITH_OR_WITHOUT_MODULES}-modules
