#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=make
export SOURCE_PACKAGE_VERSION=4

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
${SED} -i \
       's/fcntl (intptr_t fd, int cmd, ...)/unused_fcntl (intptr_t fd, int cmd, ...)/g' \
       ${SOURCE_ROOT}/src/output.h \
       ${SOURCE_ROOT}/src/w32/compat/posixfcn.c

if [ "${HOST_OS}" = "mingw32" ]; then
    MAKE_FS_CMD="--enable-case-insensitive-file-system"
fi

# Invoke one-shot template for stage/configure/install
CFLAGS="\
    -U__MINGW32__ \
    ${CFLAGS} \
" \
package-configure-install \
    "${MAKE_FS_CMD}"