#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-openssl-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU}-${QUALIFIED_HOST_PROCESSOR} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU}-${QUALIFIED_HOST_PROCESSOR} (>=1.0.0) \
"

# Invoke one-shot template for cmake/install
package-cmake-install-archive \
    -DBUILD_EXAMPLES=FALSE \
    -DBUILD_SHARED_LIBS=TRUE \
    -DBUILD_TESTING=FALSE \
    -DOPENSSL_ROOT_DIR=${PACKAGE_PREFIX}