#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU}-${QUALIFIED_HOST_PROCESSOR} (>=1.0.0)"

# Invoke one-shot template for stage/configure/install
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
DISABLE_AUTOUPDATE=TRUE \
LDFLAGS="\
    -lssl \
    ${LDFLAGS} \
" \
package-stage-configure-install-archive \
    --disable-static \
    --enable-shared \
    --with-ssl=${PACKAGE_PREFIX}
