#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=fontconfig
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment

# Configure the build components
cd ${SOURCE_ROOT}
package-meson-build

# Build the components
cd ${STAGE_ROOT}
ninja-install

# Build and install the package
package-invoke-artifact-install
