#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# fftw build
package-invoke-builder fftw3-cross 3

# libjpeg build
package-invoke-builder libjpeg-cross 9

# libpng build
package-invoke-builder libpng-cross 1

# libtiff build
package-invoke-builder libtiff-cross 4

# xorg-macros build
package-invoke-builder xorg-macros-cross 1

# xorgproto build
package-invoke-builder xorg-xorgproto-cross 2021

# xcb-proto build
package-invoke-builder xcb-proto-cross 1

# xcb-pthread-stubs build
package-invoke-builder xcb-pthread-stubs-cross 0

# libxau build
package-invoke-builder xorg-libxau-cross 1

# pixman build
package-invoke-builder pixman-cross 1

if [ "${HOST_OS}" != "macos" ] &&
   [ "${HOST_OS}" != "mingw" ]; then
    # xorg-libpciaccess build
    package-invoke-builder xorg-libpciaccess-cross 0
fi

# xorg-libxtrans build
package-invoke-builder xorg-libxtrans-cross 1

# libxdmcp build
package-invoke-builder libxdmcp-cross 1

# libxcb build
package-invoke-builder xcb-libxcb-cross 1

# libx11 build
package-invoke-builder libx11-cross 1

# libxext build
package-invoke-builder libxext-cross 1

# xorg-libxrender build
package-invoke-builder xorg-libxrender-cross 0

# xorg-libxfixes build
package-invoke-builder xorg-libxfixes-cross 5

# xorg-libxi build
package-invoke-builder xorg-libxi-cross 1

# xorg-libice build
package-invoke-builder xorg-libice-cross 1

# xorg-libsm build
package-invoke-builder xorg-libsm-cross 1

# xorg-libxrandr build
package-invoke-builder xorg-libxrandr-cross 1

# xkeyboard-config build
package-invoke-builder xkeyboard-config-cross 2

# libxinerama build
package-invoke-builder libxinerama-cross 1

# libxcb-util build
package-invoke-builder libxcb-util-cross 0

# libxcb-image build
package-invoke-builder libxcb-image-cross 0

# libxcb-wm build
package-invoke-builder libxcb-wm-cross 0

# xorg-libxcursor build
package-invoke-builder xorg-libxcursor-cross 1

# xorg-libxcvt build
package-invoke-builder xorg-libxcvt-cross 1

# xorg-libxkbfile build
package-invoke-builder xorg-libxkbfile-cross 1

# xorg-libxdamage build
package-invoke-builder xorg-libxdamage-cross 1

# xcb-render-util build
package-invoke-builder xcb-render-util-cross 0

# xorg-xcb-util-keysyms build
package-invoke-builder xorg-xcb-util-keysyms-cross 0

# xorg-libxt build
package-invoke-builder xorg-libxt-cross 1

# xorg-libxtst build
package-invoke-builder xorg-libxtst-cross 1

if [ "${HOST_OS}" != "mingw" ]; then
    # xorg-libxshmfence build
    package-invoke-builder xorg-libxshmfence-cross 1

    # xorg-libxxf86vm build
    package-invoke-builder xorg-libxxf86vm-cross 1

    # xorg-libxmu build
    package-invoke-builder xorg-libxmu-cross 1

    # xorg-xauth build
    package-invoke-builder xorg-xauth-cross 1

    # xorg-xhost build
    package-invoke-builder xorg-xhost-cross 1
fi

# xorg-xinput build
package-invoke-builder xorg-xinput-cross 1

if [ "${HOST_OS}" != "macos" ] &&
   [ "${HOST_OS}" != "mingw" ]; then
    # wayland build
    package-invoke-builder wayland-cross 1

    # wayland-protocols build
    package-invoke-builder wayland-protocols-cross 1
fi

if [ "${HOST_OS}" != "mingw" ]; then
    # libxkbcommon build
    package-invoke-builder libxkbcommon-cross 1

    # mesa-drm build
    package-invoke-builder mesa-drm-cross 2
fi

# shared-mime-info build
package-invoke-builder shared-mime-info-cross 2

# opencl headers build
package-invoke-builder opencl-headers-cross 2020

# opencl icd loader build
package-invoke-builder opencl-icd-loader-cross 2020

if [ "${HOST_OS}" = "mingw" ]; then
    # egl headers build
    package-invoke-builder egl-headers-cross 1
else
    # libglvnd build
    package-invoke-builder libglvnd-cross 1
fi

# vulkan headers build
package-invoke-builder vulkan-headers-cross 1

# vulkan loader build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder vulkan-loader-cross 1

# brotli build
package-invoke-builder brotli-cross 1

# freetype2 build
ARCHIVE_PATH=${BOOTSTRAP_ARCHIVE_PATH} \
package-invoke-builder freetype2-cross 2 bootstrap-only

# fontconfig build
package-invoke-builder fontconfig-cross 2

# cairo build
package-invoke-builder cairo-cross 1

# graphite2 build
package-invoke-builder graphite2-cross 1

# harfbuzz build
package-invoke-builder harfbuzz-cross 4

# freetype2 build
package-invoke-builder freetype2-cross 2

# xorg-font-util-cross build
package-invoke-builder xorg-font-util-cross 1

# libfontenc build
package-invoke-builder libfontenc-cross 1

# libxfont-cross build
package-invoke-builder libxfont-cross 2

# fribidi build
package-invoke-builder fribidi-cross 1

# graphene build
package-invoke-builder graphene-cross 1

# gdk-pixbuf build
package-invoke-builder gdk-pixbuf-cross 2

# pango build
package-invoke-builder pango-cross 1
