#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libiconv
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
DISABLE_LIBTOOLIZE=TRUE \
USE_GENERATED_TOOLS=TRUE \
package-configure-install-archive \
    --disable-shared \
    --enable-shared
