#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
export LLVM_STAGE_ROOT=${LLVM_STAGE_ROOT:-${STAGE_ROOT_BASE}/${QUALIFIED_LLVM_PATH}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU}}

package-cmake-install-archive \
    -DBASE_LLVM_VERSION="${LLVM_VERSION}.0" \
    -DLLVM_DIR=${LLVM_STAGE_ROOT}/lib/cmake/llvm \
    -DLLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=${PACKAGE_PREFIX}/include \
    -DSPIRV_HEADERS_SKIP_INSTALL=TRUE \
    -DSPIRV_HEADERS_SKIP_EXAMPLES=TRUE