#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=pcre
export SOURCE_PACKAGE_VERSION=8

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
DISABLE_AUTOUPDATE=TRUE \
package-configure-install \
    --disable-static \
    --enable-pcre16 \
    --enable-pcre32 \
    --enable-pcregrep-libz \
    --enable-pcregrep-libbz2 \
    --enable-shared \
    --enable-unicode-properties

# Build and install the package
package-invoke-artifact-install
