#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=fribidi
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
DISABLE_FORTIFY_SOURCE_LEVEL=TRUE \
package-meson-install-archive \
    -Ddocs=false
