#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Build the components
COMMON_CFLAGS="\
    -L${PACKAGE_PREFIX}/lib \
    ${COMMON_CFLAGS} \
" \
NUMPY_VERSION="1.21.4" \
package-python-build

# Build and install the package
package-invoke-archive-install
