#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=klee
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export LLVM_NATIVE_STAGE_ROOT=${LLVM_NATIVE_STAGE_ROOT:-${STAGE_ROOT_BASE}/${QUALIFIED_LLVM_PATH}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}}

# Configure the build components
cd ${STAGE_ROOT}
COMMON_LDFLAGS="\
    -L${PACKAGE_PREFIX}/lib \
    ${COMMON_LDFLAGS} \
" \
package-cmake \
    ${SOURCE_ROOT} \
    -DENABLE_TCMALLOC=FALSE \
    -DLLVM_CONFIG_BINARY=${LLVM_NATIVE_STAGE_ROOT}/bin/llvm-config \
    -DLLVM_LIBRARY=`package-get-path LLVM SHARED HOST` \
    -DLLVMCC=${CC} \
    -DLLVMCXX=${CXX}

# Build the components
ninja-install

# Build and install the package
package-invoke-archive-install
