#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=c-ares
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
package-cmake-install-archive \
    -DHAVE_AF_INET6=TRUE \
    -DHAVE_IOCTLSOCKET_FIONBIO=TRUE \
    -DHAVE_RECV=TRUE \
    -DHAVE_RECVFROM=TRUE \
    -DHAVE_SEND=TRUE \
    -DHAVE_STRDUP=TRUE \
    -DHAVE_STRUCT_ADDRINFO=TRUE \
    -DHAVE_STRUCT_SOCKADDR_IN6=TRUE \
    -DHAVE_STRUCT_TIMEVAL=TRUE