#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=python
export SOURCE_PACKAGE_VERSION=3.6.8

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export-compiler-environment
generate-compiler-tools

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-bzip2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-libffi-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-openssl-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-ncurses-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-sqlite-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-util-linux-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
COMMON_CFLAGS="\
    --sysroot=${SYSROOT} \
    -I${PACKAGE_PREFIX}/include \
    -I${PACKAGE_PREFIX}/include/ncurses \
"

export _PYTHON_PROJECT_BASE=${STAGE_ROOT}
export CFLAGS=`${ECHO} "\
    ${COMMON_CFLAGS} \
    ${CFLAGS} \
" | ${XARGS}`
export CPPFLAGS=`${ECHO} "\
    ${COMMON_CFLAGS} \
    ${CPPFLAGS} \
" | ${XARGS}`
export CXXFLAGS=`${ECHO} "\
    ${COMMON_CFLAGS} \
    ${CXXFLAGS} \
" | ${XARGS}`
export LDFLAGS=`${ECHO} "\
    --sysroot=${SYSROOT} \
    ${LDFLAGS} \
" | ${XARGS}`
export OPENSSL_LIBS=`${ECHO} "\
    -lcrypto \
    -lssl \
" | ${XARGS}`

cd ${STAGE_ROOT}
${SOURCE_ROOT}/configure \
    ac_cv_buggy_getaddrinfo=no \
    ac_cv_file__dev_ptc=no \
    ac_cv_file__dev_ptmx=yes \
    --build=${BUILD_TRIPLE} \
    --host=${CONFIGURE_HOST_TRIPLE:-${HOST_TRIPLE}} \
    --enable-shared \
    --prefix=${PACKAGE_PREFIX} \
    --with-ensurepip=yes \
    --with-openssl=${PACKAGE_PREFIX} \
    --with-system-expat \
    --with-system-ffi

# Build the components
make-install

${LN} -sf \
      pip3 \
      ${INSTALL_PREFIX}/bin/pip
${LN} -sf \
      python3 \
      ${INSTALL_PREFIX}/bin/python

# Build the package
deb-package-build

# Install the package
deb-package-install
