#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=ldns
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
copy-source-to-staging

cd ${STAGE_ROOT}
package-libtoolize -ci
package-autoreconf -fi

LDFLAGS="\
    -lssl \
    ${LDFLAGS} \
" \
package-configure \
    ${STAGE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    --with-ssl=${PACKAGE_PREFIX}

# Build the components
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
