#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
function package-install-completion-callback() {
    ${MKDIR} -p \
             ${INSTALL_PREFIX}/bin \
             ${INSTALL_PREFIX}/include/alive2/ir \
             ${INSTALL_PREFIX}/include/alive2/smt \
             ${INSTALL_PREFIX}/include/alive2/tools \
             ${INSTALL_PREFIX}/include/alive2/utils \
             ${INSTALL_PREFIX}/lib/pkgconfig

    package-rsync -ax \
                  ${STAGE_ROOT}/alive${EXECUTABLE_SUFFIX} \
                  ${INSTALL_PREFIX}/bin/

    if [ "${HOST_OS}" = "mingw" ]; then
        package-rsync -ax \
                      ${STAGE_ROOT}/libalive2.dll \
                      ${INSTALL_PREFIX}/bin/
    fi

    package-rsync -ax \
                  ${SOURCE_ROOT}/ir/*.h \
                  ${INSTALL_PREFIX}/include/alive2/ir/
    package-rsync -ax \
                  ${SOURCE_ROOT}/smt/*.h \
                  ${INSTALL_PREFIX}/include/alive2/smt/
    package-rsync -ax \
                  ${SOURCE_ROOT}/tools/*.h \
                  ${INSTALL_PREFIX}/include/alive2/tools/
    package-rsync -ax \
                  ${SOURCE_ROOT}/util/*.h \
                  ${INSTALL_PREFIX}/include/alive2/util/
    package-rsync -ax \
                  ${STAGE_ROOT}/libalive2${SHARED_LIBRARY_SUFFIX} \
                  ${INSTALL_PREFIX}/lib/

    ${ECHO} "
V=${SOURCE_PACKAGE_VERSION}
R=${SOURCE_PACKAGE_VERSION}

prefix=${PACKAGE_PREFIX}
INSTALL_INC=\${prefix}/include
INSTALL_LIB=\${prefix}/lib
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: alive2
Description: Automatic verification of LLVM optimizations
Version: \${R}
Requires:
Libs: -L\${libdir} -lalive2
Cflags: -I\${includedir}
" > ${INSTALL_PREFIX}/lib/pkgconfig/alive2.pc
}

function tool-install-invocation() {
    return
}

PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
TOOL_INSTALL_INVOCATION=tool-install-invocation \
package-cmake-install-archive \
    -DGIT_EXECUTABLE=${GIT} \
    -DHIREDIS_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DHIREDIS_LIBRARIES=`package-get-path hiredis SHARED HOST` \
    -DRE2C=${BUILD_PACKAGE_PREFIX}/bin/re2c \
    -DZ3_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DZ3_LIBRARIES=`package-get-path z3 SHARED HOST` \
    -DZLIB_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DZLIB_LIBRARY_DEBUG=`package-get-path zlib SHARED HOST` \
    -DZLIB_LIBRARY_RELEASE=`package-get-path zlib SHARED HOST`