#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Build the components
copy-source-to-staging

COMMON_CFLAGS="\
    -Wno-deprecated-non-prototype \
    -Wno-implicit-function-declaration \
    ${COMMON_CFLAGS} \
" \
export-compiler-environment

if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "macos" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    PLATFORM=unix
elif [ "${HOST_OS}" = "mingw" ]; then
    PLATFORM=win32
fi

cd ${STAGE_ROOT}
make-build \
    -f ${STAGE_ROOT}/${PLATFORM}/Makefile \
    prefix=${INSTALL_PREFIX} \
    AS="${AS} ${ASFLAGS}" \
    CC="${CC} ${CFLAGS} ${CCLDFLAGS}" \
    CPP="${CPP} ${CPPFLAGS}" \
    generic
make-install \
    -f ${STAGE_ROOT}/${PLATFORM}/Makefile \
    prefix=${INSTALL_PREFIX} \
    AS="${AS} ${ASFLAGS}" \
    CC="${CC} ${CFLAGS} ${CCLDFLAGS}" \
    CPP="${CPP} ${CPPFLAGS}"

# Build and install the package
package-invoke-archive-install