#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=opengl-es-headers
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}
${MKDIR} -p ${INSTALL_PREFIX}/include
${SYNC} -aPx \
        ${SOURCE_ROOT}/api/GLES \
        ${SOURCE_ROOT}/api/GLES2 \
        ${SOURCE_ROOT}/api/GLES3 \
        ${INSTALL_PREFIX}/include/

# Build the package
deb-package-build

# Install the package
deb-package-install
