#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=opencl-icd-loader
export SOURCE_PACKAGE_VERSION=2020
export PACKAGE_INSTALL_FLAG='build'

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
package-cmake-install-archive \
    -DOPENCL_ICD_LOADER_DISABLE_OPENCLON12=TRUE