#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-cmake-3-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU}-${QUALIFIED_HOST_PROCESSOR} (>=1.0.0)"

# Configure the build components
cd ${STAGE_ROOT}
copy-source-to-staging
export-compiler-environment
make-install \
    CC=${CCLD} \
    CFLAGS="${CCLDFLAGS}" \
    DSTROOT=${INSTALL_PREFIX} \
    OUTDIR=${STAGE_ROOT}

# Build and install the package
package-invoke-archive-install
