#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
ENABLE_WAYLAND=false

if [ "${HOST_OS}" = "macos" ] ||
   [ "${HOST_OS}" = "mingw" ]; then
   ENABLE_WAYLAND=false
fi

package-meson-install-archive \
    -Denable-docs=false \
    -Denable-wayland=${ENABLE_WAYLAND} \
    -Denable-x11=true \
    -Denable-xkbregistry=true