#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
DISABLE_TOOL_BUILD=TRUE \
INSTALL_TARGET="XMLTOFLAGS=\"--skip-validation\" install" \
package-stage-configure-install-archive
