#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=xz
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
package-configure-install \
    --disable-static \
    --enable-shared