#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=android-patch-elf
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-cmake-3-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
cd ${STAGE_ROOT}
copy-source-to-staging
export-compiler-environment
make-install \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    DSTROOT=${INSTALL_PREFIX} \
    OUTDIR=${STAGE_ROOT}

# Build and install the package
package-invoke-archive-install
