#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libxml2
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-icu4c-68-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for stage/configure/install
if [ -z "${DISABLE_PYTHON}" ]; then
    WITH_OR_WITHOUT_PYTHON=--with-python
else
    WITH_OR_WITHOUT_PYTHON=--without-python
fi

DISABLE_AUTOUPDATE=TRUE \
RPATH_COMPONENTS="\
    ${INSTALL_PREFIX}/lib/${SHARED_LIBRARY_PREFIX}xml2${SHARED_LIBRARY_SUFFIX} \
" \
package-stage-configure-install \
    lt_cv_deplibs_check_method=pass_all \
    --disable-static \
    --enable-shared \
    --with-icu \
    ${WITH_OR_WITHOUT_PYTHON}
