#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
function package-install-completion-callback() {
    if [ "${HOST_OS}" = "mingw" ]; then
        ${MKDIR} -p ${INSTALL_PREFIX}/bin
        ${MV} ${INSTALL_PREFIX}/lib/`package-get-filename objc SHARED HOST` \
              ${INSTALL_PREFIX}/bin/
    fi
}

PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-cmake-install-archive \
    -DTESTS=FALSE