#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=ncurses
export SOURCE_PACKAGE_VERSION=6

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment

# Invoke one-shot template for configure/install
TIC=${TIC:-/usr/bin/tic}

if [ "${HOST_OS}" = "mingw32" ]; then
    ENABLE_VERSIONED_SYMS=no
else
    ENABLE_VERSIONED_SYMS=yes
fi

${MKDIR} -p \
         ${INSTALL_PREFIX}/include \
         ${INSTALL_PREFIX}/lib
${LN} -sf \
      ncursesw \
      ${INSTALL_PREFIX}/include/ncurses
${LN} -sf \
      `package-get-filename ncursesw SHARED` \
      ${INSTALL_PREFIX}/lib/`package-get-filename ncurses SHARED`

DISABLE_AUTOUPDATE=TRUE \
INSTALL_PREFIX=${PACKAGE_PREFIX} \
package-stage-configure-install-archive \
    --disable-termcap \
    --enable-ext-colors \
    --enable-mixed-case \
    --enable-pc-files \
    --enable-rpath \
    --enable-sp-funcs \
    --enable-term-driver \
    --enable-widec \
    --with-curses-h \
    --with-cxx \
    --with-cxx-shared \
    --with-install-prefix=${INSTALL_ROOT}/ \
    --with-pkg-config=${PKG_CONFIG} \
    --with-pkg-config-libdir=${PACKAGE_PREFIX}/lib/pkgconfig \
    --with-shared \
    --with-tic-path=${TIC} \
    --with-ticlib \
    --with-versioned-syms=${ENABLE_VERSIONED_SYMS} \
    --without-debug \
    --without-manpages \
    --without-progs \
    --without-tack \
    --without-termlib \
    --without-tests
