#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=lz4
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment
generate-compiler-tools

# Configure the build components
copy-source-to-staging

# Build the components
if [ "${HOST_OS}" = "macos" ]; then
    TARGET_OS=Darwin
elif [ "${HOST_OS}" = "mingw32" ]; then
    TARGET_OS=Windows
else
    TARGET_OS=Linux
fi

cd ${STAGE_ROOT}
make-install \
    AR=${AR} \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    PREFIX=${PACKAGE_PREFIX} \
    RANLIB=${RANLIB} \
    TARGET_OS=${TARGET_OS} \
    WINDRES=${WINDRES}

# Build and install the package
package-invoke-archive-install
