#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-corelibs-foundation
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

${MKDIR} -p ${INSTALL_PREFIX}/lib/swift/macosx
${RSYNC} -aPx \
         ${SYSROOT}/usr/lib/swift/CoreFoundation.swiftmodule \
         ${SYSROOT}/usr/lib/swift/Foundation.swiftmodule \
         ${SYSROOT}/usr/lib/swift/libswiftCoreFoundation.tbd \
         ${SYSROOT}/usr/lib/swift/libswiftFoundation.tbd \
         ${INSTALL_PREFIX}/lib/swift/macosx/

DISABLE_INSTALL_DEB=TRUE \
package-invoke-archive-install
