#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
BOOTSTRAP_FILE=autogen.sh \
BUILD_COMMON_CFLAGS="\
    -L${BUILD_PACKAGE_PREFIX}/lib \
    ${BUILD_COMMON_CFLAGS} \
" \
LIBTOOLIZE_ARGS="-i" \
package-bootstrap-configure-install-archive \
  --disable-g13-test \
  --disable-glibtest \
  --disable-gpg-test \
  --disable-gpgconf-test \
  --disable-gpgsm-test
