#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=spirv-tools
export SOURCE_PACKAGE_VERSION=2020

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
package-cmake \
    -DLIBRT= \
    -DPYTHON_EXECUTABLE=${PYTHON} \
    -DSPIRV-Headers_SOURCE_DIR=${PACKAGE_PREFIX} \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build the package
deb-package-build

# Install the package
deb-package-install
