#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libarchive
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-bzip2-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd ${STAGE_ROOT}

if [ "${HOST_OS}" != "gnu" ]; then
    export DEPENDS="\
        ${PACKAGE_BASE_NAME}-libiconv-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
        ${DEPENDS} \
    "
fi

if [ "${HOST_OS}" != "mingw32" ]; then
    export DEPENDS="\
        ${PACKAGE_BASE_NAME}-acl-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
        ${DEPENDS} \
    "
    ACL_LIBRARY=`package-get-path acl SHARED HOST`
fi

LIBLZMA_LIBRARY=`package-get-path lzma SHARED HOST`
ZLIB_LIBRARY=`package-get-path z SHARED HOST` \

package-cmake \
    -DACL_LIBRARY=${ACL_LIBRARY} \
    -DBZIP2_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DBZIP2_LIBRARIES=`package-get-path bz2 STATIC HOST` \
    -DENABLE_CAT_SHARED=TRUE \
    -DENABLE_CPIO_SHARED=TRUE \
    -DENABLE_LibGCC=FALSE \
    -DENABLE_TAR_SHARED=TRUE \
    -DENABLE_TEST=FALSE \
    -DLIBLZMA_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DLIBLZMA_LIBRARY=${LIBLZMA_LIBRARY} \
    -DZLIB_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DZLIB_LIBRARY=${ZLIB_LIBRARY} \
    -DZLIB_WINAPI_EXITCODE=0 \
    -DZLIB_WINAPI_EXITCODE__TRYRUN_OUTPUT=1 \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build and install the package
package-invoke-archive-install
