#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libffi
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure

SDK_PLATFORM_DIR=`${ECHO} ${SYSTEM_NAME} | ${TR} '[:upper:]' '[:lower:]'`

if [ "${SDK_PLATFORM_DIR}" = "windows" ]; then
    SYMVER_CMD="--disable-symvers"
fi

cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    "${SYMVER_CMD}"

# Build the components
make-install

${RM} -rf ${INSTALL_PREFIX}/share/info/dir

# Build the package
deb-package-build

# Install the package
deb-package-install
