#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=findutils
export SOURCE_PACKAGE_VERSION=4

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
package-bootstrap-configure-install