#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
if [ "${HOST_PROCESSOR}" = "aarch64" ]; then
    ENABLE_ARM_DYNAREC=TRUE
else
    ENABLE_ARM_DYNAREC=FALSE
fi

if [ -n "${ENABLE_LARGE_PAGE_SUPPORT}" ] &&
   [ "${HOST_CPU}" = "apple-m1" ]; then
    ENABLE_M1=TRUE
else
    ENABLE_M1=FALSE
fi

export-compiler-environment-for-build-tools
package-cmake-install-archive \
    -DARM_DYNAREC=${ENABLE_ARM_DYNAREC} \
    -DM1=${ENABLE_M1} \
    -DPython3_EXECUTABLE=${PYTHON}