#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=python
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-bzip2-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-libffi-3-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-openssl-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-sqlite-3-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-util-linux-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for stage/configure/install
function package-install-completion-callback() {
    ${LN} -sf \
          pip3 \
          ${INSTALL_PREFIX}/bin/pip
    ${LN} -sf \
          python3 \
          ${INSTALL_PREFIX}/bin/python
}

COMMON_CFLAGS="\
    -I${PACKAGE_PREFIX}/include \
    -I${PACKAGE_PREFIX}/include/ncurses \
" \
export-compiler-environment

PYTHON_CFLAGS=${CFLAGS}
PYTHON_LDFLAGS=${LDFLAGS}
unset \
    CFLAGS \
    LDFLAGS

_PYTHON_PROJECT_BASE=${STAGE_ROOT} \
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
DISABLE_GENERATED_TOOLS=TRUE \
OPENSSL_LIBS=`${ECHO} "\
    -lcrypto \
    -lssl \
" | ${XARGS}` \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-stage-configure-install-archive \
    ac_cv_buggy_getaddrinfo=no \
    ac_cv_file__dev_ptc=no \
    ac_cv_file__dev_ptmx=yes \
    CFLAGS_NODIST="${PYTHON_CFLAGS}" \
    LDFLAGS_NODIST="${PYTHON_LDFLAGS}" \
    --enable-shared \
    --with-ensurepip=yes \
    --with-openssl=${PACKAGE_PREFIX} \
    --with-system-expat \
    --with-system-ffi