#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=freetype2
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}

if [ -z "${DISABLE_HARFBUZZ}" ]; then
    FT_WITH_HARFBUZZ=TRUE
    HARFBUZZ_INCLUDE_DIRS=${PACKAGE_PREFIX}/include/harfbuzz
    HARFBUZZ_LIBRARIES=`package-get-path harfbuzz SHARED HOST`
else
    FT_WITH_HARFBUZZ=FALSE
fi

package-cmake \
    -DBUILD_SHARED_LIBS=true \
    -DFT_WITH_BROTLI=TRUE \
    -DFT_WITH_BZIP2=TRUE \
    -DFT_WITH_HARFBUZZ=${FT_WITH_HARFBUZZ} \
    -DFT_WITH_PNG=TRUE \
    -DFT_WITH_ZLIB=TRUE \
    -DHARFBUZZ_INCLUDE_DIRS=${HARFBUZZ_INCLUDE_DIRS} \
    -DHARFBUZZ_LIBRARIES=${HARFBUZZ_LIBRARIES} \
    -DPNG_LIBRARY_DEBUG=`package-get-path png SHARED HOST` \
    -DPNG_LIBRARY_RELEASE=`package-get-path png SHARED HOST` \
    -DPNG_PNG_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build and install the package
package-invoke-archive-install
