#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

if [ "${HOST_OS}" != "macos" ] &&
   [ "${HOST_OS}" != "mingw32" ]; then
    export DEPENDS="\
        ${PACKAGE_BASE_NAME}-acl-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
        ${PACKAGE_BASE_NAME}-attr-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
    "
fi

# Invoke one-shot template for bootstrap/configure/install
COREUTILS_NATIVE_STAGE_ROOT=${STAGE_ROOT_BASE}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_CPU}

if [ "${HOST_OS}" != "${HOST_TRIPLE}" ]; then
    export MAKE_PRIME_LIST=${COREUTILS_NATIVE_STAGE_ROOT}/build/src/make-prime-list
fi

DISABLE_AUTOUPDATE=TRUE \
FORCE_UNSAFE_CONFIGURE=1 \
package-bootstrap-configure-install-archive \
    --with-openssl
