#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-python-3-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-swift-${SOURCE_PACKAGE_VERSION}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

if [ "${HOST_OS}" != "macos" ]; then
    export DEPENDS="\
        ${DEPENDS}, \
        ${PACKAGE_BASE_NAME}-swift-corelibs-foundation-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
        ${PACKAGE_BASE_NAME}-swift-corelibs-libdispatch-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
    "
fi

# Build the components
cd ${SOURCE_ROOT}
SWIFT_BUILD_SCRIPT_ENVIRONMENT=TRUE \
package-swift-build

if [ "${HOST_OS}" = "gnu" ]; then
    SDK_PLATFORM_DIR="linux"
elif [ "${HOST_OS}" = "macos" ]; then
    SDK_PLATFORM_DIR="macosx"
elif [ "${HOST_OS}" = "mingw" ]; then
    SDK_PLATFORM_DIR="windows"
else
    SDK_PLATFORM_DIR=${HOST_OS}
fi

cd ${STAGE_ROOT}

if [ "${HOST_OS}" != "macos" ]; then
    if [ "${HOST_PROCESSOR}" = "armv7a" ]; then
        SWIFT_ARCH_DIR=armv7
    elif [ "${HOST_PROCESSOR}" = "i386" ] ||
         [ "${HOST_PROCESSOR}" = "i486" ] ||
         [ "${HOST_PROCESSOR}" = "i586" ] ||
         [ "${HOST_PROCESSOR}" = "i686" ] ||
         [ "${HOST_PROCESSOR}" = "i786" ]; then
        SWIFT_ARCH_DIR=i686
    else
        SWIFT_ARCH_DIR=${HOST_PROCESSOR}
    fi
fi

${MKDIR} -p ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/${SWIFT_ARCH_DIR}/
package-rsync -ax \
              release/*.swiftdoc \
              release/*.swiftmodule \
              ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/${SWIFT_ARCH_DIR}/
package-rsync -ax \
              release/${SHARED_LIBRARY_PREFIX}*${SHARED_LIBRARY_SUFFIX} \
              ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/

# Build and install the package
package-invoke-archive-install