#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=grep
export SOURCE_PACKAGE_VERSION=3.6

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
if [ ${HOST_OS} = "mingw32" ]; then
    export CFLAGS="\
        -pthread \
        ${CFLAGS} \
    "
fi

cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure

# Build the components
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
