#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
if [ "${HOST_OS}" = "musl" ]; then
    COMMON_CFLAGS="\
        -lfts \
        ${COMMON_CFLAGS} \
    "
fi

SOURCE_ROOT=${SOURCE_ROOT}/xar \
package-stage-configure-install-archive \
    --disable-shared \
    --enable-shared