#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libxml2
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-icu4c-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure

cd ${STAGE_ROOT}
CFLAGS="\
    -DTRUE=1 \
    ${CFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure \
    lt_cv_deplibs_check_method=pass_all \
    --disable-static \
    --enable-shared \
    --with-icu \
    --without-python

# Build the components
make-install

# RPATH fixups
COMPONENTS="\
    ${INSTALL_PREFIX}/lib/libxml2.so \
" \
rpath-fixup

# Build the package
deb-package-build

# Install the package
deb-package-install
