#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
package-meson-install-archive \
    -Ddebug=false \
    -Djpeg=true \
    -Dgtk_doc=false \
    -Dinstalled_tests=false \
    -Dintrospection=disabled \
    -Dman=false \
    -Dpng=true