#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
if [ "${HOST_OS}" = "gnu" ]; then
    export CFLAGS=`${ECHO} "\
        -D_IO_ftrylockfile=1 \
        -D_IO_IN_BACKUP=0x100 \
        ${CFLAGS} \
    " | ${XARGS}`
fi

HELP2MAN=`${WHICH} true` \
package-bootstrap-configure-install-archive \
    ac_cv_func_snprintf=no \
    gl_cv_func_printf_directive_n=no