#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU}-${QUALIFIED_HOST_PROCESSOR} (>=1.0.0)"

# Invoke one-shot template for bootstrap/configure/install
if [ "${HOST_OS}" = "mingw" ]; then
    COMMON_CFLAGS="\
        -lshlwapi \
        -lws2_32 \
        -I${STAGE_ROOT}/pc \
        ${COMMON_CFLAGS} \
    "
    DISABLE_TOOL_BUILD=TRUE
    INSTALL_TARGET="AWKPROG=${GAWK} install"
fi

BOOTSTRAP_FILE=bootstrap.sh \
DISABLE_AUTOUPDATE=TRUE \
package-bootstrap-configure-install-archive
