#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=khr-headers
export SOURCE_PACKAGE_VERSION=1.0.0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}
${MKDIR} -p ${INSTALL_PREFIX}/include
${RSYNC} -aPx \
         ${SOURCE_ROOT}/api/KHR \
         ${INSTALL_PREFIX}/include/

# Build the package
deb-package-build

# Install the package
deb-package-install
