#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
if [ "${BUILD_TRIPLE}" != "${HOST_TRIPLE}" ]; then
    HELP2MAN=`package-get-path true EXECUTABLE BUILD`
    MAKEINFO=`package-get-path true EXECUTABLE BUILD`
fi

BOOTSTRAP_ARGS="\
    --force \
    --no-git \
    --gnulib-srcdir=${STAGE_ROOT}/glib \
    --skip-po \
" \
ENABLE_GNULIB_OVERRIDE=TRUE \
package-bootstrap-configure-install-archive
