#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
function package-install-completion-callback() {
    ${LN} -sf \
         `package-get-filename GLESv2 SHARED` \
         ${INSTALL_PREFIX}/lib/`package-get-filename GLESv3 SHARED`
}

ENABLE_TLS=true

if [ "${HOST_OS}" = "android" ]; then
    ENABLE_TLS=false
fi

PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-meson-install-archive \
    -Dasm=disabled \
    -Dtests=false \
    -Dtls=${ENABLE_TLS}