#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=gdbm
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
COMMON_CFLAGS="\
    -fcommon \
    ${COMMON_CFLAGS} \
" \
COMMON_LDFLAGS="\
    -Wl,-allow-multiple-definition \
    ${COMMON_LDFLAGS} \
" \
LIBS="\
    -ledit \
    ${LIBS} \
" \
DISABLE_AUTOUPDATE=TRUE \
package-configure-install-archive \
    --disable-static \
    --enable-shared
