#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# spice-protocol build
package-invoke-builder spice-protocol-cross

# spice build
package-invoke-builder spice-cross

if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "macos" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    # virglrenderer build
    package-invoke-builder virglrenderer-cross
fi

# qemu build
package-invoke-builder qemu-cross
