#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=meson
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Build the components
cd ${SOURCE_ROOT}
package-python-build

# Build the package
deb-package-build

# Install the package
deb-package-install
