#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# remove host foundation and libdispatch to avoid module collisions
PACKAGES_TO_MANAGE=( 'swift-argument-parser-5'         'BUILD' \
                     'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-libdispatch-5'    'BUILD' \
                     'swift-corelibs-xctest-5'         'BUILD' \
                     'swift-crypto-5'                  'BUILD' \
                     'swift-driver-5'                  'BUILD' \
                     'swift-llbuild-5'                 'BUILD' \
                     'swift-package-manager-5'         'BUILD' \
                     'swift-tools-support-core-5'      'BUILD' \
                     'yams-3'                          'BUILD' )
PACKAGE_ACTION=UNINSTALL \
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# musl libdispatch build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-corelibs-libdispatch-cross 5 no-install

# musl foundation build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-corelibs-foundation-cross 5 no-install

# musl xctest build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-corelibs-xctest-cross 5 no-install

# musl llbuild build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-llbuild-cross 5 no-install

# musl swift tools support core build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-tools-support-core-cross 5 no-install

# musl yams build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder yams-cross 3 no-install

# musl swift argument parser build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-argument-parser-cross 5 no-install

# swift crypto build
package-invoke-builder swift-crypto-cross 5 no-install

# musl swift driver build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-driver-cross 5 no-install

# swift package manager build
package-invoke-builder swift-package-manager-cross 5 no-install

# reinstall swiftpm for build and host
PACKAGES_TO_MANAGE=( 'swift-argument-parser-5'         'BUILD' \
                     'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-libdispatch-5'    'BUILD' \
                     'swift-corelibs-xctest-5'         'BUILD' \
                     'swift-crypto-5'                  'BUILD' \
                     'swift-driver-5'                  'BUILD' \
                     'swift-llbuild-5'                 'BUILD' \
                     'swift-package-manager-5'         'BUILD' \
                     'swift-tools-support-core-5'      'BUILD' \
                     'yams-3'                          'BUILD' \
                     'swift-argument-parser-5'         'HOST' \
                     'swift-corelibs-foundation-5'     'HOST' \
                     'swift-corelibs-libdispatch-5'    'HOST' \
                     'swift-corelibs-xctest-5'         'HOST' \
                     'swift-crypto-5'                  'HOST' \
                     'swift-driver-5'                  'HOST' \
                     'swift-llbuild-5'                 'HOST' \
                     'swift-package-manager-5'         'HOST' \
                     'swift-tools-support-core-5'      'HOST' \
                     'yams-3'                          'HOST' )

PACKAGE_ACTION=INSTALL \
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# swift-protobuf build
package-invoke-builder swift-protobuf-cross 1

# swift-syntax build
package-invoke-builder swift-syntax-cross 5

# swift-syntax-highlighter build
package-invoke-builder swift-syntax-highlighter-cross 1

# swift-format build
package-invoke-builder swift-format-cross 5

# swift-semantics build
package-invoke-builder swift-semantics-cross 0

# swift-doc build
package-invoke-builder swift-doc-cross 5

# sourcekit-lsp build
package-invoke-builder sourcekit-lsp-cross 5

# baikonur build
package-invoke-builder baikonur-cross 1

# pythonkit build
package-invoke-builder pythonkit-cross 5

# swift tensorflows apis build
# package-invoke-builder swift-tensorflow-apis
