#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libcap
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}

copy-source-to-staging
export-compiler-environment
make-install \
    lib=lib \
    prefix=${PACKAGE_PREFIX} \
    AR=${AR} \
    BUILD_CC=${BUILD_CC} \
    BUILD_CFLAGS="${BUILD_CFLAGS}" \
    BUILD_COPTS="-O${OPTIMIZATION_LEVEL}" \
    BUILD_LD=${BUILD_LD} \
    BUILD_LDFLAGS="${BUILD_CCLDFLAGS}" \
    BUILD_GPERF=${GPERF} \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    GOLANG=yes \
    COPTS="-O${OPTIMIZATION_LEVEL}" \
    DYNAMIC=yes \
    INDENT=${INDENT} \
    KERNEL_HEADERS=${PACKAGE_PREFIX}/include/uapi \
    LD=${CCLD} \
    PSXLINKFLAGS=-pthread \
    SYSTEM_HEADERS=${PACKAGE_PREFIX}/include \
    TESTS=no \
    LDFLAGS="-shared ${CCLDFLAGS}"

# Build and install the package
package-invoke-archive-install
