#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=yautja-server
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export INSTALL_PREFIX=${INSTALL_ROOT}${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk/web/${SOURCE_PACKAGE_NAME}

# Configure & build the package
cd ${STAGE_ROOT}

copy-source-to-staging
export-compiler-environment
yarn-build

${MKDIR} -p ${INSTALL_PREFIX}
package-rsync -ax \
              ${STAGE_ROOT}/ \
              ${INSTALL_PREFIX}/

# Build and install the package
package-invoke-archive-install