#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
MAIL_DIR=/var/mail

if [ "${HOST_OS}" = "android" ]; then
    export CFLAGS="\
        -DHAVE_ATTRIBUTE__SENTINEL__=1 \
        -DHAVE_BZERO=1 \
        -DHAVE_MEMSET_S=1 \
        -Dmemset_s\\\(d,ds,c,s\\\)=bzero\\\(d,s\\\) \
        ${CFLAGS} \
    "
    MAIL_DIR=/data/local/tmp/mail
fi

INSTALL_TARGET=install-nokeys \
package-stage-configure-install-archive \
    --disable-static \
    --disable-strip \
    --disable-utmpx \
    --enable-shared \
    --with-ldns=${PACKAGE_PREFIX} \
    --with-maildir=${MAIL_DIR}
