#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}

copy-source-to-staging

BUILD_COMMON_CFLAGS="\
    -L${BUILD_PACKAGE_PREFIX}/lib \
    ${BUILD_COMMON_CFLAGS} \
" \
COMMON_CFLAGS="\
    -L${PACKAGE_PREFIX}/lib \
    ${COMMON_CFLAGS} \
" \
export-compiler-environment
generate-compiler-tools
export-compiler-environment-for-go
make-install \
    lib=lib \
    prefix=${PACKAGE_PREFIX} \
    AR=${AR} \
    BUILD_CC=${BUILD_CC} \
    BUILD_CFLAGS="${BUILD_CFLAGS}" \
    BUILD_COPTS="-O${OPTIMIZATION_LEVEL}" \
    BUILD_LD=${BUILD_CCLD} \
    BUILD_LDFLAGS="${BUILD_CCLDFLAGS}" \
    BUILD_GPERF=${GPERF} \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    CGO_CFLAGS="${CGO_CFLAGS}" \
    CGO_CPPFLAGS="${CGO_CPPFLAGS}" \
    CGO_CXXFLAGS="${CGO_CXXFLAGS}" \
    CGO_LDFLAGS="${CGO_LDFLAGS}" \
    GOLANG=yes \
    COPTS="-O${OPTIMIZATION_LEVEL}" \
    DYNAMIC=yes \
    INDENT=${INDENT} \
    KERNEL_HEADERS=${PACKAGE_PREFIX}/include/uapi \
    LD=${CCLD} \
    LDFLAGS="-shared ${CCLDFLAGS}" \
    OBJCOPY=${OBJCOPY} \
    PSXLINKFLAGS=-pthread \
    RANLIB=${RANLIB} \
    SYSTEM_HEADERS=${PACKAGE_PREFIX}/include \
    TESTS=no

# Build and install the package
package-invoke-archive-install