#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
if [ "${HOST_OS}" = "mingw" ]; then
    export COMMON_CFLAGS="\
        -pthread \
        ${COMMON_CFLAGS} \
    "
fi

package-bootstrap-configure-install-archive \
    GREP=
