#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
if [ "${HOST_OS}" = "macos" ]; then
    ENABLE_OR_DISABLE_CORETEXT=enabled
else
    ENABLE_OR_DISABLE_CORETEXT=disabled
fi

package-meson-install-archive \
    -Dcairo=enabled \
    -Dcoretext=${ENABLE_OR_DISABLE_CORETEXT} \
    -Ddocs=disabled \
    -Dfreetype=enabled \
    -Dglib=enabled \
    -Dgobject=disabled \
    -Dgraphite=enabled \
    -Dintrospection=disabled \
    -Dtests=disabled
