#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-gmp-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0)"

# Invoke one-shot template for stage/configure/install
if [ "${HOST_OS}" = "musl" ]; then
    CONFIGURE_HOST_TRIPLE="${HOST_PROCESSOR}-${HOST_KERNEL}-gnu"
fi

if [ "${BUILD_TRIPLE}" = "${HOST_TRIPLE}" ]; then
    CROSS_COMPILING=no
else
    CROSS_COMPILING=yes
fi

CONFIGURE_FILE_ROOT=${STAGE_ROOT}/dist \
INSTALL_TARGET="install_include install_lib install_utilities" \
package-stage-configure-install-archive \
    cross_compiling=${CROSS_COMPILING} \
    --disable-doc \
    --disable-static \
    --enable-dbm \
    --enable-shared