#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
if [ -z "${DISABLE_SYSTEMD}" ]; then
    FEATURE_SYSTEMD=enabled
else
    FEATURE_SYSTEMD=disabled
fi

package-meson-install-archive \
    -Dsystemd=${FEATURE_SYSTEMD}