#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=wineditline
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
cd ${STAGE_ROOT}
CFLAGS="\
     -I${SOURCE_ROOT} \
     -I${SOURCE_ROOT}/src \
     ${CFLAGS} \
" \
package-cmake \
    ${SOURCE_ROOT}/src

# Build the components
ninja-install

${MV} ${SOURCE_ROOT}/src/bin \
      ${SOURCE_ROOT}/src/include \
      ${SOURCE_ROOT}/src/lib \
      ${INSTALL_PREFIX}/

# Build the package
deb-package-build

# Install the package
deb-package-install
