#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=mesa-drm
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${SOURCE_ROOT}
package-meson-build \
    -Damdgpu=true \
    -Dbuild-tests=false \
    -Dcairo-tests=false \
    -Detnaviv=true \
    -Dexynos=true \
    -Dfreedreno=true \
    -Dinstall-test-programs=false \
    -Dintel=true \
    -Dlibkms=true \
    -Domap=true \
    -Dnouveau=true \
    -Dradeon=true \
    -Dtegra=true \
    -Dvivante=true \
    -Dvmwgfx=true

# Build the components
cd ${STAGE_ROOT}
ninja-install

# Build and install the package
package-invoke-archive-install
