#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# remove host foundation and libdispatch to avoid module collisions
PACKAGE_ACTION=UNINSTALL
PACKAGES_TO_MANAGE=( 'swift-argument-parser-5'         'BUILD' \
                     'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-libdispatch-5'    'BUILD' \
                     'swift-corelibs-xctest-5'         'BUILD' \
                     'swift-crypto-5'                  'BUILD' \
                     'swift-driver-5'                  'BUILD' \
                     'swift-llbuild-5'                 'BUILD' \
                     'swift-package-manager-5'         'BUILD' \
                     'swift-tools-support-core-5'      'BUILD' \
                     'yams-3'                          'BUILD' )
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# libdispatch build
package-invoke-builder swift-corelibs-libdispatch-cross

# foundation build
package-invoke-builder swift-corelibs-foundation-cross

# xctest build
package-invoke-builder swift-corelibs-xctest-cross

# llbuild build
package-invoke-builder swift-llbuild

# swift tools support core build
package-invoke-builder swift-tools-support-core

# yams build
package-invoke-builder yams-cross

# swift argument parser build
package-invoke-builder swift-argument-parser

# swift crypto build
package-invoke-builder swift-crypto

# swift driver build
package-invoke-builder swift-driver

# swift package manager build
package-invoke-builder swift-package-manager

# reinstall swiftpm for build and host
PACKAGE_ACTION=INSTALL
PACKAGES_TO_MANAGE=( 'swift-argument-parser-5'         'BUILD' \
                     'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-libdispatch-5'    'BUILD' \
                     'swift-corelibs-xctest-5'         'BUILD' \
                     'swift-crypto-5'                  'BUILD' \
                     'swift-driver-5'                  'BUILD' \
                     'swift-llbuild-5'                 'BUILD' \
                     'swift-package-manager-5'         'BUILD' \
                     'swift-tools-support-core-5'      'BUILD' \
                     'yams-3'                          'BUILD' \
                     'swift-argument-parser-5'         'HOST' \
                     'swift-corelibs-foundation-5'     'HOST' \
                     'swift-corelibs-libdispatch-5'    'HOST' \
                     'swift-corelibs-xctest-5'         'HOST' \
                     'swift-crypto-5'                  'HOST' \
                     'swift-driver-5'                  'HOST' \
                     'swift-llbuild-5'                 'HOST' \
                     'swift-package-manager-5'         'HOST' \
                     'swift-tools-support-core-5'      'HOST' \
                     'yams-3'                          'HOST' )
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}
