#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=android-patch-elf
export SOURCE_PACKAGE_VERSION=1.0.0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment
generate-compiler-tools

export DEPENDS="${PACKAGE_BASE_NAME}-cmake-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
copy-source-to-staging

# Build the components
cd ${STAGE_ROOT}
make-install \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    DSTROOT=${INSTALL_PREFIX} \
    OUTDIR=${STAGE_ROOT}

# Build the package
cd ${STAGE_ROOT}
deb-package-build

# Install the package
deb-package-install
