#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=apt
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
package-cmake \
    -DCONF_DIR=/etc/apt \
    -DCACHE_DIR=/var/cache/apt \
    -DLOG_DIR=/var/log/apt \
    -DSTATE_DIR=/var/lib/apt \
    -DTRIEHASH_EXECUTABLE=${SOURCE_ROOT_BASE}/triehash-0/triehash.pl \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build the package
deb-package-build

# Install the package
deb-package-install
