#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for python/build/install
COMMON_CFLAGS="\
    -lpython${PYTHON_VERSION} \
    ${COMMON_CFLAGS} \
" \
SKBUILD_CMAKE_ARGUMENTS="\
    -DEXPAT_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DEXPAT_LIBRARY=`package-get-path expat SHARED HOST` \
    -DLIBXML2_INCLUDE_DIR=${PACKAGE_PREFIX}/include/libxml2 \
    -DLIBXML2_LIBRARY=`package-get-path xml2 SHARED HOST` \
    -DZLIB_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DZLIB_LIBRARY_DEBUG=`package-get-path z SHARED HOST` \
    -DZLIB_LIBRARY_RELEASE=`package-get-path z SHARED HOST` \
    ${SKBUILD_CMAKE_ARGUMENTS} \
" \
package-python-install-archive