#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=elfutils
export SOURCE_PACKAGE_VERSION=0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-curl-7-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-libarchive-3-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-libmicrohttpd-0-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for stage/configure/installs
CFLAGS="\
    -Wno-implicit-function-declaration \
    -Wno-unknown-warning-option \
    -Wno-unused-command-line-argument \
    -Wno-unused-parameter \
    ${CFLAGS} \
" \
INSTALL_TARGET="-C lib -C libelf install" \
RPATH_COMPONENTS="\
    ${INSTALL_PREFIX}/lib/libelf.so \
" \
package-stage-configure-install \
    ac_cv_c99=yes \
    ac_cv_lib_argp_argp_parse=yes \
    ac_cv_implicit_fallthrough=no \
    --disable-debuginfod \
    --disable-static \
    --enable-shared \
    --with-zlib=yes