#!/bin/bash


# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-icu4c-71-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

# Invoke one-shot template for configure/install
CONFIGURE_FILE=autogen.sh \
DISABLE_AUTOUPDATE=TRUE \
package-configure-install-archive \
    ac_cv_path_LIBGCRYPT_CONFIG=${PACKAGE_PREFIX}/bin/libgcrypt-config \
    ac_cv_path_XML_CONFIG=${PACKAGE_PREFIX}/bin/xml2-config \
    --disable-static \
    --enable-shared
