#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=wayland
export SOURCE_PACKAGE_VERSION=1.18.91

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

OPTIMIZATION_FLAGS="\
    -UNDEBUG \
    ${CFLAGS} \
" \
export-compiler-environment

# Configure the build components
cd ${SOURCE_ROOT}
package-meson-build \
    -Ddocumentation=false

# Build the components
cd ${STAGE_ROOT}
ninja-install

# Build the package
deb-package-build

# Build the package
deb-package-install
