#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

# Invoke one-shot template for bootstrap/configure/install
if [ -n "${NON_PERSISTENT_ARCHIVE}" ]; then
    DISABLE_PYTHON=TRUE
    DISABLE_SYSTEMD=TRUE
fi

if [ -z "${DISABLE_PYTHON}" ]; then
    ENABLE_OR_DISABLE_PYTHON=enable
else
    ENABLE_OR_DISABLE_PYTHON=disable
fi

if [ -z "${DISABLE_SYSTEMD}" ]; then
    ENABLE_OR_DISABLE_SYSTEMD=enable
else
    ENABLE_OR_DISABLE_SYSTEMD=disable
fi

ENABLE_OR_DISABLE_LIBBLKID=enable
ENABLE_OR_DISABLE_LIBSMARTCOLS=enable

if [ "${HOST_OS}" = "macos" ] ||
   [ "${HOST_OS}" = "mingw32" ]; then
    COMMON_CFLAGS="\
        -lintl \
        ${COMMON_CFLAGS} \
    "
    ENABLE_OR_DISABLE_LIBMOUNT=disable
    ENABLE_OR_DISABLE_LIBUUID=disable

    if [ "${HOST_OS}" = "mingw32" ]; then
        ENABLE_OR_DISABLE_LIBBLKID=disable
        ENABLE_OR_DISABLE_LIBSMARTCOLS=disable
    fi
else
    ENABLE_OR_DISABLE_LIBMOUNT=enable
    ENABLE_OR_DISABLE_LIBUUID=enable
fi

BOOTSTRAP_FILE=autogen.sh \
DISABLE_AUTOUPDATE=TRUE \
NCURSESW_CFLAGS="-I${PACKAGE_PREFIX}/include" \
NCURSESW_LDFLAGS="-L`package-get-path ncurses SHARED HOST`" \
NCURSESW6_CONFIG=`package-get-path ncurses6-config SCRIPT HOST` \
PYTHON_CFLAGS=${PACKAGE_PREFIX}/include/python3.9 \
PYTHON_LDFLAGS="-L`package-get-path ncurses SHARED HOST`" \
SYSTEMD_CFLAGS=${PACKAGE_PREFIX}/include \
SYSTEMD_LDFLAGS="-L`package-get-path systemd SHARED HOST`" \
package-bootstrap-configure-install-archive \
    ac_cv_func_setns=yes \
    ac_cv_func_unshare=yes \
    --disable-all-programs \
    --disable-bash-completion \
    --disable-static \
    --enable-libuuid \
    --enable-shared \
    --with-ncursesw \
    --${ENABLE_OR_DISABLE_LIBBLKID}-libblkid \
    --${ENABLE_OR_DISABLE_LIBMOUNT}-libmount \
    --${ENABLE_OR_DISABLE_LIBSMARTCOLS}-libsmartcols \
    --${ENABLE_OR_DISABLE_LIBUUID}-libuuid \
    --${ENABLE_OR_DISABLE_PYTHON}-python \
    --${ENABLE_OR_DISABLE_SYSTEMD}-systemd
