#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

if [ "${HOST_OS}" != "macos" ] &&
   [ "${HOST_OS}" != "mingw" ]; then
    export DEPENDS="${PACKAGE_BASE_NAME}-acl-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0)"
fi

# Invoke one-shot template for bootstrap/configure/install
HAS_STRVERSCMP=yes

if [ "${HOST_OS}" = "macos" ]; then
    HAS_STRVERSCMP=no
elif [ "${HOST_OS}" = "mingw" ]; then
    FORTIFY_SOURCE_LEVEL=0
    HAS_STRVERSCMP=no
    unset DISABLE_FORTIFY_SOURCE_LEVEL
fi

DISABLE_AUTOUPDATE=TRUE \
package-bootstrap-configure-install-archive \
    ac_cv_func_strverscmp=${HAS_STRVERSCMP} \
    --disable-gcc-warnings