#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=mesa-demos
export SOURCE_PACKAGE_VERSION=8

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
PACKAGE_USR_PREFIX=${PACKAGE_USR_PREFIX}/mesa-demos \
package-cmake-install-archive \
    -DGLEW_glew_LIBRARY=`package-get-path GLEW SHARED HOST` \
    -DGLEW_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DGLUT_glu_LIBRARY=`package-get-path glu SHARED HOST` \
    -DGLUT_glut_LIBRARY=`package-get-path glut SHARED HOST` \
    -DGLUT_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DX11_dpms_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_xcb_icccm_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_xcb_icccm_LIB=`package-get-path xcb-icccm SHARED HOST` \
    -DX11_xcb_util_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_xcb_util_LIB=`package-get-path xcb-util SHARED HOST` \
    -DX11_xcb_xfixes_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_xcb_xfixes_LIB=`package-get-path xcb-xfixes SHARED HOST` \
    -DX11_xcb_xkb_LIB=`package-get-path xcb-xkb SHARED HOST` \
    -DX11_xcb_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_xcb_LIB=`package-get-path xcb SHARED HOST` \
    -DX11_xkbcommon_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_xkbcommon_LIB=`package-get-path xkbcommon SHARED HOST` \
    -DX11_xkbcommon_X11_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_xkbcommon_X11_LIB=`package-get-path xkbcommon-x11 SHARED HOST` \
    -DX11_xkbfile_LIB=`package-get-path xkbfile SHARED HOST` \
    -DX11_xkbfile_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_GL_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_GL_LIB=`package-get-path GL SHARED HOST` \
    -DX11_GLU_LIB=`package-get-path GLU SHARED HOST` \
    -DX11_ICE_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_ICE_LIB=`package-get-path ICE SHARED HOST` \
    -DX11_SM_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_SM_LIB=`package-get-path SM SHARED HOST` \
    -DX11_X11_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_X11_LIB=`package-get-path X11 SHARED HOST` \
    -DX11_X11_xcb_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_X11_xcb_LIB=`package-get-path X11-xcb SHARED HOST` \
    -DX11_Xaccessrules_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xaccessstr_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xau_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xau_LIB=`package-get-path Xau SHARED HOST` \
    -DX11_Xcursor_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xcursor_LIB=`package-get-path Xcursor SHARED HOST` \
    -DX11_Xdamage_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xdamage_LIB=`package-get-path Xdamage SHARED HOST` \
    -DX11_Xdmcp_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xdmcp_LIB=`package-get-path Xdmcp SHARED HOST` \
    -DX11_Xext_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xext_LIB=`package-get-path Xext SHARED HOST` \
    -DX11_Xfixes_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xfixes_LIB=`package-get-path Xfixes SHARED HOST` \
    -DX11_Xi_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xi_LIB=`package-get-path Xi SHARED HOST` \
    -DX11_Xinerama_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xinerama_LIB=`package-get-path Xinerama SHARED HOST` \
    -DX11_Xkb_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xkblib_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xlib_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xmu_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xmu_LIB=`package-get-path Xmu SHARED HOST` \
    -DX11_Xrandr_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xrandr_LIB=`package-get-path Xrandr SHARED HOST` \
    -DX11_Xrender_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xrender_LIB=`package-get-path Xrender SHARED HOST` \
    -DX11_Xshape_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xt_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xt_LIB=`package-get-path Xt SHARED HOST` \
    -DX11_Xtst_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xtst_LIB=`package-get-path Xtst SHARED HOST` \
    -DX11_Xutil_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_Xxf86vm_LIB=`package-get-path Xxf86vm SHARED HOST` \
    -DX11_Xxf86vm_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_XShm_INCLUDE_PATH=${PACKAGE_PREFIX}/include \
    -DX11_XSync_INCLUDE_PATH=${PACKAGE_PREFIX}/include
