#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# python-wheel build
package-invoke-builder python-wheel-cross 0

# python-cython build
package-invoke-builder python-cython-cross 0

# python-distro build
package-invoke-builder python-distro-cross 1

# python-gpgme build
package-invoke-builder python-gpgme-cross 0

# python-jinja build
package-invoke-builder python-jinja-cross 3

# python-lxml build
package-invoke-builder python-lxml-cross 4

# python-mako build
package-invoke-builder python-mako-cross 1

# python-markdown build
package-invoke-builder python-markdown-cross 3

# python-markupsafe build
package-invoke-builder python-markupsafe-cross 2

# python-meson build
package-invoke-builder python-meson-cross 0

# python-scikit-build build
package-invoke-builder python-scikit-build-cross 0

# python-mpmath build
package-invoke-builder python-mpmath-cross 1

# python-numpy build
package-invoke-builder python-numpy-cross 1

# python-packaging build
package-invoke-builder python-packaging-cross 21

# python-protobuf build
package-invoke-builder python-protobuf-cross 3

# python-pybind11 build
package-invoke-builder python-pybind11-cross 2

# python-pygments build
package-invoke-builder python-pygments-cross 2

# python-pyparsing build
package-invoke-builder python-pyparsing-cross 2

# python-libcomps build
package-invoke-builder python-libcomps-cross 0

# python-six build
package-invoke-builder python-six-cross 1

# python-smartcols build
package-invoke-builder python-smartcols-cross 0

# python-sympy build
package-invoke-builder python-sympy-cross 1

# python-toml build
package-invoke-builder python-toml-cross 0

# python-tqdm build
package-invoke-builder python-tqdm-cross 4

# python-typogrify build
package-invoke-builder python-typogrify-cross 2

# python-yaml build
package-invoke-builder python-yaml-cross 6

# python-zmq build
package-invoke-builder python-zmq-cross 22

# swig build
package-invoke-builder swig-cross 4