#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=vulkan-validation-layers
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
CMAKE_XCB_CMD="-DBUILD_WSI_XCB_SUPPORT=FALSE"

if [ "${HOST_OS}" = "gnu" ]; then
    CMAKE_XCB_CMD="-DBUILD_WSI_XCB_SUPPORT=TRUE"
fi

package-cmake-install-archive \
    -DBUILD_LAYER_SUPPORT_FILES=TRUE \
    -DBUILD_WERROR=FALSE \
    -DBUILD_WSI_DIRECTFB_SUPPORT=FALSE \
    -DBUILD_WSI_WAYLAND_SUPPORT=FALSE \
    -DBUILD_WSI_XLIB_SUPPORT=FALSE \
    -DGLSLANG_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DPKG_CONFIG_EXECUTABLE=${PKG_CONFIG} \
    -DSPIRV_HEADERS_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DSPIRV_TOOLS_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DSPIRV_TOOLS_LIB=`package-get-path SPIRV-Tools STATIC HOST` \
    -DSPIRV_TOOLS_OPT_SEARCH_PATH=${PACKAGE_PREFIX} \
    -DSPIRV_TOOLS_OPT_LIB=`package-get-path SPIRV-Tools-opt STATIC HOST` \
    -DUSE_ROBIN_HOOD_HASHING=FALSE \
    -DVulkanHeaders_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DVulkanRegistry_DIR=${PACKAGE_PREFIX}/share/vulkan/registry \
    ${CMAKE_XCB_CMD}
