#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
CXX_STANDARD=14 \
package-meson-install-archive \
    -Dgtk_doc=false \
    -Dinstall-tests=false \
    -Dintrospection=disabled
