#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
function package-install-completion-callback() {
    ${RM} -f ${INSTALL_PREFIX}/bin/`package-get-filename groups EXECUTABLE HOST`
}

if [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    ENABLE_OR_DISABLE_SHADOWGRP=enable
else
    ENABLE_OR_DISABLE_SHADOWGRP=disable
fi

CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
CONFIGURE_FILE=autogen.sh \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-configure-install-archive \
    --${ENABLE_OR_DISABLE_SHADOWGRP}-shadowgrp \
    --disable-static \
    --enable-shared \
    --with-libintl-prefix=${PACKAGE_PREFIX} \
    --without-selinux
