#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
COMMON_CFLAGS="\
    -Wno-register \
    ${COMMON_CFLAGS} \
" \
INSTALL_TARGET="INSTALL_DATA=${INSTALL} INSTALL_PROGRAM=${INSTALL} install" \
package-stage-configure-install-archive
