#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=indent
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment

# Invoke one-shot template for configure/install
CFLAGS="\
    -Wno-unused-command-line-argument \
    ${CFLAGS} \
" \
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
CONFIGURE_FILE=bootstrap \
INSTALL_TARGET="CC_FOR_BUILD=${BUILD_CC} install" \
package-configure-install

# Build and install the package
package-invoke-artifact-install
