#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
package-cmake-install-archive \
    -DLIBRT= \
    -DPYTHON_EXECUTABLE=${PYTHON} \
    -DSPIRV-Headers_SOURCE_DIR=${PACKAGE_PREFIX}