#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=opengl-headers
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
${MKDIR} -p ${INSTALL_PREFIX}/include
package-rsync -ax \
              ${SOURCE_ROOT}/api/GL \
              ${INSTALL_PREFIX}/include/

# Build and install the package
package-invoke-artifact-install
