#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=icu4c
export SOURCE_PACKAGE_VERSION=68

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
if [ "${BUILD_TRIPLE}" != "${HOST_TRIPLE}" ]; then
    CROSS_BUILD_CMD="--with-cross-build=${STAGE_ROOT_BASE}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}/build"
fi

CONFIGURE_FILE_ROOT=${STAGE_ROOT}/${SOURCE_PACKAGE_NAME}/source \
RPATH_COMPONENTS="\
    ${INSTALL_PREFIX}/lib/${SHARED_LIBRARY_PREFIX}icudataswift${SHARED_LIBRARY_SUFFIX} \
    ${INSTALL_PREFIX}/lib/${SHARED_LIBRARY_PREFIX}icui18nswift${SHARED_LIBRARY_SUFFIX} \
    ${INSTALL_PREFIX}/lib/${SHARED_LIBRARY_PREFIX}icuioswift${SHARED_LIBRARY_SUFFIX} \
    ${INSTALL_PREFIX}/lib/${SHARED_LIBRARY_PREFIX}icuucswift${SHARED_LIBRARY_SUFFIX} \
" \
package-configure-install \
    --disable-extras \
    --disable-samples \
    --disable-static \
    --disable-tests \
    --enable-shared \
    --enable-tools \
    --with-library-suffix=swift \
    "${CROSS_BUILD_CMD}"

# Build and install the package
package-invoke-artifact-install
