#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=tar
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-acl-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-bzip2-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd ${STAGE_ROOT}
FORCE_UNSAFE_CONFIGURE=1 \
package-configure \
    ${SOURCE_ROOT}/configure

# Build the components
make-install

${RM} -rf ${INSTALL_PREFIX}/share/info/dir

# Build the package
deb-package-build

# Install the package
deb-package-install
