#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libgpg-error
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
copy-source-to-staging

cd ${STAGE_ROOT}

BOOTSTRAP_FILE=./autogen.sh \
package-bootstrap

package-configure \
    ${STAGE_ROOT}/configure \
    --disable-doc \
    --disable-static \
    --enable-shared

# Build the components
make-install

# Build the package
deb-package-build

# Build the package
deb-package-install
