#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
copy-source-to-staging
export-compiler-environment

TOOL_LOG=builder-invocation \
tool-log ${PERL} ${SOURCE_ROOT}/Makefile.PL
make-install \
    AR=${AR} \
    CC=${CC} \
    CCFLAGS="${CFLAGS}" \
    LD=${CCLD} \
    LDFLAGS="${CCLDFLAGS}" \
    OPTIMIZE="-O${OPTIMIZATION_LEVEL}" \
    PREFIX=${INSTALL_PREFIX} \
    RANLIB=${RANLIB}
${RM} -f `${FIND} ${INSTALL_PREFIX} | ${GREP} "\.pod"`

# Build and install the package
package-invoke-archive-install