#!/bin/bash

set -e

# Set all environment vars
export GNULIB_SRCDIR=${SOURCE_ROOT_BASE}/gnulib-0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
BOOTSTRAP_FILE=./autogen.sh \
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
package-bootstrap-configure-install-archive \
    --disable-static \
    --enable-shared
