#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=freeglut
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
CMAKE_CONFIGURE_ROOT=${SOURCE_ROOT}/freeglut/freeglut \
package-cmake-install-archive