#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

if [ "${HOST_OS}" = "gnu" ]; then
    ICONV_LIB=libc
    LIBELF_ENABLED=enabled
elif [ "${HOST_OS}" = "macos" ] ||
     [ "${HOST_OS}" = "mingw32" ]; then
    ICONV_LIB=external
    LIBELF_ENABLED=disabled
else
    ICONV_LIB=external
    LIBELF_ENABLED=enabled
fi

if [ "${HOST_OS}" != "mingw32" ]; then
    export DEPENDS="\
        ${PACKAGE_BASE_NAME}-util-linux-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
        ${DEPENDS} \
    "
fi

if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    COMMON_CFLAGS="\
        -lintl \
        ${COMMON_CFLAGS} \
    "
fi

# Invoke one-shot template for meson/install
package-meson-install-archive \
    -Diconv=${ICONV_LIB} \
    -Dlibelf=${LIBELF_ENABLED}