#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-swift-${SOURCE_PACKAGE_VERSION}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-swift-corelibs-foundation-${SOURCE_PACKAGE_VERSION}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd ${SOURCE_ROOT}

# Build the components
SWIFT_BUILD_FLAGS="\
    -Xlinker -lc++ \
    -Xlinker -licuucswift \
    -Xlinker -lncurses \
    ${SWIFT_BUILD_FLAGS} \
" \
package-swift-build

cd ${STAGE_ROOT}
${MKDIR} -p ${INSTALL_PREFIX}/bin
package-rsync -ax \
              `${FIND} -type f -name sourcekit-lsp\*` \
              ${INSTALL_PREFIX}/bin

# Build and install the package
package-invoke-archive-install
