#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=lunarg-vulkan-tools
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}
package-cmake \
    -DBUILD_WSI_DIRECTFB_SUPPORT=FALSE \
    -DBUILD_WSI_WAYLAND_SUPPORT=FALSE \
    -DBUILD_WSI_XLIB_SUPPORT=FALSE \
    -DJSONCPP_INCLUDE_DIR=/sources/spirv-headers/tools/buildHeaders/jsoncpp/dist \
    -DJSONCPP_SEARCH_PATH=/sources/spirv-headers/tools/buildHeaders/jsoncpp/dist \
    -DJSONCPP_SOURCE_DIR=/sources/spirv-headers/tools/buildHeaders/jsoncpp/dist \
    -DVkLayer_utils_LIBRARY=${PACKAGE_PREFIX}/lib/libVkLayer_utils.a \
    -DVulkan_LIBRARY=${PACKAGE_PREFIX}/lib/libvulkan-1.dll.a \
    -DVULKAN_HEADERS_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DVULKAN_LOADER_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DVULKAN_VALIDATIONLAYERS_INSTALL_DIR=${PACKAGE_PREFIX} \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build the package
deb-package-build

# Install the package
deb-package-install
