#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# coremltools build
package-invoke-builder coremltools-cross

# tensorflow build
package-invoke-builder tensorflow-cross
