#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=glib
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-util-linux-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd ${SOURCE_ROOT}
package-meson-build \
    -Diconv=external

# Build the components
cd ${STAGE_ROOT}
ninja-install

# Build the package
deb-package-build

# Build the package
deb-package-install
