#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=mtdev
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
BOOTSTRAP_FILE=autogen.sh \
package-bootstrap-configure-install-archive \
    --disable-static \
    --enable-shared
