#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=xcbproto
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
function package-install-completion-callback() {
    ${SED} -i \
           's/${PYTHON_PREFIX}/${prefix}/g' \
	   ${INSTALL_PREFIX}/lib/pkgconfig/*.pc
}

export-compiler-environment-for-python

CONFIGURE_FILE=autogen.sh \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-configure-install-archive
