#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=xxhash
export SOURCE_PACKAGE_VERSION=0.8.0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export-compiler-environment
generate-compiler-tools

# Configure the build components
copy-source-to-staging

# Build the components
cd ${STAGE_ROOT}
make-install \
    AR=${AR} \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    PREFIX=${PACKAGE_PREFIX} \
    RANLIB=${RANLIB}

# Build the package
deb-package-build

# Install the package
deb-package-install
