#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-bzip2-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

# Invoke one-shot template for cmake/install
if [ "${HOST_OS}" != "gnu" ]; then
    export DEPENDS="\
        ${PACKAGE_BASE_NAME}-libiconv-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
        ${DEPENDS} \
    "
fi

if [ "${HOST_OS}" != "macos" ] &&
   [ "${HOST_OS}" != "mingw32" ]; then
    export DEPENDS="\
        ${PACKAGE_BASE_NAME}-acl-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
        ${DEPENDS} \
    "
fi

ACL_LIBRARY=`package-get-path acl SHARED HOST`
BZIP2_LIBRARY=`package-get-path bz2 STATIC HOST`
LZ4_LIBRARY=`package-get-path lz4 SHARED HOST`
LIBLZMA_LIBRARY=`package-get-path lzma SHARED HOST`
LIBXML2_LIBRARY=`package-get-path xml2 SHARED HOST`
ZLIB_LIBRARY=`package-get-path z SHARED HOST`
ZSTD_LIBRARY=`package-get-path zstd SHARED HOST`

package-cmake-install-archive \
    -DACL_LIBRARY=${ACL_LIBRARY} \
    -DBZIP2_LIBRARY_DEBUG=${BZIP2_LIBRARY} \
    -DBZIP2_LIBRARY_RELEASE=${BZIP2_LIBRARY} \
    -DENABLE_CAT_SHARED=TRUE \
    -DENABLE_CPIO_SHARED=TRUE \
    -DENABLE_LibGCC=FALSE \
    -DENABLE_TAR_SHARED=TRUE \
    -DENABLE_TEST=FALSE \
    -DLZ4_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DLZ4_LIBRARY=${LZ4_LIBRARY} \
    -DLIBLZMA_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DLIBLZMA_LIBRARY=${LIBLZMA_LIBRARY} \
    -DLIBXML2_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DLIBXML2_LIBRARY=${LIBXML2_LIBRARY} \
    -DZLIB_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DZLIB_LIBRARY=${ZLIB_LIBRARY} \
    -DZLIB_WINAPI_EXITCODE=0 \
    -DZLIB_WINAPI_EXITCODE__TRYRUN_OUTPUT=1 \
    -DZSTD_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DZSTD_LIBRARY=${ZSTD_LIBRARY}