#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libffi
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
SDK_PLATFORM_DIR=`${ECHO} ${SYSTEM_NAME} | ${TR} '[:upper:]' '[:lower:]'`

if [ "${SDK_PLATFORM_DIR}" = "windows" ]; then
    SYMVER_CMD="--disable-symvers"
fi

package-stage-configure-install \
    --disable-static \
    --enable-shared \
    "${SYMVER_CMD}"

# Build and install the package
package-invoke-artifact-install
