#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=bash
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-acl-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-bzip2-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd ${STAGE_ROOT}

if [ "${HOST_OS}" = "musl" ]; then
    MALLOC_CMD="--without-bash-malloc"
fi

package-configure \
    ${SOURCE_ROOT}/configure \
    ${MALLOC_CMD}

# Build the components
NUM_PROCESSORS=1 \
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
