#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=sqlite
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Invoke one-shot template for stage/configure/install
package-stage-configure-install \
    lt_cv_deplibs_check_method=pass_all \
    --disable-static \
    --enable-shared