#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=gperf
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
CXXFLAGS="\
    -std=c++11 \
    ${CXXFLAGS} \
" \
package-configure-install