#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for python/build/install
${ECHO} "\
[global]
skip_check_zmq=True
zmq_prefix=${PACKAGE_PREFIX}
" > ${STAGE_ROOT}/setup.cfg
package-python-install-archive