#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swig
export SOURCE_PACKAGE_VERSION=4.0.2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-lua-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-pcre-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-python-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
copy-source-to-staging
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${STAGE_ROOT}/configure

cd ${STAGE_ROOT}
PCRE_CFLAGS=`echo "\
    -I${PACKAGE_PREFIX}/include \
    -L${PACKAGE_PREFIX}/lib \
" | xargs` \
PCRE_LIBS="-lpcre" \
package-configure \
    ${STAGE_ROOT}/configure \
    --disable-static \
    --enable-shared

# Build the components
make-build swig
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
