#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-corelibs-foundation
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-curl-7-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-icu4c-68-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-libxml2-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-llvm-project-13-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-swift-${SOURCE_PACKAGE_VERSION}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd ${STAGE_ROOT}
package-cmake \
    -Ddispatch_DIR=${STAGE_ROOT_BASE}/swift-corelibs-libdispatch-${SOURCE_PACKAGE_VERSION}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}/cmake/modules \
    -DICU_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DICU_LIBRARY=`package-get-path icudataswift SHARED HOST` \
    -DICU_I18N_LIBRARY_RELEASE=`package-get-path icui18nswift SHARED HOST` \
    -DICU_UC_LIBRARY_RELEASE=`package-get-path icuucswift SHARED HOST` \
    -DCURL_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DCURL_LIBRARY=`package-get-path curl SHARED HOST` \
    -DLIBXML2_INCLUDE_DIR=${PACKAGE_PREFIX}/include/libxml2 \
    -DLIBXML2_LIBRARY=`package-get-path xml2 SHARED HOST` \
    -DOPENSSL_CRYPTO_LIBRARY=`package-get-path crypto SHARED HOST` \
    -DOPENSSL_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DOPENSSL_SSL_LIBRARY=`package-get-path ssl SHARED HOST` \
    ${SOURCE_ROOT}

# Build the components
ninja-install

SDK=${HOST_OS}

if [ "${HOST_OS}" = "android" ]; then
    ${MV} ${INSTALL_PREFIX}/lib/swift/linux \
          ${INSTALL_PREFIX}/lib/swift/android
elif [ "${HOST_OS}" = "musl" ]; then
    ${MV} ${INSTALL_PREFIX}/lib/swift/linux \
          ${INSTALL_PREFIX}/lib/swift/musl
fi

# RPATH fixups
COMPONENT_RPATH="\$ORIGIN:\$ORIGIN/../.." \
COMPONENTS="\
    ${INSTALL_PREFIX}/lib/swift/${SDK}/${SHARED_LIBRARY_PREFIX}*${SHARED_LIBRARY_SUFFIX} \
" \
rpath-fixup

# Build and install the package
DISABLE_INSTALL_DEB=TRUE \
package-invoke-artifact-install
