#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libedit
export SOURCE_PACKAGE_VERSION=20210714-3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Invoke one-shot template for stage/configure/install
CFLAGS="\
    -D__STDC_ISO_10646__=201103L \
    -DNBBY=CHAR_BIT \
    -I${PACKAGE_PREFIX}/include/ncurses \
    ${CFLAGS} \
" \
DISABLE_AUTOUPDATE=TRUE \
RPATH_COMPONENTS="\
    ${INSTALL_PREFIX}/lib/${SHARED_LIBRARY_PREFIX}edit${SHARED_LIBRARY_SUFFIX} \
" \
package-stage-configure-install-archive \
    --disable-static \
    --enable-shared
