#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
ENABLE_GLX=yes
ENABLE_X11=true

if [ "${HOST_OS}" = "mingw" ]; then
    ENABLE_GLX=no
    ENABLE_X11=false
fi

package-meson-install-archive \
    -Ddocs=false \
    -Dglx=${ENABLE_GLX} \
    -Degl=yes \
    -Dtests=false \
    -Dx11=${ENABLE_X11}