#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=rpm
export SOURCE_PACKAGE_VERSION=4

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-lua-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-popt-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for configure/install
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
CONFIGURE_FILE=autogen.sh \
DISABLE_AUTOUPDATE=TRUE \
package-configure-install \
    --disable-static \
    --enable-shared

# Build and install the package
package-invoke-artifact-install
