#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=sdl
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-vulkan-loader-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
copy-source-to-staging

sed -i \
    's|${ANDROID_NDK}/sources/android/cpufeatures/cpu-features.c||g' \
    ${STAGE_ROOT}/CMakeLists.txt

if [ "${HOST_OS}" = "android" ]; then
    PLATFORM_CMD="-DANDROID=TRUE"
fi

${MKDIR} -p ${STAGE_ROOT}/build

cd ${STAGE_ROOT}/build
COMMON_LDFLAGS="\
    -liconv \
    ${COMMON_LDFLAGS} \
" \
package-cmake \
    "${PLATFORM_CMD}" \
    ${STAGE_ROOT}

# Build the components
ninja-install

# Build the package
deb-package-build

# Install the package
deb-package-install
