#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=openjdk
export SOURCE_PACKAGE_VERSION=16

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export-compiler-environment
generate-compiler-tools

# Configure the build components
chmod +x ${SOURCE_ROOT}/configure
mkdir -p ${STAGE_ROOT}/build

cd ${STAGE_ROOT}/build
BUILD_CFLAGS=`echo "\
    -I${BUILD_PACKAGE_PREFIX}/include \
    -L${BUILD_PACKAGE_PREFIX}/lib \
" | xargs`
BUILD_CXXFLAGS=`echo "\
    ${BUILD_CFLAGS} \
    -stdlib++-isystem ${BUILD_PACKAGE_PREFIX}/include/c++/v1 \
" | xargs`

create-host-tool ${BUILD_CC} BUILD_CFLAGS ${STAGE_ROOT}/build-clang
create-host-tool ${BUILD_CC}++ BUILD_CXXFLAGS ${STAGE_ROOT}/build-clang++
unset BUILD_CC

${SOURCE_ROOT}/configure \
    AR=${AR} \
    BUILD_CC=${STAGE_ROOT}/build-clang \
    BUILD_CXX=${STAGE_ROOT}/build-clang++ \
    MAKE=${MAKE} \
    NM=${NM} \
    OBJCOPY=${OBJCOPY} \
    OBJDUMP=${OBJDUMP} \
    READELF=${READELF} \
    STRIP=${STRIP} \
    --disable-jvm-feature-static-build \
    --disable-static-build \
    --disable-warnings-as-errors \
    --openjdk-target=${HOST_TRIPLE} \
    --prefix=${INSTALL_PREFIX} \
    --with-boot-jdk=${BUILD_PACKAGE_PREFIX} \
    --with-extra-cflags="-O${OPTIMIZATION_LEVEL}" \
    --with-extra-cxxflags="-O${OPTIMIZATION_LEVEL}" \
    --with-extra-ldflags="-O${LINKER_OPTIMIZATION_LEVEL}" \
    --with-freetype-include=${PACKAGE_PREFIX}/include \
    --with-freetype-lib=${PACKAGE_PREFIX}/lib \
    --with-stdc++lib=dynamic \
    --with-toolchain-type=clang

# Build the components
${BUILD_PACKAGE_PREFIX}/bin/make \
    JOBS=${NUM_PROCESSORS} \
    install

# Build the package
deb-package-build

# Build the package
deb-package-install
