#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=expat
export SOURCE_PACKAGE_VERSION=2.2.10

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
sed -i "s/'auto-import'/'ld'/g" ${SOURCE_ROOT}/configure

cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    --without-docbook \
    --without-examples \
    --without-tests

# Build the components
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
