#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=npm-yarn
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

${MKDIR} -p ${INSTALL_PREFIX}/bin \
            ${INSTALL_PREFIX}/lib

# Build the components
cd ${INSTALL_PREFIX}/lib
${BUILD_PACKAGE_PREFIX}/bin/npm install --no-save yarn
${LN} -sf ../lib/node_modules/.bin/yarn \
          ../lib/node_modules/.bin/yarnpkg \
          ${INSTALL_PREFIX}/bin/
${RM} ${INSTALL_PREFIX}/lib/node_modules/.package-lock.json

if [ "${HOST_OS}" = "android" ]; then
    ${SED} -i \
           's|/usr/bin/env|/system/bin/env|g' \
           `${GREP} -rl "/usr/bin/env" ${INSTALL_PREFIX}`
fi

# Build the package
deb-package-build

# Install the package
deb-package-install
