#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-syntax
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-swift-${SOURCE_PACKAGE_VERSION}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-swift-corelibs-foundation-${SOURCE_PACKAGE_VERSION}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Build the components
cd ${SOURCE_ROOT}
package-swift-build

SDK_PLATFORM_DIR=`${ECHO} ${SYSTEM_NAME} | ${TR} '[:upper:]' '[:lower:]'`

if [ "${HOST_OS}" = "android" ]; then
    SDK_PLATFORM_DIR="android"
fi

cd ${STAGE_ROOT}
${MKDIR} -p ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/${HOST_PROCESSOR}/
package-rsync -ax \
              release/Swift*.swiftdoc \
              ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/${HOST_PROCESSOR}/
package-rsync -ax \
              release/Swift*.swiftmodule \
              ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/${HOST_PROCESSOR}/
package-rsync -ax \
              release/${STATIC_LIBRARY_PREFIX}Swift*${STATIC_LIBRARY_SUFFIX} \
              ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/

# Build and install the package
package-invoke-archive-install
