#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=pcre
export SOURCE_PACKAGE_VERSION=8

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
${MKDIR} -p ${INSTALL_PREFIX}/lib/pkgconfig
${ECHO} "
V=${SOURCE_PACKAGE_VERSION}
R=${SOURCE_PACKAGE_VERSION}

prefix=${PACKAGE_PREFIX}
INSTALL_INC=\${prefix}/include
INSTALL_LIB=\${prefix}/lib
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: libpcre
Description: PCRE - Perl compatible regular expressions C library with 8 bit character support
Version: \${R}
Requires:
Libs: -L\${libdir} -lpcre
Cflags: -I\${includedir}
" > ${INSTALL_PREFIX}/lib/pkgconfig/libpcre.pc

if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "mingw32" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    HAVE_STRTOQ=FALSE
else
    HAVE_STRTOQ=TRUE
fi

cd ${STAGE_ROOT}
package-cmake \
    -DHAVE_STRTOQ=${HAVE_STRTOQ} \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build and install the package
package-invoke-archive-install
