#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libsecret
export SOURCE_PACKAGE_VERSION=0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${SOURCE_ROOT}
package-meson-build \
    -Dgcrypt=false \
    -Dgtk_doc=false \
    -Dintrospection=false \
    -Dmanpage=false

# Build the components
cd ${STAGE_ROOT}
ninja-install

# Build and install the package
package-invoke-artifact-install
