#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=curl
export SOURCE_PACKAGE_VERSION=7

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-libssh2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-openssl-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd ${STAGE_ROOT}
package-cmake \
    -DBUILD_SHARED_LIBS=TRUE \
    -DBUILD_TESTING=FALSE \
    -DCURL_TARGET_WINDOWS_VERSION=0x0A00 \
    -DHAVE_POLL_FINE_EXITCODE=0 \
    -DHAVE_POLL_FINE_EXITCODE__TRYRUN_OUTPUT=1 \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build the package
deb-package-build

# Install the package
deb-package-install
