#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-bzip2-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-tar-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

# Invoke one-shot template for stage/configure/install
if [ "${BUILD_TRIPLE}" != "${HOST_TRIPLE}" ]; then
    CROSS_COMPILING=yes
else
    CROSS_COMPILING=no
fi

ADMIN_DIR=/var/lib/dpkg
CONFIGURE_HOST_KERNEL=${HOST_KERNEL}

if [ "${HOST_OS}" = "android" ]; then
    ADMIN_DIR=/data/local/tmp
    COMMON_CFLAGS="\
        -lobstack \
        ${COMMON_CFLAGS} \
    "
    CONFIGURE_HOST_KERNEL=unknown
elif [ "${HOST_OS}" = "mingw" ]; then
    ADMIN_DIR=/
    CONFIGURE_HOST_KERNEL=unknown
elif [ "${HOST_OS}" = "musl" ]; then
    COMMON_CFLAGS="\
        -lobstack \
        ${COMMON_CFLAGS} \
    "
fi

CONFIGURE_HOST_TRIPLE=${HOST_PROCESSOR}-${CONFIGURE_HOST_KERNEL}-gnu \
CXX_STANDARD=14 \
TAR=tar \
BOOTSTRAP_FILE=./autogen \
package-bootstrap-configure-install-archive \
    cross_compiling=${CROSS_COMPILING} \
    --disable-dselect \
    --with-admindir=${ADMIN_DIR}
