#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=coreutils
export SOURCE_PACKAGE_VERSION=8

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

if [ "${HOST_OS}" != "macos" ] &&
   [ "${HOST_OS}" != "mingw32" ]; then
    export DEPENDS="\
        ${PACKAGE_BASE_NAME}-acl-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
        ${PACKAGE_BASE_NAME}-attr-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
    "
fi

# Invoke one-shot template for stage/configure/install
DISABLE_AUTOUPDATE=TRUE \
FORCE_UNSAFE_CONFIGURE=1 \
package-stage-configure-install-archive \
    --with-openssl