#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
function package-install-completion-callback() {
    ${MKDIR} -p ${INSTALL_PREFIX}/lib/pkgconfig

    ${ECHO} "\
V=${SOURCE_PACKAGE_VERSION}.3.3
R=${SOURCE_PACKAGE_VERSION}.3.3

prefix=${PACKAGE_PREFIX}
INSTALL_INC=\${prefix}/include
INSTALL_LIB=\${prefix}/lib
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: CUPS
Description: Common UNIX printer system
Version: \${R}
Requires:
Libs: -L\${libdir} -lcups
Cflags: -I\${includedir}
" > ${INSTALL_PREFIX}/lib/pkgconfig/cups.pc
}

ENABLE_OR_DISABLE_GSSAPI=disable
ENABLE_OR_DISABLE_SYSTEMD=disable

if [ "${HOST_OS}" = "gnu" ]; then
    ENABLE_OR_DISABLE_GSSAPI=enable
    ENABLE_OR_DISABLE_SYSTEMD=enable
fi

if [ "${HOST_OS}" = "macos" ]; then
    CODE_SIGN="`package-get-path codesign EXECUTABLE BUILD` -f"
    ENABLE_LIBTOOL_CMD="--enable-libtool_unsupported=${LIBTOOL}"
fi

COMMON_CFLAGS="\
    -L${PACKAGE_PREFIX}/lib \
    ${COMMON_CFLAGS} \
" \
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
DISABLE_LIBTOOLIZE=TRUE \
KRB5CONFIG=`package-get-path krb5-config SCRIPT HOST` \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-configure-install-archive \
    ac_cv_path_CODE_SIGN="${CODE_SIGN}" \
    --disable-static \
    --enable-shared \
    --with-dbusdir=${PACKAGE_PLATFORM_SYSROOT}/etc/dbus-1 \
    --with-icondir=${PACKAGE_PREFIX}/share/icons \
    --with-menudir=${PACKAGE_PREFIX}/share/applications \
    --with-rcdir=${PACKAGE_PLATFORM_SYSROOT}/etc \
    --with-systemd=${PACKAGE_PLATFORM_SYSROOT}/lib/systemd \
    --${ENABLE_OR_DISABLE_GSSAPI}-gssapi \
    --${ENABLE_OR_DISABLE_SYSTEMD}-systemd \
    ${ENABLE_LIBTOOL_CMD}