#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=ldns
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Invoke one-shot template for stage/configure/install
DISABLE_AUTOUPDATE=TRUE \
ENABLE_LIBTOOLIZE=TRUE \
LDFLAGS="\
    -lssl \
    ${LDFLAGS} \
" \
package-stage-configure-install-archive \
    --disable-static \
    --enable-shared \
    --with-ssl=${PACKAGE_PREFIX}
