#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=go
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

copy-source-to-staging

# Configure the build components
CGO_ENABLED=0 \
export-compiler-environment
generate-compiler-tools

export CC_FOR_TARGET=${CC}
export CXX_FOR_TARGET=${CXX}
export CC=${BUILD_CC}
export CXX=${BUILD_CXX}
export GOBIN=${BUILD_PACKAGE_PREFIX}/go/bin
export GOROOT_BOOTSTRAP=${BUILD_PACKAGE_PREFIX}/go
export GOROOT_FINAL=${PACKAGE_PREFIX}/go

package-push-directory ${STAGE_ROOT}/src
    TOOL_LOG=${STAGE_ROOT}/builder-invocation \
    tool-log ${BASH} make.bash
package-pop-directory

${MKDIR} -p \
         ${INSTALL_PREFIX}/bin \
         ${INSTALL_PREFIX}/go

package-rsync -ax \
              ${STAGE_ROOT}/bin \
              ${STAGE_ROOT}/pkg \
              ${STAGE_ROOT}/src \
              ${INSTALL_PREFIX}/go

${LN} -sf \
      ../go/bin/go \
      ${INSTALL_PREFIX}/bin/go
${LN} -sf \
      ../go/bin/gofmt \
      ${INSTALL_PREFIX}/bin/gofmt

# Build and install the package
package-invoke-archive-install
