#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# wine build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder wine-cross 6

if [ "${HOST_OS}" = "mingw32" ]; then
    # dxvk-cross build
    package-invoke-builder dxvk-cross 1
fi

# vkd3d-proton-cross build
package-invoke-builder vkd3d-proton-cross 2

