#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=automake
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}

package-configure \
    ${SOURCE_ROOT}/configure

# Build the components
make-install

${RM} -rf ${INSTALL_PREFIX}/share/info/dir

# Build the package
deb-package-build

# Install the package
deb-package-install
