#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=wget
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-openssl-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-pcre-8-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
if [ "${HOST_OS}" = "mingw32" ]; then
    export LIBS="\
        -lbcrypt \
        ${LIBS} \
    "
fi

cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --with-linux-crypto \
    --with-openssl \
    --with-ssl=openssl

# Build the components
make-install

${RM} -rf ${INSTALL_PREFIX}/share/info/dir

# Build the package
deb-package-build

# Install the package
deb-package-install
