#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=vim
export SOURCE_PACKAGE_VERSION=8

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Invoke one-shot template for configure/install
CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
DISABLE_AUTOUPDATE=TRUE \
package-configure-install \
    ac_cv_small_wchar_t=yes \
    vim_cv_getcwd_broken=no \
    vim_cv_memmove_handles_overlap=yes \
    vim_cv_stat_ignores_slash=no \
    vim_cv_terminfo=yes \
    vim_cv_tgetent=yes \
    vim_cv_toupper_broken=no \
    --with-tlib=ncurses
