#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=unzip
export SOURCE_PACKAGE_VERSION=60

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export-compiler-environment
generate-compiler-tools

# Configure the build components
if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    PLATFORM=unix
elif [ "${HOST_OS}" = "mingw32" ]; then
    PLATFORM=win32
fi

# Build the components
copy-source-to-staging

cd ${STAGE_ROOT}
make-build \
    -f ${STAGE_ROOT}/${PLATFORM}/Makefile \
    prefix=${PACKAGE_PREFIX} \
    CC=${CC} \
    generic
make-install \
    -f ${STAGE_ROOT}/${PLATFORM}/Makefile \
    prefix=${PACKAGE_PREFIX} \
    CC=${CC}

# Build the package
deb-package-build

# Install the package
deb-package-install
