#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for bootstrap/configure/install
if [ "${HOST_OS}" = "macos" ]; then
    export CONFIGURE_HOST_TRIPLE=${HOST_PROCESSOR}-${HOST_KERNEL}-${DARWIN_OS}
elif [ "${HOST_OS}" = "mingw32" ]; then
    COMMON_CFLAGS="\
        -lws2_32 \
        ${COMMON_CFLAGS} \
    "
fi

BOOTSTRAP_FILE=./autogen.sh \
BUILD_COMMON_CFLAGS="\
    -L${BUILD_PACKAGE_PREFIX}/lib \
    ${BUILD_COMMON_CFLAGS} \
" \
DISABLE_LIBTOOLIZE=TRUE \
package-bootstrap-configure-install-archive \
    --disable-doc \
    --disable-static \
    --enable-shared