#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=glslang
export SOURCE_PACKAGE_VERSION=10-11

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-spirv-tools-2020-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
cd ${STAGE_ROOT}

if [ "${HOST_OS}" = "android" ]; then
    CMAKE_ANDROID_DEFINE_CMD="-DANDROID=1"
fi

package-cmake \
    -DPYTHON_EXECUTABLE=${PYTHON} \
    "${CMAKE_ANDROID_DEFINE_CMD}" \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build and install the package
package-invoke-archive-install
