#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils
export SOURCE_ROOT=${SOURCE_ROOT_BASE}/linux-5

# Configure the build components
cd ${STAGE_ROOT}
export-compiler-environment

ARCH=${HOST_PROCESSOR}

if [ "${HOST_PROCESSOR}" = "aarch64" ]; then
    ARCH=arm64
elif [ "${HOST_PROCESSOR}" = "armv7a" ]; then
    ARCH=arm
elif [ "${HOST_PROCESSOR}" = "i686" ]; then
    ARCH=x86
fi

make-build \
    -C ${SOURCE_ROOT} \
    AR=${AR} \
    ARCH=${ARCH} \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    CXX=${CXX} \
    CXXFLAGS="${CXXFLAGS}" \
    HOSTAR=${AR} \
    HOSTCC=${BUILD_CC} \
    HOSTCFLAGS="${BUILD_CFLAGS}" \
    HOSTCXX=${BUILD_CXX} \
    HOSTCXXFLAGS="${BUILD_CXXFLAGS}" \
    HOSTLD=${BUILD_LD} \
    HOSTLDFLAGS="${BUILD_LDFLAGS}" \
    INSTALL_HDR_PATH=${INSTALL_PREFIX} \
    LD=${LD} \
    LDFLAGS="${LDFLAGS}" \
    LLVM_IAS=1 \
    NM=${NM} \
    OBJCOPY=${OBJCOPY} \
    OBJDUMP=${OBJDUMP} \
    RANLIB=${RANLIB} \
    READELF=${READELF} \
    STRIP=${STRIP} \
    defconfig \
    headers_install

# Build and install the package
package-invoke-archive-install
