#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-spirv-tools-2021-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0)"

# Configure the build components
if [ "${HOST_OS}" = "android" ]; then
    CMAKE_ANDROID_DEFINE_CMD="-DANDROID=1"
fi

package-cmake-install-archive \
    -DBUILD_SHARED_LIBS=TRUE \
    -DBUILD_TESTING=FALSE \
    -DPYTHON_EXECUTABLE=${PYTHON} \
    ${CMAKE_ANDROID_DEFINE_CMD}
