#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
CMAKE_CONFIGURE_ROOT=${SOURCE_ROOT}/build/cmake \
package-cmake-install-archive