#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=lunarg-vulkan-tools
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
package-cmake-install-archive \
    -DBUILD_WSI_DIRECTFB_SUPPORT=FALSE \
    -DBUILD_WSI_WAYLAND_SUPPORT=FALSE \
    -DBUILD_WSI_XLIB_SUPPORT=FALSE \
    -DJSONCPP_INCLUDE_DIR=/sources/spirv-headers/tools/buildHeaders/jsoncpp/dist \
    -DJSONCPP_SEARCH_PATH=/sources/spirv-headers/tools/buildHeaders/jsoncpp/dist \
    -DJSONCPP_SOURCE_DIR=/sources/spirv-headers/tools/buildHeaders/jsoncpp/dist \
    -DVkLayer_utils_LIBRARY=`package-get-path VkLayer_utils STATIC HOST` \
    -DVulkan_LIBRARY=`package-get-path vulkan-1 SHARED HOST` \
    -DVULKAN_HEADERS_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DVULKAN_LOADER_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DVULKAN_VALIDATIONLAYERS_INSTALL_DIR=${PACKAGE_PREFIX}