#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=autoconf-archive
export SOURCE_PACKAGE_VERSION=2021

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
package-stage-configure-install \
    --disable-static \
    --enable-shared

# Build and install the package
package-invoke-artifact-install
