#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=gzip
export SOURCE_PACKAGE_VERSION=1.10

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
copy-source-to-staging

cd ${STAGE_ROOT}
autoreconf -fi
package-configure \
    ${STAGE_ROOT}/configure \
    --disable-static \
    --enable-shared

# Build the components
make-build

# Build the package
deb-package-build

# Build the package
deb-package-install
