#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

CONFIGURE_FILE_DIR=unix
ENABLE_OR_DISABLE_FRAMEWORK=disable
HAVE_SEH=yes
TCL_SYSTEM=Linux

if [ "${HOST_OS}" = "macos" ]; then
    TCL_SYSTEM=Darwin
    ENABLE_OR_DISABLE_FRAMEWORK=enable
elif [ "${HOST_OS}" = "mingw" ]; then
    COMMON_CFLAGS="\
        -fms-extensions \
        ${COMMON_CFLAGS} \
    "
    CONFIGURE_FILE_DIR=win

    if [ "${HOST_PROCESSOR}" = "armv7a" ] ||
       [ "${HOST_PROCESSOR}" = "i386" ] ||
       [ "${HOST_PROCESSOR}" = "i486" ] ||
       [ "${HOST_PROCESSOR}" = "i586" ] ||
       [ "${HOST_PROCESSOR}" = "i686" ] ||
       [ "${HOST_PROCESSOR}" = "i786" ]; then
       HAVE_SEH=no
    fi
fi

# Invoke one-shot template for stage/configure/install
function package-install-completion-callback() {
    # Extract TCL_VERSION from unix configure builder to set up tclsh symlink
    TCL_VERSION=`${GREP} -r TCL_VERSION= ${SOURCE_ROOT}/unix/configure.in | ${CUT} -d= -f2`
    ${LN} -sf \
          `package-get-filename ${SOURCE_PACKAGE_NAME}sh${TCL_VERSION} EXECUTABLE` \
          ${INSTALL_PREFIX}/bin/`package-get-filename ${SOURCE_PACKAGE_NAME}sh EXECUTABLE`

    # Duplicated man file with perl
    ${RM} ${INSTALL_PREFIX}/share/man/man3/Thread.3
}

CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
CONFIGURE_FILE_ROOT=${STAGE_ROOT}/${CONFIGURE_FILE_DIR} \
INSTALL_TARGET="INSTALL_ROOT=${INSTALL_ROOT} install" \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-stage-configure-install-archive \
    ac_cv_func_memmove=yes \
    tcl_cv_seh=${HAVE_SEH} \
    tcl_cv_sys_version=${TCL_SYSTEM} \
    --${ENABLE_OR_DISABLE_FRAMEWORK}-framework