#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=bash
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-acl-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-bzip2-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for configure/install
if [ "${HOST_OS}" = "musl" ]; then
    MALLOC_CMD="--without-bash-malloc"
fi

NUM_PROCESSORS=1 \
package-configure-install \
    ${MALLOC_CMD}