#!/bin/bash

set -e

SDK_PLATFORM_DIR=`echo ${SYSTEM_NAME} | tr '[:upper:]' '[:lower:]'`

# spirv headers build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-spirv-headers-cross

# spirv tools build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-spirv-tools-cross

if [ "${SDK_PLATFORM_DIR}" != "gnu" ] ||
   [ "${SDK_PLATFORM_DIR}" != "windows" ]; then
    # khr headers build
    bash ${VAL_VERDE_GH_TEAM}-platform-sdk-khr-headers-cross

    # opengl headers build
    bash ${VAL_VERDE_GH_TEAM}-platform-sdk-opengl-headers-cross
fi

if [ "${SDK_PLATFORM_DIR}" != "gnu" ]; then
    # egl headers build
    bash ${VAL_VERDE_GH_TEAM}-platform-sdk-egl-headers-cross

    # opengl-es headers build
    bash ${VAL_VERDE_GH_TEAM}-platform-sdk-opengl-es-headers-cross
fi

# glslang build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-glslang-cross

# vulkan headers build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-vulkan-headers-cross

# vulkan loader build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-vulkan-loader-cross

# vulkan tools build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-vulkan-tools-cross

# vulkan validation layers build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-vulkan-validation-layers-cross

if [ "${HOST_OS}" = "gnu" ]; then
    # mesa build
    MESON=/usr/bin/meson \
    bash ${VAL_VERDE_GH_TEAM}-platform-sdk-mesa-cross
fi

# sdl build
DXSDK_DIR=${SYSROOT} \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sdl-cross

# filament build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-filament-cross
