#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=vulkan-tools
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="${PACKAGE_BASE_NAME}-vulkan-loader-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
cd ${STAGE_ROOT}

CMAKE_XCB_CMD="-DBUILD_WSI_XCB_SUPPORT=TRUE"
CUBE_WSI_SELECTION=XCB

if [ "${HOST_OS}" = "android" ]; then
    CMAKE_ANDROID_DEFINE_CMD="-DANDROID=1"
    CUBE_WSI_SELECTION=Display
    CMAKE_XCB_CMD="-DBUILD_WSI_XCB_SUPPORT=FALSE"
elif [ "${HOST_OS}" = "mingw32" ]; then
    CMAKE_XCB_CMD="-DBUILD_WSI_XCB_SUPPORT=FALSE"
    LIB_SUFFIX=dll.a
    LIB_VERSION_SUFFIX=-1
    export LIBS="\
        -lgdi32 \
        ${LDFLAGS} \
    "
else
    LIB_SUFFIX=so
fi

package-cmake \
    -DBUILD_CUBE=FALSE \
    -DBUILD_ICD=FALSE \
    -DBUILD_WSI_DIRECTFB_SUPPORT=FALSE \
    -DBUILD_WSI_WAYLAND_SUPPORT=FALSE \
    -DBUILD_WSI_XLIB_SUPPORT=FALSE \
    -DCUBE_WSI_SELECTION=${CUBE_WSI_SELECTION} \
    -DGLSLANG_VALIDATOR=${BUILD_PACKAGE_PREFIX}/bin/glslangValidator \
    -DPKG_CONFIG_EXECUTABLE=${PKG_CONFIG} \
    -DVulkan_LIBRARY=${PACKAGE_PREFIX}/lib/libvulkan${LIB_VERSION_SUFFIX}.${LIB_SUFFIX} \
    "${CMAKE_ANDROID_DEFINE_CMD}" \
    "${CMAKE_XCB_CMD}" \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build the package
deb-package-build

# Install the package
deb-package-install
