#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=spice
export SOURCE_PACKAGE_VERSION=0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
package-meson-install-archive \
    -Dgstreamer=no \
    -Dsasl=false
