#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=yautja-server
export SOURCE_PACKAGE_VERSION=1.0.0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export INSTALL_PREFIX=${INSTALL_ROOT}${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk/web/${SOURCE_PACKAGE_NAME}

export-compiler-environment

# Configure & build the package
copy-source-to-staging
cd ${STAGE_ROOT}
yarn-build

${MKDIR} -p ${INSTALL_PREFIX}
${RSYNC} -aPx \
         ${STAGE_ROOT}/ \
         ${INSTALL_PREFIX}/

# Build the package
deb-package-build

# Install the package
deb-package-install
