#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
COMMON_CFLAGS="\
    -DHAVE_DECL_ASPRINTF=1 \
    -DHAVE_DECL_SNPRINTF=1 \
    -DHAVE_DECL_VASPRINTF=1 \
    -DHAVE_DECL_VSNPRINTF=1 \
    ${COMMON_CFLAGS} \
" \
package-meson-install-archive
