#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
COMMON_CFLAGS="\
    -L${PACKAGE_PREFIX}/lib \
    ${COMMON_CFLAGS} \
" \
package-cmake-install-archive \
    -DJANSSON_BUILD_DOCS=FALSE \
    -DJANSSON_BUILD_SHARED_LIBS=TRUE \
    -DJANSSON_EXAMPLES=FALSE