#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-curl-7-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-libarchive-3-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-libmicrohttpd-0-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for stage/configure/installs
if [ "${BUILD_TRIPLE}" != "${HOST_TRIPLE}" ]; then
    I386_GENDIR_ROOT=${STAGE_ROOT_BASE}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}/build/libcpu
else
    I386_GENDIR_ROOT=.
fi

if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    COMMON_CFLAGS="\
        -lintl \
        ${COMMON_CFLAGS} \
    "
elif [ "${HOST_OS}" = "gnu" ]; then
    ARGP_LIB="yes"
else
    ARGP_LIB="-largp"
fi

DISABLED_WARNINGS="\
    -Wno-gnu-variable-sized-type-not-at-end \
    -Wno-implicit-const-int-float-conversion \
    -Wno-implicit-function-declaration \
    -Wno-logical-not-parentheses \
    -Wno-pointer-integer-compare \
    -Wno-unknown-warning-option \
    -Wno-unused-const-variable \
    -Wno-unused-parameter \
    -Wno-xor-used-as-pow \
"

COMMOM_CFLAGS="\
    ${DISABLED_WARNINGS} \
    ${COMMON_CFLAGS} \
" \
I386_GENDIR_ROOT=${I386_GENDIR_ROOT} \
RPATH_COMPONENTS="\
    ${INSTALL_PREFIX}/lib/${SHARED_LIBRARY_PREFIX}elf${SHARED_LIBRARY_SUFFIX} \
" \
package-stage-configure-install-archive \
    ac_cv_c99=yes \
    ac_cv_lib_argp_argp_parse=${ARGP_LIB} \
    ac_cv_implicit_fallthrough=no \
    --enable-debuginfod \
    --enable-maintainer-mode \
    --with-bzlib=yes \
    --with-lzma=yes \
    --with-zlib=yes
