#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libmicrohttpd
export SOURCE_PACKAGE_VERSION=0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for stage/configure/install
package-stage-configure-install \
    --disable-static \
    --enable-shared
