#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=zstd
export SOURCE_PACKAGE_VERSION=0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
package-cmake \
    ${SOURCE_ROOT}/build/cmake

# Build the components
ninja-install

# Build and install the package
package-invoke-archive-install
