#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=tensorflow
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Build the components
cd ${SOURCE_ROOT}
SETUP_PY=${SOURCE_ROOT}/tensorflow/tools/pip_package/setup.py \
package-python-build

# Remove duplicated copies of easy_install script
${RM} -rf ${INSTALL_PREFIX}/bin/easy_install*

# Build and install the package
package-invoke-artifact-install
