#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# cpio build
package-invoke-builder cpio-cross 2

# kmod build
package-invoke-builder kmod-cross 29

# kernel-image build
# package-invoke-builder kernel-image-cross 5

# busybox build
# package-invoke-builder busybox-cross 1
