#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
GL_BACKEND=gl
ENABLE_QUARTZ=disabled
ENABLE_XCB=enabled
ENABLE_XLIB=enabled

if [ "${HOST_OS}" = "android" ]; then
    GL_BACKEND=glesv3
elif [ "${HOST_OS}" = "macos" ]; then
    GL_BACKEND=disabled
    ENABLE_QUARTZ=enabled
elif [ "${HOST_OS}" = "mingw" ]; then
    GL_BACKEND=disabled
    ENABLE_XCB=disabled
    ENABLE_XLIB=disabled
fi

MESON_EXTRA_PROPERTIES="
ipc_rmid_deferred_release=false
"

package-meson-install-archive \
    -Dfontconfig=enabled \
    -Dfreetype=enabled \
    -Dgl-backend=${GL_BACKEND} \
    -Dglesv2=enabled \
    -Dglesv3=enabled \
    -Dpng=enabled \
    -Dquartz=${ENABLE_QUARTZ} \
    -Dsymbol-lookup=disabled \
    -Dtests=disabled \
    -Dxcb=${ENABLE_XCB} \
    -Dxlib=${ENABLE_XLIB} \
    -Dzlib=enabled