#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for meson/install
ENABLE_OR_DISABLE_GLX=yes

if [ "${HOST_OS}" = "mingw" ]; then
    ENABLE_OR_DISABLE_GLX=no
fi

package-meson-install-archive \
    -Ddocs=false \
    -Dglx=${ENABLE_OR_DISABLE_GLX} \
    -Degl=yes \
    -Dtests=false \
    -Dx11=true
