#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
if [ -n "${NON_PERSISTENT_ARCHIVE}" ]; then
    DISABLE_HARFBUZZ=TRUE
fi

if [ -z "${DISABLE_HARFBUZZ}" ]; then
    FT_DISABLE_HARFBUZZ=FALSE
    FT_WITH_HARFBUZZ=TRUE
    HARFBUZZ_INCLUDE_DIRS=${PACKAGE_PREFIX}/include/harfbuzz
    HARFBUZZ_LIBRARIES=`package-get-path harfbuzz SHARED HOST`
else
    FT_DISABLE_HARFBUZZ=TRUE
    FT_WITH_HARFBUZZ=FALSE
fi

package-cmake-install-archive \
    -DBUILD_SHARED_LIBS=true \
    -DFT_DISABLE_HARFBUZZ=${FT_DISABLE_HARFBUZZ} \
    -DBZIP2_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DBZIP2_LIBRARY_DEBUG=`package-get-path bz2 STATIC HOST` \
    -DBZIP2_LIBRARY_RELEASE=`package-get-path bz2 STATIC HOST` \
    -DFT_WITH_BROTLI=TRUE \
    -DFT_WITH_BZIP2=TRUE \
    -DFT_WITH_HARFBUZZ=${FT_WITH_HARFBUZZ} \
    -DFT_WITH_PNG=TRUE \
    -DFT_WITH_ZLIB=TRUE \
    -DHARFBUZZ_INCLUDE_DIRS=${HARFBUZZ_INCLUDE_DIRS} \
    -DHARFBUZZ_LIBRARIES=${HARFBUZZ_LIBRARIES} \
    -DPNG_LIBRARY_DEBUG=`package-get-path png SHARED HOST` \
    -DPNG_LIBRARY_RELEASE=`package-get-path png SHARED HOST` \
    -DPNG_PNG_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DZLIB_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DZLIB_LIBRARY_DEBUG=`package-get-path z SHARED HOST` \
    -DZLIB_LIBRARY_RELEASE=`package-get-path z SHARED HOST`