#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
package-cmake-install-archive \
    -DBoost_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DBUILD_TESTS=FALSE \
    -DCLANG_USE_LIBCPP=TRUE \
    -DWITH_WERROR=FALSE