#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

if [ "${HOST_OS}" = "mingw" ]; then
    CMAKE_STACK_PROTECTOR_CMD="-Dfstack-protector-strong=FALSE"
fi

# Invoke one-shot template for cmake/install
CXX_STANDARD=17 \
package-cmake-install-archive \
    -DBoost_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DBoost_FILESYSTEM_LIBRARY=`package-get-path boost_filesystem STATIC HOST` \
    -DBoost_LIBRARY_DIR=${PACKAGE_PREFIX}/lib \
    -DBoost_PROGRAM_OPTIONS_LIBRARY=`package-get-path boost_program_options STATIC HOST` \
    -DBoost_UNIT_TEST_FRAMEWORK=`package-get-path boost_unit_test_framework STATIC HOST` \
    -DCCACHE=`package-get-path ccache EXECUTABLE BUILD` \
    -DSTRICT_Z3_VERSION=FALSE \
    -DTESTS=FALSE \
    -DUSE_CVC4=FALSE \
    -DUSE_LD_GOLD=FALSE \
    -DZ3_DIR=${PACKAGE_PREFIX}/lib/cmake/z3 \
    ${CMAKE_STACK_PROTECTOR_CMD}
