#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for python/build/install
function package-install-completion-callback() {
    # Remove duplicated copies of easy_install script
    ${RM} -rf ${INSTALL_PREFIX}/bin/easy_install*
}

${MKDIR} -p ${STAGE_ROOT}/tensorflow/python/platform
${PYTHON} ${SOURCE_ROOT}/tensorflow/tools/build_info/gen_build_info.py --raw_generate ${STAGE_ROOT}/tensorflow/python/platform/build_info.py \
                                                                       --key_value

PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
SETUP_PY=tensorflow/tools/pip_package/setup.py \
package-python-install-archive