#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-lua-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-pcre-8-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for bootstrap/configure/install
BOOTSTRAP_FILE=./autogen.sh \
PCRE_CFLAGS=`${ECHO} "\
    -I${PACKAGE_PREFIX}/include \
    -L${PACKAGE_PREFIX}/lib \
" | ${XARGS}` \
PCRE_LIBS="-lpcre" \
package-bootstrap-configure-install-archive \
    --disable-static \
    --enable-shared \
    --without-maximum-compile-warnings
