#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=meson
export SOURCE_PACKAGE_VERSION=0.56

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Build the components
cd ${SOURCE_ROOT}
package-python-build

# Build the package
deb-package-build

# Install the package
deb-package-install
