#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=autogen
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-guile-3-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Invoke one-shot template for stage/configure/install
if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    COMMON_CFLAGS="\
        -lintl \
        ${COMMON_CFLAGS} \
    "
fi

COMMON_CFLAGS="\
    -Wno-format \
    -Wno-missing-field-initializers \
    -Wno-unknown-warning-option \
    ${COMMON_CFLAGS} \
" \
COLUMNS=${COLUMNS:-${BINDIR}/columns} \
DISABLE_AUTOUPDATE=TRUE \
package-stage-configure-install-archive \
    ag_cv_run_strcspn=yes \
    libopts_cv_with_libregex=yes \
    --disable-dependency-tracking \
    --disable-static \
    --enable-shared \
    --with-regex-header=${SOURCE_ROOT_BASE}/gnulib-0/lib/regex.h
