#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libdb
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
copy-source-to-staging

cd ${STAGE_ROOT}/dist
package-autoreconf -fi
cd ${STAGE_ROOT}
package-configure \
    ${STAGE_ROOT}/dist/configure \
    cross_compiling=yes \
    --disable-doc \
    --disable-static \
    --enable-shared

# Build the components
make-build

INSTALL_TARGET="install_include install_lib install_utilities" \
make-install

# Build the package
deb-package-build

# Build the package
deb-package-install
