#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
if [ "${HOST_OS}" = "macos" ]; then
    PYTHON_INCLUDE_DIR=${PACKAGE_PLATFORM_SYSROOT}/System/Library/Frameworks/Python.framework/Versions/${PYTHON_VERSION}/include/python${PYTHON_VERSION}
else
    PYTHON_INCLUDE_DIR=${PACKAGE_PREFIX}/include/python${PYTHON_VERSION}
fi

export-compiler-environment-for-build-tools
export-compiler-environment-for-python
package-cmake-install-archive \
    -D_GPGMECONFIG_EXECUTABLE=`package-get-path gpgme-config SCRIPT HOST` \
    -DCURL_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DCURL_LIBRARY=`package-get-path curl SHARED HOST` \
    -DENABLE_DOCS=FALSE \
    -DENABLE_TESTS=FALSE \
    -DPYTHON_EXECUTABLE=${PYTHON} \
    -DPYTHON_INCLUDE_DIR=${PYTHON_INCLUDE_DIR} \
    -DPYTHON_LIBRARY=`package-get-path python${PYTHON_VERSION} SHARED HOST` \
    -DWITH_ZCHUNK=FALSE