#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=gdbm
export SOURCE_PACKAGE_VERSION=1.18.1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure

cd ${STAGE_ROOT}

COMMON_LDFLAGS="\
    -Wl,-allow-multiple-definition \
    ${COMMON_LDFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-static \
    --enable-shared

# Build the components
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
