#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# android ndk headers build
package-invoke-builder android-ndk-headers

# android compiler-rt build (for host)
package-invoke-builder compiler-rt-cross

# android ndk runtime build
package-invoke-builder android-ndk-runtime

# android libcxx build
package-invoke-builder libcxx-bootstrap

# android llvm dependencies build
category-invoke-builder llvm-dependencies-android

# android llvm build
package-invoke-builder llvm-project-android

# android souper build
package-invoke-builder souper-cross

# android cmark build
package-invoke-builder swift-cmark-cross

# android swift build
package-invoke-builder swift-android

# android lldb build
package-invoke-builder swift-lldb-android

# swift sdk build
DISABLE_FORTIFY_SOURCE_LEVEL=TRUE \
category-invoke-builder swift-sdk-cross

# android go build
package-invoke-builder go-cross

# android graphics sdk build
category-invoke-builder graphics-sdk-cross

# android virtualization sdk build
# package-invoke-builder virtualization-sdk-cross

# android node + sdk build
package-invoke-builder node-cross
package-invoke-builder npm-yarn-cross

# android blockchain sdk build
package-invoke-builder blockchain-sdk-cross
