#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_BASE_NAME=android-ndk
export SOURCE_PACKAGE_NAME=${SOURCE_PACKAGE_BASE_NAME}-headers
export SOURCE_PACKAGE_VERSION=${ANDROID_NDK_VERSION}

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export ANDROID_NDK_STAGE_ROOT=${TEMPDIR}/org.${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_BASE_NAME}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}
export TOOLCHAIN_ROOT=${ANDROID_NDK_STAGE_ROOT}/${BUILD_PACKAGE_PREFIX}/android-ndk-${ANDROID_NDK_VERSION}/toolchains/llvm/prebuilt/${BUILD_KERNEL}-${BUILD_PROCESSOR}
export INCLUDES_PATH=${TOOLCHAIN_ROOT}/sysroot/usr/include

# Configure the build components
${MKDIR} -p ${INSTALL_PREFIX}/include
${RSYNC} -ax \
         ${INCLUDES_PATH}/${HOST_PROCESSOR}-${HOST_KERNEL}-${HOST_OS}/asm \
         ${INCLUDES_PATH}/*.h \
         ${INCLUDES_PATH}/android \
         ${INCLUDES_PATH}/arpa \
         ${INCLUDES_PATH}/asm-generic \
         ${INCLUDES_PATH}/bits \
         ${INCLUDES_PATH}/linux \
         ${INCLUDES_PATH}/net \
         ${INCLUDES_PATH}/netinet \
         ${INCLUDES_PATH}/netpacket \
         ${INCLUDES_PATH}/sys \
         ${INSTALL_PREFIX}/include

# Remove iconv and zlib components as they are rebuilt.
${RM} -f ${INSTALL_PREFIX}/include/iconv.h \
         ${INSTALL_PREFIX}/include/zconf.h \
         ${INSTALL_PREFIX}/include/zlib.h \
         ${INSTALL_PREFIX}/include/sys/capability.h

# Build the package
deb-package-build

# Install the package
deb-package-install
