#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# android autoconf build
package-invoke-builder autoconf-cross

# android automake build
package-invoke-builder automake-cross

# android autoconf-archive build
package-invoke-builder autoconf-archive-cross

# android argp-standalone build
package-invoke-builder argp-standalone-cross

# android musl obstack build
package-invoke-builder musl-obstack

# android libxcrypt build
package-invoke-builder libxcrypt-cross

# android zlib build
package-invoke-builder zlib-cross

# android bzip2 build
package-invoke-builder bzip2-cross

# android gzip build
package-invoke-builder gzip-cross

# android lz4 build
package-invoke-builder lz4-cross

# android xxhash build
package-invoke-builder xxhash-cross

# android zip build
package-invoke-builder zip-cross

# android zstd build
package-invoke-builder zstd-cross

# android unzip build
package-invoke-builder unzip-cross

# android help2man build
package-invoke-builder help2man-cross

# android gperf build
package-invoke-builder gperf-cross

# android libtool build
package-invoke-builder libtool-cross

# libatomic-ops build
package-invoke-builder libatomic-ops-cross

# android libffi build
package-invoke-builder libffi-cross

# android libiconv build
package-invoke-builder libiconv-cross

# android icu build
package-invoke-builder icu4c-cross

# android libunistring build
package-invoke-builder libunistring-cross

# android gc build
package-invoke-builder gc-cross

# android gmp build
package-invoke-builder gmp-cross

# android ncurses build
package-invoke-builder ncurses-cross

# android gettext build (without libxml2 and xz)
DISABLE_LIBXML2=TRUE \
DISABLE_XZ=TRUE \
FORTIFY_SOURCE_LEVEL=0 \
package-invoke-builder gettext-cross

# android xz build
package-invoke-builder xz-cross

# android libxml2 build
DISABLE_PYTHON=TRUE \
package-invoke-builder libxml2-cross

# android gettext build
FORTIFY_SOURCE_LEVEL=0 \
package-invoke-builder gettext-cross

# android texinfo build
# package-invoke-builder texinfo-cross

# guile build
package-invoke-builder guile-cross

# android make build
package-invoke-builder make-cross

# android m4 build
# package-invoke-builder m4-cross

# android ninja build
if [ "${HOST_OS_API_LEVEL}" -ge "28" ]; then
    package-invoke-builder ninja-cross
fi

# android file build
package-invoke-builder file-cross

# android gnulib build
package-invoke-builder gnulib-cross

# android libedit build
package-invoke-builder libedit-cross

# android pcre build
package-invoke-builder pcre-cross

# android mpfr build
package-invoke-builder mpfr-cross

# android mpc build
package-invoke-builder mpc-cross

# android isl build
package-invoke-builder isl-cross

# android libev build
package-invoke-builder libev-cross

# android gdbm build
package-invoke-builder gdbm-cross

# android libdb build
package-invoke-builder libdb-cross

# android tcl build
package-invoke-builder tcl-cross

# android sqlite build
package-invoke-builder sqlite-cross

# android openssl build
package-invoke-builder openssl-cross

# android libcap build
package-invoke-builder libcap-cross

# android krb5 build
package-invoke-builder krb5-cross

# android expat build
package-invoke-builder expat-cross

# android gawk build
package-invoke-builder gawk-cross

# autogen build
package-invoke-builder autogen-cross

# android libgpg-error build
package-invoke-builder libgpg-error-cross

# android libgcrypt build
package-invoke-builder libgcrypt-cross

# android indent build
package-invoke-builder indent-cross

# android util-linux build
DISABLE_PYTHON=TRUE \
DISABLE_SYSTEMD=TRUE \
package-invoke-builder util-linux-cross

# android attr build
package-invoke-builder attr-cross

# android acl build
package-invoke-builder acl-cross

# android libarchive build
package-invoke-builder libarchive-cross

# android libssh build
package-invoke-builder libssh-cross

# android libssh2 build
package-invoke-builder libssh2-cross

# android curl build
package-invoke-builder curl-cross

# android apple-mig build
package-invoke-builder apple-mig-cross

# alsa-lib build
package-invoke-builder alsa-lib-cross

# android libuv build
package-invoke-builder libuv-cross

# android ldns build
package-invoke-builder ldns-cross

# android c-ares build
package-invoke-builder c-ares-cross

# android openssh-portable build
package-invoke-builder openssh-portable-cross

# android bash build
package-invoke-builder bash-cross

# android grep build
package-invoke-builder grep-cross

# android sed build
package-invoke-builder sed-cross

# android bison build
package-invoke-builder bison-cross

# android flex build
# package-invoke-builder flex-cross

# android jq build
package-invoke-builder jq-cross

# android json-c build
package-invoke-builder json-c-cross

# android tar build
if [ "${HOST_OS_API_LEVEL}" -ge "28" ]; then
    package-invoke-builder tar-cross
fi

# android coreutils build
package-invoke-builder coreutils-cross

# android findutils build
package-invoke-builder findutils-cross

# android dpkg build
package-invoke-builder dpkg-cross

# android rsync build
package-invoke-builder rsync-cross

# android lua build
package-invoke-builder lua-cross

# android wget build
package-invoke-builder wget-cross

# android python build
_PYTHON_HOST_PLATFORM=${HOST_OS}-${HOST_PROCESSOR} \
package-invoke-builder python-cross

# android libxml2 build (with python support)
package-invoke-builder libxml2-cross

# android python sdk build
category-invoke-builder python-sdk-cross

# android libxslt build
package-invoke-builder libxslt-cross

# android libtasn1 build
package-invoke-builder libtasn1-cross

# android p11-kit build
DISABLE_SYSTEMD=TRUE \
package-invoke-builder p11-kit-cross

# android dbus build
package-invoke-builder dbus-cross

# android util-linux build (with python support)
DISABLE_SYSTEMD=TRUE \
package-invoke-builder util-linux-cross

# android nettle build
package-invoke-builder nettle-cross

# android gnutls build
package-invoke-builder gnutls-cross

# android unbound build
package-invoke-builder unbound-cross

# android libmicrohttpd build
package-invoke-builder libmicrohttpd-cross

# android elfutils build
package-invoke-builder elfutils-cross

# android strace build
# if [ "${HOST_OS_API_LEVEL}" -ge "28" ]; then
#     package-invoke-builder strace-cross
# else
#     COMMON_CFLAGS="\
#         -Dfputs_unlocked=fputs \
#         ${COMMON_CFLAGS} \
#     " \
#     package-invoke-builder strace-cross
# fi

# android glib build
package-invoke-builder glib-cross

# android gobject-introspection build
# package-invoke-builder gobject-introspection-cross

# android libsecret build
package-invoke-builder libsecret-cross

# android pkg-config build
package-invoke-builder pkg-config-cross

# android graphics server build
package-invoke-builder graphics-server-cross

# android itstool build
package-invoke-builder itstool-cross

# android gtk-doc build
package-invoke-builder gtk-doc-cross

# android graphviz build
package-invoke-builder graphviz-cross

# android cups build
package-invoke-builder cups-cross

# android apt build
package-invoke-builder apt-cross

# android popt build
package-invoke-builder popt-cross

# android rpm build
package-invoke-builder rpm-cross

# android dnf build
# package-invoke-builder dnf-cross

# android swig build
package-invoke-builder swig-cross

# android openjdk build
package-invoke-builder openjdk-cross

# openjdk jansi build
package-invoke-builder jansi-cross

# android maven build
package-invoke-builder maven-cross

# android z3 build
package-invoke-builder z3-cross

# android git build
package-invoke-builder git-cross

# android vim build
package-invoke-builder vim-cross

# android cmake build
package-invoke-builder cmake-cross

# android boost build
package-invoke-builder boost-cross

# android cereal build
package-invoke-builder cereal-cross

# android libobjc2 build
package-invoke-builder libobjc2-cross

# android patch elf
package-invoke-builder android-patch-elf-cross

# android jwasm (ml64) cross compiler build
package-invoke-builder jwasm

# android re2c build
package-invoke-builder re2c-cross

# android alive2 build
package-invoke-builder alive2-cross

# android hiredis build
package-invoke-builder hiredis-cross
