#!/bin/bash

set -e

# android zlib build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-zlib-cross

# android bzip2 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bzip2-cross

# android lz4 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-lz4-cross

# android xxhash build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xxhash-cross

# android zip build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-zip-cross

# android zstd build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-zstd-cross

# android unzip build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-unzip-cross

# android autoconf build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-autoconf-cross

# android automake build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-automake-cross

# android make build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-make-cross

# android ninja build
if [ "${HOST_OS_API_LEVEL}" -ge "28" ]; then
    bash ${VAL_VERDE_GH_TEAM}-platform-sdk-ninja-cross
fi

# android libtool build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libtool-cross

# android m4 build
# bash ${VAL_VERDE_GH_TEAM}-platform-sdk-m4-cross

# android libiconv build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libiconv-cross

# android glib build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-glib-cross

# android pkg-config build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-pkg-config-cross

# android gnulib build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gnulib-cross

# android pcre build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-pcre-cross

# android icu build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-icu4c-cross

# android xz build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xz-cross

# android libxml2 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libxml2-cross

# android libffi build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libffi-cross

# android gdbm build
CFLAGS="\
    -fcommon \
    ${CFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gdbm-cross

# android ncurses build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-ncurses-cross

# android libedit build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libedit-cross

# android sqlite3 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sqlite-cross

# android openssl build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-openssl-cross

# android libexpat build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-expat-cross

# android xorg-macros build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xorg-macros-cross

# android xorgproto build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xorg-xorgproto-cross

# android xcb-proto build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xcb-proto-cross

# android xcb-pthread-stubs build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xcb-pthread-stubs-cross

# android libuv build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libuv-cross

# android libssh2 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libssh2-cross

# android ldns build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-ldns-cross

# android openssh-portable build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-openssh-portable-cross

# android curl build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-curl-cross

# android gettext build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gettext-cross

# android attr build
CFLAGS="\
    -lintl \
    -D__THROW= \
    ${CFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-attr-cross

# android acl build
CFLAGS="\
    -lintl \
    -D__THROW= \
    ${CFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-acl-cross

# android bash build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bash-cross

# android util-linux build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-util-linux-cross

# android libarchive build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libarchive-cross

# android libmicrohttpd build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libmicrohttpd-cross

# android elfutils build
CFLAGS="\
    -lintl \
    ${CFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-elfutils-cross

# android grep build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-grep-cross

# android sed build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sed-cross

# android bison build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bison-cross

# android gawk build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gawk-cross

# android strace build
if [ "${HOST_OS_API_LEVEL}" -ge "28" ]; then
    bash ${VAL_VERDE_GH_TEAM}-platform-sdk-strace-cross
else
    CFLAGS="\
        -Dfputs_unlocked=fputs \
        ${CFLAGS} \
    " \
    bash ${VAL_VERDE_GH_TEAM}-platform-sdk-strace-cross
fi

# android gperf build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gperf-cross

# android tar build
if [ "${HOST_OS_API_LEVEL}" -ge "28" ]; then
    bash ${VAL_VERDE_GH_TEAM}-platform-sdk-tar-cross
fi

# android coreutils build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-coreutils-cross

# android findutils build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-findutils-cross

# android dpkg build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-dpkg-cross

# android rsync build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-rsync-cross

# android wget build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-wget-cross

# android python build
_PYTHON_HOST_PLATFORM=${HOST_OS}-${HOST_PROCESSOR} \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-python-cross

# android gobject-introspection build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gobject-introspection-cross

# android libsecret build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gobject-libsecret-cross

# android lua build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-lua-cross

# android swig build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swig-cross

# android z3 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-z3-cross

# android git build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-git-cross

# android vim build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-vim-cross

# android cmake build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-cmake-cross

# android patch elf
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-android-patch-elf-cross

# android jwasm (ml64) cross compiler build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-jwasm
