#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# android autoconf build
package-invoke-builder autoconf-cross 2

# android automake build
package-invoke-builder automake-cross 1

# android autoconf-archive build
package-invoke-builder autoconf-archive-cross 2022

# android argp-standalone build
package-invoke-builder argp-standalone-cross 1

# android musl obstack build
package-invoke-builder musl-obstack 1

# android libxcrypt build
package-invoke-builder libxcrypt-cross 4

# android zlib build
package-invoke-builder zlib-cross 1

# android bzip2 build
package-invoke-builder bzip2-cross 1

# android lz4 build
package-invoke-builder lz4-cross 1

# android xxhash build
package-invoke-builder xxhash-cross 0

# android zip build
package-invoke-builder zip-cross 30

# android zstd build
package-invoke-builder zstd-cross 0

# android unzip build
package-invoke-builder unzip-cross 60

# android help2man build
package-invoke-builder help2man-cross 1

# android gperf build
package-invoke-builder gperf-cross 3

# android libtool build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder libtool-cross 2

# libatomic-ops build
package-invoke-builder libatomic-ops-cross 7

# android libffi build
package-invoke-builder libffi-cross 3

# android libiconv build
package-invoke-builder libiconv-cross 1

# android icu build
package-invoke-builder icu4c-cross 71

# android libunistring build
package-invoke-builder libunistring-cross 0

# android gc build
package-invoke-builder gc-cross 8

# android gmp build
package-invoke-builder gmp-cross 6

# android ncurses build
package-invoke-builder ncurses-cross 6

# android gettext build (without libxml2 and xz)
FORTIFY_SOURCE_LEVEL=0 \
ARCHIVE_PATH=${BOOTSTRAP_ARCHIVE_PATH} \
package-invoke-builder gettext-cross 0 bootstrap-only

# android gzip build
package-invoke-builder gzip-cross 1

# android xz build
package-invoke-builder xz-cross 5

# android libxml2 build (without python)
ARCHIVE_PATH=${BOOTSTRAP_ARCHIVE_PATH} \
DISABLE_PYTHON=TRUE \
package-invoke-builder libxml2-cross 2 bootstrap-only

# android gettext build
FORTIFY_SOURCE_LEVEL=0 \
package-invoke-builder gettext-cross 0

# android texinfo build
# package-invoke-builder texinfo-cross 6

# guile build
package-invoke-builder guile-cross 3

# android make build
package-invoke-builder make-cross 4

# android m4 build
# package-invoke-builder m4-cross 1

# android ninja build
if [ "${HOST_OS_API_LEVEL}" -ge "28" ]; then
    package-invoke-builder ninja-cross 1
fi

# android file build
package-invoke-builder file-cross 5

# android libedit build
package-invoke-builder libedit-cross 20210910-3

# android readline build
package-invoke-builder readline-cross 8

# android pcre build
package-invoke-builder pcre-cross 10

# android mpfr build
package-invoke-builder mpfr-cross 4

# android mpc build
package-invoke-builder mpc-cross 1

# android isl build
package-invoke-builder isl-cross 0

# android libaio build
package-invoke-builder libaio-cross 0

# android libev build
package-invoke-builder libev-cross 4

# android gdbm build
package-invoke-builder gdbm-cross 1

# android libdb build
package-invoke-builder libdb-cross 5

# android tcl build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder tcl-cross 8

# android sqlite build
package-invoke-builder sqlite-cross 3

# android openssl build
package-invoke-builder openssl-cross 1

# android libcap build
package-invoke-builder libcap-cross 2

# android util-linux build
ARCHIVE_PATH=${BOOTSTRAP_ARCHIVE_PATH} \
package-invoke-builder util-linux-cross 2 bootstrap-only

# android e2fsprogs build
package-invoke-builder e2fsprogs-cross 1

# android krb5 build
package-invoke-builder krb5-cross 1

# android expat build
package-invoke-builder expat-cross 2

# android gawk build
package-invoke-builder gawk-cross 5

# autogen build
package-invoke-builder autogen-cross 5

# android libgpg-error build
package-invoke-builder libgpg-error-cross 1

# android libgcrypt build
package-invoke-builder libgcrypt-cross 1

# android libassuan build
package-invoke-builder libassuan-cross 2

# android gpgme build
package-invoke-builder gpgme-cross 1

# android indent build
package-invoke-builder indent-cross 2

# android attr build
package-invoke-builder attr-cross 2

# android acl build
package-invoke-builder acl-cross 2

# android libarchive build
package-invoke-builder libarchive-cross 3

# android libssh build
package-invoke-builder libssh-cross 0

# android libssh2 build
package-invoke-builder libssh2-cross 1

# android curl build
package-invoke-builder curl-cross 7

# android apple-mig build
package-invoke-builder apple-mig-cross 122

# android apple-xar build
package-invoke-builder apple-xar-cross 487

# android cctools-port-cross build
package-invoke-builder cctools-port-cross 973

# android sigtool build
package-invoke-builder sigtool-cross 0

# android libusb build
package-invoke-builder libusb-cross 1

# android libuv build
package-invoke-builder libuv-cross 1

# android ldns build
package-invoke-builder ldns-cross 1

# android c-ares build
package-invoke-builder c-ares-cross 1

# android openssh-portable build
package-invoke-builder openssh-portable-cross 9

# android bash build
package-invoke-builder bash-cross 5

# android grep build
package-invoke-builder grep-cross 3

# android sed build
package-invoke-builder sed-cross 4

# android bison build
package-invoke-builder bison-cross 3

# android flex build
# package-invoke-builder flex-cross 2

# android jq build
package-invoke-builder jq-cross 1

# android json-c build
package-invoke-builder json-c-cross 0

# android jsoncpp build
package-invoke-builder jsoncpp-cross 1

# android tar build
if [ "${HOST_OS_API_LEVEL}" -ge "28" ]; then
    package-invoke-builder tar-cross 1
fi

# android bc build
package-invoke-builder bc-cross 1

# android coreutils build
package-invoke-builder coreutils-cross 9

# android which build
package-invoke-builder which-cross 2

# android ed build
package-invoke-builder ed-cross 1

# android findutils build
package-invoke-builder findutils-cross 4

# android less build
package-invoke-builder less-cross 590

# android dpkg build
package-invoke-builder dpkg-cross 1

# android rsync build
package-invoke-builder rsync-cross 3

# android lua build
package-invoke-builder lua-cross 5

# android wget build
package-invoke-builder wget-cross 1

# android python bootstrap build
package-invoke-category-builder python-bootstrap-cross

# android libxml2 build (with python support)
package-invoke-builder libxml2-cross 2

# android libxslt build
package-invoke-builder libxslt-cross 1

# android pugixml build
package-invoke-builder pugixml-cross 1

# android xmlto build
package-invoke-builder xmlto-cross 0

# android libyaml build
package-invoke-builder libyaml-cross 0

# android libzmq build
package-invoke-builder libzmq-cross 4

# android protobuf build
package-invoke-builder protobuf-cross 3

# android python sdk build
package-invoke-category-builder python-sdk-cross

# android itstool build
package-invoke-builder itstool-cross 2

# android gtk-doc build
package-invoke-builder gtk-doc-cross 1

# android libtasn1 build
package-invoke-builder libtasn1-cross 4

# android p11-kit build
ARCHIVE_PATH=${BOOTSTRAP_ARCHIVE_PATH} \
DISABLE_SYSTEMD=TRUE \
package-invoke-builder p11-kit-cross 0

# android nettle build
package-invoke-builder nettle-cross 3

# android unbound build
package-invoke-builder unbound-cross 1

# android gnutls build
package-invoke-builder gnutls-cross 3

# android libmicrohttpd build
package-invoke-builder libmicrohttpd-cross 0

# android elfutils build
package-invoke-builder elfutils-cross 0

# android strace build
if [ "${HOST_OS_API_LEVEL}" -ge "28" ]; then
    package-invoke-builder strace-cross 5
else
    COMMON_CFLAGS="\
        -Dfputs_unlocked=fputs \
        ${COMMON_CFLAGS} \
    " \
    package-invoke-builder strace-cross 5
fi

# android glib build
package-invoke-builder glib-cross 1

# android gobject-introspection build
# package-invoke-builder gobject-introspection-cross 1

# android libsecret build
package-invoke-builder libsecret-cross 0

# android pkg-config build
package-invoke-builder pkg-config-cross 0

# android boost build
package-invoke-builder boost-cross 1

# android graphics server build
package-invoke-category-builder graphics-server-cross

# android sound sdk build
package-invoke-category-builder sound-sdk-cross

# android graphviz build
package-invoke-builder graphviz-cross 2

# android intltool build
package-invoke-builder intltool-cross 0

# android hwloc build
package-invoke-builder hwloc-cross 2

# android linux-pam build
# package-invoke-builder linux-pam-cross 1

# android p11-kit build
DISABLE_SYSTEMD=TRUE \
package-invoke-builder p11-kit-cross 0

# shadow-utils build
# package-invoke-builder shadow-utils-cross 4

# android sudo build
package-invoke-builder sudo-cross 1

# android dbus build
package-invoke-builder dbus-cross 1

# android dnf package manager category build
package-invoke-category-builder dnf-package-manager-cross

# android cups build
package-invoke-builder cups-cross 2

# android util-linux build (with python support)
DISABLE_SYSTEMD=TRUE \
package-invoke-builder util-linux-cross 2

# android apt build
package-invoke-builder apt-cross 2

# android alien package tool build
package-invoke-builder alien-package-tool-cross 8

# android AI SDK build
package-invoke-category-builder ai-sdk-cross

# android openjdk build
package-invoke-builder openjdk-cross 17

# android jansi build
package-invoke-builder jansi-cross 2

# android maven build
package-invoke-builder maven-cross 3

# android onetbb build
package-invoke-builder onetbb-cross 2021

# android z3 build
package-invoke-builder z3-cross 4

# android git build
package-invoke-builder git-cross 2

# android vim build
package-invoke-builder vim-cross 9

# android cmake build
package-invoke-builder cmake-cross 3

# android gflags build
package-invoke-builder gflags-cross 2

# android glog build
package-invoke-builder glog-cross 0

# android cereal build
package-invoke-builder cereal-cross 1

# android libobjc2 build
package-invoke-builder libobjc2-cross 2

# android patch elf
package-invoke-builder android-patch-elf-cross 1

# android jwasm (ml64) cross compiler build
package-invoke-builder jwasm 2

# android nasm build
package-invoke-builder nasm-cross 2

# android re2c build
package-invoke-builder re2c-cross 3

# android alive2 build
package-invoke-builder alive2-cross 1

# android hiredis build
package-invoke-builder hiredis-cross 1

# android ccache build
package-invoke-builder ccache-cross 4

# android distcc build
package-invoke-builder distcc-cross 3