#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# android ndk headers build
package-invoke-builder android-ndk-headers ${ANDROID_NDK_VERSION}

# android compiler-rt build (for host)
package-invoke-builder compiler-rt-cross 15

# android ndk runtime build
package-invoke-builder android-ndk-runtime ${ANDROID_NDK_VERSION}

# android libcxx build
package-invoke-builder libcxx-bootstrap 15

# android llvm dependencies build
package-invoke-category-builder llvm-dependencies-android

# android llvm build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder llvm-project-android 15 no-install

# remove libcxx, libcxxabi and libunwind as they are superceded by llvm-project.
PACKAGES_TO_MANAGE=( 'libcxx-15' 'HOST' )

package-invoke-archive-action uninstall ${PACKAGES_TO_MANAGE[@]}

# install llvm for host
PACKAGES_TO_MANAGE=( 'llvm-project-15' 'HOST'
                     'llvm-project-15-stage' 'HOST' )

package-invoke-archive-action install ${PACKAGES_TO_MANAGE[@]}

# android souper build
package-invoke-builder souper-cross 1

# android cmark build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-cmark-cross 5 none

# android swift build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-android 5

# android lldb build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-lldb-android 5

# swift sdk build
DISABLE_FORTIFY_SOURCE_LEVEL=TRUE \
package-invoke-category-builder swift-sdk-cross

# android go build
package-invoke-builder go-cross 1

# android ruby build
package-invoke-builder ruby-cross 3

# android graphics sdk build
package-invoke-category-builder graphics-sdk-cross

# android virtualization sdk build
# package-invoke-category-builder virtualization-sdk-cross

# android node + sdk build
package-invoke-builder node-cross 17
package-invoke-builder npm-yarn-cross 1

# android blockchain sdk build
package-invoke-category-builder blockchain-sdk-cross
