#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# android ndk headers build
package-invoke-builder android-ndk-headers

# android ndk runtime build
package-invoke-builder android-ndk-runtime

# android compiler-rt build (for host)
package-invoke-builder compiler-rt

# android libunwind build
package-invoke-builder libunwind-cross

# android libcxxabi build
package-invoke-builder libcxxabi-cross

# android libcxx build
package-invoke-builder libcxx-cross

# android llvm dependencies build
package-invoke-builder llvm-dependencies-android

# android llvm build
package-invoke-builder llvm-project-android

# android cmark build
package-invoke-builder swift-cmark-cross

# android swift build
package-invoke-builder swift-android

# android lldb build
package-invoke-builder swift-lldb-android

# android libdispatch build
package-invoke-builder swift-corelibs-libdispatch-cross

# remove host foundation and libdispatch to avoid module collisions
PACKAGES_TO_MANAGE=( 'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-libdispatch-5'    'BUILD' )

PACKAGE_ACTION=UNINSTALL \
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# android foundation build
package-invoke-builder swift-corelibs-foundation-cross

# android xctest build
package-invoke-builder swift-corelibs-xctest-cross

# android llbuild build
package-invoke-builder swift-llbuild-android

# android swift-tools-support-core build
package-invoke-builder swift-tools-support-core-android

# android yams build
package-invoke-builder yams-cross

# android swift-argument-parser build
package-invoke-builder swift-argument-parser-cross

# android swift-driver build
package-invoke-builder swift-driver-cross

# android swiftpm build
package-invoke-builder swift-package-manager-cross

# reinstall swiftpm for build and host
PACKAGES_TO_MANAGE=( 'swift-argument-parser-5'         'BUILD' \
                     'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-libdispatch-5'    'BUILD' \
                     'swift-corelibs-xctest-5'         'BUILD' \
                     'swift-driver-5'                  'BUILD' \
                     'swift-llbuild-5'                 'BUILD' \
                     'swift-package-manager-5'         'BUILD' \
                     'swift-tools-support-core-5'      'BUILD' \
                     'yams-3'                          'BUILD' \
                     'swift-argument-parser-5'         'HOST' \
                     'swift-corelibs-foundation-5'     'HOST' \
                     'swift-corelibs-libdispatch-5'    'HOST' \
                     'swift-corelibs-xctest-5'         'HOST' \
                     'swift-driver-5'                  'HOST' \
                     'swift-llbuild-5'                 'HOST' \
                     'swift-package-manager-5'         'HOST' \
                     'swift-tools-support-core-5'      'HOST' \
                     'yams-3'                          'HOST' )

PACKAGE_ACTION=INSTALL \
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# android swift-syntax build
package-invoke-builder swift-syntax-cross

# android swift-format build
package-invoke-builder swift-format-cross

# android swift-doc build
package-invoke-builder swift-doc-cross

# android sourcekit-lsp build
package-invoke-builder sourcekit-lsp-android

# android baikonur build
package-invoke-builder baikonur

# android pythonkit build
package-invoke-builder pythonkit-cross

# android graphics sdk build
package-invoke-builder graphics-sdk-cross

# android node + sdk build
package-invoke-builder node-cross
package-invoke-builder npm-yarn-cross

# android rust build
# package-invoke-builder rust-cross
