#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_BASE_NAME=android-ndk

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

ANDROID_NDK_BUILD_PROCESSOR=x86_64
TOOLCHAIN_ROOT=${BUILD_PACKAGE_PREFIX}/share/${SOURCE_PACKAGE_BASE_NAME}-${ANDROID_NDK_VERSION}/toolchains/llvm/prebuilt/${BUILD_KERNEL}-${ANDROID_NDK_BUILD_PROCESSOR}
INCLUDES_PATH=${TOOLCHAIN_ROOT}/sysroot/usr/include

# Configure the build components
${MKDIR} -p ${INSTALL_PREFIX}/include
package-rsync -ax \
              ${INCLUDES_PATH}/${HOST_PROCESSOR}-${HOST_KERNEL}-${HOST_OS}/asm \
              ${INCLUDES_PATH}/*.h \
              ${INCLUDES_PATH}/aaudio \
              ${INCLUDES_PATH}/android \
              ${INCLUDES_PATH}/arpa \
              ${INCLUDES_PATH}/asm-generic \
              ${INCLUDES_PATH}/bits \
              ${INCLUDES_PATH}/linux \
              ${INCLUDES_PATH}/net \
              ${INCLUDES_PATH}/netinet \
              ${INCLUDES_PATH}/netpacket \
              ${INCLUDES_PATH}/sys \
              ${INCLUDES_PATH}/SLES \
              ${INSTALL_PREFIX}/include/

# Remove iconv and zlib components as they are rebuilt.
${RM} -f ${INSTALL_PREFIX}/include/iconv.h \
         ${INSTALL_PREFIX}/include/zconf.h \
         ${INSTALL_PREFIX}/include/zlib.h \
         ${INSTALL_PREFIX}/include/sys/capability.h

${PATCH} -p1 \
         -i ${SOURCE_ROOT_BASE}/android-ndk-patches-1/android-ndk-dirent-versionsort.diff \
         ${INSTALL_PREFIX}/include/dirent.h
${PATCH} -p1 \
         -i ${SOURCE_ROOT_BASE}/android-ndk-patches-1/android-ndk-string-strverscmp.diff \
         ${INSTALL_PREFIX}/include/string.h
${PATCH} -p1 \
         -i ${SOURCE_ROOT_BASE}/android-ndk-patches-1/android-ndk-string-ctype.diff \
         ${INSTALL_PREFIX}/include/string.h

# Build and install the package
package-invoke-archive-install