#!/bin/bash

set -e

OS_VER=${OS_VER:-20.04}
PACKAGE_BASE_NAME=${PACKAGE_BASE_NAME:-val-verde}

variantArrayCount=$((${#variantArray[@]} / 3))
prefix='openvalverde'
packageType='deb-images'
tag='val-verde-compilers'
version='1.0.0'
target=ubuntu
buildArgs=`echo "\
    --build-arg DEB_PATH=/debs \
    --build-arg PACKAGE_BASE_NAME=${PACKAGE_BASE_NAME} \
    --build-arg PACKAGE_ROOT=/opt \
    --build-arg VAL_VERDE_GH_TEAM=val-verde \
" | xargs`

docker build -f ubuntu${OS_VER}.Dockerfile -t $prefix/$target-$packageType:$tag-$version $buildArgs .
