#!/bin/bash

set -e

DISTRO=${DISTRO:-ubuntu}

if [ "${DISTRO}" == "ubuntu" ]; then
    OS_RELEASE_VERSION=${OS_RELEASE_VERSION:-'rolling'}
    PACKAGE_ARCHIVE_CLASS=${PACKAGE_ARCHIVE_CLASS:-deb}
elif [ "${DISTRO}" == "fedora" ]; then
    OS_RELEASE_VERSION=${OS_RELEASE_VERSION:-'latest'}
    PACKAGE_ARCHIVE_CLASS=${PACKAGE_ARCHIVE_CLASS:-rpm}
fi

PACKAGE_BASE_NAME=${PACKAGE_BASE_NAME:-val-verde}
PACKAGE_ROOT=${PACKAGE_ROOT:-/opt}

variantArrayCount=$((${#variantArray[@]} / 3))
prefix='openvalverde'
packageType="${PACKAGE_ARCHIVE_CLASS}-images"
tag='val-verde-compilers'
version='1.0.0'
target="${DISTRO}"
buildArgs=`echo "\
    --build-arg OS_RELEASE_VERSION=${OS_RELEASE_VERSION} \
    --build-arg PACKAGE_ARCHIVE_CLASS=${PACKAGE_ARCHIVE_CLASS} \
    --build-arg PACKAGE_BASE_NAME=${PACKAGE_BASE_NAME} \
    --build-arg PACKAGE_ROOT=${PACKAGE_ROOT} \
    --build-arg VAL_VERDE_GH_TEAM=val-verde \
" | xargs`

docker build -f ${DISTRO}.Dockerfile -t $prefix/$target-$packageType:$tag-$version $buildArgs .
