version: '3.5'

services: 
    ubuntu-builder:
        container_name: ubuntu-builder
        image: openvalverde/ubuntu20.04-deb-images:val-verde-compilers-1.0.0
        build: 
            context: ./
            dockerfile: ubuntu20.04.Dockerfile
            args:
                - PACKAGE_BASE_NAME=val-verde
                - PACKAGE_ROOT=/opt
                - DEB_PATH=${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk/debs \
                - SOURCE_ROOT_BASE=${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk/sources \
                - STAGE_ROOT_BASE=${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk/staging \
                - VAL_VERDE_GH_TEAM=val-verde
        privileged: true
