version: '3.5'

services: 
    ubuntu-builder:
        container_name: ubuntu-builder
        image: openvalverde/ubuntu-deb-images:val-verde-compilers-1.0.0
        security_opt:
            - seccomp:unconfined
        build:
            context: ./
            dockerfile: ubuntu.Dockerfile
            args:
                - PACKAGE_ARCHIVE_CLASS=deb
                - PACKAGE_BASE_NAME=dutch
                - PACKAGE_ROOT=/opt
                - VAL_VERDE_GH_TEAM=val-verde
        privileged: true
    fedora-builder:
        container_name: fedora-builder
        image: openvalverde/fedora-rpm-images:val-verde-compilers-1.0.0
        security_opt:
            - seccomp:unconfined
        build:
            context: ./
            dockerfile: fedora.Dockerfile
            args:
                - PACKAGE_ARCHIVE_CLASS=rpm
                - PACKAGE_BASE_NAME=dutch
                - PACKAGE_ROOT=/opt
                - VAL_VERDE_GH_TEAM=val-verde
        privileged: true
