version: '3.5'

services: 
    ubuntu-builder:
        container_name: ubuntu-builder
        image: openvalverde/ubuntu-deb-images:val-verde-compilers-1.0.0
        build: 
            context: ./
            dockerfile: ubuntu.Dockerfile
            args:
                - PACKAGE_BASE_NAME=val-verde
                - PACKAGE_ROOT=/opt
                - VAL_VERDE_GH_TEAM=val-verde
        privileged: true
