#!/bin/bash

set -e

variantArray=('ubuntu20.04'
              'ubuntu'
              '--build-arg BUILD_KERNEL=linux
                --build-arg BUILD_OS=gnu
                --build-arg BUILD_PROCESSOR=x86_64
                --build-arg DEB_PATH=/sources
                --build-arg HOST_KERNEL=linux
                --build-arg HOST_OS=gnu
                --build-arg HOST_PROCESSOR=x86_64
                --build-arg PACKAGE_BASE_NAME=val-verde
                --build-arg PACKAGE_ROOT=/usr/local'
              'android10'
              'android'
              '--build-arg ANDROID_NDK_PACKAGE_NAME=android-ndk-r21b
               --build-arg ANDROID_NDK_URL=https://dl.google.com/android/repository
               --build-arg BUILD_KERNEL=linux
               --build-arg BUILD_OS=gnu
               --build-arg BUILD_PROCESSOR=x86_64
               --build-arg DEB_PATH=/sources
               --build-arg HOST_KERNEL=linux
               --build-arg HOST_OS=android
               --build-arg HOST_OS_API_LEVEL=28
               --build-arg HOST_PROCESSOR=aarch64
               --build-arg PACKAGE_BASE_NAME=val-verde
               --build-arg PACKAGE_ROOT=/usr/local')

variantArrayCount=$((${#variantArray[@]} / 3))
prefix='openvalverde'
packageType='deb-images'
tag='val-verde-compilers'
version='1.0.0'

#echo $prefix/${variantArray[0]}-$packageType:$tag-$version
for i in `seq 0 $(($variantArrayCount - 1))`; do
    dirIndex=$((i * 3))
    targetIndex=$((i * 3 + 1))
    buildArgIndex=$((i * 3 + 2))
    dir=${variantArray[$dirIndex]}
    target=${variantArray[$targetIndex]}
    buildArgs=${variantArray[$buildArgIndex]}
    pushd $dir
    docker build -f $target.Dockerfile -t $prefix/$target-$packageType:$tag-$version $buildArgs .
    popd
done

