#!/bin/bash

set -e

function platform-get-builder-args() {
    OS_ARG="$(cut -d'-' -f1 <<<$1)"
    PROCESSOR_ARG="$(cut -d'-' -f2 <<<$1)"
    ECHO=/usr/bin/echo
    if [[ "${OS_ARG}" = "gnu" && "${PROCESSOR_ARG}" = "x86_64" ]]; then
        BUILD_ARGS="\
		HOST_ARCH="${BUILD_ARCH}" \
		HOST_CPU="${BUILD_CPU}" \
		HOST_KERNEL="${BUILD_KERNEL}" \
		HOST_OS="${BUILD_OS}" \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
    elif [[ "${OS_ARG}" = "gnu" && "${PROCESSOR_ARG}" = "aarch64" ]]; then
        BUILD_ARGS="\
		HOST_ARCH=armv8-a \
		HOST_CPU=apple-m1 \
		HOST_KERNEL="${BUILD_KERNEL}" \
		HOST_OS="${BUILD_OS}" \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
	elif [[ "${OS_ARG}" = "gnu" && "${PROCESSOR_ARG}" = "i686" ]]; then
        BUILD_ARGS="\
		HOST_ARCH=westmere \
		HOST_CPU=westmere \
		HOST_KERNEL="${BUILD_KERNEL}" \
		HOST_OS="${BUILD_OS}" \
		HOST_OS_API_LEVEL=32 \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
	elif [[ "${OS_ARG}" = "gnu" && "${PROCESSOR_ARG}" = "armv7a" ]]; then
        BUILD_ARGS="\
		HOST_ARCH=armv7-a+fp \
		HOST_CPU=westmere \
		HOST_KERNEL="${BUILD_KERNEL}" \
		HOST_OS="${BUILD_OS}" \
		HOST_OS_API_LEVEL=eabihf \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
    elif [[ "${OS_ARG}" = "darwin" && "${PROCESSOR_ARG}" = "x86_64" ]]; then
        BUILD_ARGS="\
		DARWIN_OS=darwin \
		DARWIN_OS_API_LEVEL=21 \
		HOST_ARCH=westmere \
		HOST_CPU=westmere \
		HOST_KERNEL=apple \
		HOST_OS=macos \
		HOST_OS_API_LEVEL="${MACOS_VERSION}" \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
    elif [[ "${OS_ARG}" = "darwin" && "${PROCESSOR_ARG}" = "aarch64" ]]; then
        BUILD_ARGS="\
		DARWIN_OS=darwin \
		DARWIN_OS_API_LEVEL=21 \
		HOST_ARCH=armv8-a \
		HOST_CPU=apple-m1 \
		HOST_KERNEL=apple \
		HOST_OS=macos \
		HOST_OS_API_LEVEL="${MACOS_VERSION}" \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
    elif [[ "${OS_ARG}" = "musl" && "${PROCESSOR_ARG}" = "x86_64" ]]; then
        BUILD_ARGS="\
		HOST_ARCH="${BUILD_ARCH}" \
		HOST_CPU="${BUILD_CPU}" \
		HOST_KERNEL="${BUILD_KERNEL}" \
		HOST_OS=musl \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
    elif [[ "${OS_ARG}" = "musl" && "${PROCESSOR_ARG}" = "aarch64" ]]; then
        BUILD_ARGS="\
		HOST_ARCH=armv8-a \
		HOST_CPU=cortex-a57 \
		HOST_KERNEL="${BUILD_KERNEL}" \
		HOST_OS=musl \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
    elif [[ "${OS_ARG}" = "wasm32" && "${PROCESSOR_ARG}" = "wasm32" ]]; then
        BUILD_ARGS="\
		HOST_ARCH=wasm32 \
		HOST_CPU=wasm32 \
		HOST_KERNEL=unknown \
		HOST_OS=wasi \
		HOST_OS_API_LEVEL= \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
    elif [[ "${OS_ARG}" = "android" && "${PROCESSOR_ARG}" = "aarch64" ]]; then
        BUILD_ARGS="\
		HOST_ARCH=armv8-a \
		HOST_CPU=cortex-a57 \
		HOST_KERNEL="${BUILD_KERNEL}" \
		HOST_OS=android \
		HOST_OS_API_LEVEL=29 \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
    elif [[ "${OS_ARG}" = "android" && "${PROCESSOR_ARG}" = "x86_64" ]]; then
        BUILD_ARGS="\
		HOST_ARCH=westmere \
		HOST_CPU=westmere \
		HOST_KERNEL="${BUILD_KERNEL}" \
		HOST_OS=android \
		HOST_OS_API_LEVEL=29 \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
    elif [[ "${OS_ARG}" = "windows" && "${PROCESSOR_ARG}" = "x86_64" ]]; then
        BUILD_ARGS="\
		HOST_ARCH=westmere \
		HOST_CPU=westmere \
		HOST_KERNEL=w64 \
		HOST_OS=mingw \
		HOST_OS_API_LEVEL=64 \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
    elif [[ "${OS_ARG}" = "windows" && "${PROCESSOR_ARG}" = "aarch64" ]]; then
        BUILD_ARGS="\
		HOST_ARCH=armv8-a \
		HOST_CPU=apple-m1 \
		HOST_KERNEL=w64 \
		HOST_OS=mingw \
		HOST_OS_API_LEVEL=64 \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
	elif [[ "${OS_ARG}" = "windows" && "${PROCESSOR_ARG}" = "i686" ]]; then
        BUILD_ARGS="\
		HOST_ARCH=westmere \
		HOST_CPU=westmere \
		HOST_KERNEL=w32 \
		HOST_OS=mingw \
		HOST_OS_API_LEVEL=32 \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
	elif [[ "${OS_ARG}" = "windows" && "${PROCESSOR_ARG}" = "armv7a" ]]; then
        BUILD_ARGS="\
		HOST_ARCH=armv7-a+fp \
		HOST_CPU=apple-m1 \
		HOST_KERNEL=w32 \
		HOST_OS=mingw \
		HOST_OS_API_LEVEL=32 \
		HOST_PROCESSOR="${PROCESSOR_ARG}" \
	"
    fi

    ${ECHO} "${BUILD_ARGS}"
}

function platform-invoke-builder() {
    PLATFORM_BUILDER_ARGS=$1
    PLATFORM_BUILDER_STAGE=$2
    
    # Extract platform builder arguments.
    BUILD_ARGS=`platform-get-builder-args ${PLATFORM_BUILDER_STAGE}`
    PLATFORM_BUILD_COMMAND=""${BUILD_ARGS}" "${BASH}" "${VAL_VERDE_GH_TEAM}-platform-sdk-${PLATFORM_BUILDER_ARGS}""
    BUILDER_COMMAND=(${PLATFORM_BUILD_COMMAND})

    # Use builder arguments to invoke platform builder.
    ECHO=/usr/bin/echo
    BASH=/usr/bin/bash
    ${ECHO} -e "Platform Builder for ${PLATFORM_BUILDER_ARGS}-${PLATFORM_BUILDER_STAGE} Invocation Started."
    ${BASH} -c "${BUILDER_COMMAND[*]}"
    ${ECHO} -e "Platform Builder for ${PLATFORM_BUILDER_ARGS}-${PLATFORM_BUILDER_STAGE} Invocation Ended."
    ${ECHO}
}

