#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=autoconf
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
if [ "${HOST_OS}" = "musl" ]; then
    CONFIGURE_HOST_TRIPLE="${HOST_PROCESSOR}-${HOST_KERNEL}-gnu"
fi

package-stage-configure-install-archive
