#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=maven
export SOURCE_PACKAGE_VERSION=3

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

MAVEN_PACKAGE_VERSION=3.8.1

# Configure the build components
package-wget -c https://mirrors.ocf.berkeley.edu/apache/${SOURCE_PACKAGE_NAME}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}/${MAVEN_PACKAGE_VERSION}/binaries/apache-${SOURCE_PACKAGE_NAME}-${MAVEN_PACKAGE_VERSION}-bin.tar.gz \
             -O ${STAGE_ROOT}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz

cd ${STAGE_ROOT}
package-tar -zxf \
            ${STAGE_ROOT}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
${MV} ${STAGE_ROOT}/apache-${SOURCE_PACKAGE_NAME}*/* \
      ${STAGE_ROOT}/
${RMDIR} ${STAGE_ROOT}/apache-${SOURCE_PACKAGE_NAME}*

${MKDIR} -p \
         ${INSTALL_PREFIX}/bin \
         ${INSTALL_PREFIX}/lib
package-rsync -aPx \
              ${STAGE_ROOT}/bin/m2.conf \
              ${STAGE_ROOT}/bin/mvn \
              ${INSTALL_PREFIX}/bin/
package-rsync -aPx \
              ${STAGE_ROOT}/boot \
              ${STAGE_ROOT}/conf \
              ${INSTALL_PREFIX}/
package-rsync -aPx \
              ${STAGE_ROOT}/lib/*.jar \
              ${INSTALL_PREFIX}/lib/

# Build and install the package
package-invoke-archive-install
