#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Build and install the package
${MKDIR} -p ${INSTALL_PREFIX}/bin/

export SOURCE_DIR=${BINDIR}

package-rsync -ax \
              ${SOURCE_DIR}/${VAL_VERDE_GH_TEAM}-platform-sdk-* \
              ${INSTALL_PREFIX}/bin/
${CHMOD} +x ${INSTALL_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-clang \
            ${INSTALL_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-clang++ \
            ${INSTALL_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-ml64

package-invoke-archive-install
