#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=glibc-interface
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
function package-install-completion-callback() {
    ${RM} -rf ${INSTALL_PREFIX}/../lib
    ${MV} ${INSTALL_PREFIX}/../lib64 \
          ${INSTALL_PREFIX}/glibc-interface
    ${LN} -sf \
          ../glibc-interface/libanl.so.1 \
          ${INSTALL_PREFIX}/lib/libanl.so
    ${LN} -sf \
          ../glibc-interface/libdl.so.2 \
          ${INSTALL_PREFIX}/lib/libdl.so
    ${LN} -sf \
          ../glibc-interface/libnsl.so.1 \
          ${INSTALL_PREFIX}/lib/libnsl.so
    ${LN} -sf \
          ../glibc-interface/libnss_compat.so.2 \
          ${INSTALL_PREFIX}/lib/libnss_compat.so
    ${LN} -sf \
          ../glibc-interface/libnss_db.so.2 \
          ${INSTALL_PREFIX}/lib/libnss_db.so
    ${LN} -sf \
          ../glibc-interface/libnss_dns.so.2 \
          ${INSTALL_PREFIX}/lib/libnss_dns.so
    ${LN} -sf \
          ../glibc-interface/libnss_files.so.2 \
          ${INSTALL_PREFIX}/lib/libnss_files.so
    ${LN} -sf \
          ../glibc-interface/libnss_hesiod.so.2 \
           ${INSTALL_PREFIX}/lib/libnss_hesiod.so
    ${LN} -sf \
          ../glibc-interface/libpthread.so.0 \
          ${INSTALL_PREFIX}/lib/libpthread.so
    ${LN} -sf \
          ../glibc-interface/libresolv.so.2 \
          ${INSTALL_PREFIX}/lib/libresolv.so
    ${LN} -sf \
          ../glibc-interface/librt.so.1 \
          ${INSTALL_PREFIX}/lib/librt.so
    ${LN} -sf \
          ../glibc-interface/libthread_db.so.1 \
          ${INSTALL_PREFIX}/lib/libthread_db.so
    ${LN} -sf \
          ../glibc-interface/libutil.so.1 \
          ${INSTALL_PREFIX}/lib/libutil.so
    ${LN} -sf \
          ../glibc-interface/libBrokenLocale.so.1 \
          ${INSTALL_PREFIX}/lib/libBrokenLocale.so

    if [ "${HOST_PROCESSOR}" = "aarch64" ]; then
        ${LN} -sf \
              ../glibc-interface/libm.so.6 \
              ${INSTALL_PREFIX}/lib/libm.so
    elif [ "${HOST_PROCESSOR}" = "x86_64" ]; then
        ${LN} -sf \
              ../glibc-interface/libmvec.so.1 \
              ${INSTALL_PREFIX}/lib/libmvec.so
        ${SED} -i \
               "s| /lib64/| ../glibc-interface/|g" \
               ${INSTALL_PREFIX}/lib/libm.so
    fi

    ${SED} -i \
           "s| /usr/lib/| |g" \
           ${INSTALL_PREFIX}/lib/libc.so
    ${SED} -i \
           "s| /lib/| ../glibc-interface/|g" \
           ${INSTALL_PREFIX}/lib/libc.so
    ${SED} -i \
           "s| /lib64/| ../glibc-interface/|g" \
           ${INSTALL_PREFIX}/lib/libc.so
}

CONFIGURE_PACKAGE_PREFIX=${PACKAGE_USR_PREFIX} \
DESTDIR=${INSTALL_PREFIX}/.. \
DISABLE_AUTOUPDATE=TRUE \
DISABLE_FORTIFY_SOURCE_LEVEL=TRUE \
DISABLE_FPIC=TRUE \
HOST_ARCH= \
HOST_CPU= \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
USE_GCC=TRUE \
package-configure-install-archive \
    libc_cv_gcc_builtin_redirection=yes \
    libc_cv_include_x86_isa_level=no \
    --disable-crypt \
    --disable-sanity-checks \
    --disable-werror \
    --enable-cet \
    --enable-kernel=4.0 \
    --libdir=/usr/lib \
    --with-headers=${PACKAGE_PREFIX}/include
