#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-zlib-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

if [ "${HOST_OS}" = "mingw" ]; then
    COMMON_CFLAGS="\
        -ltermiwin \
        ${COMMON_CFLAGS} \
    "
fi

# Invoke one-shot template for meson/install
package-meson-install-archive \
    -Dglib_assert=false \
    -Dglib_checks=false \
    -Dglib_debug=disabled \
    -Dlibelf=disabled \
    -Dlibmount=disabled \
    -Dman=false \
    -Dtests=false