#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=openjdk
export SOURCE_PACKAGE_VERSION=17
SUB_VERSION=35
OPENJDK_URL=https://download.java.net/java/GA/jdk${SOURCE_PACKAGE_VERSION}/0d483333a00540d886896bac774ff48b/${SUB_VERSION}/GPL
OPENJDK_TAR_GZ=${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}-${BUILD_KERNEL}-${BUILD_PROCESSOR}.tar.gz

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
if [ "${BUILD_PROCESSOR}" = "x86_64" ]; then
    OPENJDK_ARCH=x64
else
    OPENJDK_ARCH=${BUILD_PROCESSOR}
fi

if [ "${BUILD_OS}" = "mingw32" ]; then
    OPENJDK_OS=windows
else
    OPENJDK_OS=${BUILD_KERNEL}
fi

package-wget -c ${OPENJDK_URL}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}_${OPENJDK_OS}-${OPENJDK_ARCH}_bin.tar.gz \
             -O ${STAGE_ROOT}/${OPENJDK_TAR_GZ}
package-tar -zxf \
            ${STAGE_ROOT}/${OPENJDK_TAR_GZ} \
            -C ${INSTALL_PREFIX}

${MKDIR} -p ${INSTALL_PREFIX}/bin

EXECUTABLES="\
    jar \
    java \
    javac \
    javadoc \
"

for EXECUTABLE in ${EXECUTABLES}; do
    ${LN} -sf \
          ../jdk-${SOURCE_PACKAGE_VERSION}/bin/${EXECUTABLE} \
          ${INSTALL_PREFIX}/bin/${EXECUTABLE}
done

# Build and install the package
package-invoke-archive-install
