#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=automake
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
if [ "${HOST_OS}" = "musl" ]; then
    CONFIGURE_HOST_TRIPLE="${HOST_PROCESSOR}-${HOST_KERNEL}-gnu"
fi

DISABLE_AUTOUPDATE=TRUE \
DISABLE_LIBTOOLIZE=TRUE \
package-bootstrap-configure-install-archive
