#!/bin/bash

set -e

# Source package build helper functions
source ${PACKAGE_PREFIX}/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
DESTINATION_DIR=${INSTALL_PREFIX}
RUST_PACKAGE_LIST=${PACKAGE_PREFIX}/share/${VAL_VERDE_GH_TEAM}-rust-binaries.json
RUST_PACKAGE_COUNT=$(jq -r length ${RUST_PACKAGE_LIST})
RUST_PROCESSOR=${HOST_PROCESSOR}

mkdir -p ${DESTINATION_DIR}

for index in `seq 0 $(($RUST_PACKAGE_COUNT - 1))`; do
    index=$index \
    get-rust-build-deps

    RUST_PACKAGE_URL=${RUST_PACKAGE_URL//'${RUST_PACKAGE_NAME}'/${RUST_PACKAGE_NAME}}
    RUST_PACKAGE_URL=${RUST_PACKAGE_URL//'${RUST_PACKAGE_VERSION}'/${RUST_PACKAGE_VERSION}}
    RUST_PACKAGE_URL=${RUST_PACKAGE_URL//'${BUILD_OS}'/${BUILD_OS}}
    RUST_PACKAGE_URL=${RUST_PACKAGE_URL//'${BUILD_KERNEL}'/${BUILD_KERNEL}}
    RUST_PACKAGE_URL=${RUST_PACKAGE_URL//'${BUILD_PROCESSOR}'/${RUST_PROCESSOR}}

    package-wget -c ${RUST_PACKAGE_URL} \
     -O ${RUST_PACKAGE_NAME}-${RUST_PACKAGE_VERSION}-${RUST_PROCESSOR}-unknown-${BUILD_KERNEL}-${BUILD_OS}.tar.xz
    package-tar -xf \
            ${RUST_PACKAGE_NAME}-${RUST_PACKAGE_VERSION}-${RUST_PROCESSOR}-unknown-${BUILD_KERNEL}-${BUILD_OS}.tar.xz

    if [ ${RUST_PACKAGE_NAME} = 'rust-std' ]; then
        package-rsync -ax \
                ${RUST_PACKAGE_NAME}-${RUST_PACKAGE_VERSION}-${RUST_PROCESSOR}-unknown-${BUILD_KERNEL}-${BUILD_OS}/${RUST_PACKAGE_NAME}-${RUST_PROCESSOR}-unknown-${BUILD_KERNEL}-${BUILD_OS}/* \
                ${DESTINATION_DIR}/
    elif [ ${RUST_PACKAGE_NAME} = 'rustfmt' ]; then
        package-rsync -ax \
                ${RUST_PACKAGE_NAME}-${RUST_PACKAGE_VERSION}-${RUST_PROCESSOR}-unknown-${BUILD_KERNEL}-${BUILD_OS}/${RUST_PACKAGE_NAME}-preview/* \
                ${DESTINATION_DIR}/
    else
        package-rsync -ax \
              ${RUST_PACKAGE_NAME}-${RUST_PACKAGE_VERSION}-${RUST_PROCESSOR}-unknown-${BUILD_KERNEL}-${BUILD_OS}/${RUST_PACKAGE_NAME}/* \
              ${DESTINATION_DIR}/
    fi

done

${CHMOD} 755 \
         ${DESTINATION_DIR}/lib \
         ${DESTINATION_DIR}/libexec \
         ${DESTINATION_DIR}/bin \
         ${DESTINATION_DIR}/share \
         ${DESTINATION_DIR}/share/doc \
         ${DESTINATION_DIR}/share/man \
         ${DESTINATION_DIR}/share/man/man1 \
         ${DESTINATION_DIR}/share/zsh \
         ${DESTINATION_DIR}/share/zsh/site-functions

# Build and install the package
package-invoke-archive-install
