#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=souper
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment

export KLEE_SRC_DIR=${SOURCE_ROOT_BASE}/klee-2
export LLVM_NATIVE_STAGE_ROOT=${LLVM_NATIVE_STAGE_ROOT:-${STAGE_ROOT_BASE}/${QUALIFIED_LLVM_PATH}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}}

# Configure the build components
cd ${STAGE_ROOT}

TOOL_LOG=${STAGE_ROOT}/builder-go-init \
tool-log ${GO} mod init souper
TOOL_LOG=${STAGE_ROOT}/builder-go-get \
tool-log ${GO} get github.com/gomodule/redigo/redis

DISABLED_WARNINGS="\
    -Wno-deprecated-enum-enum-conversion \
    -Wno-unused-command-line-argument \
"
CFLAGS="\
    -I${PACKAGE_PREFIX}/include/alive2 \
    -I${KLEE_SOURCE_ROOT}/include \
    ${DISABLED_WARNINGS} \
    ${CFLAGS} \
" \
CXXFLAGS="\
    -I${PACKAGE_PREFIX}/include/alive2 \
    -I${KLEE_SOURCE_ROOT}/include \
    ${DISABLED_WARNINGS} \
    ${CXXFLAGS} \
" \
COMMON_LDFLAGS="\
    -L${PACKAGE_PREFIX}/lib \
    ${COMMON_LDFLAGS} \
" \
package-cmake \
    ${SOURCE_ROOT} \
    -DALIVE_LIBRARY=`package-get-path alive2 SHARED HOST` \
    -DHIREDIS_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DHIREDIS_LIBRARY=`package-get-path hiredis SHARED HOST` \
    -DKLEE_SRC_DIR=${KLEE_SRC_DIR} \
    -DLLVM_CONFIG_EXECUTABLE=${LLVM_NATIVE_STAGE_ROOT}/bin/llvm-config \
    -DZ3_LIBRARY=`package-get-path z3 SHARED HOST`

# Build the components
ninja-build

${MKDIR} -p \
         ${INSTALL_PREFIX}/bin \
         ${INSTALL_PREFIX}/lib

package-rsync -ax \
              clang-souper \
              sclang \
              sclang++ \
              souper \
              ${INSTALL_PREFIX}/bin/
package-rsync -ax \
              libsouperCodegen.* \
              libsouperPass.* \
              libsouperPassProfileAll.* \
              ${INSTALL_PREFIX}/lib/
${LN} -sf \
      clang-cpp \
      ${INSTALL_PREFIX}/bin/sclang-cpp

# Build the package
deb-package-build

# Install the package
deb-package-install
