#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=glibc-interface
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

copy-source-to-staging

# Configure the build components
${MKDIR} -p ${STAGE_ROOT}/build

cd ${STAGE_ROOT}/build

DISABLE_FORTIFY_SOURCE_LEVEL=TRUE \
DISABLE_FPIC=TRUE \
HOST_ARCH= \
HOST_CPU= \
OPTIMIZATION_LEVEL=2 \
USE_GCC=TRUE \
export-compiler-environment
generate-compiler-tools

TOOL_LOG=${STAGE_ROOT}/builder-invocation \
tool-log ${STAGE_ROOT}/configure \
    libc_cv_gcc_builtin_redirection=yes \
    libc_cv_include_x86_isa_level=no \
    --enable-cet \
    --enable-kernel=4.0 \
    --disable-sanity-checks \
    --disable-werror \
    --libdir=/usr/lib \
    --prefix=/usr

# Build the components
make-build

DESTDIR=${INSTALL_PREFIX}/.. \
make-install

# Build and install the package
package-invoke-archive-install
