#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=bazel
export SOURCE_PACKAGE_VERSION=4

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

BAZEL_PACKAGE_VERSION=4.0.0

# Configure the build components
mkdir -p ${INSTALL_PREFIX}/bin

BAZEL_PROCESSOR=${BUILD_PROCESSOR}

if [ "${BUILD_PROCESSOR}" = "aarch64" ]; then
    BAZEL_PROCESSOR=arm64
fi

package-wget -c https://github.com/bazelbuild/${SOURCE_PACKAGE_NAME}/releases/download/${BAZEL_PACKAGE_VERSION}/${SOURCE_PACKAGE_NAME}-${BAZEL_PACKAGE_VERSION}-${BUILD_KERNEL}-${BAZEL_PROCESSOR} \
             -O ${INSTALL_PREFIX}/bin/${SOURCE_PACKAGE_NAME}

${CHMOD} +x ${INSTALL_PREFIX}/bin/${SOURCE_PACKAGE_NAME}

# Build the package
deb-package-build

# Build the package
deb-package-install
