#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
MAVEN_PACKAGE_LIST=/usr/share/${VAL_VERDE_GH_TEAM}-maven-binaries.json
MAVEN_PACKAGE_COUNT=$(jq -r length ${MAVEN_PACKAGE_LIST})

for index in `seq 0 $((${MAVEN_PACKAGE_COUNT} - 1))`; do
    index=$index \
    get-maven-build-deps

    MAVEN_PACKAGE_URL=${MAVEN_PACKAGE_URL//'${MAVEN_PACKAGE_NAME}'/${MAVEN_PACKAGE_NAME}}
    MAVEN_PACKAGE_URL=${MAVEN_PACKAGE_URL//'${SOURCE_PACKAGE_VERSION}'/${SOURCE_PACKAGE_VERSION}}
    MAVEN_PACKAGE_URL=${MAVEN_PACKAGE_URL//'${MAVEN_PACKAGE_VERSION}'/${MAVEN_PACKAGE_VERSION}}
    
    package-wget -c ${MAVEN_PACKAGE_URL} \
      -O ${STAGE_ROOT}/${MAVEN_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
    package-tar -zxf \
      ${STAGE_ROOT}/${MAVEN_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz \
      -C ${STAGE_ROOT}
    ${MV} ${STAGE_ROOT}/apache-${MAVEN_PACKAGE_NAME}*/* \
      ${STAGE_ROOT}/
    ${RMDIR} ${STAGE_ROOT}/apache-${MAVEN_PACKAGE_NAME}*
done

${MKDIR} -p \
         ${INSTALL_PREFIX}/bin \
         ${INSTALL_PREFIX}/lib
package-rsync -aPx \
              ${STAGE_ROOT}/bin/m2.conf \
              ${STAGE_ROOT}/bin/mvn \
              ${INSTALL_PREFIX}/bin/
package-rsync -aPx \
              ${STAGE_ROOT}/boot \
              ${STAGE_ROOT}/conf \
              ${INSTALL_PREFIX}/
package-rsync -aPx \
              ${STAGE_ROOT}/lib/*.jar \
              ${INSTALL_PREFIX}/lib/

# Build and install the package
package-invoke-archive-install
