#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=gcc
export SOURCE_PACKAGE_VERSION=11

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
AS=`package-get-path as EXECUTABLE BUILD` \
ASFLAGS="" \
BUILD_SYSROOT=/ \
DISABLE_CXX_INCLUDE=TRUE \
DISABLE_CXX_STDLIB=TRUE \
SYSROOT=/ \
OBJDUMP=`package-get-path objdump EXECUTABLE BUILD` \
export-compiler-environment

CFLAGS_FOR_TARGET="-O${OPTIMIZATION_LEVEL} ${STRIP_CFLAG}" \
CPPFLAGS_FOR_TARGET="-O${OPTIMIZATION_LEVEL} ${STRIP_CFLAG}" \
CXXFLAGS_FOR_TARGET="-O${OPTIMIZATION_LEVEL} ${STRIP_CFLAG}" \
DISABLE_AUTOUPDATE=TRUE \
DISABLE_GENERATED_TOOLS=TRUE \
package-stage-configure-install-archive \
    --disable-bootstrap \
    --disable-c++tools \
    --disable-libgomp \
    --disable-multilib \
    --disable-static \
    --enable-werror=no \
    --enable-languages=c \
    --enable-shared
