#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=glibc-interface
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
CONFIGURE_PACKAGE_PREFIX=${PACKAGE_USR_PREFIX} \
DESTDIR=${INSTALL_PREFIX}/.. \
DISABLE_AUTOUPDATE=TRUE \
DISABLE_FORTIFY_SOURCE_LEVEL=TRUE \
DISABLE_FPIC=TRUE \
DISABLE_SOUPER=TRUE \
HOST_ARCH= \
HOST_CPU= \
USE_GCC=TRUE \
package-configure-install-archive \
    libc_cv_gcc_builtin_redirection=yes \
    libc_cv_include_x86_isa_level=no \
    --enable-cet \
    --enable-kernel=4.0 \
    --disable-sanity-checks \
    --disable-werror \
    --libdir=/usr/lib