#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=pkg-config
export SOURCE_PACKAGE_VERSION=0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
package-configure-install \
    ac_cv_func_posix_getgrgid_r=yes \
    ac_cv_func_posix_getpwuid_r=yes \
    glib_cv_stack_grows=no \
    glib_cv_uscore=no \
    --with-internal-glib \
    --with-libiconv=gnu