#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
ANDROID_NDK_BUILD_PROCESSOR=x86_64
ANDROID_PACKAGE_LIST=/usr/share/${VAL_VERDE_GH_TEAM}-android-binaries.json
ANDROID_PACKAGE_COUNT=$(jq -r length ${ANDROID_PACKAGE_LIST})
DESTINATION_DIR=${INSTALL_PREFIX}/share/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

${MKDIR} -p ${DESTINATION_DIR}

for index in `seq 0 $((${ANDROID_PACKAGE_COUNT} - 1))`; do
    index=$index \
    get-android-build-deps

    ANDROID_PACKAGE_URL=${ANDROID_PACKAGE_URL//'${ANDROID_PACKAGE_NAME}'/${ANDROID_PACKAGE_NAME}}
    ANDROID_PACKAGE_URL=${ANDROID_PACKAGE_URL//'${ANDROID_PACKAGE_VERSION}'/${ANDROID_PACKAGE_VERSION}}
    ANDROID_PACKAGE_URL=${ANDROID_PACKAGE_URL//'${BUILD_KERNEL}'/${BUILD_KERNEL}}
    
    if [[ "${ANDROID_NDK_VERSION}" < "r23" ]]; then
        ANDROID_PACKAGE_URL=${ANDROID_PACKAGE_URL}-${ANDROID_NDK_BUILD_PROCESSOR}
    fi
done

package-wget -c ${ANDROID_PACKAGE_URL}.zip \
      -O ${STAGE_ROOT}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.zip
package-unzip \
      ${STAGE_ROOT}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.zip \
      -d ${STAGE_ROOT}/

package-rsync -ax \
              ${STAGE_ROOT}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}/* \
              ${DESTINATION_DIR}/

package-rsync -ax \
              ${SOURCE_ROOT_BASE}/${SOURCE_PACKAGE_NAME}-patches-1/* \
              ${STAGE_ROOT}

${PATCH} -p1 \
        -i ${STAGE_ROOT}/${SOURCE_PACKAGE_NAME}-dirent-versionsort.diff \
        ${DESTINATION_DIR}/toolchains/llvm/prebuilt/${BUILD_KERNEL}-${ANDROID_NDK_BUILD_PROCESSOR}/sysroot/usr/include/dirent.h
${PATCH} -p1 \
        -i ${STAGE_ROOT}/${SOURCE_PACKAGE_NAME}-string-strverscmp.diff \
        ${DESTINATION_DIR}/toolchains/llvm/prebuilt/${BUILD_KERNEL}-${ANDROID_NDK_BUILD_PROCESSOR}/sysroot/usr/include/string.h


${CHMOD} 755 \
         ${INSTALL_PREFIX}/share

# Build and install the package
package-invoke-archive-install