#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
if [ "${HOST_OS}" = "macos" ] ||
   [ "${HOST_OS}" = "mingw32" ]; then
    ENABLE_OR_DISABLE_SYMVERS=disable
else
    ENABLE_OR_DISABLE_SYMVERS=enable
fi

package-stage-configure-install-archive \
    --disable-static \
    --enable-shared \
    --${ENABLE_OR_DISABLE_SYMVERS}-symvers