#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for cmake/install
COMMON_LDFLAGS="\
    -lunwind \
    ${COMMON_LDFLAGS} \
" \
package-cmake-install-archive \
    -DPYTHON_EXECUTABLE=${PYTHON}