#!/bin/bash

set -e

source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

if [ -z "${MAKEINFO}" ]; then
    export-build-util MAKEINFO true
fi

if [ "${BUILD_TRIPLE}" = "${HOST_TRIPLE}" ]; then
    # zlib bootstrap build
    package-invoke-builder zlib 1

    # help2man bootstrap build
    package-invoke-builder help2man 1
    unset HELP2MAN

    # libtool bootstrap build
    package-invoke-builder libtool 2
    unset LIBTOOL

    # libffi bootstrap build
    package-invoke-builder libffi 3

    # pcre build
    package-invoke-builder pcre 10

    # glib bootstrap build
    package-invoke-builder glib 1

    # pkg-config bootstrap build
    package-invoke-builder pkg-config 0
    unset PKG_CONFIG

    # re2c build
    package-invoke-builder re2c 3

    # hiredis build
    package-invoke-builder hiredis 1

    # alive2 build
    package-invoke-builder alive2 1

    # souper build
    package-invoke-builder souper 1

    # gmp build
    package-invoke-builder gmp 6

    # mpfr build
    package-invoke-builder mpfr 4

    # mpc build
    package-invoke-builder mpc 1

    # isl build
    package-invoke-builder isl 0
fi

# binutils-gdb build
package-invoke-builder cross-binutils-gdb 2

# gcc build
package-invoke-builder cross-gcc 12