#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=icu4c
export SOURCE_PACKAGE_VERSION=68
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
CFLAGS=`${ECHO} "\
    -D_WASI_EMULATED_SIGNAL \
    ${CFLAGS} \
" | ${XARGS}` \
CXXFLAGS=`${ECHO} "\
    -D_WASI_EMULATED_SIGNAL \
    ${CXXFLAGS} \
" | ${XARGS}` \
LDFLAGS=`${ECHO} "\
    -lwasi-emulated-signal \
    ${LDFLAGS} \
" | ${XARGS}` \
CONFIGURE_HOST_TRIPLE=i686-unknown-gnu \
${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-configure \
    ${SOURCE_ROOT}/source/configure \
    --disable-dyload \
    --disable-extras \
    --disable-samples \
    --disable-shared \
    --disable-tests \
    --disable-tools \
    --enable-static \
    --prefix=${STAGE_ROOT}/install${PACKAGE_PREFIX} \
    --with-cross-build=${STAGE_ROOT_BASE}/${SOURCE_PACKAGE_NAME}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH} \
    --with-library-suffix=swift

# Build the components
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
