#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=wasi-libc
export SOURCE_PACKAGE_VERSION=0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment
generate-compiler-tools

# Configure the build components
copy-source-to-staging

# Build the components
cd ${STAGE_ROOT}
INSTALL_DIR=${INSTALL_PREFIX} \
OBJDIR=${STAGE_ROOT} \
THREAD_MODEL=local-exec \
WASM_AR=${AR} \
WASM_CC=${CC} \
WASM_CFLAGS=${CFLAGS} \
WASM_NM=${NM} \
SYSROOT=${SYSROOT} \
make-build \
    install

# Build and install the package
package-invoke-archive-install
