#!/bin/bash

set -e

# Source package build helper functions
export PACKAGE_USR_PREFIX=.

source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# webassembly libc
package-invoke-builder wasi-libc 0

# webassembly compiler-rt (bootstrap)
package-invoke-builder compiler-rt-cross 13

# webassembly libcxx
package-invoke-builder libcxx-bootstrap 13