#!/bin/bash

set -e

# Source package build helper functions
export PACKAGE_PREFIX=${PACKAGE_PREFIX:-${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk/${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}/sysroot}

# webassembly environment
export SYSTEM_NAME=Fuchsia
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# webassembly libc
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-wasi-libc

# webassembly compiler-rt (bootstrap)
CFLAGS="\
    -nostdlib \
    -Wl,--allow-undefined \
    -Wl,--no-entry \
    ${CFLAGS} \
" \
CXXFLAGS="\
    -nostdlib \
    -Wl,--allow-undefined \
    -Wl,--no-entry \
    ${CXXFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-compiler-rt-wasi

# webassembly libcxxabi
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcxxabi-wasi

# webassembly libcxx
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcxx-wasi

# webassembly compiler-rt (rebuild with c++)
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-compiler-rt-wasi
