#!/bin/bash

set -e

export BINDIR=/usr/bin \
    DEB_PATH=${TOOLCHAIN_DEB_PATH}

source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# cuda bootstrap build
package-invoke-builder cuda-bootstrap 11

# bazel bootstrap build
package-invoke-builder bazel-bootstrap 4

# go bootstrap build
package-invoke-builder go-bootstrap 1

# openjdk bootstrap build
package-invoke-builder openjdk-bootstrap 17

# maven bootstrap build
package-invoke-builder maven-bootstrap 3

# rust bootstrap build
package-invoke-builder rust-bootstrap 1

# android ndk build
package-invoke-builder android-ndk ${ANDROID_NDK_VERSION}