#!/bin/bash

set -e

export BINDIR=/usr/bin
source /sources/packaging-tools/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-common-variables
source /sources/packaging-tools/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-packaging-api

export SOURCE_PACKAGE_NAME=sources-builder
export SOURCE_PACKAGE_VERSION=1
export INSTALL_ROOT=/tmp/org.${VAL_VERDE_GH_TEAM}/scripts
export STAGE_ROOT=${STAGE_ROOT_BASE}/${SOURCE_PACKAGE_NAME}
export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}

${MKDIR} -p \
         ${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM} \
         ${STAGE_ROOT}

# Install builder sources
package-rsync -ax \
              /sources/packaging-tools/* \
              ${INSTALL_ROOT}/usr/
package-rsync -ax \
              /sources/archive-templates/* \
              ${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM}/

# Package debs
BASE_DIRECTORY=${INSTALL_ROOT}/usr \
PACKAGE_INSTALL_BASE=/usr \
TEMPLATE_ROOT_BASE=${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM} \
package-archive-build-install

# Fetch sources
bash /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-fetch-packages

# Rerun source deb checks to install
trigger-source-package-install
