#!/bin/bash

set -e

export BINDIR=/usr/bin
source /sources/packaging-tools/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-common-variables
source /sources/packaging-tools/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-packaging-api

export SOURCE_PACKAGE_NAME=sources-builder
export SOURCE_PACKAGE_VERSION=1
export INSTALL_ROOT=/tmp/org.${VAL_VERDE_GH_TEAM}/scripts
export STAGE_ROOT=${STAGE_ROOT_BASE}/${SOURCE_PACKAGE_NAME}
export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}

# Establish base architecture for package-builder
# Assumes that deb is the default choice for archive tool on debian
# and rpm, the defualt choice on fedora distributions.
if [ "$(package-determine-os-distribution)" = "ubuntu" ]; then
    export PACKAGE_ARCH=all
elif [ "$(package-determine-os-distribution)" = "fedora" ]; then
    export PACKAGE_ARCH=noarch
fi

${MKDIR} -p \
         ${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM} \
         ${STAGE_ROOT}

# Install builder sources
package-rsync -ax \
              /sources/packaging-tools/* \
              ${INSTALL_ROOT}/usr/
package-rsync -ax \
              /sources/archive-templates/* \
              ${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM}/

# Package debs
BASE_DIRECTORY=${INSTALL_ROOT}/usr \
PACKAGE_INSTALL_BASE=/usr \
TEMPLATE_ROOT_BASE=${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM} \
package-archive-build-install

# Fetch sources
bash /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-fetch-packages

# Rerun source deb checks to install
trigger-source-package-install
