#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export SYSROOT=${PACKAGE_PREFIX}/glibc-interface

# rust build
package-invoke-builder rust 1