#!/bin/bash

set -e

# Source package build helper functions

# Set all environment vars
export SOURCE_PACKAGE_NAME=rust
export SOURCE_PACKAGE_VERSION=1

source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment
generate-compiler-tools

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-llvm-project-13-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-z3-4-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"
export LLVM_NATIVE_STAGE_ROOT=${LLVM_NATIVE_STAGE_ROOT:-${STAGE_ROOT_BASE}/${QUALIFIED_LLVM_PATH}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}}

# Configure the build components
BUILD_TRIPLE=${BUILD_PROCESSOR}-unknown-${BUILD_KERNEL}-${BUILD_OS}${BUILD_OS_API_LEVEL}

${MKDIR} -p ${STAGE_ROOT}/${BUILD_TRIPLE}
package-rsync -ax \
              ${PACKAGE_PREFIX}/staging-data/${BUILD_TRIPLE}/* \
              ${STAGE_ROOT}/${BUILD_TRIPLE}/
${SED} -i \
       "s|build.download_stage0()|#build.download_stage0()|g" \
       ${SOURCE_ROOT}/src/bootstrap/bootstrap.py

cd ${STAGE_ROOT}
package-rsync -ax \
              ${SOURCE_ROOT}/${VAL_VERDE_GH_TEAM}-config.toml.in \
              ${STAGE_ROOT}/config.toml

FILECHECK=${LLVM_NATIVE_STAGE_ROOT}/bin/FileCheck
LD=${CC}
LDFLAGS=
LLVMCONFIG=${LLVM_NATIVE_STAGE_ROOT}/bin/llvm-config

${SED} -i "s|@@AR@@|${AR}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@BUILD_TRIPLE@@|${BUILD_TRIPLE}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@CC@@|${CC}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@CFLAGS@@|${CFLAGS}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@CXX@@|${CXX}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@CXXFLAGS@@|${CXXFLAGS}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@FILECHECK@@|${FILECHECK}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@INSTALL_PREFIX@@|${INSTALL_PREFIX}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@LD@@|${LD}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@LDFLAGS@@|${LDFLAGS}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@LLVMCONFIG@@|${LLVMCONFIG}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@NODE@@|${NODE}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@PYTHON@@|${PYTHON}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@RANLIB@@|${RANLIB}|g" ${STAGE_ROOT}/config.toml
${SED} -i "s|@@STAGE_ROOT@@|${STAGE_ROOT}|g" ${STAGE_ROOT}/config.toml

# Build the components
TOOL_LOG=${STAGE_ROOT}/builder-invocation \
tool-log ${PYTHON} ${SOURCE_ROOT}/x.py build --config ${STAGE_ROOT}/config.toml
TOOL_LOG=${STAGE_ROOT}/builder-installation \
tool-log ${PYTHON} ${SOURCE_ROOT}/x.py install --config ${STAGE_ROOT}/config.toml

# Build and install the package
package-invoke-artifact-install
