#!/bin/bash

set -e

# windows zlib build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-zlib-cross

# windows bzip2 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bzip2-cross

# windows lz4 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-lz4-cross

# windows xxhash build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xxhash-cross

# windows zip build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-zip-cross

# windows zstd build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-zstd-cross

# windows unzip build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-zip-cross

# windows autoconf build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-autoconf-cross

# windows automake build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-automake-cross

# windows libtool build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libtool-cross

# windows m4 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-m4-cross

# windows make build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-make-cross

# windows libiconv build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libiconv-cross

# windows pkg-config build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-pkg-config-cross

# windows pcre build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-pcre-cross

# windows icu build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-icu4c-cross

# windows xz build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xz-cross

# windows libxml2 build
CFLAGS="\
    -fuse-ld=${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-mslink \
    ${CFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libxml2-cross

# windows libffi build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libffi-cross

# android ncurses build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-ncurses-cross

# windows editline build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-wineditline-cross

# windows sqlite3 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sqlite-cross

# windows openssl build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-openssl-cross

# windows libexpat build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-expat-cross

# windows xorg-macros build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xorg-macros-cross

# windows xorgproto build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xorg-xorgproto-cross

# windows xcb-proto build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xcb-proto-cross

# windows xcb-pthread-stubs build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xcb-pthread-stubs-cross

# windows libuv build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libuv-cross

# windows libssh2 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libssh2-cross

# windows curl build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-curl-cross

# windows gettext build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gettext-cross

# windows libarchive build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libarchive-cross

# windows libmicrohttpd build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libmicrohttpd-cross

# windows grep build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-grep-cross

# windows sed build
# bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sed-cross

# windows bison build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bison-cross

# windows gperf build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gperf-cross

# windows findutils build
# bash ${VAL_VERDE_GH_TEAM}-platform-sdk-findutils-cross

# windows wget build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-wget-cross

# windows z3 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-z3-cross

# windows ninja build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-ninja-cross

# windows cmake build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-cmake-cross

# windows lua build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-lua-cross

# windows jwasm build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-jwasm
