#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=wineditline
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Invoke one-shot template for cmake/install
function package-install-completion-callback() {
    ${MV} ${INSTALL_ROOT}${SOURCE_ROOT}/bin \
          ${INSTALL_ROOT}${SOURCE_ROOT}/include \
          ${INSTALL_ROOT}${SOURCE_ROOT}/lib \
          ${INSTALL_PREFIX}/
    ${RM} -rf ${INSTALL_ROOT}${SOURCE_ROOT_BASE}
}

COMMON_CFLAGS="\
     -I${SOURCE_ROOT} \
     -I${SOURCE_ROOT}/src \
     ${COMMON_CFLAGS} \
" \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-cmake-install-archive \
    -DCMAKE_POSITION_INDEPENDENT_CODE=FALSE \
    -DLIB_SUFFIX=
