#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=mingw-w64-headers
export SOURCE_PACKAGE_VERSION=6

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export SOURCE_ROOT=${SOURCE_ROOT_BASE}/mingw-w64-${SOURCE_PACKAGE_VERSION}/${SOURCE_PACKAGE_NAME}

# Invoke one-shot template for configure/install
function package-install-completion-callback() {
    ${CP} ${SOURCE_ROOT}/include/module.modulemap \
          ${INSTALL_PREFIX}/include/
    ${LN} -sf . \
          ${INSTALL_PREFIX}/mingw
    ${LN} -sf . \
          ${INSTALL_PREFIX}/usr
}

CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-stage-configure-install-archive \
    --enable-crt \
    --enable-sdk=all \
    --with-default-msvcrt=ucrt \
    --with-default-win32-winnt=0x0A00
