#!/bin/bash

set -e

# windows llvm build
package-invoke-builder llvm-project-windows

# windows cmark build
package-invoke-builder swift-cmark-cross

# windows swift build
package-invoke-builder swift-windows

# windows lldb build
package-invoke-builder swift-lldb-windows
