#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# windows zlib build
package-invoke-builder zlib-cross

# windows bzip2 build
package-invoke-builder bzip2-cross

# windows lz4 build
package-invoke-builder lz4-cross

# windows xxhash build
# package-invoke-builder xxhash-cross

# windows zip build
# package-invoke-builder zip-cross

# windows zstd build
package-invoke-builder zstd-cross

# windows unzip build
# package-invoke-builder unzip-cross

# windows help2man build
# package-invoke-builder help2man-cross

# windows autoconf build
package-invoke-builder autoconf-cross

# windows automake build
package-invoke-builder automake-cross

# windows libtool build
package-invoke-builder libtool-cross

# windows m4 build
HELP2MAN=${BINDIR}/true \
package-invoke-builder m4-cross

# windows make build
package-invoke-builder make-cross

# windows ninja build
package-invoke-builder ninja-cross

# windows libiconv build
package-invoke-builder libiconv-cross

# windows libffi build
package-invoke-builder libffi-cross

# windows pcre build
CXXFLAGS="\
    -lclang_rt.builtins-x86_64 \
    ${CXXFLAGS} \
" \
package-invoke-builder pcre-cross

# windows icu build
package-invoke-builder icu4c-cross

# windows xz build
package-invoke-builder xz-cross

# windows libxml2 build
CFLAGS="\
    -fuse-ld=${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-mslink \
    ${CFLAGS} \
" \
package-invoke-builder libxml2-cross

# windows ncurses build
package-invoke-builder ncurses-cross

# windows editline build
package-invoke-builder wineditline-cross

# windows sqlite build
package-invoke-builder sqlite-cross

# windows openssl build
package-invoke-builder openssl-cross

# windows expat build
package-invoke-builder expat-cross

# windows gettext build
package-invoke-builder gettext-cross

# gawk build
# package-invoke-builder gawk-cross

# windows gperf build
package-invoke-builder gperf-cross

# windows libarchive build
package-invoke-builder libarchive-cross

# windows libmicrohttpd build
package-invoke-builder libmicrohttpd-cross

# windows libssh2 build
package-invoke-builder libssh2-cross

# windows curl build
package-invoke-builder curl-cross

# windows glib build
package-invoke-builder glib-cross

# windows pkg-config build
package-invoke-builder pkg-config-cross

# windows xorg-macros build
package-invoke-builder xorg-macros-cross

# windows xorgproto build
package-invoke-builder xorg-xorgproto-cross

# windows xcb-proto build
package-invoke-builder xcb-proto-cross

# windows xcb-pthread-stubs build
package-invoke-builder xcb-pthread-stubs-cross

# windows opencl headers build
package-invoke-builder opencl-headers-cross

# windows opencl icd loader build
# package-invoke-builder opencl-icd-loader-cross

# windows vulkan headers build
package-invoke-builder vulkan-headers-cross

# windows vulkan loader build
package-invoke-builder vulkan-loader-cross

# cups build
# package-invoke-builder cups-cross

# windows libuv build
package-invoke-builder libuv-cross

# windows grep build
package-invoke-builder grep-cross

# windows sed build
# package-invoke-builder sed-cross

# windows bison build
package-invoke-builder bison-cross

# windows findutils build
# package-invoke-builder findutils-cross

# windows wget build
package-invoke-builder wget-cross

# windows openjdk build
# package-invoke-builder openjdk-cross

# windows z3 build
package-invoke-builder z3-cross

# windows gobject-introspection build
# package-invoke-builder gobject-introspection-cross

# windows lua build
package-invoke-builder lua-cross

# windows cmake build
package-invoke-builder cmake-cross

# windows android patch elf build
# package-invoke-builder android-patch-elf-cross

# windows jwasm build
package-invoke-builder jwasm
