#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-mingw-w64-crt-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"
export SOURCE_ROOT=${SOURCE_ROOT_BASE}/mingw-w64-${SOURCE_PACKAGE_VERSION}/mingw-w64-libraries/${SOURCE_PACKAGE_NAME}

# Configure the build components
cd ${STAGE_ROOT}
${SED} -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure
package-configure \
    ${SOURCE_ROOT}/configure

# Build the components
make-install

${RM} -rf ${INSTALL_PREFIX}/include/pthread_signal.h \
          ${INSTALL_PREFIX}/include/pthread_time.h \
          ${INSTALL_PREFIX}/include/pthread_unistd.h

# Build and install the package
package-invoke-archive-install
