#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

export COMPILER_TARGET=${HOST_PROCESSOR}-unknown-windows-gnu

# remove host foundation and libdispatch to avoid module collisions
PACKAGES_TO_MANAGE=( 'swift-argument-parser-5'         'BUILD' \
                     'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-libdispatch-5'    'BUILD' \
                     'swift-corelibs-xctest-5'         'BUILD' \
                     'swift-crypto-5'                  'BUILD' \
                     'swift-driver-5'                  'BUILD' \
                     'swift-llbuild-5'                 'BUILD' \
                     'swift-package-manager-5'         'BUILD' \
                     'swift-tools-support-core-5'      'BUILD' \
                     'yams-3'                          'BUILD' )

package-invoke-archive-action uninstall ${PACKAGES_TO_MANAGE[@]}

# windows libdispatch build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-corelibs-libdispatch-windows 5 no-install

# windows foundation build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-corelibs-foundation-windows 5 no-install

# windows xctest build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-corelibs-xctest-windows 5 no-install

# windows llbuild build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-llbuild-windows 5 no-install

# windows swift-tools-support-core build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-tools-support-core-windows 5 no-install

# windows yams build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder yams-windows 3 no-install

# windows swift-argument-parser build
COMMON_CFLAGS="\
    -fms-compatibility-version=19.2 \
    -fms-extensions \
    ${COMMON_CFLAGS} \
" \
package-invoke-builder swift-argument-parser-cross 5 no-install

# windows swift-crypto build
COMMON_CFLAGS="\
    -fms-compatibility-version=19.2 \
    -fms-extensions \
    ${COMMON_CFLAGS} \
" \
package-invoke-builder swift-crypto-cross 5 no-install

# windows swift-driver build
COMMON_CFLAGS="\
    -fms-compatibility-version=19.2 \
    -fms-extensions \
    ${COMMON_CFLAGS} \
" \
package-invoke-builder swift-driver-cross 5 no-install

# windows swiftpm build
COMMON_CFLAGS="\
    -fms-compatibility-version=19.2 \
    -fms-extensions \
    ${COMMON_CFLAGS} \
" \
package-invoke-builder swift-package-manager-cross 5 no-install

# reinstall swiftpm for build and host
PACKAGES_TO_MANAGE=( 'swift-corelibs-libdispatch-5'    'BUILD' \
                     'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-xctest-5'         'BUILD' \
                     'swift-crypto-5'                  'BUILD' \
                     'swift-driver-5'                  'BUILD' \
                     'swift-argument-parser-5'         'BUILD' \
                     'swift-llbuild-5'                 'BUILD' \
                     'swift-tools-support-core-5'      'BUILD' \
                     'yams-3'                          'BUILD' \
                     'swift-driver-5'                  'BUILD' \
                     'swift-package-manager-5'         'BUILD' \
                     'swift-corelibs-libdispatch-5'    'HOST' \
                     'swift-corelibs-foundation-5'     'HOST' \
                     'swift-corelibs-xctest-5'         'HOST' \
                     'swift-crypto-5'                  'HOST' \
                     'swift-driver-5'                  'HOST' \
                     'swift-argument-parser-5'         'HOST' \
                     'swift-llbuild-5'                 'HOST' \
                     'swift-tools-support-core-5'      'HOST' \
                     'yams-3'                          'HOST' \
                     'swift-driver-5'                  'HOST' \
                     'swift-package-manager-5'         'HOST')

package-invoke-archive-action install ${PACKAGES_TO_MANAGE[@]}

# swift-protobuf build
package-invoke-builder swift-protobuf-cross 1

# swift-syntax build
package-invoke-builder swift-syntax-cross 5

# swift-syntax-highlighter build
package-invoke-builder swift-syntax-highlighter-cross 1

# swift-format build
package-invoke-builder swift-format-cross 5

# swift-semantics build
package-invoke-builder swift-semantics-cross 0

# swift-doc build
package-invoke-builder swift-doc-cross 5

# sourcekit-lsp build
package-invoke-builder sourcekit-lsp-windows 5

# baikonur build
# package-invoke-builder baikonur-cross

# pythonkit build
# package-invoke-builder pythonkit-cross

# swift tensorflows apis build
# package-invoke-builder swift-tensorflow-apis
