#!/bin/bash

set -e

# Source package build helper functions
export \
    DISABLE_FORTIFY_SOURCE_LEVEL=TRUE \
    FORTIFY_SOURCE_LEVEL=0 \
    PACKAGE_USR_PREFIX=.
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# windows mingw-headers build
package-invoke-builder mingw-w64-headers 6

# windows mingw-crt build
package-invoke-builder mingw-w64-crt 6

# windows compiler-rt build (for host)
package-invoke-builder compiler-rt-cross 13

# windows libcxx build
package-invoke-builder libcxx-bootstrap 13

# windows mingw-winpthreads build
package-invoke-builder winpthreads-cross 6

# windows llvm dependencies
package-invoke-category-builder llvm-dependencies-windows

# windows swift tools build
package-invoke-category-builder swift-tools-windows

# windows swift sdk build
package-invoke-category-builder swift-sdk-cross

# windows go build
package-invoke-builder go-cross 1

# windows ruby build
# package-invoke-builder ruby-cross 3

# windows graphics sdk build
package-invoke-category-builder graphics-sdk-cross

# windows virtualization sdk build
package-invoke-category-builder virtualization-sdk-cross

# wine-sdk build
package-invoke-category-builder wine-sdk-cross

# windows blockchain sdk build
package-invoke-category-builder blockchain-sdk-cross
