#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=mingw-w64-crt
export SOURCE_PACKAGE_VERSION=6

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export SOURCE_ROOT=${SOURCE_ROOT_BASE}/mingw-w64-${SOURCE_PACKAGE_VERSION}/${SOURCE_PACKAGE_NAME}

# Configure the build components
cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-lib32 \
    --enable-experimental=registeredprintf,softmath \
    --enable-warnings=0 \
    --with-default-msvcrt=ucrt

# Build the components
make-install

${LN} -sf \
      `package-get-filename uuid STATIC` \
      ${INSTALL_PREFIX}/lib/`package-get-filename winuuid STATIC`

# Build the package
deb-package-build

# Install the package
deb-package-install
