#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=wineditline
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-6-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
cd ${STAGE_ROOT}
CFLAGS="\
     -I${SOURCE_ROOT} \
     -I${SOURCE_ROOT}/src \
     ${CFLAGS} \
" \
package-cmake \
    -DCMAKE_POSITION_INDEPENDENT_CODE=FALSE

# Build the components
ninja-install

${MV} ${INSTALL_ROOT}${SOURCE_ROOT}/src/bin \
      ${INSTALL_ROOT}${SOURCE_ROOT}/src/include \
      ${INSTALL_ROOT}${SOURCE_ROOT}/src/lib \
      ${INSTALL_PREFIX}/
${RM} -rf ${INSTALL_ROOT}${SOURCE_ROOT_BASE}

# Build and install the package
package-invoke-archive-install
