#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# windows llvm build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder llvm-project-windows 15 no-install

# remove libcxx, libcxxabi and libunwind as they are superceded by llvm-project.
PACKAGES_TO_MANAGE=( 'libcxx-15' 'HOST' )

package-invoke-archive-action uninstall ${PACKAGES_TO_MANAGE[@]}

# install llvm for host
PACKAGES_TO_MANAGE=( 'llvm-project-15' 'HOST'
                     'llvm-project-15-stage' 'HOST' )

package-invoke-archive-action install ${PACKAGES_TO_MANAGE[@]}

# souper build
package-invoke-builder souper-cross 1

# windows cmark build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-cmark-cross 5 none

# windows swift build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-windows 5

# windows lldb build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-lldb-windows 5
