#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=mingw-w64-headers
export SOURCE_PACKAGE_VERSION=6

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export SOURCE_ROOT=${SOURCE_ROOT_BASE}/mingw-w64-${SOURCE_PACKAGE_VERSION}/${SOURCE_PACKAGE_NAME}

# Configure the build components
cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --enable-crt \
    --enable-sdk=all \
    --with-default-msvcrt=ucrt \
    --with-default-win32-winnt=0x0A00

# Build the components
make-install

${CP} ${SOURCE_ROOT}/include/module.modulemap \
      ${INSTALL_PREFIX}/include/
${LN} -sf . \
      ${INSTALL_PREFIX}/mingw
${LN} -sf . \
      ${INSTALL_PREFIX}/usr

# Build and install the package
package-invoke-artifact-install
