#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-${QUALIFIED_LLVM_PATH}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-swift-${SOURCE_PACKAGE_VERSION}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

# Invoke one-shot template for cmake/install
COMMON_CFLAGS="\
    -fms-compatibility-version=19.2 \
    -fms-extensions \
    ${COMMON_CFLAGS} \
" \
package-cmake-install-archive \
    -DBUILD_TESTING=FALSE \
    -DENABLE_SWIFT=TRUE
