#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=mingw-w64-crt
export SOURCE_PACKAGE_VERSION=6

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export SOURCE_ROOT=${SOURCE_ROOT_BASE}/mingw-w64-${SOURCE_PACKAGE_VERSION}/${SOURCE_PACKAGE_NAME}

# Invoke one-shot template for configure/install
if [ "${HOST_PROCESSOR}" = "aarch64" ]; then
    ENABLE_OR_DISABLE_LIB64=disable
    ENABLE_OR_DISABLE_LIBARM64=enable
else
    ENABLE_OR_DISABLE_LIB64=enable
    ENABLE_OR_DISABLE_LIBARM64=disable
fi

function package-install-completion-callback() {
    ${LN} -sf \
          `package-get-filename uuid STATIC` \
          ${INSTALL_PREFIX}/lib/`package-get-filename winuuid STATIC`
}

CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
DISABLE_AUTOUPDATE=TRUE \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-stage-configure-install-archive \
    --disable-libarm32 \
    --disable-lib32 \
    --enable-experimental=registeredprintf,softmath \
    --enable-warnings=0 \
    --with-default-msvcrt=ucrt \
    --${ENABLE_OR_DISABLE_LIB64}-lib64 \
    --${ENABLE_OR_DISABLE_LIBARM64}-libarm64
