#!/bin/bash

"$@" -G Ninja \
     -DCMAKE_BUILD_TYPE=Release \
     -DANDROID_NDK=${ANDROID_NDK_HOME} \
     -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
     -DCMAKE_ANDROID_STL_TYPE=c++_shared \
     -DCMAKE_SYSTEM_NAME=Android \
     -DCMAKE_SYSTEM_VERSION=${HOST_OS_API_LEVEL} \



