#!/bin/bash

set -e

yum -y update
yum -y upgrade
yum -y install redhat-lsb

yum -y install \
    apt \
    autoconf \
    bison \
    bzip2 \
    ca-certificates \
    clang \
    cmake \
    dpkg \
    flex \
    gawk \
    git \
    gmp-devel \
    isl-devel \
    jq \
    libmpc-devel \
    libnsl \
    lld \
    llvm \
    make \
    meson \
    mpfr-devel \
    ninja-build \
    patchelf \
    pkg-config \
    python3 \
    python3-distutils-extra \
    python3-six \
    rsync \
    ruby \
    openssh-clients \
    unzip \
    wget

update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/lld 100
