#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=glibc-runtime
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
function package-install-completion-callback() {
    ${RM} -rf \
          ${INSTALL_PREFIX}/../etc \
          ${INSTALL_PREFIX}/../sbin \
          ${INSTALL_PREFIX}/../var \
          ${INSTALL_PREFIX}
}

CONFIGURE_PACKAGE_PLATFORM_PREFIX=/ \
DESTDIR=${INSTALL_PREFIX}/.. \
DISABLE_AUTOUPDATE=TRUE \
DISABLE_FORTIFY_SOURCE_LEVEL=TRUE \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
USE_GCC=TRUE \
package-configure-install-archive \
    libc_cv_include_x86_isa_level=no \
    --disable-crypt \
    --disable-sanity-checks \
    --disable-werror \
    --enable-cet \
    --enable-kernel=5.0 \
    --with-headers=${PACKAGE_PREFIX}/include