#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for stage/configure/install
function package-install-completion-callback() {
    ${SED} -i \
            "s| /| =/|g" \
            ${INSTALL_PREFIX}/glibc-interface/usr/lib/libc.so

    if [ "${HOST_PROCESSOR}" = "x86_64" ]; then
        ${SED} -i \
                "s| /| =/|g" \
                ${INSTALL_PREFIX}/glibc-interface/usr/lib/libm.so
    fi
}

if [ "${HOST_PROCESSOR}" = "x86_64" ]; then
    ENABLE_OR_DISABLE_STATIC_PIE=enable
else
    ENABLE_OR_DISABLE_STATIC_PIE=disable
fi

BUILD_CC=`BINDIR=${BUILD_PACKAGE_PREFIX}/${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_CPU}/bin package-get-path ${BUILD_TRIPLE}-gcc EXECUTABLE BUILD` \
CC=`BINDIR=${BUILD_PACKAGE_PREFIX}/${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU}/bin package-get-path ${HOST_TRIPLE}-gcc EXECUTABLE BUILD` \
CONFIGURE_PACKAGE_PLATFORM_PREFIX=/ \
DESTDIR=${INSTALL_PREFIX}/glibc-interface \
DISABLE_FORTIFY_SOURCE_LEVEL=TRUE \
INSTALL_TARGET=${INSTALL_TARGET} \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
USE_GCC=TRUE \
package-stage-configure-install-archive \
    libc_cv_include_x86_isa_level=no \
    --disable-crypt \
    --disable-multiarch \
    --disable-multilib \
    --disable-sanity-checks \
    --disable-werror \
    --enable-cet=yes \
    --enable-kernel=4.0 \
    --with-headers=${PACKAGE_PREFIX}/include \
    --${ENABLE_OR_DISABLE_STATIC_PIE}-static-pie \
    --with-system-zlib