#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-acl-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-openssl-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-pcre-8-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-util-linux-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU} (>=1.0.0) \
"

# Invoke one-shot template for meson/install
function package-install-completion-callback() {
    ${MV} ${INSTALL_ROOT}/var \
          ${INSTALL_ROOT}/${PACKAGE_PLATFORM_SYSROOT}/
}

PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-meson-install-archive \
    -Dapparmor=false \
    -Daudit=false \
    -Dbinfmt=true \
    -Dbzip2=true \
    -Dcoredump=true \
    -Dcreate-log-dirs=true \
    -Defi=true \
    -Delfutils=true \
    -Denvironment-d=true \
    -Dgcrypt=true \
    -Dglib=true \
    -Dgnutls=true \
    -Dgshadow=true \
    -Dhibernate=true \
    -Dhomed=false \
    -Dhostnamed=true \
    -Dinitrd=true \
    -Dldconfig=true \
    -Dlibcurl=true \
    -Dlink-boot-shared=true \
    -Dlink-networkd-shared=true \
    -Dlink-systemctl-shared=true \
    -Dlink-timesyncd-shared=true \
    -Dlink-udev-shared=true \
    -Dlocaled=true \
    -Dlogind=true \
    -Dlz4=true \
    -Dmachined=true \
    -Dmode=release \
    -Dmicrohttpd=true \
    -Dnetworkd=true \
    -Dopenssl=true \
    -Doomd=true \
    -Dp11kit=true \
    -Dpamconfdir=/etc/pam.d \
    -Dportabled=true \
    -Dpstore=true \
    -Dremote=true \
    -Drepart=false \
    -Dresolve=true \
    -Drootprefix=${PACKAGE_PLATFORM_SYSROOT} \
    -Drootlibdir=${PACKAGE_PREFIX}/lib \
    -Dseccomp=false \
    -Dselinux=false \
    -Dstandalone-binaries=true \
    -Dsysext=true \
    -Dsysvinit-path=${PACKAGE_PLATFORM_SYSROOT}/etc/init.d \
    -Dtimedated=true \
    -Dtimesyncd=true \
    -Dtpm=true \
    -Dtests=false \
    -Duserdb=true \
    -Dutmp=true \
    -Dzlib=true \
    -Dzstd=true
