#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export SYSROOT=${PACKAGE_PREFIX}/glibc-interface

# llvm dependencies
ECHO=/usr/bin/echo \
package-invoke-category-builder llvm-dependencies-gnu

# llvm build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder llvm-project ${LLVM_VERSION}

# souper build
package-invoke-builder souper-cross 1

# cmark build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-cmark-cross 5 none

# swift build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift 5

# lldb build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-lldb 5

# swift sdk build
package-invoke-category-builder swift-sdk-cross

# go build
package-invoke-builder go-cross 1

# ruby build
package-invoke-builder ruby-cross 3

# graphics sdk build
package-invoke-category-builder graphics-sdk-cross

# virtualization sdk build
package-invoke-category-builder virtualization-sdk-cross

if [ "${HOST_PROCESSOR}" = "aarch64" ] ||
   [ "${HOST_PROCESSOR}" = "x86_64" ]; then
    if [ "${BUILD_PROCESSOR}" = "x86_64" ] ||
       [ "${HOST_PROCESSOR}" != "x86_64" ]; then
        # node + sdk build
        package-invoke-builder node-cross 18
        package-invoke-builder npm-yarn-cross 1

        # yautja server build
        # package-invoke-builder yarn-yautja-server-cross 1
    fi
fi

# rust sdk build
package-invoke-category-builder rust-sdk-cross

# networking tools build
package-invoke-category-builder networking-tools-cross

# wine-sdk build
package-invoke-category-builder wine-sdk-cross

# blockchain sdk build
package-invoke-category-builder blockchain-sdk-cross

# blender build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder blender-cross 3

# base system build
package-invoke-category-builder base-system-cross