#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=icu4c
export SOURCE_PACKAGE_VERSION=68

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
CONFIGURE_FILE_ROOT=${SOURCE_ROOT}/${SOURCE_PACKAGE_NAME}/source \
RPATH_COMPONENTS="\
    ${INSTALL_PREFIX}/lib/libicudataswift.so \
    ${INSTALL_PREFIX}/lib/libicui18nswift.so \
    ${INSTALL_PREFIX}/lib/libicuioswift.so \
    ${INSTALL_PREFIX}/lib/libicutestswift.so \
    ${INSTALL_PREFIX}/lib/libicutuswift.so \
    ${INSTALL_PREFIX}/lib/libicuucswift.so \
" \
package-configure-install \
    --disable-extras \
    --disable-samples \
    --disable-static \
    --disable-tests \
    --enable-shared \
    --with-library-suffix=swift