#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# llvm dependencies
ECHO=/usr/bin/echo \
category-invoke-builder llvm-dependencies-gnu

# llvm build
package-invoke-builder llvm-project

# souper build
package-invoke-builder souper-cross

# cmark build
package-invoke-builder swift-cmark-cross

# swift build
package-invoke-builder swift

# lldb build
package-invoke-builder swift-lldb

# swift sdk build
category-invoke-builder swift-sdk-cross

# go build
package-invoke-builder go-cross

# graphics sdk build
category-invoke-builder graphics-sdk-cross

# virtualization sdk build
package-invoke-builder virtualization-sdk-cross

# node + sdk build
package-invoke-builder node-cross
package-invoke-builder npm-yarn-cross

# yautja server build
package-invoke-builder yarn-yautja-server-cross

# wine build
package-invoke-builder wine-cross

# blockchain sdk build
package-invoke-builder blockchain-sdk-cross
