#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=glibc-runtime
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

copy-source-to-staging

# Configure the build components
${MKDIR} -p ${STAGE_ROOT}/build

cd ${STAGE_ROOT}/build

CC=gcc \
CPP=cpp \
CXX=${BINDIR}/clang++ \
DISABLE_COMPILER_TARGET=TRUE \
DISABLE_FPIC=TRUE \
DISABLE_POLLY=TRUE \
DISABLE_UNUSED_ARGUMENTS=TRUE \
FORTIFY_SOURCE_LEVEL=0 \
HOST_ARCH= \
HOST_CPU= \
OPTIMIZATION_LEVEL=2 \
export-compiler-environment
generate-compiler-tools

TOOL_LOG=${STAGE_ROOT}/builder-invocation \
tool-log ${STAGE_ROOT}/configure \
    libc_cv_gcc_builtin_redirection=yes \
    libc_cv_include_x86_isa_level=no \
    --enable-cet \
    --disable-sanity-checks \
    --disable-werror \
    --libdir=/usr/lib \
    --prefix=/usr

# Build the components
make-build

DESTDIR=${INSTALL_PREFIX}/.. \
make-install

${RM} -rf \
      ${INSTALL_PREFIX}/../etc \
      ${INSTALL_PREFIX}/../sbin \
      ${INSTALL_PREFIX}/../var \
      ${INSTALL_PREFIX}

# Build and install the package
package-invoke-archive-install
