#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-tensorflow-apis
export SOURCE_PACKAGE_VERSION=5

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}
package-cmake \
    -DBUILD_TESTING=FALSE \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build and install the package
package-invoke-artifact-install