#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=wayland
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Invoke one-shot template for configure/install
CONFIGURE_FILE=autogen.sh \
OPTIMIZATION_FLAGS="\
    -UNDEBUG \
    ${CFLAGS} \
" \
package-configure-install \
    --disable-documentation \
    --disable-static \
    --disable-tests \
    --enable-shared

# Build and install the package
package-invoke-artifact-install
