#!/bin/bash

set -e

export SYSROOT=/

export \
    APT=/usr/bin/apt \
    AUTORECONF=/usr/bin/autoreconf \
    AUTOUPDATE=/usr/bin/autoupdate \
    BASH=/usr/bin/bash \
    BISON=/usr/bin/bison \
    CHMOD=/usr/bin/chmod \
    CMAKE=/usr/bin/cmake \
    CP=/usr/bin/cp \
    CURL=/usr/bin/curl \
    CUT=/usr/bin/cut \
    DPKG=/usr/bin/dpkg \
    ECHO=/usr/bin/echo \
    FIND=/usr/bin/find \
    GAWK=/usr/bin/gawk \
    GETTEXT=/usr/bin/gettext \
    GIT=/usr/bin/git \
    GPERF=/usr/bin/gperf \
    GREP=/usr/bin/grep \
    HELP2MAN=/usr/bin/true \
    INSTALL=/usr/bin/install \
    LN=/usr/bin/ln \
    LS=/usr/bin/ls \
    M4=/usr/bin/m4 \
    MAKE=/usr/bin/make \
    MAKEINFO=/usr/bin/true \
    MESON=/usr/bin/meson \
    MKDIR=/usr/bin/mkdir \
    MV=/usr/bin/mv \
    NINJA=/usr/bin/ninja \
    PERL=/usr/bin/perl \
    PYTHON=/usr/bin/python3 \
    RM="/usr/bin/rm -f" \
    RMDIR=/usr/bin/rmdir \
    RPM=/usr/bin/rpm \
    RSYNC=/usr/bin/rsync \
    SED=/usr/bin/sed \
    SSH=/usr/bin/ssh \
    TAR=/usr/bin/tar \
    TEE=/usr/bin/tee \
    TR=/usr/bin/tr \
    WGET=/usr/bin/wget \
    XARGS=/usr/bin/xargs \
    XZ=/usr/bin/xz

GUNZIP=/usr/bin/gunzip
GZIP=/usr/bin/gzip
UNZIP=/usr/bin/unzip
ZIP=/usr/bin/zip

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# kernel headers builds
package-invoke-builder kernel-headers-cross

# glibc interface build
package-invoke-builder glibc-interface-cross
unset SYSROOT

# autoconf build
package-invoke-builder autoconf-cross
unset AUTORECONF
unset AUTOUPDATE

# automake build
package-invoke-builder automake-cross

# autoconf-archive build
package-invoke-builder autoconf-archive-cross

# glibc runtime build
package-invoke-builder glibc-runtime-cross

# zlib build
package-invoke-builder zlib-cross

# bzip2 build
package-invoke-builder bzip2-cross

# gzip build
package-invoke-builder gzip-cross
unset GUNZIP
unset GZIP

# lz4 build
package-invoke-builder lz4-cross

# xxhash build
package-invoke-builder xxhash-cross

# zip build
package-invoke-builder zip-cross
unset ZIP

# zstd build
package-invoke-builder zstd-cross

# unzip build
package-invoke-builder unzip-cross
unset UNZIP

# help2man build
package-invoke-builder help2man-cross
unset HELP2MAN

# gperf build
package-invoke-builder gperf-cross
unset GPERF

# libtool build
package-invoke-builder libtool-cross

# libatomic-ops build
package-invoke-builder libatomic-ops-cross

# libffi build
package-invoke-builder libffi-cross

# icu build
package-invoke-builder icu4c-cross

# xz build
package-invoke-builder xz-cross
unset XZ

# libxml2 build
DISABLE_PYTHON=TRUE \
package-invoke-builder libxml2-cross

# libunistring build
package-invoke-builder libunistring-cross

# gc build
package-invoke-builder gc-cross

# gmp build
package-invoke-builder gmp-cross

# ncurses build
package-invoke-builder ncurses-cross

# gettext build
package-invoke-builder gettext-cross
unset GETTEXT

# texinfo build
package-invoke-builder texinfo-cross
unset MAKEINFO

# guile build
package-invoke-builder guile-cross

# make build
package-invoke-builder make-cross
unset MAKE

# m4 build
package-invoke-builder m4-cross
unset M4

# ninja build
package-invoke-builder ninja-cross
unset NINJA

# file build
package-invoke-builder file-cross
unset FILE

# perl build
package-invoke-builder perl-cross
unset PERL

# pcre build
package-invoke-builder pcre-cross

# mpfr build
package-invoke-builder mpfr-cross

# mpc build
package-invoke-builder mpc-cross

# isl build
package-invoke-builder isl-cross

# libev build
package-invoke-builder libev-cross

# gdbm build
CFLAGS="\
    -fcommon \
    ${CFLAGS} \
" \
package-invoke-builder gdbm-cross

# libdb build
package-invoke-builder libdb-cross

# libedit build
package-invoke-builder libedit-cross

# sqlite build
package-invoke-builder sqlite-cross

# openssl build
package-invoke-builder openssl-cross

# libcap build
package-invoke-builder libcap-cross

# expat build
package-invoke-builder expat-cross

# gawk build
package-invoke-builder gawk-cross

# autogen build
package-invoke-builder autogen-cross

# libgpg-error build
package-invoke-builder libgpg-error-cross

# libgcrypt build
package-invoke-builder libgcrypt-cross

# indent build
package-invoke-builder indent-cross

# util-linux build
package-invoke-builder util-linux-cross

# attr build
package-invoke-builder attr-cross

# acl build
package-invoke-builder acl-cross

# libarchive build
package-invoke-builder libarchive-cross

# libmicrohttpd build
package-invoke-builder libmicrohttpd-cross

# libssh2 build
package-invoke-builder libssh2-cross

# curl build
package-invoke-builder curl-cross
unset CURL

# elfutils build
package-invoke-builder elfutils-cross

# glib build
package-invoke-builder glib-cross

# pkg-config build
package-invoke-builder pkg-config-cross

# xorg-macros build
package-invoke-builder xorg-macros-cross

# xorgproto build
package-invoke-builder xorg-xorgproto-cross

# xcb-proto build
package-invoke-builder xcb-proto-cross

# xcb-pthread-stubs build
package-invoke-builder xcb-pthread-stubs-cross

# libxau build
package-invoke-builder xorg-libxau-cross

# libxcb build
package-invoke-builder xcb-libxcb-cross

# pixman build
package-invoke-builder pixman-cross

# xorg-libpciaccess build
package-invoke-builder xorg-libpciaccess-cross

# xorg-libxtrans build
package-invoke-builder xorg-libxtrans-cross

# libx11 build
package-invoke-builder libx11-cross

# libxext build
package-invoke-builder libxext-cross

# xorg-libxrender build
package-invoke-builder xorg-libxrender-cross

# xorg-libxfixes build
package-invoke-builder xorg-libxfixes-cross

# xorg-libxi build
package-invoke-builder xorg-libxi-cross

# xorg-libice build
package-invoke-builder xorg-libice-cross

# alsa-lib build
package-invoke-builder alsa-lib-cross

# cups build
package-invoke-builder cups-cross

# libuv build
package-invoke-builder libuv-cross

# ldns build
package-invoke-builder ldns-cross

# openssh-portable build
package-invoke-builder openssh-portable-cross
unset SSH

# bash build
package-invoke-builder bash-cross
unset BASH

# xorg-libsm build
package-invoke-builder xorg-libsm-cross

# xorg-libxt build
package-invoke-builder xorg-libxt-cross

# xorg-libxtst build
package-invoke-builder xorg-libxtst-cross

# xorg-libxrandr build
package-invoke-builder xorg-libxrandr-cross

# xorg-xinput build
# package-invoke-builder xorg-xinput-cross

# xorg-libxkbfile build
package-invoke-builder xorg-libxkbfile-cross

# xorg-libxshmfence build
package-invoke-builder xorg-libxshmfence-cross

# xorg-libxxf86vm build
package-invoke-builder xorg-libxxf86vm-cross

# freetype2 build
package-invoke-builder freetype2-cross

# wayland build
package-invoke-builder wayland

# wayland-protocols build
package-invoke-builder wayland-protocols-cross

# mesa-drm build
package-invoke-builder mesa-drm-cross

# opencl headers build
package-invoke-builder opencl-headers-cross

# opencl icd loader build
package-invoke-builder opencl-icd-loader-cross

# vulkan headers build
package-invoke-builder vulkan-headers-cross

# vulkan loader build
package-invoke-builder vulkan-loader-cross

# grep build
package-invoke-builder grep-cross
unset GREP

# sed build
package-invoke-builder sed-cross
unset SED

# bison build
package-invoke-builder bison-cross
unset BISON

# flex build
package-invoke-builder flex-cross

# jq build
package-invoke-builder jq-cross

# strace build
package-invoke-builder strace-cross

# fontconfig build
package-invoke-builder fontconfig-cross

# tar build
package-invoke-builder tar-cross
unset TAR

# coreutils build
package-invoke-builder coreutils-cross
unset \
    CHMOD \
    CP \
    CUT \
    ECHO \
    INSTALL \
    LS \
    LN \
    MKDIR \
    MV \
    RM \
    RMDIR \
    TEE \
    TR

# findutils build
package-invoke-builder findutils-cross
unset \
    FIND \
    XARGS

# dpkg build
package-invoke-builder dpkg-cross
unset DPKG

# rsync build
package-invoke-builder rsync-cross
unset RSYNC

# systemd build
package-invoke-builder systemd

# p11-kit build
package-invoke-builder p11-kit-cross

# lua build
package-invoke-builder lua-cross

# popt build
package-invoke-builder popt-cross

# rpm build
package-invoke-builder rpm-cross
unset RPM

# wget build
package-invoke-builder wget-cross
unset WGET

# python build
package-invoke-builder python-cross
unset PYTHON

# libxml2 build (with python support)
package-invoke-builder libxml2-cross

# cython build
package-invoke-builder cython-cross

# pygments build
package-invoke-builder pygments-cross

# numpy build
package-invoke-builder numpy-cross

# mako build
package-invoke-builder mako-cross

# meson build
package-invoke-builder meson-cross
unset MESON

# libxslt build
package-invoke-builder libxslt-cross

# itstool build
package-invoke-builder itstool-cross

# gtk-doc build
package-invoke-builder gtk-doc-cross

# gobject-introspection build
package-invoke-builder gobject-introspection-cross

# libsecret build
package-invoke-builder libsecret-cross

# libtans1 build
package-invoke-builder libtasn1-cross

# nettle build
package-invoke-builder nettle-cross

# gnutls build
package-invoke-builder gnutls-cross

# apt build
package-invoke-builder apt-cross
unset APT

# tensorflow build
package-invoke-builder tensorflow-cross

# swig build
package-invoke-builder swig-cross

# openjdk build
package-invoke-builder openjdk-cross

# z3 build
package-invoke-builder z3-cross

# git build
package-invoke-builder git-cross
unset GIT

# vim build
package-invoke-builder vim-cross

# cmake build
package-invoke-builder cmake-cross
unset CMAKE

# android patch elf
package-invoke-builder android-patch-elf-cross

# jwasm (ml64) cross compiler build
package-invoke-builder jwasm

# re2c build
package-invoke-builder re2c-cross

# alive2 build
package-invoke-builder alive2-cross

# hiredis build
package-invoke-builder hiredis-cross
