#!/bin/bash

set -e

export \
    APT=/usr/bin/apt \
    AUTOGEN=/usr/bin/autogen \
    AUTORECONF=/usr/bin/autoreconf \
    AUTOUPDATE=/usr/bin/autoupdate \
    BASENAME=/usr/bin/basename \
    BASH=/usr/bin/bash \
    BISON=/usr/bin/bison \
    CHMOD=/usr/bin/chmod \
    CMAKE=/usr/bin/cmake \
    CP=/usr/bin/cp \
    CURL=/usr/bin/curl \
    CUT=/usr/bin/cut \
    DNF=/usr/bin/dnf \
    DPKG=/usr/bin/dpkg \
    ECHO=/usr/bin/echo \
    FIND=/usr/bin/find \
    GAWK=/usr/bin/gawk \
    GETTEXT=/usr/bin/gettext \
    GIT=/usr/bin/git \
    GPERF=/usr/bin/gperf \
    GREP=/usr/bin/grep \
    HELP2MAN=/usr/bin/true \
    INSTALL=/usr/bin/install \
    LESS=/usr/bin/less \
    LN=/usr/bin/ln \
    LS=/usr/bin/ls \
    M4=/usr/bin/m4 \
    MAKE=/usr/bin/make \
    MAKEINFO=/usr/bin/true \
    MESON=/usr/bin/meson \
    MKDIR=/usr/bin/mkdir \
    MV=/usr/bin/mv \
    NINJA=/usr/bin/ninja \
    PERL=/usr/bin/perl \
    PYTHON=/usr/bin/python3 \
    RM="/usr/bin/rm -f" \
    RMDIR=/usr/bin/rmdir \
    RPM=/usr/bin/rpm \
    RSYNC=/usr/bin/rsync \
    SED=/usr/bin/sed \
    SSH=/usr/bin/ssh \
    TAR=/usr/bin/tar \
    TEE=/usr/bin/tee \
    TR=/usr/bin/tr \
    WGET=/usr/bin/wget \
    XARGS=/usr/bin/xargs \
    XZ=/usr/bin/xz

GUNZIP=/usr/bin/gunzip
GZIP=/usr/bin/gzip
UNZIP=/usr/bin/unzip
ZIP=/usr/bin/zip

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# kernel headers build
package-invoke-builder kernel-headers-cross

# glibc interface build
CC=/usr/bin/gcc \
package-invoke-builder glibc-interface

# autoconf build
package-invoke-builder autoconf-cross
unset \
    AUTORECONF \
    AUTOUPDATE

# automake build
package-invoke-builder automake-cross

# autoconf-archive build
package-invoke-builder autoconf-archive-cross

# glibc runtime build
CC=/usr/bin/gcc \
package-invoke-builder glibc-runtime

# zlib build
package-invoke-builder zlib-cross

# bzip2 build
package-invoke-builder bzip2-cross

# gzip build
package-invoke-builder gzip-cross
unset \
    GUNZIP \
    GZIP

# lz4 build
package-invoke-builder lz4-cross

# xxhash build
package-invoke-builder xxhash-cross

# zip build
package-invoke-builder zip-cross
unset ZIP

# zstd build
package-invoke-builder zstd-cross

# unzip build
package-invoke-builder unzip-cross
unset UNZIP

# help2man build
package-invoke-builder help2man-cross
unset HELP2MAN

# gperf build
package-invoke-builder gperf-cross
unset GPERF

# libtool build
package-invoke-builder libtool-cross

# libatomic-ops build
package-invoke-builder libatomic-ops-cross

# libffi build
package-invoke-builder libffi-cross

# icu build
package-invoke-builder icu4c-cross

# xz build
package-invoke-builder xz-cross
unset XZ

# libxml2 build
DISABLE_PYTHON=TRUE \
package-invoke-builder libxml2-cross

# libunistring build
package-invoke-builder libunistring-cross

# gc build
package-invoke-builder gc-cross

# gmp build
package-invoke-builder gmp-cross

# ncurses build
package-invoke-builder ncurses-cross

# gettext build
package-invoke-builder gettext-cross
unset GETTEXT

# texinfo build
package-invoke-builder texinfo-cross
unset MAKEINFO

# guile build
package-invoke-builder guile-cross

# make build
package-invoke-builder make-cross
unset MAKE

# m4 build
package-invoke-builder m4-cross
unset M4

# ninja build
package-invoke-builder ninja-cross
unset NINJA

# file build
package-invoke-builder file-cross
unset FILE

# perl build
package-invoke-builder perl-cross
unset PERL

# libedit build
package-invoke-builder libedit-cross

# pcre build
package-invoke-builder pcre-cross

# mpfr build
package-invoke-builder mpfr-cross

# mpc build
package-invoke-builder mpc-cross

# isl build
package-invoke-builder isl-cross

# libaio build
package-invoke-builder libaio-cross

# libev build
package-invoke-builder libev-cross

# gdbm build
package-invoke-builder gdbm-cross

# libdb build
package-invoke-builder libdb-cross

# tcl build
package-invoke-builder tcl-cross

# sqlite build
package-invoke-builder sqlite-cross

# openssl build
package-invoke-builder openssl-cross

# libcap build
package-invoke-builder libcap-cross

# expat build
package-invoke-builder expat-cross

# perl-xml-parser build
package-invoke-builder perl-xml-parser-cross

# gawk build
package-invoke-builder gawk-cross

# autogen build
package-invoke-builder autogen-cross
unset AUTOGEN

# libgpg-error build
package-invoke-builder libgpg-error-cross

# libgcrypt build
package-invoke-builder libgcrypt-cross

# indent build
package-invoke-builder indent-cross

# util-linux build
DISABLE_PYTHON=TRUE \
DISABLE_SYSTEMD=TRUE \
package-invoke-builder util-linux-cross

# attr build
package-invoke-builder attr-cross

# acl build
package-invoke-builder acl-cross

# libarchive build
package-invoke-builder libarchive-cross

# libssh2 build
package-invoke-builder libssh2-cross

# curl build
package-invoke-builder curl-cross
unset CURL

# libndp build
package-invoke-builder libndp-cross

# apple-mig build
package-invoke-builder apple-mig-cross

# alsa-lib build
package-invoke-builder alsa-lib-cross

# libuv build
package-invoke-builder libuv-cross

# ldns build
package-invoke-builder ldns-cross

# c-ares build
package-invoke-builder c-ares-cross

# openssh-portable build
package-invoke-builder openssh-portable-cross
unset SSH

# bash build
package-invoke-builder bash-cross
unset BASH

# grep build
package-invoke-builder grep-cross
unset GREP

# sed build
package-invoke-builder sed-cross
unset SED

# bison build
package-invoke-builder bison-cross
unset BISON

# flex build
package-invoke-builder flex-cross

# jq build
package-invoke-builder jq-cross

# json-c build
package-invoke-builder json-c-cross

# tar build
package-invoke-builder tar-cross
unset TAR

# coreutils build
package-invoke-builder coreutils-cross
unset \
    BASENAME \
    CHMOD \
    CP \
    CUT \
    ECHO \
    INSTALL \
    LS \
    LN \
    MKDIR \
    MV \
    RM \
    RMDIR \
    TEE \
    TR

# less build
package-invoke-builder less-cross
unset LESS

# findutils build
package-invoke-builder findutils-cross
unset \
    FIND \
    XARGS

# dpkg build
package-invoke-builder dpkg-cross
unset DPKG

# rsync build
package-invoke-builder rsync-cross
unset RSYNC

# lua build
package-invoke-builder lua-cross

# wget build
package-invoke-builder wget-cross
unset WGET

# python build
package-invoke-builder python-cross
unset PYTHON

# libxml2 build (with python support)
package-invoke-builder libxml2-cross

# python sdk build
category-invoke-builder python-sdk-cross
unset MESON

# libxslt build
package-invoke-builder libxslt-cross

# itstool build
package-invoke-builder itstool-cross

# gtk-doc build
package-invoke-builder gtk-doc-cross

# graphviz build
package-invoke-builder graphviz-cross

# libtasn1 build
package-invoke-builder libtasn1-cross

# p11-kit build
DISABLE_SYSTEMD=TRUE \
package-invoke-builder p11-kit-cross

# nettle build
package-invoke-builder nettle-cross

# gnutls build
package-invoke-builder gnutls-cross

# unbound build
package-invoke-builder unbound-cross

# libmicrohttpd build
package-invoke-builder libmicrohttpd-cross

# elfutils build
package-invoke-builder elfutils-cross

# strace build
package-invoke-builder strace-cross

# glib build
package-invoke-builder glib-cross

# gobject-introspection build
package-invoke-builder gobject-introspection-cross

# libsecret build
package-invoke-builder libsecret-cross

# pkg-config build
package-invoke-builder pkg-config-cross

# graphics server build
package-invoke-builder graphics-server-cross

# cups build
package-invoke-builder cups-cross

# intltool build
package-invoke-builder intltool-cross

# systemd build
package-invoke-builder systemd

# p11-kit build
package-invoke-builder p11-kit-cross

# dbus build
package-invoke-builder dbus-cross

# util-linux build (with python and systemd support)
package-invoke-builder util-linux-cross

# lvm2 build
package-invoke-builder lvm2-cross

# apt build
package-invoke-builder apt-cross
unset APT

# popt build
package-invoke-builder popt-cross

# rpm build
package-invoke-builder rpm-cross
unset RPM

# rpm build
package-invoke-builder dnf-cross
unset DNF

# tensorflow build
package-invoke-builder tensorflow-cross

# swig build
package-invoke-builder swig-cross

# openjdk build
package-invoke-builder openjdk-cross

# z3 build
package-invoke-builder z3-cross

# git build
package-invoke-builder git-cross
unset GIT

# vim build
package-invoke-builder vim-cross

# cmake build
package-invoke-builder cmake-cross
unset CMAKE

# boost build
package-invoke-builder boost-cross

# cereal build
package-invoke-builder cereal-cross

# libobjc2 build
package-invoke-builder libobjc2-cross

# android patch elf
package-invoke-builder android-patch-elf-cross

# jwasm (ml64) cross compiler build
package-invoke-builder jwasm

# re2c build
package-invoke-builder re2c-cross

# alive2 build
package-invoke-builder alive2-cross

# hiredis build
package-invoke-builder hiredis-cross