#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# rust bootstrap build
package-invoke-builder rust-bootstrap

# rust build
package-invoke-builder rust
