#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=baikonur
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-swift-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-swift-corelibs-foundation-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd ${SOURCE_ROOT}

if [ "${HOST_OS}" = "android" ]; then
    export MAINLINE_BRANCH=val-verde-android-mainline
fi

SWIFT_BUILD_FLAGS="\
    -Xcxx -fno-modules \
    -Xcxx -Wno-unused-command-line-argument \
    -Xlinker -lc++ \
    -Xlinker -licuucswift \
    -Xlinker -lm \
    -Xlinker -lunwind \
    ${SWIFT_BUILD_FLAGS} \
" \
package-swift-build

cd ${STAGE_ROOT}
${MKDIR} -p ${INSTALL_PREFIX}/bin
package-rsync -ax \
              `${FIND} release/baikonur* -executable -type f` \
              ${INSTALL_PREFIX}/bin

# RPATH fixups
COMPONENTS="\
    ${INSTALL_PREFIX}/bin/baikonur \
" \
rpath-fixup

# Build and install the package
package-invoke-artifact-install
