#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=glibc-interface
export SOURCE_PACKAGE_VERSION=2

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

copy-source-to-staging

# Configure the build components
${MKDIR} -p ${STAGE_ROOT}/build

cd ${STAGE_ROOT}/build

DISABLE_FORTIFY_SOURCE_LEVEL=TRUE \
DISABLE_FPIC=TRUE \
HOST_ARCH= \
HOST_CPU= \
OPTIMIZATION_LEVEL=2 \
USE_GCC=TRUE \
export-compiler-environment
generate-compiler-tools

TOOL_LOG=${STAGE_ROOT}/builder-invocation \
tool-log ${STAGE_ROOT}/configure \
    libc_cv_gcc_builtin_redirection=yes \
    libc_cv_include_x86_isa_level=no \
    --enable-cet \
    --disable-sanity-checks \
    --disable-werror \
    --libdir=/usr/lib \
    --prefix=/usr

# Build the components
make-build

DESTDIR=${INSTALL_PREFIX}/.. \
make-install

${RM} -rf ${INSTALL_PREFIX}/../lib
${MV} ${INSTALL_PREFIX}/../lib64 \
      ${INSTALL_PREFIX}/glibc-interface
${LN} -sf \
      ../../lib64/libBrokenLocale.so.1 \
      ${INSTALL_PREFIX}/lib/libBrokenLocale.so
${LN} -sf \
      ../glibc-interface/libanl.so.1 \
      ${INSTALL_PREFIX}/lib/libanl.so
${LN} -sf \
      ../glibc-interface/libcrypt.so.1 \
      ${INSTALL_PREFIX}/lib/libcrypt.so
${LN} -sf \
      ../glibc-interface/libdl.so.2 \
      ${INSTALL_PREFIX}/lib/libdl.so
${LN} -sf \
      ../glibc-interface/libmvec.so.1 \
      ${INSTALL_PREFIX}/lib/libmvec.so
${LN} -sf \
      ../glibc-interface/libnsl.so.1 \
      ${INSTALL_PREFIX}/lib/libnsl.so
${LN} -sf \
      ../glibc-interface/libnss_compat.so.2 \
      ${INSTALL_PREFIX}/lib/libnss_compat.so
${LN} -sf \
      ../glibc-interface/libnss_db.so.2 \
      ${INSTALL_PREFIX}/lib/libnss_db.so
${LN} -sf \
      ../glibc-interface/libnss_dns.so.2 \
      ${INSTALL_PREFIX}/lib/libnss_dns.so
${LN} -sf \
      ../glibc-interface/libnss_files.so.2 \
      ${INSTALL_PREFIX}/lib/libnss_files.so
${LN} -sf \
      ../glibc-interface/libnss_hesiod.so.2 \
      ${INSTALL_PREFIX}/lib/libnss_hesiod.so
${LN} -sf \
      ../glibc-interface/libpthread.so.0 \
      ${INSTALL_PREFIX}/lib/libpthread.so
${LN} -sf \
      ../glibc-interface/libresolv.so.2 \
      ${INSTALL_PREFIX}/lib/libresolv.so
${LN} -sf \
      ../glibc-interface/librt.so.1 \
      ${INSTALL_PREFIX}/lib/librt.so
${LN} -sf \
      ../glibc-interface/libthread_db.so.1 \
      ${INSTALL_PREFIX}/lib/libthread_db.so
${LN} -sf \
      ../glibc-interface/libutil.so.1 \
      ${INSTALL_PREFIX}/lib/libutil.so

if [ "${HOST_PROCESSOR}" = "x86_64" ]; then
    ${SED} -i \
           "s| /lib64/| ${PACKAGE_PREFIX}/glibc-interface/|g" \
           ${INSTALL_PREFIX}/lib/libm.so
    ${SED} -i \
           "s| /usr/| ${PACKAGE_PREFIX}/|g" \
           ${INSTALL_PREFIX}/lib/libm.so
fi

${SED} -i \
       "s| /lib64/| ${PACKAGE_PREFIX}/glibc-interface/|g" \
       ${INSTALL_PREFIX}/lib/libc.so
${SED} -i \
       "s| /usr/| ${PACKAGE_PREFIX}/|g" \
       ${INSTALL_PREFIX}/lib/libc.so

# Build and install the package
package-invoke-archive-install
