#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=systemd
export SOURCE_PACKAGE_VERSION=248

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-acl-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-openssl-1-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-pcre-8-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-util-linux-2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-5-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Invoke one-shot template for meson/install
function package-install-completion-callback() {
    package-rsync -ax \
                  ${STAGE_ROOT}/${SHARED_LIBRARY_PREFIX}systemd*${SHARED_LIBRARY_SUFFIX}* \
                  ${INSTALL_PREFIX}/lib/
}

PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-meson-install-archive \
    -Drootprefix=${PACKAGE_PREFIX} \
    -Dtests=false