#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-tensorflow-apis
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}
${CURL} -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
${MV} bazel.gpg /etc/apt/trusted.gpg.d/
${ECHO} "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
${APT} update
${APT} install -y bazel-3.1.0
${LN} -sf `which bazel-3.1.0` /usr/local/bin/bazel

${BUILD_PACKAGE_PREFIX}/bin/pip3 install --upgrade pip
${BUILD_PACKAGE_PREFIX}/bin/pip3 install wheel
${BUILD_PACKAGE_PREFIX}/bin/pip3 install numpy

SWIFTCFLAGS=" \
    -I${PACKAGE_PREFIX}/lib/swift/${HOST_OS}/dispatch \
    ${SWIFTCFLAGS} \
" \
package-cmake \
    -DBUILD_TESTING=FALSE \
    ${SOURCE_ROOT}

# Build the components
ninja-install

# Build the package
deb-package-build

# Install the package
deb-package-install
