#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# llvm dependencies
ECHO=/usr/bin/echo \
package-invoke-builder llvm-dependencies-gnu

# llvm build
package-invoke-builder llvm-project

# souper build
package-invoke-builder souper-cross

# cmark build
package-invoke-builder swift-cmark

# swift build
package-invoke-builder swift

# lldb build
package-invoke-builder swift-lldb

# libdispatch build
package-invoke-builder swift-corelibs-libdispatch

# foundation build
package-invoke-builder swift-corelibs-foundation

# xctest build
package-invoke-builder swift-corelibs-xctest

# llbuild build
package-invoke-builder swift-llbuild-cross

# swift tools support core build
package-invoke-builder swift-tools-support-core

# yams build
package-invoke-builder yams

# swift argument parser build
package-invoke-builder swift-argument-parser

# swift driver build
package-invoke-builder swift-driver

# swift package manager build
package-invoke-builder swift-package-manager

# reinstall swiftpm for build and host
PACKAGES_TO_MANAGE=( 'swift-argument-parser-5'         'BUILD' \
                     'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-libdispatch-5'    'BUILD' \
                     'swift-corelibs-xctest-5'         'BUILD' \
                     'swift-driver-5'                  'BUILD' \
                     'swift-llbuild-5'                 'BUILD' \
                     'swift-package-manager-5'         'BUILD' \
                     'swift-tools-support-core-5'      'BUILD' \
                     'yams-3'                          'BUILD')

PACKAGE_ACTION=INSTALL \
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# swift-syntax build
package-invoke-builder swift-syntax-cross

# swift-format build
package-invoke-builder swift-format-cross

# swift-doc build
package-invoke-builder swift-doc-cross

# sourcekit-lsp build
package-invoke-builder sourcekit-lsp

# baikonur build
package-invoke-builder baikonur

# pythonkit build
package-invoke-builder pythonkit

# swift tensorflows apis build
# package-invoke-builder swift-tensorflow-apis

# go build
package-invoke-builder go-cross

# graphics sdk build
package-invoke-builder graphics-sdk-cross

# node + sdk build
package-invoke-builder node-cross
package-invoke-builder npm-yarn-cross

# yautja server build
package-invoke-builder yarn-yautja-server-cross

# wine build
package-invoke-builder wine-cross

