#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# llvm build
package-invoke-builder llvm-project-darwin 13

# souper build
package-invoke-builder souper-cross 1

# cmark build
package-invoke-builder swift-cmark-cross 5 none

# swift build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-darwin 5

# lldb build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-lldb-darwin 5
