#!/bin/bash

set -e

# Source package build helper functions
export CONFIGURE_HOST_TRIPLE=${HOST_PROCESSOR}-${HOST_KERNEL}-${DARWIN_OS}${DARWIN_OS_API_LEVEL}
export SYSROOT=${SOURCE_ROOT_BASE}/macosx-${HOST_OS_API_LEVEL}
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# libcxx build
package-invoke-builder libcxx-bootstrap

# llvm dependencies
package-invoke-builder llvm-dependencies-darwin

# swift tools build
# package-invoke-builder swift-tools-darwin

# swift sdk build
# package-invoke-builder swift-sdk-darwin

# go build
package-invoke-builder go-cross

# graphics sdk build
# package-invoke-builder graphics-sdk-cross

# node + sdk build
# package-invoke-builder node-cross
# package-invoke-builder npm-yarn-cross

# rust build
# package-invoke-builder rust-cross
