#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=musl-fts
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

copy-source-to-staging

# Configure the build components
mkdir -p ${STAGE_ROOT}/build
cd ${STAGE_ROOT}

BOOTSTRAP_FILE=./bootstrap.sh \
package-bootstrap

cd ${STAGE_ROOT}/build
package-configure \
    ${STAGE_ROOT}/configure \
    --disable-static \
    --enable-shared

# Build the components
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
