#!/bin/bash

set -e

# llvm build
package-invoke-builder llvm-project-musl

# cmark build
package-invoke-builder swift-cmark

# swift build
package-invoke-builder swift-musl

# lldb build
package-invoke-builder swift-lldb-musl

