#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# llvm build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder llvm-project-musl ${LLVM_VERSION} no-install

# remove libcxx, libcxxabi and libunwind as they are superceded by llvm-project.
PACKAGES_TO_MANAGE=( "libcxx-${LLVM_VERSION}" "HOST" )

package-invoke-archive-action uninstall ${PACKAGES_TO_MANAGE[@]}

# install llvm for host
PACKAGES_TO_MANAGE=( "llvm-project-${LLVM_VERSION}" "HOST"
                     "llvm-project-${LLVM_VERSION}-stage" "HOST" )

package-invoke-archive-action install ${PACKAGES_TO_MANAGE[@]}

# souper build
package-invoke-builder souper-cross 1

# cmark build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-cmark-cross 5 none

# swift build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-musl 5

# lldb build
ENABLE_STAGE_ROOT_BUILD=TRUE \
package-invoke-builder swift-lldb-musl 5

