#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# remove host foundation and libdispatch to avoid module collisions
PACKAGE_ACTION=UNINSTALL
PACKAGES_TO_MANAGE=( 'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-libdispatch-5'    'BUILD' )
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# musl libdispatch build
package-invoke-builder swift-corelibs-libdispatch-cross

# musl foundation build
SWIFTCFLAGS="\
    -lfts \
    -DNO_BACKTRACE \
    ${SWIFTCFLAGS} \
" \
package-invoke-builder swift-corelibs-foundation-cross

# musl xctest build
package-invoke-builder swift-corelibs-xctest-cross

# musl llbuild build
package-invoke-builder swift-llbuild-cross

# musl swift tools support core build
SWIFTCFLAGS="\
    -DUSE_MUSL_LIBC \
    ${SWIFTCFLAGS} \
" \
package-invoke-builder swift-tools-support-core-cross

# musl yams build
package-invoke-builder yams-cross

# musl swift argument parser build
package-invoke-builder swift-argument-parser-cross

# musl swift driver build
package-invoke-builder swift-driver-cross

# musl swift package manager build
SWIFTCFLAGS="\
    -DUSE_MUSL_LIBC \
    ${SWIFTCFLAGS} \
" \
package-invoke-builder swift-package-manager-cross

# reinstall swiftpm for build and host
PACKAGE_ACTION=INSTALL
PACKAGES_TO_MANAGE=( 'swift-argument-parser-5'         'BUILD' \
                     'swift-corelibs-foundation-5'     'BUILD' \
                     'swift-corelibs-libdispatch-5'    'BUILD' \
                     'swift-corelibs-xctest-5'         'BUILD' \
                     'swift-driver-5'                  'BUILD' \
                     'swift-llbuild-5'                 'BUILD' \
                     'swift-package-manager-5'         'BUILD' \
                     'swift-tools-support-core-5'      'BUILD' \
                     'yams-3'                          'BUILD' \
                     'swift-argument-parser-5'         'HOST' \
                     'swift-corelibs-foundation-5'     'HOST' \
                     'swift-corelibs-libdispatch-5'    'HOST' \
                     'swift-corelibs-xctest-5'         'HOST' \
                     'swift-driver-5'                  'HOST' \
                     'swift-llbuild-5'                 'HOST' \
                     'swift-package-manager-5'         'HOST' \
                     'swift-tools-support-core-5'      'HOST' \
                     'yams-3'                          'HOST' )
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# musl swift-syntax build
package-invoke-builder swift-syntax-cross

# musl swift-format build
package-invoke-builder swift-format-cross

# musl swift-doc build
package-invoke-builder swift-doc-cross

# musl sourcekit-lsp build
package-invoke-builder sourcekit-lsp-cross

# musl baikonur build
package-invoke-builder baikonur

# musl pythonkit build
package-invoke-builder pythonkit-cross

# musl swift tensorflows apis build
# package-invoke-builder swift-tensorflow-apis
