#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# kernel headers build
package-invoke-builder kernel-headers-cross 5

# musl headers build
package-invoke-builder musl-headers 1

# compiler-rt build
package-invoke-builder compiler-rt-cross 13

# musl libc build
DISABLE_FORTIFY_SOURCE_LEVEL=TRUE \
package-invoke-builder musl-libc 1

# libcxx build
ENABLE_MUSL_LIBC=TRUE \
package-invoke-builder libcxx-bootstrap 13

# llvm dependencies
package-invoke-category-builder llvm-dependencies-musl

# swift tools build
package-invoke-category-builder swift-tools-musl

# swift sdk build
package-invoke-category-builder swift-sdk-cross

# go build
package-invoke-builder go-cross 1

# ruby build
package-invoke-builder ruby-cross 3

# graphics sdk build
package-invoke-category-builder graphics-sdk-cross

# virtualization sdk build
package-invoke-category-builder virtualization-sdk-cross

# node + sdk build
package-invoke-builder node-cross 16
package-invoke-builder npm-yarn-cross 1

# wine build
package-invoke-builder wine-cross 6

# blockchain sdk build
package-invoke-category-builder blockchain-sdk-cross
