#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=musl-libc
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
function package-install-completion-callback() {
      ${MKDIR} -p ${INSTALL_PREFIX}/bin
      ${LN} -sf \
            ../lib/${SHARED_LIBRARY_PREFIX}c${SHARED_LIBRARY_SUFFIX} \
            ${INSTALL_PREFIX}/bin/ldd
      ${LN} -sf \
            ../usr/lib/${SHARED_LIBRARY_PREFIX}c${SHARED_LIBRARY_SUFFIX} \
            ${INSTALL_PREFIX}/../lib/ld-${HOST_OS}-${HOST_PROCESSOR}${SHARED_LIBRARY_SUFFIX}.1
}

DISABLE_AUTOUPDATE=TRUE \
DISABLE_TOOL_BUILD=TRUE \
LIBCC=`${BUILD_PACKAGE_PREFIX}/bin/clang -target ${HOST_TRIPLE} \
                                         --sysroot ${SYSROOT} \
                                         -print-libgcc-file-name` \
INSTALL_TARGET="install-libs install-tools" \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-configure-install-archive \
    --syslibdir=${SYSROOT}/lib
