#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# kernel headers build
package-invoke-builder kernel-headers-cross

# musl headers build
package-invoke-builder musl-headers

# compiler-rt build
if [ "${BUILD_PROCESSOR}" != ${HOST_PROCESSOR} ]; then
    CLANG_RT_LIB=`package-get-filename clang_rt.builtins-${HOST_PROCESSOR} STATIC` \
    CXXFLAGS="\
        -Dprintf\\\(...\\\)= \
        ${CXXFLAGS} \
    " \
    package-invoke-builder compiler-rt-musl
fi

# musl libc build
package-invoke-builder musl-libc

# libcxx build
ENABLE_MUSL_LIBC=TRUE \
package-invoke-builder libcxx-bootstrap

# llvm dependencies
category-invoke-builder llvm-dependencies-musl

# swift tools build
category-invoke-builder swift-tools-musl

# swift sdk build
category-invoke-builder swift-sdk-musl

# go build
package-invoke-builder go-cross

# graphics sdk build
category-invoke-builder graphics-sdk-cross

# node + sdk build
package-invoke-builder node-cross
package-invoke-builder npm-yarn-cross

# rust build
# package-invoke-builder rust-cross
