#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# llvm build
package-invoke-builder llvm-project-musl

# cmark build
package-invoke-builder swift-cmark

# swift build
package-invoke-builder swift-musl

# lldb build
package-invoke-builder swift-lldb-musl

