#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# kernel headers build
package-invoke-builder kernel-headers-cross

# musl headers build
package-invoke-builder musl-headers

# compiler-rt build
package-invoke-builder compiler-rt-cross

# musl libc build
DISABLE_FORTIFY_SOURCE_LEVEL=TRUE \
package-invoke-builder musl-libc

# libcxx build
ENABLE_MUSL_LIBC=TRUE \
package-invoke-builder libcxx-bootstrap

# llvm dependencies
category-invoke-builder llvm-dependencies-musl

# swift tools build
category-invoke-builder swift-tools-musl

# swift sdk build
category-invoke-builder swift-sdk-cross

# go build
package-invoke-builder go-cross

# graphics sdk build
category-invoke-builder graphics-sdk-cross

# virtualization sdk build
package-invoke-builder virtualization-sdk-cross

# node + sdk build
package-invoke-builder node-cross
package-invoke-builder npm-yarn-cross

# rust build
# package-invoke-builder rust-cross
