#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=musl-libc
export SOURCE_PACKAGE_VERSION=1.0.0

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

# Configure the build components
cd ${STAGE_ROOT}

CFLAGS="\
     -U_ALL_SOURCE \
     ${CFLAGS} \
" \
LIBCC=`${BUILD_PACKAGE_PREFIX}/bin/clang -target ${HOST_TRIPLE} \
                                         --sysroot ${SYSROOT} \
                                         -print-libgcc-file-name` \
package-configure \
    ${SOURCE_ROOT}/configure \
    --syslibdir=${SYSROOT}/lib

# Build the components
INSTALL_TARGET="install-libs install-tools" \
make-install

${MKDIR} -p ${INSTALL_PREFIX}/bin
${LN} -sf \
      ../lib/libc.so \
      ${INSTALL_PREFIX}/bin/ldd
${LN} -sf \
      ../usr/lib/libc.so \
      ${INSTALL_PREFIX}/../lib/ld-${HOST_OS}-${HOST_PROCESSOR}.so.1

# Build the package
deb-package-build

# Install the package
deb-package-install
