#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=musl-libc
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}

LIBCC=`${BUILD_PACKAGE_PREFIX}/bin/clang -target ${HOST_TRIPLE} \
                                         --sysroot ${SYSROOT} \
                                         -print-libgcc-file-name` \

CFLAGS="\
     -U_ALL_SOURCE \
     ${CFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure \
    --syslibdir=${INSTALL_PREFIX}/../lib

# Build the components
INSTALL_TARGET="install-libs install-tools" \
make-install

mkdir -p ${INSTALL_PREFIX}/bin
ln -sf \
   ../lib/libc.so \
   ${INSTALL_PREFIX}/bin/ldd
ln -sf \
   ../usr/lib/libc.so \
   ${INSTALL_PREFIX}/../lib/ld-${HOST_OS}-${HOST_PROCESSOR}.so.1

# Build the package
deb-package-build

# Install the package
deb-package-install
