#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=musl-fts
export SOURCE_PACKAGE_VERSION=1

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export-compiler-environment

# Configure the build components
cd ${SOURCE_ROOT}
./bootstrap.sh

cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-static \
    --enable-shared

# Build the components
make-install

# Build the package
deb-package-build

# Install the package
deb-package-install
