#!/bin/bash

BINDIR=${PACKAGE_ROOT}/bin
SYSROOT=${PACKAGE_ROOT}/val-verde-platform-sdk-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_PROCESSOR}/sysroot

AS=${BINDIR}/llvm-as
AR=${BINDIR}/llvm-ar
CC=${BINDIR}/val-verde-platform-sdk-clang
CPP="${CC} -E"
CXX=${BINDIR}/val-verde-platform-sdk-clang++
LD=${BINDIR}/ld.lld
NM=${BINDIR}/llvm-nm
OBJCOPY=${BINDIR}/llvm-objcopy
OBJDUMP=${BINDIR}/llvm-objdump
RANLIB=${BINDIR}/llvm-ranlib
READELF=${BINDIR}/llvm-readelf
SIZE=${BINDIR}/llvm-size
STRIP=${BINDIR}/llvm-strip
STRINGS=${BINDIR}/llvm-strings

OPTIMIZATION_LEVEL=${OPTIMIZATION_LEVEL:-z}

"$@" AR=${AR} \
     AS=${AS} \
     CC=${CC} \
     CFLAGS="-flto -O${OPTIMIZATION_LEVEL} ${CFLAGS}" \
     CPP="${CPP}" \
     CXX=${CXX} \
     CXXFLAGS="-flto -O${OPTIMIZATION_LEVEL} ${CXXFLAGS}" \
     LD=${LD} \
     LDFLAGS="-flto -lc++_shared -s -O2 --sysroot=${SYSROOT} ${LDFLAGS}" \
     LIBTOOLFLAGS="-avoid-version" \
     NM=${NM} \
     OBJDUMP=${OBJDUMP} \
     PKG_CONFIG_PATH=${PACKAGE_PREFIX}/lib/pkgconfig \
     RANLIB=${RANLIB} \
     READELF=${READELF} \
     SIZE=${SIZE} \
     STRIP=${STRIP} \
     STRINGS=${STRINGS} \
    --build=${BUILD_PROCESSOR}-${BUILD_KERNEL}-${BUILD_OS} \
    --host=${HOST_PROCESSOR}-${HOST_KERNEL}-${HOST_OS}
