#!/bin/bash

apt update && apt upgrade -y && \
    apt install -y \
        alien \
        build-essential \
        ca-certificates \
        clang \
        cmake \
        expat \
        git \
        g++ \
        icu-devtools \
        libc++-dev \
        libc++abi-dev \
        libicu-dev \
        libcurl4-openssl-dev \
        libedit-dev \
        liblzma-dev \
        libncurses-dev \
        libpython2.7 \
        libpython2.7-dev \
        libssl-dev \
        libsqlite3-dev \
        libxml2-dev \
        lld \
        llvm \
        make \
        ninja-build \
        nvidia-cuda-dev \
        pkg-config \
        python \
        python3-distutils \
        python3-six \
        rsync \
        ssh \
        swig \
        uuid-dev \
        zlib1g-dev && \
    apt autoremove && \
    apt clean

update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.lld" 20
