#!/bin/bash

set -e

apt update
apt dist-upgrade -y
apt install -y \
    bison \
    build-essential \
    ca-certificates \
    clang \
    cmake \
    git \
    flex \
    intltool \
    jq \
    libedit-dev \
    libelf-dev \
    libffi-dev \
    libmpc-dev \
    libmpfr-dev \
    libnvidia-compute-440 \
    libsqlite3-dev \
    libxml2-dev \
    libz3-dev \
    lld \
    llvm \
    make \
    meson \
    ninja-build \
    nvidia-cuda-dev \
    nvidia-cuda-toolkit \
    patchelf \
    pkg-config \
    python3 \
    python3-distutils \
    python3-six \
    rsync \
    ssh \
    uuid-dev \
    unzip \
    zlib1g-dev
apt autoremove
apt clean
