#!/bin/bash

set -e

apt update
apt dist-upgrade -y
apt install -y \
    autoconf \
    bison \
    build-essential \
    ca-certificates \
    clang \
    cmake \
    flex \
    gawk \
    git \
    jq \
    libelf-dev \
    libffi-dev \
    libxml2-dev \
    libz3-dev \
    lld \
    llvm \
    make \
    meson \
    ninja-build \
    nvidia-cuda-dev \
    nvidia-cuda-toolkit \
    patchelf \
    pkg-config \
    python3 \
    python3-distutils \
    python3-six \
    rsync \
    ssh \
    uuid-dev \
    unzip \
    zlib1g-dev
apt autoremove -y
apt clean -y
