#!/bin/bash

set -e

apt update
apt dist-upgrade -y
apt install -y \
    autoconf \
    bison \
    build-essential \
    ca-certificates \
    clang \
    cmake \
    flex \
    gawk \
    git \
    jq \
    lld \
    llvm \
    make \
    meson \
    ninja-build \
    patchelf \
    pkg-config \
    python3 \
    python3-distutils \
    python3-six \
    rsync \
    ssh \
    unzip
apt autoremove -y
apt clean -y
