#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=openjdk
export SOURCE_PACKAGE_VERSION=15.0.1
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${SOURCE_ROOT}
wget -c https://download.java.net/java/GA/jdk${SOURCE_PACKAGE_VERSION}/51f4f36ad4ef43e39d0dfdbaf6549e32/9/GPL/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}_${HOST_KERNEL}-x64_bin.tar.gz \
     -O ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}-${BUILD_KERNEL}-${BUILD_PROCESSOR}.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}-${BUILD_KERNEL}-${BUILD_PROCESSOR}.tar.gz

mkdir -p ${INSTALL_ROOT}${BUILD_PACKAGE_PREFIX}
rsync -aPx ${SOURCE_ROOT}/jdk-${SOURCE_PACKAGE_VERSION}/* \
           ${INSTALL_ROOT}${BUILD_PACKAGE_PREFIX}/
