#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libtool
export SOURCE_PACKAGE_VERSION=2.4.6

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure

cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
