#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=jwasm
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
GIT_URL="https://github.com/${SOURCE_PACKAGE_NAME}/${SOURCE_PACKAGE_NAME}.git" \
git-clone master
cd ${STAGE_ROOT}

package-cmake \
    ${SOURCE_ROOT}

# Build the components
ninja -j${NUM_PROCESSORS}
mkdir -p ${INSTALL_ROOT}${PACKAGE_PREFIX}/bin

cp ${STAGE_ROOT}/jwasm* \
   ${INSTALL_ROOT}${PACKAGE_PREFIX}/bin/

deb-package-build

# Build the package
deb-package-install
