#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=icu4c
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}

package-configure \
    ${SOURCE_ROOT}/${SOURCE_PACKAGE_NAME}/source/configure \
    --disable-extras \
    --disable-samples \
    --disable-static \
    --disable-tests \
    --disable-tools \
    --enable-shared \
    --prefix=${INSTALL_PREFIX} \
    --with-cross-build=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH} \
    --with-library-suffix=swift

# Build the components
make-build

# RPATH fixups
COMPONENTS="\
    ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libicudataswift.so \
    ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libicui18nswift.so \
    ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libicuioswift.so \
    ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libicuucswift.so \
" \
rpath-fixup

# Build the package
deb-package-build

# Install the package
deb-package-install
