#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=vapor
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

# Configure & build the package
rm -rf ${SOURCE_ROOT}
git clone https://github.com/${PACKAGE_BASE_NAME}/${SOURCE_PACKAGE_NAME}.git \
          --branch dutch-master \
          --single-branch \
          ${SOURCE_ROOT}

mkdir -p ${STAGE_ROOT}
cd ${SOURCE_ROOT}

SDK_PLATFORM_DIR=`echo ${SYSTEM_NAME} | tr '[:upper:]' '[:lower:]'`
SWIFT_BUILD_FLAGS="\
    -Xlinker -lc++ \
    ${SWIFT_BUILD_FLAGS} \
" \
${PACKAGE_BASE_NAME}-platform-sdk-swift-build

cd ${STAGE_ROOT}
mkdir -p install${BUILD_PACKAGE_PREFIX}/bin
mkdir -p install${BUILD_PACKAGE_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}
rsync -aPx release/vapor* \
           install${BUILD_PACKAGE_PREFIX}/bin
rsync -aPx release/*.swiftdoc \
           release/*.swiftmodule \
           install${BUILD_PACKAGE_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}

# Build the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-install
