#!/bin/bash

set -e

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=icu4c
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}
export QUALIFIED_PACKAGE_NAME=${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}
export INSTALL_ROOT=${TEMPDIR}/org.${VAL_VERDE_GH_TEAM}/${QUALIFIED_PACKAGE_NAME}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

# Configure the build components
rm -rf ${STAGE_ROOT}
git clone https://github.com/${VAL_VERDE_GH_TEAM}/icu.git \
          --branch val-verde-mainline \
          --single-branch \
          ${SOURCE_ROOT}

mkdir -p ${STAGE_ROOT} ${INSTALL_ROOT}
cd ${STAGE_ROOT}

${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-configure \
    ${SOURCE_ROOT}/source/configure \
    --disable-extras \
    --disable-samples \
    --disable-static \
    --disable-tests \
    --enable-shared \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX} \
    --with-library-suffix=swift

# Build the components
make -j${NUM_PROCESSORS}
make-build

# RPATH fixups
COMPONENTS="\
    ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libicudataswift.so \
    ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libicui18nswift.so \
    ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libicuioswift.so \
    ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libicutestswift.so \
    ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libicutuswift.so \
    ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libicuucswift.so \
" \
rpath-fixup

# Build the package
deb-package-build

# Build the package
deb-package-install
