#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=strace
export SOURCE_PACKAGE_VERSION=5.9
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
GIT_URL="https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git" \
git-clone val-verde-mainline

cd ${STAGE_ROOT}

CFLAGS="\
    -Wno-macro-redefined \
    -Wno-unused-command-line-argument \
    ${CFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure \
    --enable-mpers=no \
    --prefix=${INSTALL_PREFIX}

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
