#!/bin/bash

set -e

BINDIR=${BINDIR:-${PACKAGE_ROOT}/bin}
LINKER_OPTIMIZATION_LEVEL=${LINKER_OPTIMIZATION_LEVEL:-2}
OPTIMIZATION_LEVEL=${OPTIMIZATION_LEVEL:-z}
PKG_CONFIG_PATH=${PKG_CONFIG_PATH:-"${PACKAGE_PREFIX}/lib/pkgconfig:${PACKAGE_PREFIX}/share/pkgconfig"}
SDK_PLATFORM_DIR=`echo ${SYSTEM_NAME} | tr '[:upper:]' '[:lower:]'`
SWIFT_BUILD_TYPE=${SWIFT_BUILD_TYPE:-release}
SYSROOT=${SYSROOT:-${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}/sysroot}
TEMP_FILE=`mktemp`

if [ -z "${DISABLE_POLLY}" ]; then
    POLLY_CFLAG="\"-mllvm\", \"-polly\""
    POLLY_SWIFTCFLAG="\"-Xllvm\", \"-polly\""
fi

if [ -z "${DISABLE_STRIP}" ]; then
    STRIP_LDFLAG="-s"
fi

if [ -n "${ENABLE_FLTO}" ]; then
    FLTO_OPTION=`echo ${ENABLE_FLTO} | tr '[:upper:]' '[:lower:]'`
    FLTO_CFLAG="-flto=${FLTO_OPTION}"
    FLTO_SWIFTCFLAG="-whole-module-optimization"
fi

if [ "${SDK_PLATFORM_DIR}" != "windows" ]; then
    FPIC_CFLAG="-fPIC"
    TARGET=${TARGET:-${HOST_PROCESSOR}-unknown-${HOST_KERNEL}-${HOST_OS}${HOST_OS_API_LEVEL}}
else
    TARGET=${TARGET:-${HOST_PROCESSOR}-unknown-windows-gnu}
fi

echo -e "{ \n\
    \"version\": 1, \n\
    \"sdk\": \"${SYSROOT}\", \n\
    \"toolchain-bin-dir\": \"${BINDIR}\", \n\
    \"target\": \"${TARGET}\", \n\
    \"extra-cc-flags\": [ \n\
        \"-march=${HOST_ARCH}\", \n\
        \"-mtune=${HOST_CPU}\", \n\
        \"-I${PACKAGE_PREFIX}/lib/swift\", \n\
        \"-I${PACKAGE_PREFIX}/lib/swift/Block\", \n\
        \"-O${OPTIMIZATION_LEVEL}\", \n\
        \"${FLTO_CFLAG}\", \n\
        \"${FPIC_CFLAG}\", \n\
        ${POLLY_CFLAG} \n\
    ], \n\
    \"extra-cpp-flags\": [ \n\
        \"-I${PACKAGE_PREFIX}/lib/swift\", \n\
        \"-I${PACKAGE_PREFIX}/lib/swift/Block\", \n\
        \"${FLTO_CFLAG}\", \n\
        ${POLLY_CFLAG} \n\
    ], \n\
    \"extra-linker-flags\": [ \n\
        \"-disable-verify\", \n\
        \"-O${LINKER_OPTIMIZATION_LEVEL}\", \n\
        \"${FLTO_CFLAG}\", \n\
        \"${STRIP_LDFLAG}\", \n\
        ${POLLY_CFLAG} \n\
    ], \n\
    \"extra-swiftc-flags\": [ \n\
        \"-target-cpu\", \"${HOST_CPU}\", \n\
        \"-L${PACKAGE_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/${HOST_PROCESSOR}\", \n\
        \"-O${SWIFT_OPTIMIZATION_LEVEL}\", \n\
        \"-Xfrontend\", \"-disable-llvm-verify\", \n\
        \"${FLTO_SWIFTCFLAG}\", \n\
       ${POLLY_SWIFTCFLAG} \n\
    ] \n\
} \n\
" > ${TEMP_FILE}

PKG_CONFIG_PATH=${PKG_CONFIG_PATH} \
${BINDIR}/swift \
    build \
    --build-path ${STAGE_ROOT} \
    --configuration ${SWIFT_BUILD_TYPE} \
    --destination ${TEMP_FILE} \
    --enable-test-discovery \
    ${SWIFT_BUILD_FLAGS}
