#!/bin/bash

set -e

SDK_PLATFORM_DIR=`echo ${SYSTEM_NAME} | tr '[:upper:]' '[:lower:]'`

if [ "${SDK_PLATFORM_DIR}" != "windows" ]; then
    COMPONENT_RPATH=${COMPONENT_RPATH:-"\$ORIGIN/../lib:\$ORIGIN/../lib/swift/${SDK_PLATFORM_DIR}"}

    for COMPONENT in ${COMPONENTS}; do
        patchelf --set-rpath ${COMPONENT_RPATH} \
                             ${COMPONENT}
    done
fi