#!/bin/bash

set -e

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=libsecret
export SOURCE_PACKAGE_VERSION=0.20.4
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}
export QUALIFIED_PACKAGE_NAME=${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}
export INSTALL_ROOT=${TEMPDIR}/org.${VAL_VERDE_GH_TEAM}/${QUALIFIED_PACKAGE_NAME}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:${BUILD_PACKAGE_PREFIX}/lib/x86_64-linux-gnu/pkgconfig:${BUILD_PACKAGE_PREFIX}/lib/pkgconfig:/usr/share/pkgconfig
export ACLOCAL_PATH=/usr/share/aclocal:${BUILD_PACKAGE_PREFIX}/share/aclocal

# Configure the build components
rm -rf ${STAGE_ROOT}
GIT_URL=https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git \
git-clone val-verde-mainline

cd ${STAGE_ROOT}
${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-configure \
    ${SOURCE_ROOT}/configure \
    --disable-gcrypt \
    --disable-static \
    --enable-gtk-doc=no \
    --enable-gtk-doc-html=no \
    --enable-gtk-doc-pdf=no \
    --enable-introspection=no \
    --enable-shared \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX}

# Build the components
make -j${NUM_PROCESSORS}
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
