#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=android-patch-elf
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export-compiler-environment
generate-compiler-tools

export DEPENDS="${PACKAGE_BASE_NAME}-cmake-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
rsync -aPx ${SOURCE_ROOT}/* \
           ${STAGE_ROOT}/

# Build the components
cd ${SOURCE_ROOT}
mkdir -p ${INSTALL_ROOT}${PACKAGE_PREFIX}
MAKE_PROGRAM=${MAKE_PROGRAM:-${BUILD_PACKAGE_PREFIX}/bin/make}

${MAKE_PROGRAM} \
    CC=${CC} \
    CFLAGS="${CFLAGS}" \
    DSTROOT=${INSTALL_ROOT}${PACKAGE_PREFIX} \
    OUTDIR=${STAGE_ROOT} \
    install

# Build the package
cd ${STAGE_ROOT}
deb-package-build

# Install the package
deb-package-install
