#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=wasi-libc
export SOURCE_PACKAGE_VERSION=9999-wasm32
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}
export QUALIFIED_PACKAGE_NAME=${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}
export INSTALL_ROOT=${TEMPDIR}/org.${PACKAGE_BASE_NAME}/${QUALIFIED_PACKAGE_NAME}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

# Configure the package
rm -rf ${SOURCE_ROOT}
git clone https://github.com/${PACKAGE_BASE_NAME}/${SOURCE_PACKAGE_NAME}.git \
          --branch dutch-master \
          --single-branch \
          ${SOURCE_ROOT}
rsync -aPx ${SOURCE_ROOT}/* \
           ${STAGE_ROOT}/
cd ${STAGE_ROOT}
mkdir -p ${INSTALL_ROOT}${PACKAGE_PREFIX}

# Build the components
CFLAGS=`echo "\
    -D_WASI_EMULATED_MMAN \
    -D_WASI_EMULATED_SIGNAL \
" | xargs`

INSTALL_DIR=${INSTALL_ROOT}${PACKAGE_PREFIX} \
OBJDIR=${STAGE_ROOT} \
THREAD_MODEL=local-exec \
WASM_AR=${BUILDER_SCRIPT_PATH}/llvm-ar \
WASM_CC=${BUILDER_SCRIPT_PATH}/${PACKAGE_BASE_NAME}-platform-sdk-clang \
WASM_CFLAGS=${CFLAGS} \
WASM_NM=${BUILDER_SCRIPT_PATH}/llvm-nm \
SYSROOT=${STAGE_ROOT}/sysroot \
${BUILDER_SCRIPT_PATH}/make \
    install

# Build the package
cd ${STAGE_ROOT}
source ${BUILDER_SCRIPT_PATH}/${PACKAGE_BASE_NAME}-platform-sdk-package-${PACKAGE_CLASS}-build

# Install the package
source ${BUILDER_SCRIPT_PATH}/${PACKAGE_BASE_NAME}-platform-sdk-package-install
