#!/bin/bash

set -e

BINDIR=${BINDIR:-${BUILD_PACKAGE_PREFIX}/bin}
BINTOOLS_PREFIX=${BINTOOLS_PREFIX:-llvm-}
BINTOOLS_PATH_PREFIX=${BINDIR}/${BINTOOLS_PREFIX}
CONFIGURE_HOST_TRIPLE=${CONFIGURE_HOST_TRIPLE:-${HOST_TRIPLE}}
LINKER_OPTIMIZATION_LEVEL=${LINKER_OPTIMIZATION_LEVEL:-2}
OPTIMIZATION_FLAGS=${OPTIMIZATION_FLAGS:-"-DNDEBUG"}
OPTIMIZATION_LEVEL=${OPTIMIZATION_LEVEL:-z}
SYSROOT=${SYSROOT:-${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}/sysroot}

if [ -z "${DISABLE_POLLY}" ]; then
    CFLAGS="\
        -mllvm -polly \
        ${CFLAGS} \
    "
    CXXFLAGS="\
        -mllvm -polly \
        ${CXXFLAGS} \
    "
    LDFLAGS="\
        -mllvm -polly \
        ${LDFLAGS} \
    "
fi

if [ -z "${DISABLE_STRIP}" ]; then
    LDFLAGS="\
        -s \
        ${LDFLAGS} \
    "
fi

if [ -z "${ENABLE_LLVM_VERIFIER}" ]; then
    LDFLAGS="\
        -disable-llvm-verifier \
        ${LDFLAGS} \
    "
fi

if [ -n "${ENABLE_FLTO}" ]; then
    FLTO_OPTION=`echo ${ENABLE_FLTO} | tr '[:upper:]' '[:lower:]'`
    FLTO_CFLAG="-flto=${FLTO_OPTION}"
    LDFLAGS="\
        ${FLTO_CFLAG} \
        ${LDFLAGS} \
    "
fi

if [ -n "${LDFLAGS}" ]; then
    LDFLAGS_CMD="LDFLAGS=${LDFLAGS}"
fi

if [ -n "${LIBS}" ]; then
    LIBS_CMD="LIBS=${LIBS}"
fi

AR=${AR:-${BINTOOLS_PATH_PREFIX}ar}
CC=${CC:-${BINDIR}/${PACKAGE_BASE_NAME}-platform-sdk-clang}
CPP=${CPP:-"${CC} -E"}
CXX=${CXX:-${BINDIR}/${PACKAGE_BASE_NAME}-platform-sdk-clang++}
DLLTOOL=${DLLTOOL:-${BINTOOLS_PATH_PREFIX}dlltool}
LD=${LD:-${BINDIR}/ld.lld}
MANIFEST_TOOL=${MANIFEST_TOOL:-${BINTOOLS_PATH_PREFIX}mt}
NM=${NM:-${BINTOOLS_PATH_PREFIX}nm}
OBJCOPY=${OBJCOPY:-${BINTOOLS_PATH_PREFIX}objcopy}
OBJDUMP=${OBJDUMP:-${BINTOOLS_PATH_PREFIX}objdump}
RANLIB=${RANLIB:-${BINTOOLS_PATH_PREFIX}ranlib}
RC=${RC:-${BINDIR}/${PACKAGE_BASE_NAME}-platform-sdk-rc}
PKG_CONFIG_PATH=${PKG_CONFIG_PATH:-"${PACKAGE_PREFIX}/lib/pkgconfig"}
READELF=${READELF:-${BINTOOLS_PATH_PREFIX}readelf}
SIZE=${SIZE:-${BINTOOLS_PATH_PREFIX}size}
STRINGS=${STRINGS:-${BINTOOLS_PATH_PREFIX}strings}
STRIP=${STRIP:-${BINTOOLS_PATH_PREFIX}strip}

if [ -n "${HOST_ARCH}" ]; then
    ARCH_FLAGS="\
        -march=${HOST_ARCH} \
        ${ARCH_FLAGS} \
    "
fi

if [ -n "${HOST_CPU}" ]; then
    ARCH_FLAGS="\
        -mtune=${HOST_CPU} \
        ${ARCH_FLAGS} \
    "
fi

ASFLAGS="\
    ${ARCH_FLAGS} \
    ${FLTO_CFLAG} \
    ${OPTIMIZATION_FLAGS} \
    -O${OPTIMIZATION_LEVEL} \
    ${ASMFLAGS} \
" \
CFLAGS="\
    ${ARCH_FLAGS} \
    ${FLTO_CFLAG} \
    ${OPTIMIZATION_FLAGS} \
    -O${OPTIMIZATION_LEVEL} \
    ${CFLAGS} \
" \
CXXFLAGS="\
    ${ARCH_FLAGS} \
    ${FLTO_CFLAG} \
    ${OPTIMIZATION_FLAGS} \
    -O${OPTIMIZATION_LEVEL} \
    ${CXXFLAGS} \
" \
LDFLAGS="\
    ${ARCH_FLAGS} \
    ${FLTO_LDFLAG} \
    ${LDFLAGS} \
    -O${LINKER_OPTIMIZATION_LEVEL} \
" \
LIBS="${LIBS}" \
"$@" AR=${AR} \
     AS=${CC} \
     ASFLAGS="${ASFLAGS}" \
     CC=${CC} \
     CFLAGS="${CFLAGS}" \
     CPP="${CPP}" \
     CXX=${CXX} \
     CXXFLAGS="${CXXFLAGS}" \
     DLLTOOL=${DLLTOOL} \
     LD=${LD} \
     LDFLAGS="${LDFLAGS}" \
     LIBS="${LIBS}" \
     LIBTOOLFLAGS="-avoid-version" \
     MANIFEST_TOOL=${MANIFEST_TOOL} \
     NM=${NM} \
     OBJCOPY=${OBJCOPY} \
     OBJDUMP=${OBJDUMP} \
     PKG_CONFIG_PATH=${PKG_CONFIG_PATH} \
     RANLIB=${RANLIB} \
     RC=${RC} \
     RCFLAGS=${RCFLAGS} \
     READELF=${READELF} \
     SIZE=${SIZE} \
     STRIP=${STRIP} \
     STRINGS=${STRINGS} \
     WINDRES=${RC} \
    --build=${BUILD_TRIPLE} \
    --host=${CONFIGURE_HOST_TRIPLE} \
    "${CONFIGURE_FLAGS}" \
    "${LDFLAGS_CMD}" \
    "${LIBS_CMD}"
