#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=musl-libc
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}

LIBCC=`${BUILD_PACKAGE_PREFIX}/bin/clang -target ${HOST_TRIPLE} \
                                         --sysroot ${SYSROOT} \
                                         -print-libgcc-file-name` \

CFLAGS="\
     -U_ALL_SOURCE \
     ${CFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX} \
    --syslibdir=${INSTALL_ROOT}${PACKAGE_PREFIX}/../lib

# Build the components
TARGETS="install-libs install-tools" \
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
