#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=wasi-libc
export SOURCE_PACKAGE_VERSION=9999-wasm32

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
copy-source-to-staging

# Build the components
CFLAGS=`echo "\
    -D_WASI_EMULATED_MMAN \
    -D_WASI_EMULATED_SIGNAL \
" | xargs`

cd ${STAGE_ROOT}

INSTALL_DIR=${INSTALL_PREFIX} \
OBJDIR=${STAGE_ROOT} \
THREAD_MODEL=local-exec \
WASM_AR=${BUILD_PACKAGE_PREFIX}/bin/llvm-ar \
WASM_CC=${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-clang \
WASM_CFLAGS=${CFLAGS} \
WASM_NM=${BUILD_PACKAGE_PREFIX}/bin/llvm-nm \
SYSROOT=${STAGE_ROOT}/sysroot \
${BUILD_PACKAGE_PREFIX}/bin/make \
    install

# Build the package
cd ${STAGE_ROOT}
deb-package-build

# Install the package
deb-package-install
