#!/bin/bash

set -e

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# gnu environment
export HOST_TRIPLE=${HOST_PROCESSOR}-${HOST_KERNEL}-${HOST_OS}
export SYSTEM_NAME=Linux

# libunwind bootstrap build
BINDIR=/usr/bin \
LLVM_NATIVE_STAGE_ROOT=/usr \
MAKE_PROGRAM=/usr/bin/ninja \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libunwind-cross

# libcxxabi bootstrap build
BINDIR=/usr/bin \
LLVM_NATIVE_STAGE_ROOT=/usr \
MAKE_PROGRAM=/usr/bin/ninja \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcxxabi-cross

# libcxx bootstrap build
BINDIR=/usr/bin \
LLVM_NATIVE_STAGE_ROOT=/usr \
MAKE_PROGRAM=/usr/bin/ninja \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcxx-cross

# llvm bootstrap build
MAKE_PROGRAM=/usr/bin/ninja \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-llvm-project-bootstrap

# remove host compiler and libraries as it is superceded by bootstrapped clang
apt remove -y clang \
              clang-10 \
              libc++-dev \
              libc++1 \
              libunwind-dev \
              lld \
              lld-10 \
              llvm \
              llvm-10
apt autoremove -y
