#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=pcre
export SOURCE_PACKAGE_VERSION=8.44

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure

if [ "${HOST_OS}" = "mingw32" ]; then
    sed -i \
        "s/-nostdlib//g" \
        ${SOURCE_ROOT}/configure
fi

cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    --prefix=${INSTALL_PREFIX}

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
