#!/bin/bash

set -e

args=("$@")
BINDIR=${BINDIR:-${BUILD_PACKAGE_PREFIX}/bin}
TEMP_FILE=`mktemp`

for ((i=0; i<"${#args[@]}"; ++i)); do
    case ${args[i]} in
    -i)
        IN_FILE=${args[i+1]}
        i=$((i+1))
        ;;
    -o|/fo|/Fo)
        OUT_FILE=${args[i+1]}
        i=$((i+1))
        ;;
    -D)
        DEFINE=`echo ${args[i+1]} | xargs`
        OTHER_FLAGS="${OTHER_FLAGS} -D${DEFINE}"
        i=$((i+1))
        ;;
    -I)
        INCLUDE=`echo ${args[i+1]} | xargs`
        OTHER_FLAGS="${OTHER_FLAGS} -I${INCLUDE}"
        i=$((i+1))
        ;;
    --target*)
        ;;
    *.rc)
        IN_FILE=${args[i]}
        ;;
    -*)
        OTHER=`echo ${args[i]} | xargs`
        OTHER_FLAGS="${OTHER_FLAGS} ${OTHER}"
        ;;
    *)
        OUT_FILE=${args[i]}
        ;;
    esac
done

${BINDIR}/${PACKAGE_BASE_NAME}-platform-sdk-gcc-mingw32 \
    -E \
    -DRC_INVOKED \
    -xc \
    ${OTHER_FLAGS} \
    ${IN_FILE} \
    -o ${TEMP_FILE}
 tr -cd '\11\12\15\40-\176' \
    < ${TEMP_FILE} \
    > ${TEMP_FILE}.rc

WORKING_DIR=`dirname ${IN_FILE}`
pushd ${WORKING_DIR}
${BINDIR}/llvm-rc \
    ${TEMP_FILE}.rc \
    -fo ${TEMP_FILE}.res
popd

rm ${TEMP_FILE}.rc
mv ${TEMP_FILE}.res \
   ${OUT_FILE}
