#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=openjdk
export SOURCE_PACKAGE_VERSION=16

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
chmod +x ${SOURCE_ROOT}/configure

mkdir -p ${STAGE_ROOT}/build ${INSTALL_ROOT}
cd ${STAGE_ROOT}/build

package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-jvm-feature-static-build \
    --disable-static-build \
    --disable-warnings-as-errors \
    --prefix=${INSTALL_PREFIX} \
    --with-boot-jdk=${BUILD_PACKAGE_PREFIX} \
    --with-extra-cflags="-O${OPTIMIZATION_LEVEL}" \
    --with-extra-cxxflags="-O${OPTIMIZATION_LEVEL}" \
    --with-extra-ldflags="-O${LINKER_OPTIMIZATION_LEVEL}" \
    --with-stdc++lib=dynamic \
    --with-toolchain-type=clang

# Build the components
${BUILD_PACKAGE_PREFIX}/bin/make \
    JOBS=${NUM_PROCESSORS} \
    install

# Build the package
deb-package-build

# Build the package
deb-package-install
