#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=strace
export SOURCE_PACKAGE_VERSION=5.9

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export SOURCE_ROOT=${PACKAGE_SOURCES_ROOT}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Configure the build components
cd ${STAGE_ROOT}

CFLAGS="\
    -Wno-macro-redefined \
    -Wno-unused-command-line-argument \
    ${CFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure \
    --enable-mpers=no \
    --prefix=${INSTALL_PREFIX}

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
