#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=unzip
export SOURCE_PACKAGE_VERSION=60

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export-compiler-environment
generate-compiler-tools

# Configure the build components
if [ "${HOST_OS}" = "android" ] ||
   [ "${HOST_OS}" = "gnu" ] ||
   [ "${HOST_OS}" = "musl" ]; then
    PLATFORM=unix
elif [ "${HOST_OS}" = "mingw32" ]; then
    PLATFORM=win32
fi

# Build the components
rsync -aPx ${SOURCE_ROOT}/ \
           ${STAGE_ROOT}

cd ${STAGE_ROOT}
MAKE_PROGRAM=${MAKE_PROGRAM:-${BUILD_PACKAGE_PREFIX}/bin/make}

${MAKE_PROGRAM} \
    -f ${STAGE_ROOT}/${PLATFORM}/Makefile \
    prefix=${INSTALL_ROOT}${PACKAGE_PREFIX} \
    CC=${CC} \
    generic \
    install

# Build the package
deb-package-build

# Install the package
deb-package-install
