#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=swift-package-manager
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}-${HOST_PROCESSOR}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_PROCESSOR}

# Configure the package
mkdir -p ${STAGE_ROOT}
cd ${STAGE_ROOT}

${PACKAGE_BASE_NAME}-platform-sdk-cmake \
    -DCMAKE_INSTALL_PREFIX=${STAGE_ROOT}/install${PACKAGE_PREFIX} \
    -DCMAKE_Swift_COMPILER=${PACKAGE_ROOT}/bin/swiftc \
    -DCMAKE_Swift_COMPILER_TARGET=${HOST_TRIPLE} \
    -DCMAKE_Swift_FLAGS="${SWIFTCFLAGS} \
                         -sdk ${SYSROOT}" \
    -DLLBuild_DIR=/sources/build-staging/swift-llbuild-${HOST_OS}-${HOST_PROCESSOR}/cmake/modules \
    -DSwiftDriver_DIR=/sources/build-staging/swift-driver-${HOST_OS}-${HOST_PROCESSOR}/cmake/modules \
    -DTSC_DIR=/sources/build-staging/swift-tools-support-core-${HOST_OS}-${HOST_PROCESSOR}/cmake/modules \
    -DYams_DIR=/sources/build-staging/yams-${HOST_OS}-${HOST_PROCESSOR}/cmake/modules \
    ${SOURCE_ROOT}

# Build the components
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-ninja-build

# Build the package
rsync -aPx ${STAGE_ROOT}/bin ${STAGE_ROOT}/lib install${PACKAGE_PREFIX}
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-install
dpkg -i ${DEB_PATH}/${PACKAGE_BASE_NAME}-yams-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_PROCESSOR}.deb
dpkg -i ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-tools-support-core-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_PROCESSOR}.deb
