#!/bin/bash

set -e

# zlib build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-zlib-cross

# bzip2 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bzip2-cross

# autoconf build
CONFIGURE_HOST_TRIPLE="${HOST_PROCESSOR}-${HOST_KERNEL}-linux" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-autoconf-cross

# automake build
CONFIGURE_HOST_TRIPLE="${HOST_PROCESSOR}-${HOST_KERNEL}-linux" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-automake-cross

# make build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-make-cross

# libiconv build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libiconv-cross

# pkg-config build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-pkg-config-cross

# gnulib build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gnulib-cross

# pcre build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-pcre-cross

# icu build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-icu4c

# xz build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xz-cross

# libxml2 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libxml2-cross

# libffi build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libffi-cross

# gdbm build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gdbm-cross

# ncurses build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-ncurses-cross

# libedit build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libedit-cross

# sqlite3 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sqlite-cross

# openssl build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-openssl-cross

# libcap build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcap-cross

# libexpat build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-expat-cross

# libuv build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libuv-cross

# libssh2 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libssh2-cross

# curl build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-curl-cross

# gettext build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gettext-cross

# attr build
CFLAGS="\
    -D__BEGIN_DECLS= \
    -D__END_DECLS= \
    -D__THROW= \
    ${CFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-attr-cross

# acl build
CFLAGS="\
    -D__BEGIN_DECLS= \
    -D__END_DECLS= \
    -D__THROW= \
    ${CFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-acl-cross

# bash build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bash-cross

# util-linux build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-util-linux-cross

# libarchive build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libarchive-cross

# libmicrohttpd build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libmicrohttpd-cross

# elfutils build
CFLAGS="\
    -include ${PACKAGE_PREFIX}/include/gnulib/config.h \
    -I${PACKAGE_PREFIX}/include/gnulib \
    ${CFLAGS} \
" \
LDFLAGS="\
    -lgnu \
    ${LIBS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-elfutils-cross

# strace build
# bash ${VAL_VERDE_GH_TEAM}-platform-sdk-strace-cross

# sed build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sed-cross

# bison build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bison-cross

# gawk build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gawk-cross

# gperf build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gperf-cross

# tar build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-tar-cross

# coreutils build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-coreutils-cross

# dpkg build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-dpkg-cross

# systemd build
# bash ${VAL_VERDE_GH_TEAM}-platform-sdk-systemd

# wget build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-wget-cross

# python build
_PYTHON_HOST_PLATFORM=linux-${HOST_PROCESSOR} \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-python-cross

# lua build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-lua-cross

# swig build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swig-cross

# z3 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-z3-cross

# git build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-git-cross

# ninja build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-ninja-cross

# cmake build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-cmake-cross

# android patch elf
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-android-patch-elf-cross

# jwasm (ml64) cross compiler build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-jwasm
