#!/bin/bash
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-config-deb

set -e

BASE_DIRECTORY=$(echo "${PACKAGE_ROOT}" | cut -d "/" -f2)

cd ${INSTALL_ROOT}
tar cf ${PACKAGE_NAME}.tar ${BASE_DIRECTORY}

alien ${PACKAGE_NAME}.tar
rm ${PACKAGE_NAME}.tar
mv *${SOURCE_PACKAGE_NAME}*.deb \
   ${DEB_PATH}/${PACKAGE_NAME}.deb

config-deb "${PACKAGE_NAME}"
