#!/bin/bash

set -e

export COMPILER_TARGET=${HOST_PROCESSOR}-unknown-windows-gnu

# remove host foundation and libdispatch to avoid module collisions
apt remove -y ${PACKAGE_BASE_NAME}-swift-corelibs-foundation-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH} \
              ${PACKAGE_BASE_NAME}-swift-corelibs-libdispatch-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}

# windows libdispatch build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-corelibs-libdispatch-windows

# windows foundation build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-corelibs-foundation-windows

# windows xctest build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-corelibs-xctest-windows

# windows llbuild build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-llbuild-windows

# windows swift-tools-support-core build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-tools-support-core-windows

# windows yams build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-yams-windows

# windows swift-argument-parser build
CFLAGS="\
    -fms-compatibility-version=19.2 \
    -fms-extensions \
    ${CFLAGS} \
" \
CXXFLAGS="\
    -fms-compatibility-version=19.2 \
    -fms-extensions \
    ${CXXFLAGS} \
" \
SWIFTCFLAGS="\
    -use-ld=${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-mslink \
    -L${PACKAGE_PREFIX}/lib/swift/windows/${HOST_PROCESSOR} \
    ${SWIFTCFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-argument-parser-cross

# windows swift-driver build
CFLAGS="\
    -fms-compatibility-version=19.2 \
    -fms-extensions \
    ${CFLAGS} \
" \
CXXFLAGS="\
    -fms-compatibility-version=19.2 \
    -fms-extensions \
    ${CXXFLAGS} \
" \
SWIFTCFLAGS="\
    -use-ld=${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-mslink \
    -L${PACKAGE_PREFIX}/lib/swift/windows/${HOST_PROCESSOR} \
    ${SWIFTCFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-driver-cross

# windows swiftpm build
CFLAGS="\
    -fms-compatibility-version=19.2 \
    -fms-extensions \
    ${CFLAGS} \
" \
CXXFLAGS="\
    -fms-compatibility-version=19.2 \
    -fms-extensions \
    ${CXXFLAGS} \
" \
SWIFTCFLAGS="\
    -use-ld=${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-mslink \
    -L${PACKAGE_PREFIX}/lib/swift/windows/${HOST_PROCESSOR} \
    ${SWIFTCFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-package-manager-cross

# reinstall swiftpm for build and host
dpkg -i ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-argument-parser-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-corelibs-foundation-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-corelibs-libdispatch-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-corelibs-xctest-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-driver-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-llbuild-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-package-manager-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-tools-support-core-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-corelibs-xctest-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-yams-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-argument-parser-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-corelibs-foundation-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-corelibs-libdispatch-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-driver-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-llbuild-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-package-manager-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-tools-support-core-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-swift-corelibs-xctest-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}.deb \
        ${DEB_PATH}/${PACKAGE_BASE_NAME}-yams-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}.deb

# windows swift-syntax build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-syntax-cross

# windows swift-format build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-format-cross

# windows swift-doc build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-doc-cross

# windows sourcekit-lsp build

DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sourcekit-lsp-windows
