#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=gnulib
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
GIT_URL="git://git.savannah.gnu.org/${SOURCE_PACKAGE_NAME}.git" \
git-clone master

${SOURCE_ROOT}/gnulib-tool \
    --dir ${STAGE_ROOT} \
    --create-testdir \
    --without-tests \
    argp \
    error

cd ${STAGE_ROOT}

package-configure \
    ${STAGE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    --prefix=${INSTALL_PREFIX}

# Build the components
make-build

mkdir -p ${INSTALL_ROOT}${PACKAGE_PREFIX}/include/gnulib/config \
         ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib
sed -i \
    "s/#define PACKAGE/#define GNULIB_PACKAGE/g" \
    ${STAGE_ROOT}/config.h
sed -i \
    "s/#define VERSION/#define GNULIB_VERSION/g" \
    ${STAGE_ROOT}/config.h
rsync -aPx ${STAGE_ROOT}/config.h \
           ${INSTALL_ROOT}${PACKAGE_PREFIX}/include/gnulib/config/
rsync -aPx ${STAGE_ROOT}/gllib/*.h \
           ${INSTALL_ROOT}${PACKAGE_PREFIX}/include/gnulib/
rsync -aPx ${STAGE_ROOT}/gllib/*.a \
           ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/

# Build the package
deb-package-build

# Build the package
deb-package-install
