#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=filament
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

rm -rf ${SOURCE_ROOT}
git clone https://github.com/${PACKAGE_BASE_NAME}/${SOURCE_PACKAGE_NAME}.git \
          --single-branch \
          --branch dutch-master \
          ${SOURCE_ROOT}

mkdir -p ${STAGE_ROOT}
cd ${STAGE_ROOT}

if [ "${HOST_OS}" = "android" ]; then
    CMAKE_ANDROID_DEFINE_CMD="-DANDROID=TRUE"
elif [ "${HOST_OS}" = "mingw32" ]; then
    CMAKE_ASM_COMPILER_CMD="-DCMAKE_ASM_COMPILER=${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-ml64"
    CMAKE_ASM_COMPILER_ID_CMD="-DCMAKE_ASM_COMPILER_ID=ml"
    LDFLAGS="\
        -lws2_32 \
        ${LDFLAGS} \
    "
fi

CFLAGS="\
    -fno-builtin \
    -I${PACKAGE_PREFIX}/include \
    ${CFLAGS} \
" \
CXXFLAGS="\
    -fno-builtin \
    -DSTRSAFE_NO_DEPRECATE \
    -I${PACKAGE_PREFIX}/include \
    ${CXXFLAGS} \
" \
LDFLAGS="${LDFLAGS}" \
${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-cmake \
    -DBUILD_WSI_DIRECTFB_SUPPORT=FALSE \
    -DBUILD_WSI_WAYLAND_SUPPORT=FALSE \
    -DBUILD_WSI_XLIB_SUPPORT=FALSE \
    -DCMAKE_ASM_FLAGS_MINSIZEREL= \
    -DFILAMENT_ENABLE_LTO=FALSE \
    -DFILAMENT_SKIP_SAMPLES=FALSE \
    -DFILAMENT_SUPPORTS_VULKAN=TRUE \
    -DSPIRV_WERROR=FALSE \
    -DUSE_STATIC_LIBCXX=FALSE \
    "${CMAKE_ANDROID_DEFINE_CMD}" \
    "${CMAKE_ASM_COMPILER_CMD}" \
    "${CMAKE_ASM_COMPILER_ID_CMD}" \
    ${SOURCE_ROOT}

# Build the components
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-ninja-build

# Build the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-install
