#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=opengl-headers
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=${PACKAGE_SOURCES_ROOT}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}
mkdir -p ${INSTALL_ROOT}${PACKAGE_PREFIX}/include
rsync -aPx ${SOURCE_ROOT}/api/GL \
           ${INSTALL_ROOT}${PACKAGE_PREFIX}/include/

# Build the package
deb-package-build

# Install the package
deb-package-install
