#!/bin/bash

set -e

# windows zlib build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-zlib-cross

# windows bzip2 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bzip2-cross

# windows autoconf build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-autoconf-cross

# windows automake build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-automake-cross

# windows make build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-make-cross

# windows libiconv build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libiconv-cross

# windows pkg-config build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-pkg-config-cross

# windows pcre build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-pcre-cross

# windows icu build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-icu4c-cross

# windows xz build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xz-cross

# windows libxml2 build
LDFLAGS="\
    -Wc,-fuse-ld=${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-mslink \
    ${LDFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libxml2-cross

# windows libffi build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libffi-cross

# android ncurses build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-ncurses-cross

# windows editline build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-wineditline-cross

# windows sqlite3 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sqlite-cross

# windows openssl build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-openssl-cross

# windows libcap build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcap-cross

# windows libexpat build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-expat-cross

# windows libuv build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libuv-cross

# windows libssh2 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libssh2-cross

# windows curl build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-curl-cross

# windows gettext build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gettext-cross

# windows bison build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bison-cross

# windows gperf build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gperf-cross

# windows wget build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-wget-cross

# windows z3 build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-z3-cross

# windows ninja build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-ninja-cross

# windows cmake build
DISABLE_POLLY=TRUE \
LIBS="\
    -lole32 \
    -loleaut32\
    ${LIBS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-cmake-cross

# windows lua build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-lua-cross

# windows jwasm build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-jwasm
