#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=libgcc
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}-${HOST_PROCESSOR}

mkdir -p ${STAGE_ROOT}
cd ${STAGE_ROOT}

${BUILD_PROCESSOR}-${BUILD_KERNEL}-${BUILD_OS}-configure \
    /sources/gcc/configure \
    --disable-bootstrap \
    --disable-gomp \
    --disable-libssp \
    --disable-multilib \
    --disable-werror \
    --enable-languages=c \
    --prefix=${STAGE_ROOT}/install${PACKAGE_PREFIX} \
    --target=${TARGET_PROCESSOR}-${TARGET_KERNEL}-${TARGET_OS} \
    --with-build-sysroot=${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_PROCESSOR}/sysroot \
    --with-native-system-header-dir=/include \
    --with-sysroot=${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_PROCESSOR}/sysroot \
    AR_FOR_TARGET=${PACKAGE_ROOT}/bin/llvm-ar \
    AS_FOR_TARGET=/usr/bin/${TARGET_PROCESSOR}-${TARGET_KERNEL}-${TARGET_OS}-as \
    CC_FOR_TARGET=${PACKAGE_ROOT}/bin/${PACKAGE_BASE_NAME}-platform-sdk-clang \
    CPP_FOR_TARGET="${PACKAGE_ROOT}/bin/${PACKAGE_BASE_NAME}-platform-sdk-clang -E" \
    CXX_FOR_TARGET=${PACKAGE_ROOT}/bin/${PACKAGE_BASE_NAME}-platform-sdk-clang++ \
    DLLTOOL_FOR_TARGET=${PACKAGE_ROOT}/bin/llvm-dlltool \
    GCC_FOR_TARGET=${PACKAGE_ROOT}/bin/${PACKAGE_BASE_NAME}-platform-sdk-clang \
    LIPO_FOR_TARGET=${PACKAGE_ROOT}/bin/llvm-lipo \
    LD_FOR_TARGET="/${PACKAGE_ROOT}/bin/ld.lld /force:multiple" \
    NM_FOR_TARGET=${PACKAGE_ROOT}/bin/llvm-nm \
    OBJCOPY_FOR_TARGET=${PACKAGE_ROOT}/bin/llvm-objcopy \
    OBJDUMP_FOR_TARGET=${PACKAGE_ROOT}/bin/llvm-objdump \
    RANLIB_FOR_TARGET=${PACKAGE_ROOT}/bin/llvm-ranlib \
    READELF_FOR_TARGET=${PACKAGE_ROOT}/bin/llvm-readelf \
    RC_FOR_TARGET=/usr/bin/${TARGET_PROCESSOR}-${TARGET_KERNEL}-${TARGET_OS}-windres \
    SIZE_FOR_TARGET=${PACKAGE_ROOT}/bin/llvm-size \
    STRIP_FOR_TARGET=${PACKAGE_ROOT}/bin/llvm-strip \
    STRINGS_FOR_TARGET=${PACKAGE_ROOT}/bin/llvm-strings

# Build the package
make -j${NUM_PROCESSORS} all-target-libatomic \
                         all-target-libgcc
make -j${NUM_PROCESSORS} install-target-libatomic \
                         install-target-libgcc
mv install${PACKAGE_PREFIX}/${TARGET_PROCESSOR}-${TARGET_KERNEL}-${TARGET_OS}/lib/lib* \
   install${PACKAGE_PREFIX}/lib
mv install${PACKAGE_PREFIX}/lib/gcc/${TARGET_PROCESSOR}-${TARGET_KERNEL}-${TARGET_OS}/11.0.0/include \
   install${PACKAGE_PREFIX}/include
mv install${PACKAGE_PREFIX}/lib/gcc/${TARGET_PROCESSOR}-${TARGET_KERNEL}-${TARGET_OS}/11.0.0/lib* \
   install${PACKAGE_PREFIX}/lib
rm -rf install${PACKAGE_PREFIX}/${TARGET_PROCESSOR}-${TARGET_KERNEL}-${TARGET_OS} \
       install${PACKAGE_PREFIX}/lib/gcc

source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-install