#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-doc
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_PROCESSOR}

# Configure & build the package
rm -rf ${SOURCE_ROOT}
git clone https://github.com/val-verde/${SOURCE_PACKAGE_NAME}.git --single-branch --branch dutch-master ${SOURCE_ROOT}

mkdir -p ${STAGE_ROOT}
cd ${SOURCE_ROOT}
${PACKAGE_BASE_NAME}-platform-sdk-swift-build

cd ${STAGE_ROOT}
mkdir -p install${PACKAGE_ROOT}/bin
rsync -aPx release/swift-doc install${PACKAGE_ROOT}/bin

# Build the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-install
