#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_BASE_NAME=android-ndk
export SOURCE_PACKAGE_NAME=${SOURCE_PACKAGE_BASE_NAME}-runtime
export SOURCE_PACKAGE_VERSION=${ANDROID_NDK_VERSION}
export ANDROID_NDK_STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_BASE_NAME}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}
export TOOLCHAIN_ROOT=${ANDROID_NDK_STAGE_ROOT}/install${BUILD_PACKAGE_PREFIX}/android-ndk-${ANDROID_NDK_VERSION}/toolchains/llvm/prebuilt/${BUILD_KERNEL}-${BUILD_PROCESSOR}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

mkdir -p ${STAGE_ROOT}/install${PACKAGE_PREFIX}/include

rsync -aPx ${TOOLCHAIN_ROOT}/sysroot/usr/lib/${HOST_TRIPLE}/*.so \
           ${TOOLCHAIN_ROOT}/sysroot/usr/lib/${HOST_TRIPLE}/${HOST_OS_API_LEVEL}/* \
           ${TOOLCHAIN_ROOT}/lib/gcc/${HOST_TRIPLE}/4.9.x/*.o \
           ${TOOLCHAIN_ROOT}/${HOST_TRIPLE}/lib64/*.a \
           ${STAGE_ROOT}/install${PACKAGE_PREFIX}/lib

# Remove vulkan and zlib components as they are rebuilt.
rm -f ${STAGE_ROOT}/install${PACKAGE_PREFIX}/lib/libintl* \
      ${STAGE_ROOT}/install${PACKAGE_PREFIX}/lib/libvulkan* \
      ${STAGE_ROOT}/install${PACKAGE_PREFIX}/lib/libz.*

# Build the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-install
