#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=linux
export SOURCE_PACKAGE_VERSION=5.9.12
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export-compiler-environment

# Configure the build components
wget -c https://cdn.kernel.org/pub/${SOURCE_PACKAGE_NAME}/kernel/v5.x/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.xz
tar -xf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.xz

mkdir -p ${INSTALL_ROOT}${PACKAGE_PREFIX}

MAKE_PROGRAM=${MAKE_PROGRAM:-${BUILD_PACKAGE_PREFIX}/bin/make}

ARCH=${HOST_PROCESSOR}

if [ "${HOST_PROCESSOR}" = "aarch64" ]; then
    ARCH=arm64
fi

cd ${STAGE_ROOT}
${MAKE_PROGRAM} \
    -C ${SOURCE_ROOT} \
    ARCH=${ARCH} \
    HOSTCC=${CC} \
    INSTALL_HDR_PATH=${INSTALL_ROOT}${PACKAGE_PREFIX} \
    defconfig \
    headers_install

# Build the package
deb-package-build

# Install the package
deb-package-install
