#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=wasi-libc
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_PROCESSOR}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_PROCESSOR}

# Configure the package
rm -rf ${SOURCE_ROOT}
git clone https://github.com/WebAssembly/${SOURCE_PACKAGE_NAME}.git --single-branch --branch master ${SOURCE_ROOT}

mkdir -p ${STAGE_ROOT}/install${PACKAGE_PREFIX}

# Build the package
cd ${SOURCE_ROOT}
export TARGETS="INSTALL_DIR=${STAGE_ROOT}/install${PACKAGE_PREFIX} OBJDIR=${STAGE_ROOT}"
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-make-build

cd ${STAGE_ROOT}
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-install
