#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=musl-libc
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
GIT_URL="https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git" \
git-clone val-verde-mainline

cd ${STAGE_ROOT}
CFLAGS_AUTO="-pipe" \
LIBCC=`${BUILD_PACKAGE_PREFIX}/bin/clang -target ${HOST_TRIPLE} \
                                         --sysroot ${SYSROOT} \
                                         -print-libgcc-file-name` \
package-configure \
    ${SOURCE_ROOT}/configure \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX} \
    --syslibdir=${INSTALL_ROOT}${PACKAGE_PREFIX}/../lib

# Build the components
TARGETS="install-headers" \
make-build

rm -rf ${INSTALL_ROOT}${PACKAGE_PREFIX}/include/iconv.h

# Build the package
deb-package-build

# Install the package
deb-package-install
