#!/bin/bash

set -e

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# remove host foundation and libdispatch to avoid module collisions
PACKAGE_ACTION=UNINSTALL
PACKAGES_TO_MANAGE=( 'swift-corelibs-foundation'     'BUILD' \
                     'swift-corelibs-libdispatch'    'BUILD' )
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# musl libdispatch build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-corelibs-libdispatch-cross

# musl foundation build
SWIFTCFLAGS="\
    -lfts \
    -DNO_BACKTRACE \
    ${SWIFTCFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-corelibs-foundation-cross

# musl xctest build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-corelibs-xctest-cross

# musl llbuild build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-llbuild-cross

# musl swift tools support core build
SWIFTCFLAGS="\
    -DUSE_MUSL_LIBC \
    ${SWIFTCFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-tools-support-core-cross

# musl yams build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-yams-cross

# musl swift argument parser build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-argument-parser-cross

# musl swift driver build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-driver-cross

# musl swift package manager build
SWIFTCFLAGS="\
    -DUSE_MUSL_LIBC \
    ${SWIFTCFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-package-manager-cross

# reinstall swiftpm for build and host
PACKAGE_ACTION=INSTALL
PACKAGES_TO_MANAGE=( 'swift-argument-parser'         'BUILD' \
                     'swift-corelibs-foundation'     'BUILD' \
                     'swift-corelibs-libdispatch'    'BUILD' \
                     'swift-corelibs-xctest'         'BUILD' \
                     'swift-driver'                  'BUILD' \
                     'swift-llbuild'                 'BUILD' \
                     'swift-package-manager'         'BUILD' \
                     'swift-tools-support-core'      'BUILD' \
		     'yams'                          'BUILD' \
                     'swift-argument-parser'         'HOST' \
                     'swift-corelibs-foundation'     'HOST' \
                     'swift-corelibs-libdispatch'    'HOST' \
                     'swift-corelibs-xctest'         'HOST' \
                     'swift-driver'                  'HOST' \
                     'swift-llbuild'                 'HOST' \
                     'swift-package-manager'         'HOST' \
                     'swift-tools-support-core'      'HOST' \
                     'yams'                          'HOST' )
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# musl swift-syntax build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-syntax-cross

# musl swift-format build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-format-cross

# musl swift-doc build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-doc-cross

# musl sourcekit-lsp build
# bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sourcekit-lsp-cross

# musl baikonur build
SWIFT_BUILD_FLAGS="\
    -licuucswift \
    ${SWIFT_BUILD_FLAGS} \
" \
# bash ${VAL_VERDE_GH_TEAM}-platform-sdk-baikonur

# musl pythonkit build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-pythonkit-cross

# musl swift tensorflows apis build
# bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-tensorflow-apis
