#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=mingw-w64-crt
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/mingw-w64/${SOURCE_PACKAGE_NAME}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-lib32 \
    --enable-experimental=registeredprintf,softmath \
    --enable-warnings=0 \
    --prefix=${INSTALL_PREFIX} \
    --with-default-msvcrt=ucrt

# Build the components
make-build

ln -sf libuuid.a \
       ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libwinuuid.a

# Build the package
deb-package-build

# Install the package
deb-package-install
