#!/bin/bash

set -e

# android zlib build
bash ${PACKAGE_BASE_NAME}-platform-sdk-zlib-cross

# android bzip2 build
bash ${PACKAGE_BASE_NAME}-platform-sdk-bzip2-cross

# android autoconf build
bash ${PACKAGE_BASE_NAME}-platform-sdk-autoconf-cross

# android automake build
bash ${PACKAGE_BASE_NAME}-platform-sdk-automake-cross

# android make build
bash ${PACKAGE_BASE_NAME}-platform-sdk-make-cross

# android pkg-config build
bash ${PACKAGE_BASE_NAME}-platform-sdk-pkg-config-cross

# android icu build
bash ${PACKAGE_BASE_NAME}-platform-sdk-icu4c-cross

# android xz build
bash ${PACKAGE_BASE_NAME}-platform-sdk-xz-cross

# android libxml2 build
bash ${PACKAGE_BASE_NAME}-platform-sdk-libxml2-cross

# android libffi build
bash ${PACKAGE_BASE_NAME}-platform-sdk-libffi-cross

# android gdbm build
bash ${PACKAGE_BASE_NAME}-platform-sdk-gdbm-cross

# android ncurses build
bash ${PACKAGE_BASE_NAME}-platform-sdk-ncurses-cross

# android libedit build
bash ${PACKAGE_BASE_NAME}-platform-sdk-libedit-cross

# android sqlite3 build
bash ${PACKAGE_BASE_NAME}-platform-sdk-sqlite-cross

# android openssl build
bash ${PACKAGE_BASE_NAME}-platform-sdk-openssl-cross

# android libexpat build
bash ${PACKAGE_BASE_NAME}-platform-sdk-expat-cross

# android libssh2 build
bash ${PACKAGE_BASE_NAME}-platform-sdk-libssh2-cross

# android curl build
DISABLE_POLLY=TRUE \
bash ${PACKAGE_BASE_NAME}-platform-sdk-curl-cross

# android gettext build
bash ${PACKAGE_BASE_NAME}-platform-sdk-gettext-cross

# android attr build
CFLAGS="\
    -D__THROW= \
    ${CFLAGS} \
" \
DISABLE_POLLY=TRUE \
LDFLAGS="\
    -lintl \
    ${LDFLAGS} \
" \
bash ${PACKAGE_BASE_NAME}-platform-sdk-attr-cross

# android acl build
CFLAGS="\
    -D__THROW= \
    ${CFLAGS} \
" \
DISABLE_POLLY=TRUE \
LDFLAGS="\
    -lintl \
    ${LDFLAGS} \
" \
bash ${PACKAGE_BASE_NAME}-platform-sdk-acl-cross

# android util-linux build
bash ${PACKAGE_BASE_NAME}-platform-sdk-util-linux-cross

# android strace build
bash ${PACKAGE_BASE_NAME}-platform-sdk-strace-cross

# android sed build
bash ${PACKAGE_BASE_NAME}-platform-sdk-sed-cross

# android bison build
bash ${PACKAGE_BASE_NAME}-platform-sdk-bison-cross

# android gawk build
bash ${PACKAGE_BASE_NAME}-platform-sdk-gawk-cross

# android gperf build
bash ${PACKAGE_BASE_NAME}-platform-sdk-gperf-cross

# android tar build
bash ${PACKAGE_BASE_NAME}-platform-sdk-tar-cross

# android bash build
bash ${PACKAGE_BASE_NAME}-platform-sdk-bash-cross

# android coreutils build
bash ${PACKAGE_BASE_NAME}-platform-sdk-coreutils-cross

# android dpkg build
bash ${PACKAGE_BASE_NAME}-platform-sdk-dpkg-cross

# android wget build
bash ${PACKAGE_BASE_NAME}-platform-sdk-wget-cross

# android python build
_PYTHON_HOST_PLATFORM=${HOST_OS}-${HOST_PROCESSOR} \
CFLAGS="\
    -fPIC \
    -D__ANDROID_API__=${HOST_OS_API_LEVEL} \
    --sysroot=${SYSROOT} \
    ${CFLAGS} \
" \
CPPFLAGS="\
    -fPIC \
    -D__ANDROID_API__=${HOST_OS_API_LEVEL} \
    --sysroot=${SYSROOT} \
    ${CPPFLAGS} \
" \
CXXFLAGS="\
    -fPIC \
    -D__ANDROID_API__=${HOST_OS_API_LEVEL} \
    --sysroot=${SYSROOT} \
    ${CXXFLAGS} \
" \
DISABLE_POLLY=TRUE \
LDFLAGS="\
    --sysroot=${SYSROOT} \
    ${LDFLAGS} \
" \
PYTHON_FOR_BUILD=${BUILD_PACKAGE_PREFIX}/bin/python3 \
bash ${PACKAGE_BASE_NAME}-platform-sdk-python-cross

# android z3 build
DISABLE_POLLY=TRUE \
bash ${PACKAGE_BASE_NAME}-platform-sdk-z3-cross

# android git build
bash ${PACKAGE_BASE_NAME}-platform-sdk-git-cross

# android ninja build
bash ${PACKAGE_BASE_NAME}-platform-sdk-ninja-cross

# android cmake build
DISABLE_POLLY=TRUE \
bash ${PACKAGE_BASE_NAME}-platform-sdk-cmake-android

# android patch elf
bash ${PACKAGE_BASE_NAME}-platform-sdk-android-patch-elf-cross

# android jwasm (ml64) cross compiler build
DISABLE_POLLY=TRUE \
bash ${PACKAGE_BASE_NAME}-platform-sdk-jwasm
