#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=expat
export SOURCE_PACKAGE_VERSION=2.2.10
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
rm -rf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz \
       ${SOURCE_ROOT}
cd /sources
wget -c https://fossies.org/linux/www/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.xz
tar -xf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.xz
sed -i "s/'auto-import'/'ld'/g" ${SOURCE_ROOT}/configure

cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    --prefix=${INSTALL_PREFIX} \
    --without-docbook \
    --without-examples \
    --without-tests

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
