#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=cups
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
GIT_URL="https://github.com/apple/${SOURCE_PACKAGE_NAME}.git" \
git-clone master

rsync -aPx ${SOURCE_ROOT}/* \
           ${STAGE_ROOT}/

cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    --prefix=${INSTALL_PREFIX}

# Build the components
make-build

# Build the package
deb-package-build

# Build the package
deb-package-install
