#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_BASE_NAME=android-ndk
export SOURCE_PACKAGE_NAME=${SOURCE_PACKAGE_BASE_NAME}-runtime
export SOURCE_PACKAGE_VERSION=${ANDROID_NDK_VERSION}
export ANDROID_NDK_STAGE_ROOT=${TEMPDIR}/org.${PACKAGE_BASE_NAME}/${SOURCE_PACKAGE_BASE_NAME}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}
export QUALIFIED_PACKAGE_NAME=${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}
export INSTALL_ROOT=${TEMPDIR}/org.${PACKAGE_BASE_NAME}/${QUALIFIED_PACKAGE_NAME}
export TOOLCHAIN_ROOT=${ANDROID_NDK_STAGE_ROOT}/${BUILD_PACKAGE_PREFIX}/android-ndk-${ANDROID_NDK_VERSION}/toolchains/llvm/prebuilt/${BUILD_KERNEL}-${BUILD_PROCESSOR}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

mkdir -p ${INSTALL_ROOT}${PACKAGE_PREFIX}/include

rsync -aPx ${TOOLCHAIN_ROOT}/sysroot/usr/lib/${HOST_TRIPLE}/*.so \
           ${TOOLCHAIN_ROOT}/sysroot/usr/lib/${HOST_TRIPLE}/${HOST_OS_API_LEVEL}/* \
           ${TOOLCHAIN_ROOT}/lib/gcc/${HOST_TRIPLE}/4.9.x/*.o \
           ${TOOLCHAIN_ROOT}/${HOST_TRIPLE}/lib64/*.a \
           ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib

# Remove vulkan and zlib components as they are rebuilt.
rm -f ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libintl* \
      ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libvulkan* \
      ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libz.*

# Build the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-${PACKAGE_CLASS}-build

# Install the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-install
