#!/bin/bash

set -e

BASE_DIRECTORY=$(echo "${PACKAGE_ROOT}" | cut -d "/" -f2)

cd ${INSTALL_ROOT}
tar cf ${PACKAGE_NAME}.tar ${BASE_DIRECTORY}

alien ${PACKAGE_NAME}.tar
rm ${PACKAGE_NAME}.tar
mv *${SOURCE_PACKAGE_NAME}*.deb \
   ${DEB_PATH}/${PACKAGE_NAME}.deb
