#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=xz
export SOURCE_PACKAGE_VERSION=5.2.5
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
rm -rf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz \
       ${SOURCE_ROOT}
cd /sources
wget -c http://download.openpkg.org/components/cache/${SOURCE_PACKAGE_NAME}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
sed -i "s/'auto-import'/'ld'/g" ${SOURCE_ROOT}/configure

cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX}

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
