#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=vulkan-validation-layers
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}
export INSTALL_ROOT=${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-staging-${SOURCE_PACKAGE_NAME}/${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

rm -rf ${SOURCE_ROOT}
git clone https://github.com/KhronosGroup/Vulkan-ValidationLayers.git \
          --branch master \
          --single-branch \
          ${SOURCE_ROOT}
cd ${SOURCE_ROOT}
patch -p1 \
      -i /sources/patch-vulkan-validation-layers-windows-fixes.diff

mkdir -p ${STAGE_ROOT}
cd ${STAGE_ROOT}

CMAKE_XCB_CMD="-DBUILD_WSI_XCB_SUPPORT=FALSE"

if [ "${HOST_OS}" = "linux" ]; then
    CMAKE_XCB_CMD="-DBUILD_WSI_XCB_SUPPORT=TRUE"
fi

${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-cmake \
    -DBUILD_LAYER_SUPPORT_FILES=TRUE \
    -DBUILD_WSI_DIRECTFB_SUPPORT=FALSE \
    -DBUILD_WSI_WAYLAND_SUPPORT=FALSE \
    -DBUILD_WSI_XLIB_SUPPORT=FALSE \
    -DGLSLANG_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DPKG_CONFIG_EXECUTABLE=${BUILD_PACKAGE_PREFIX}/bin/pkg-config \
    -DSPIRV_HEADERS_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DSPIRV_TOOLS_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DSPIRV_TOOLS_LIB=${PACKAGE_PREFIX}/lib/libSPIRV-Tools.a \
    -DSPIRV_TOOLS_OPT_SEARCH_PATH=${PACKAGE_PREFIX} \
    -DSPIRV_TOOLS_OPT_LIB=${PACKAGE_PREFIX}/lib/libSPIRV-Tools-opt.a \
    -DVulkanHeaders_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DVulkanRegistry_DIR=${PACKAGE_PREFIX}/share/vulkan/registry \
    "${CMAKE_XCB_CMD}" \
    ${SOURCE_ROOT}

# Build the components
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-ninja-build

# Build the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-install
