#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=coreutils
export SOURCE_PACKAGE_VERSION=8.32
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-acl-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-attr-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
GIT_URL="https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git" \
git-clone val-verde-mainline

cd ${STAGE_ROOT}

mkdir -p ${STAGE_ROOT}/bin
ln -sf /usr/bin/true \
       ${STAGE_ROOT}/bin/makeinfo

export FORCE_UNSAFE_CONFIGURE=1
export PATH=${PATH}:${STAGE_ROOT}/bin

CFLAGS="\
    -Wno-unused-command-line-argument \
    ${CFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure \
    --with-openssl \
    --prefix=${INSTALL_PREFIX}

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
