#!/bin/bash

set -e

# llvm build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-llvm-project-musl

# cmark build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-cmark

# swift build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-musl

# lldb build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-lldb-musl

