#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=ncurses
export SOURCE_PACKAGE_VERSION=6.2
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

rm -rf ${SOURCE_ROOT}
cd /sources
wget -c https://ftp.gnu.org/gnu/ncurses/ncurses-6.2.tar.gz
rm -rf ${STAGE_ROOT}/*
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
sed -i "s/'auto-import'/'ld'/g" ${SOURCE_ROOT}/configure

mkdir -p ${STAGE_ROOT}
cd ${STAGE_ROOT}

LDFLAGS=" \
    ${LDFLAGS} \
    ${LIBS} \
" \
OPTIMIZATION_LEVEL=3 \
${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-configure \
    ${SOURCE_ROOT}/configure \
    --enable-ext-colors \
    --enable-mixed-case \
    --enable-pc-files \
    --enable-rpath \
    --enable-sp-funcs \
    --enable-term-driver \
    --prefix=${PACKAGE_PREFIX} \
    --with-curses-h \
    --with-cxx \
    --with-cxx-shared \
    --with-install-prefix=${STAGE_ROOT}/install \
    --with-pkg-config=/usr/bin/pkg-config \
    --with-pkg-config-libdir=${PACKAGE_PREFIX}/lib/pkgconfig \
    --with-shared \
    --with-ticlib \
    --with-tic-path=/usr/bin/tic \
    --without-debug \
    --without-manpages \
    --without-progs \
    --without-tack \
    --without-tests

# Build the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-make-build

# Build the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-install
