#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=xcb-pthread-stubs
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export-compiler-environment

# Configure the build components
copy-source-to-staging

cd ${STAGE_ROOT}

unset ASFLAGS CFLAGS CPPFLAGS CXXFLAGS LDFLAGS
./autogen.sh

package-configure \
    ${STAGE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    --prefix=${INSTALL_PREFIX}

# Build the components
make-build

# Build the package
deb-package-build

# Build the package
deb-package-install
