#!/bin/bash

set -e

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# windows environment
export HOST_TRIPLE=${HOST_PROCESSOR}-${HOST_KERNEL}-${HOST_OS}
export SYSTEM_NAME=Windows

# windows mingw-headers build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-mingw-w64-headers

# windows mingw-crt build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-mingw-w64-crt

# windows compiler-rt build (for host)
CLANG_RT_LIB=libclang_rt.builtins-${HOST_PROCESSOR}.a \
DST_CLANG_RT_LIB=libclang_rt.builtins-${HOST_PROCESSOR}.a \
LDFLAGS="-Wl,/force:unresolved" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-compiler-rt

# windows libunwind build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libunwind-windows

# windows mingw-winpthreads build
LD=${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-mslink \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-winpthreads-cross

# windows libcxxabi build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcxxabi-windows

# windows libcxx build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcxx-windows

# windows llvm dependencies
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-llvm-dependencies-windows

# windows swift tools build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-tools-windows

# windows swift sdk build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-sdk-windows

# windows graphics sdk build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-graphics-sdk-cross
