#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=attr
export SOURCE_PACKAGE_VERSION=2.4.47

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure
rsync -aPx ${SOURCE_ROOT}/ \
           ${STAGE_ROOT}

cd ${STAGE_ROOT}
package-configure \
    ${STAGE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    --prefix=${INSTALL_PREFIX}

# Build the components
TARGETS=" " \
make-build

TARGETS="install install-dev install-lib" \
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
