#!/bin/bash

set -e

# Source package build helper functions

# Set all environment vars
export SOURCE_PACKAGE_NAME=rust
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}

source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export-compiler-environment
generate-compiler-tools

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-llvm-project-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-z3-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"
export LLVM_NATIVE_STAGE_ROOT=${LLVM_NATIVE_STAGE_ROOT:-/sources/build-staging/llvm-project-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}}

# Configure the build components
GIT_URL="https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git" \
git-clone val-verde-mainline

cd ${SOURCE_ROOT}
git submodule init
git submodule update

cd ${STAGE_ROOT}

rsync -aPx ${SOURCE_ROOT}/${VAL_VERDE_GH_TEAM}-config.toml.in \
           ${STAGE_ROOT}/config.toml

BINDIR=${BUILD_PACKAGE_PREFIX}/bin
BUILD_TRIPLE=${BUILD_PROCESSOR}-unknown-${BUILD_KERNEL}-${BUILD_OS}${BUILD_OS_API_LEVEL}

FILECHECK=${LLVM_NATIVE_STAGE_ROOT}/bin/FileCheck
LD=${CC}
LDFLAGS=
LLVMCONFIG=${LLVM_NATIVE_STAGE_ROOT}/bin/llvm-config
NODE=${BINDIR}/node
PYTHON=${BINDIR}/python3

sed -i "s|@@AR@@|${AR}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@BUILD_TRIPLE@@|${BUILD_TRIPLE}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@CC@@|${CC}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@CFLAGS@@|${CFLAGS}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@CXX@@|${CXX}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@CXXFLAGS@@|${CXXFLAGS}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@FILECHECK@@|${FILECHECK}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@INSTALL_PREFIX@@|${INSTALL_PREFIX}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@LD@@|${LD}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@LDFLAGS@@|${LDFLAGS}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@LLVMCONFIG@@|${LLVMCONFIG}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@NODE@@|${NODE}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@PYTHON@@|${PYTHON}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@RANLIB@@|${RANLIB}|g" ${STAGE_ROOT}/config.toml
sed -i "s|@@STAGE_ROOT@@|${STAGE_ROOT}|g" ${STAGE_ROOT}/config.toml

# Build the components
${BUILD_PACKAGE_PREFIX}/bin/python3 ${SOURCE_ROOT}/x.py build --config ${STAGE_ROOT}/config.toml
${BUILD_PACKAGE_PREFIX}/bin/python3 ${SOURCE_ROOT}/x.py install --config ${STAGE_ROOT}/config.toml

# Build the package
deb-package-build

# Install the package
deb-package-install
