#!/bin/bash
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-gen-deb-files

set -e

BASE_DIRECTORY=$(echo "${PACKAGE_ROOT}" | cut -d "/" -f2)

cd ${INSTALL_ROOT}
mkdir -p /sources/pkg-intermediates-${SOURCE_PACKAGE_NAME}/${PACKAGE_NAME}
rsync -aPx ${BASE_DIRECTORY} /sources/pkg-intermediates-${SOURCE_PACKAGE_NAME}/${PACKAGE_NAME}
generate-control-file "${PACKAGE_NAME}"
dpkg -b /sources/pkg-intermediates-${SOURCE_PACKAGE_NAME}/${PACKAGE_NAME}
mv /sources/pkg-intermediates-${SOURCE_PACKAGE_NAME}/${PACKAGE_NAME}.deb ${DEB_PATH}/${PACKAGE_NAME}.deb
rm -r /sources/pkg-intermediates-${SOURCE_PACKAGE_NAME}
