#!/bin/bash

set -e

source /sources/scripts-staging/share/${VAL_VERDE_GH_TEAM}-platform-sdk-deb-packaging-scripts

export SOURCE_PACKAGE_NAME=bootstrap-builders
export SOURCE_PACKAGE_VERSION=9999
export INSTALL_ROOT=/tmp/org.${VAL_VERDE_GH_TEAM}/scripts
export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}
export PACKAGE_ARCH=all

mkdir -p ${INSTALL_ROOT}/usr/libexec \
         ${INSTALL_ROOT}/usr/bin \
         ${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM}

# Move files
mv /sources/scripts-staging/share/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts \
    ${INSTALL_ROOT}/usr/libexec
mv /sources/scripts-staging/share/${VAL_VERDE_GH_TEAM}-platform-sdk-deb-packaging-scripts \
    ${INSTALL_ROOT}/usr/libexec
mv /sources/scripts-staging/share/${VAL_VERDE_GH_TEAM}-platform-sdk-retrieve-sources \
    ${INSTALL_ROOT}/usr/libexec
mv /sources/scripts-staging/share/${VAL_VERDE_GH_TEAM}-sources.json \
    ${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM}
mv /sources/scripts-staging/share/*.in \
    ${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM}
mv /sources/scripts-staging/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-fetch-packages \
    ${INSTALL_ROOT}/usr/bin

# Package debs
BASE_DIRECTORY=${INSTALL_ROOT}/usr \
TEMPLATE_ROOT=${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM} \
deb-package-build
deb-package-install

# Fetch sources
bash /usr/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-fetch-packages
