#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=vulkan-loader
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="${PACKAGE_BASE_NAME}-glslang-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
GIT_URL="https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git" \
git-clone val-verde-mainline

cd ${STAGE_ROOT}

if [ "${HOST_OS}" = "android" ]; then
    CMAKE_ANDROID_DEFINE_CMD="-DANDROID=TRUE"
fi

package-cmake \
    -DBUILD_WSI_DIRECTFB_SUPPORT=FALSE \
    -DBUILD_WSI_WAYLAND_SUPPORT=FALSE \
    -DBUILD_WSI_XLIB_SUPPORT=FALSE \
    -DCMAKE_ASM_MASM_COMPILER_WORKS=FALSE \
    -DJWASM_FOUND=${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-ml64 \
    -DPKG_CONFIG_EXECUTABLE=${PKG_CONFIG} \
    "${CMAKE_ANDROID_DEFINE_CMD}" \
    ${SOURCE_ROOT}

# Build the components
PATH=/sources/build-staging/vulkan-loader-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}/loader:${PATH} \
ninja-build

# Build the package
deb-package-build

# Install the package
deb-package-install
