#!/bin/bash

SYSROOT=${SYSROOT:-${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_PROCESSOR}/sysroot}

${PACKAGE_ROOT}/bin/swift \
    "$@" \
    -Xcc --sysroot=${SYSROOT} \
    -Xcc --target=${HOST_TRIPLE} \
    -Xcxx --sysroot=${SYSROOT} \
    -Xcxx --target=${HOST_TRIPLE} \
    -Xswiftc -sdk -Xswiftc ${SYSROOT} \
    -Xswiftc -target -Xswiftc ${HOST_TRIPLE}
