#!/bin/bash

set -e

export GNUPGHOME="$(mktemp -d)"

cat >temp_key <<EOF
     %echo Generating a basic OpenPGP key
     Key-Type: DSA
     Key-Length: 1024
     Subkey-Type: ELG-E
     Subkey-Length: 1024
     Name-Real: Val Verde
     Name-Email: openvalverde@gmail.com
     Expire-Date: 0
     %echo done
EOF
gpg --batch --generate-key temp_key
#gpg --no-tty --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$KEY"
gpg  -a --output ~/.gnupg/${PACKAGE_BASE_NAME}.gpg --export "${PACKAGE_BASE_NAME}"
gpg --import ~/.gnupg/${PACKAGE_BASE_NAME}.gpg
