#!/bin/bash
set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=swift-syntax
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}-${HOST_PROCESSOR}

# Configure & build the package
git clone https://github.com/val-verde/${SOURCE_PACKAGE_NAME}.git --single-branch --branch dutch-master ${SOURCE_ROOT}
mkdir -p ${STAGE_ROOT}
cd ${SOURCE_ROOT}
swift build ${SWIFTPM_BUILD_ARGS} \
            --build-path ${STAGE_ROOT}
cd ${STAGE_ROOT}
mkdir -p install${PACKAGE_ROOT}/lib/swift/linux
rsync -aPx release/Swift*.swiftdoc install${PACKAGE_ROOT}/lib/swift
rsync -aPx release/Swift*.swiftmodule install${PACKAGE_ROOT}/lib/swift
rsync -aPx release/libSwift*.a install${PACKAGE_ROOT}/lib/swift/linux

# Build the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-install
