#!/bin/bash

set -e

# webassembly libc
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-wasi-libc

# webassembly compiler-rt (bootstrap)
CFLAGS="\
    -nostdlib \
    ${CFLAGS} \
" \
CXXFLAGS="\
    -nostdlib \
    ${CXXFLAGS} \
" \
LDFLAGS="\
    -Wl,--allow-undefined \
    -Wl,--no-entry \
    ${LDFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-compiler-rt-wasi

# webassembly libcxxabi
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcxxabi-wasi

# webassembly libcxx
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcxx-wasi

# webassembly compiler-rt (rebuild with c++)
CXXFLAGS="\
    -stdlib++-isystem ${PACKAGE_PREFIX}/include/c++/v1 \
    -I${PACKAGE_PREFIX}/include \
    ${CXXFLAGS} \
" \
LDFLAGS="\
    -L${PACKAGE_PREFIX}/lib \
    ${LDFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-compiler-rt-wasi
