#!/bin/bash

set -e

if [ "${SYSROOT}" != "/" ]; then
    SYSROOT_CMD="\
        -Xcc --sysroot=${SYSROOT} \
        -Xcxx --sysroot=${SYSROOT} \
        -Xswiftc -sdk -Xswiftc ${SYSROOT} \
    "
fi

${PACKAGE_ROOT}/bin/swift \
    "$@" \
    -Xcc --target=${HOST_TRIPLE} \
    -Xcxx --target=${HOST_TRIPLE} \
    -Xswiftc -target -Xswiftc ${HOST_TRIPLE} \
    ${SYSROOT_CMD}
