#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=acl
export SOURCE_PACKAGE_VERSION=2.2.52
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="${PACKAGE_BASE_NAME}-attr-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
cd /sources
wget -c http://download.savannah.gnu.org/releases/${SOURCE_PACKAGE_NAME}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.src.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.src.tar.gz
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure
rsync -aPx ${SOURCE_ROOT}/ \
           ${STAGE_ROOT}

cd ${STAGE_ROOT}
package-configure \
    ${STAGE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    --includedir=${PACKAGE_PREFIX}/include \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX}

# Build the components
TARGETS=" " \
make-build

TARGETS="install install-dev install-lib" \
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
