#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-syntax
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-swift-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-swift-corelibs-foundation-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Build the components
cd ${SOURCE_ROOT}
package-swift-build

SDK_PLATFORM_DIR=`echo ${SYSTEM_NAME} | tr '[:upper:]' '[:lower:]'`

if [ "${HOST_OS}" = "android" ]; then
    SDK_PLATFORM_DIR="android"
fi

cd ${STAGE_ROOT}
mkdir -p ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/${HOST_PROCESSOR}/
rsync -aPx release/Swift*.swiftdoc \
           ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/${HOST_PROCESSOR}/
rsync -aPx release/Swift*.swiftmodule \
           ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/${HOST_PROCESSOR}/
rsync -aPx release/libSwift*.a \
           ${INSTALL_PREFIX}/lib/swift/${SDK_PLATFORM_DIR}/

# Build the package
deb-package-build

# Install the package
deb-package-install
