#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=python
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-bzip2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-libffi-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-openssl-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-ncurses-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-sqlite-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-util-linux-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd /sources
GIT_URL="https://github.com/${VAL_VERDE_GH_TEAM}/cpython.git" \
git-clone val-verde-mainline

cd ${STAGE_ROOT}

export _PYTHON_PROJECT_BASE=${STAGE_ROOT} \
CFLAGS="\
    -I${PACKAGE_PREFIX}/include/ncurses \
    -I${PACKAGE_PREFIX}/include/uuid \
    ${CFLAGS} \
" \
CPPFLAGS="\
    -I${PACKAGE_PREFIX}/include/ncurses \
    -I${PACKAGE_PREFIX}/include/uuid \
    ${CPPFLAGS} \
" \
CXXFLAGS="\
    -I${PACKAGE_PREFIX}/include/ncurses \
    -I${PACKAGE_PREFIX}/include/uuid \
    ${CXXFLAGS} \
" \
LIBS="\
    -lexpat \
    ${LIBS} \
"

package-configure \
    ${SOURCE_ROOT}/configure \
    ac_cv_buggy_getaddrinfo=no \
    ac_cv_file__dev_ptc=no \
    ac_cv_file__dev_ptmx=yes \
    --enable-shared \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX} \
    --with-ensurepip=yes \
    --with-openssl=${PACKAGE_PREFIX}/include \
    --with-system-expat \
    --with-system-ffi \
    OPENSSL_CFLAGS="-I${PACKAGE_PREFIX}/include" \
    OPENSSL_LDFLAGS="-L${PACKAGE_PREFIX}/lib" \
    OPENSSL_LIBS="-Wl,-lcrypto,-lssl"

# Build the components
make-build

ln -sf python3 ${INSTALL_ROOT}${PACKAGE_PREFIX}/bin/python

# Build the package
deb-package-build

# Install the package
deb-package-install
