#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=wineditline
export SOURCE_PACKAGE_VERSION=2.206
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}/src
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

cd /sources
wget -c https://sourceforge.net/projects/mingweditline/files/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.bz2/download \
     -O ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.bz2
tar -xf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.bz2
wget -c https://raw.githubusercontent.com/nuigroup/ccv-multicam/master/branches/test/videoInput_GUID/videoInputSrcAndDemos/libs/DShow/Include/strsafe.h \
     -O ${SOURCE_ROOT}/Strsafe.h

mkdir -p ${STAGE_ROOT}/install${PACKAGE_PREFIX}
cd ${STAGE_ROOT}

export CFLAGS="${CFLAGS} -I${SOURCE_ROOT}"
${PACKAGE_BASE_NAME}-platform-sdk-cmake \
    ${SOURCE_ROOT}

# Build the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-ninja-build

mv ${SOURCE_ROOT}/bin \
   ${SOURCE_ROOT}/include \
   ${SOURCE_ROOT}/lib \
   ${STAGE_ROOT}/install${PACKAGE_PREFIX}

source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-install
