#!/bin/bash

set -e

args=("$@")
for ((i=0; i<"${#args[@]}"; ++i)); do
    case ${args[i]} in
        -pthread)
        unset args[i]
        break
    esac
done

${BUILD_PACKAGE_PREFIX}/bin/swiftc "${args[@]}"
