#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=builders-bash-scripts
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}
export INSTALL_ROOT=${TEMPDIR}/org.${PACKAGE_BASE_NAME}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}

mkdir -p ${INSTALL_ROOT}${BUILDER_SCRIPT_PATH}

git clone https://github.com/${PACKAGE_BASE_NAME}/${SOURCE_PACKAGE_NAME}.git \
          --single-branch \
          --branch dutch-master \
          ${SOURCE_ROOT}

rsync -aPx ${SOURCE_ROOT}/* ${INSTALL_ROOT}${BUILDER_SCRIPT_PATH}

# Build the package
DEB_GEN_SCRIPT_PATH=${SOURCE_ROOT} \
source ${SOURCE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk-package-${PACKAGE_CLASS}-build

# Install the package
source ${SOURCE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk-package-install
