#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=bison
export SOURCE_PACKAGE_VERSION=3.7.4

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --prefix=${INSTALL_PREFIX}

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
