#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-format
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-swift-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-swift-corelibs-foundation-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
GIT_URL="https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git" \
git-clone val-verde-mainline

# Build the components
cd ${SOURCE_ROOT}
package-swift-build

cd ${STAGE_ROOT}
mkdir -p ${INSTALL_PREFIX}/bin
pushd release
cp `find -type f -name swift-format\*` \
   ${INSTALL_PREFIX}/bin
popd

# Build the package
deb-package-build

# Install the package
deb-package-install
