#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=sdl
export SOURCE_PACKAGE_VERSION=2.0.12

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="${PACKAGE_BASE_NAME}-vulkan-loader-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
cd ${STAGE_ROOT}

if [ "${HOST_OS}" = "android" ]; then
    PLATFORM_CMD="-DANDROID=TRUE"
fi

package-cmake \
    "${PLATFORM_CMD}" \
    ${SOURCE_ROOT}

# Build the components
ninja-build

# Build the package
deb-package-build

# Install the package
deb-package-install
