#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=mingw-w64-headers
export SOURCE_ROOT=/sources/mingw-w64/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_CPU}

mkdir -p ${STAGE_ROOT}
cd ${STAGE_ROOT}
${PACKAGE_BASE_NAME}-platform-sdk-configure \
    ${SOURCE_ROOT}/configure \
    --enable-crt \
    --enable-sdk=all \
    --prefix=${STAGE_ROOT}/install${PACKAGE_PREFIX} \
    --with-default-msvcrt=ucrt \
    --with-default-win32-winnt=0x0A00

# Build the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-make-build

cp /sources/mingw-sdk.modulemap \
   ${STAGE_ROOT}/install${PACKAGE_PREFIX}/include/module.modulemap
ln -sf . \
       ${STAGE_ROOT}/install${PACKAGE_PREFIX}/mingw
ln -sf . \
       ${STAGE_ROOT}/install${PACKAGE_PREFIX}/usr

source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-install
