#!/bin/bash
set -e

export SOURCE_PACKAGE_NAME=swift-format
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}-${HOST_PROCESSOR}

# Configure & build the package
git clone https://github.com/apple/${SOURCE_PACKAGE_NAME}.git --single-branch --branch master ${SOURCE_ROOT}
mkdir -p ${STAGE_ROOT}
cd ${SOURCE_ROOT}
swift build ${SWIFTPM_BUILD_ARGS} \
            --build-path ${STAGE_ROOT}
cd ${STAGE_ROOT}
mkdir -p install${PACKAGE_ROOT}/bin
rsync -aPx release/swift-format install${PACKAGE_ROOT}/bin

# Build the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-install
