#!/bin/bash

set -e

SYSROOT=${SYSROOT:-${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}/sysroot}

${PACKAGE_ROOT}/bin/clang \
    --sysroot=${SYSROOT} \
    --target=${HOST_TRIPLE} \
    "$@"
