#!/bin/bash

set -e

# windows llvm build
DISABLE_POLLY=TRUE \
bash ${PACKAGE_BASE_NAME}-platform-sdk-llvm-project-windows

# windows cmark build
bash ${PACKAGE_BASE_NAME}-platform-sdk-swift-cmark-cross

# windows swift build
DISABLE_POLLY=TRUE \
bash ${PACKAGE_BASE_NAME}-platform-sdk-swift-windows

# windows lldb build
DISABLE_POLLY=TRUE \
bash ${PACKAGE_BASE_NAME}-platform-sdk-swift-lldb-windows
