#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=openjdk
export SOURCE_PACKAGE_VERSION=16
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

JDK_NATIVE_STAGE_ROOT=${JDK_NATIVE_STAGE_ROOT:-${TEMPDIR}/org.${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}/${BUILD_PACKAGE_PREFIX}}

# Configure the build components
GIT_URL="https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git" \
git-clone val-verde-mainline
chmod +x ${SOURCE_ROOT}/configure

mkdir -p ${STAGE_ROOT}/build ${INSTALL_ROOT}
cd ${STAGE_ROOT}/build

package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-jvm-feature-static-build \
    --disable-static-build \
    --disable-warnings-as-errors \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX} \
    --with-boot-jdk=${JDK_NATIVE_STAGE_ROOT} \
    --with-extra-cflags="-O${OPTIMIZATION_LEVEL}" \
    --with-extra-cxxflags="-O${OPTIMIZATION_LEVEL}" \
    --with-extra-ldflags="-O${LINKER_OPTIMIZATION_LEVEL}" \
    --with-stdc++lib=dynamic \
    --with-toolchain-type=clang

# Build the components
${BUILD_PACKAGE_PREFIX}/bin/make \
    JOBS=${NUM_PROCESSORS} \
    install

# Build the package
deb-package-build

# Build the package
deb-package-install
