#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=egl-headers
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}
mkdir -p ${INSTALL_ROOT}${PACKAGE_PREFIX}/include
rsync -aPx ${SOURCE_ROOT}/api/EGL \
           ${INSTALL_ROOT}${PACKAGE_PREFIX}/include/

# Build the package
deb-package-build

# Install the package
deb-package-install
