#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=gdbm
export SOURCE_PACKAGE_VERSION=1.18.1
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd /sources
wget -c https://ftp.gnu.org/gnu/${SOURCE_PACKAGE_NAME}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz \
     -O ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure

cd ${STAGE_ROOT}

LDFLAGS="\
    -Wl,-allow-multiple-definition \
    ${LDFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX}

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
