#!/bin/bash

set -e

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# webassembly environment
export HOST_TRIPLE=${HOST_PROCESSOR}-${HOST_KERNEL}-${HOST_OS} \
export SYSTEM_NAME=Wasi

# webassembly libc
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-wasi-libc

# webassembly compiler-rt (bootstrap)
CFLAGS="\
    -nostdlib \
    ${CFLAGS} \
" \
CXXFLAGS="\
    -nostdlib \
    ${CXXFLAGS} \
" \
LDFLAGS="\
    -Wl,--allow-undefined \
    -Wl,--no-entry \
    ${LDFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-compiler-rt-wasi

# webassembly libcxxabi
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcxxabi-wasi

# webassembly libcxx
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcxx-wasi

# webassembly compiler-rt (rebuild with c++)
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-compiler-rt-wasi
