#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libuv
export SOURCE_PACKAGE_VERSION=1.40.0
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-zlib-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

GIT_URL=https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git \
git-clone val-verde-mainline

cd ${STAGE_ROOT}

if [ "${HOST_OS}" = "android" ]; then
    FORCE_ANDROID_CMD="-DFORCE_ANDROID=TRUE"
fi

package-cmake \
    -DBUILD_TESTING=FALSE \
    ${FORCE_ANDROID_CMD} \
    ${SOURCE_ROOT}

# Build the components
ninja-build

# Build the package
deb-package-build

# Install the package
deb-package-install
