#!/bin/bash

set -e

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# android environment
export HOST_TRIPLE=${HOST_PROCESSOR}-${HOST_KERNEL}-${HOST_OS}
export PACKAGE_PREFIX=${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk/${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}/sysroot/usr
export SYSROOT=${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk/${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}/sysroot

# android compiler flags
export CFLAGS="\
    -D__ANDROID_API__=${HOST_OS_API_LEVEL} \
"
export CPPFLAGS="\
    -D__ANDROID_API__=${HOST_OS_API_LEVEL} \
"
export CXXFLAGS="\
    -D__ANDROID_API__=${HOST_OS_API_LEVEL} \
"
export LDFLAGS="\
    -L${PACKAGE_PREFIX}/lib \
"
export SWIFT_BUILD_FLAGS="\
    -Xcc -D__ANDROID_API__=${HOST_OS_API_LEVEL} \
    -Xcc -I${PACKAGE_PREFIX}/include \
    -Xcxx -D__ANDROID_API__=${HOST_OS_API_LEVEL} \
    -Xcxx -I${PACKAGE_PREFIX}/include \
    -Xlinker -L${PACKAGE_PREFIX}/lib \
"
export SWIFTCFLAGS="\
    -sdk ${SYSROOT} \
"

# android ndk headers build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-android-ndk-headers

# android ndk runtime build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-android-ndk-runtime

# android compiler-rt build (for host)
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-compiler-rt

# android libunwind build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libunwind-cross

# android libcxxabi build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcxxabi-cross

# android libcxx build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcxx-cross

# android llvm dependencies build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-llvm-dependencies-android

# android llvm build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-llvm-project-android

# android cmark build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-cmark-cross

# android swift build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-android

# android lldb build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-lldb-android

# android libdispatch build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-corelibs-libdispatch-cross

# remove host foundation and libdispatch to avoid module collisions
PACKAGES_TO_MANAGE=( 'swift-corelibs-foundation'     'BUILD' \
                     'swift-corelibs-libdispatch'    'BUILD' )

PACKAGE_ACTION=UNINSTALL \
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# android foundation build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-corelibs-foundation-cross

# android xctest build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-corelibs-xctest-cross

# android llbuild build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-llbuild-android

# android swift-tools-support-core build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-tools-support-core-android

# android yams build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-yams-cross

# android swift-argument-parser build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-argument-parser-cross

# android swift-driver build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-driver-cross

# android swiftpm build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-package-manager-cross

# reinstall swiftpm for build and host
PACKAGES_TO_MANAGE=( 'swift-argument-parser'         'BUILD' \
                     'swift-corelibs-foundation'     'BUILD' \
                     'swift-corelibs-libdispatch'    'BUILD' \
                     'swift-corelibs-xctest'         'BUILD' \
                     'swift-driver'                  'BUILD' \
                     'swift-llbuild'                 'BUILD' \
                     'swift-package-manager'         'BUILD' \
                     'swift-tools-support-core'      'BUILD' \
                     'yams'                          'BUILD' \
                     'swift-argument-parser'         'HOST' \
                     'swift-corelibs-foundation'     'HOST' \
                     'swift-corelibs-libdispatch'    'HOST' \
                     'swift-corelibs-xctest'         'HOST' \
                     'swift-driver'                  'HOST' \
                     'swift-llbuild'                 'HOST' \
                     'swift-package-manager'         'HOST' \
                     'swift-tools-support-core'      'HOST' \
                     'yams'                          'HOST' )

PACKAGE_ACTION=INSTALL \
deb-package-mgmt ${PACKAGES_TO_MANAGE[@]}

# android swift-syntax build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-syntax-cross

# android swift-format build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-format-cross

# android swift-doc build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swift-doc-cross

# android sourcekit-lsp build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sourcekit-lsp-android

# android baikonur build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-baikonur

# android pythonkit build
DISABLE_POLLY=TRUE \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-pythonkit-cross

# android graphics sdk build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-graphics-sdk-cross

# android node + sdk build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-node-cross
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-npm-yarn-cross
