#!/bin/bash

set -e

# webassembly libc
bash ${PACKAGE_BASE_NAME}-platform-sdk-wasi-libc

# webassembly compiler-rt
LDFLAGS="\
    -Wl,--no-entry \
    ${LDFLAGS} \
" \
SYSTEM_NAME=Fuchsia \
bash ${PACKAGE_BASE_NAME}-platform-sdk-compiler-rt-wasi

# webassembly libcxxabi
SYSTEM_NAME=Fuchsia \
bash ${PACKAGE_BASE_NAME}-platform-sdk-libcxxabi-wasi

# webassembly libcxx
DISABLE_POLLY=TRUE \
SYSTEM_NAME=Fuchsia \
bash ${PACKAGE_BASE_NAME}-platform-sdk-libcxx-wasi