#!/bin/bash

set -e

source /sources/scripts-staging/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-deb-packaging-scripts

export SOURCE_PACKAGE_NAME=bootstrap-builders
export SOURCE_PACKAGE_VERSION=9999
export INSTALL_ROOT=/tmp/org.${VAL_VERDE_GH_TEAM}/scripts
export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}
export PACKAGE_ARCH=all

mkdir -p ${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM}

# Install builder sources
rsync -aPx \
      /sources/${VAL_VERDE_GH_TEAM}-builders/* \
      ${INSTALL_ROOT}/usr/
rsync -aPx \
      /sources/${VAL_VERDE_GH_TEAM}-deb-templates/* \
      ${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM}/

# Package debs
BASE_DIRECTORY=${INSTALL_ROOT}/usr \
TEMPLATE_ROOT=${INSTALL_ROOT}/usr/share/${VAL_VERDE_GH_TEAM} \
deb-package-build
deb-package-install

# Fetch sources
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-fetch-packages
