#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=swift-tensorflow-apis
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
GIT_URL="https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git" \
git-clone val-verde-mainline

cd ${STAGE_ROOT}
curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
mv bazel.gpg /etc/apt/trusted.gpg.d/
echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
apt update
apt install -y bazel-3.1.0
ln -sf `which bazel-3.1.0` /usr/local/bin/bazel

${BUILD_PACKAGE_PREFIX}/bin/pip3 install --upgrade pip
${BUILD_PACKAGE_PREFIX}/bin/pip3 install wheel
${BUILD_PACKAGE_PREFIX}/bin/pip3 install numpy

SWIFTCFLAGS=" \
    -I${PACKAGE_PREFIX}/lib/swift/${HOST_OS}/dispatch \
    ${SWIFTCFLAGS} \
" \
package-cmake \
    -DBUILD_TESTING=FALSE \
    ${SOURCE_ROOT}

# Build the components
ninja-build

# Build the package
deb-package-build

# Install the package
deb-package-install
