#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=pkg-config
export SOURCE_PACKAGE_VERSION=0.29.2
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd /sources
wget -c https://pkgconfig.freedesktop.org/releases/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz

cd ${STAGE_ROOT}

package-configure \
    ${SOURCE_ROOT}/configure \
    ac_cv_func_posix_getgrgid_r=yes \
    ac_cv_func_posix_getpwuid_r=yes \
    glib_cv_stack_grows=no \
    glib_cv_uscore=no \
    --prefix=${INSTALL_PREFIX} \
    --with-internal-glib \
    --with-libiconv=gnu


# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
