#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=icu4c
export SOURCE_PACKAGE_VERSION=67_1
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

mkdir -p ${STAGE_ROOT}
cd ${STAGE_ROOT}

CFLAGS=`echo "\
    -D_WASI_EMULATED_SIGNAL \
    ${CFLAGS} \
" | xargs` \
CXXFLAGS=`echo "\
    -D_WASI_EMULATED_SIGNAL \
    ${CXXFLAGS} \
" | xargs` \
LDFLAGS=`echo "\
    -lwasi-emulated-signal \
    ${LDFLAGS} \
" | xargs` \
CONFIGURE_HOST_TRIPLE=i686-unknown-gnu \
${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-configure \
    ${SOURCE_ROOT}/source/configure \
    --disable-dyload \
    --disable-extras \
    --disable-samples \
    --disable-shared \
    --disable-tests \
    --disable-tools \
    --enable-static \
    --prefix=${STAGE_ROOT}/install${PACKAGE_PREFIX} \
    --with-cross-build=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH} \
    --with-library-suffix=swift

# Build the components
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-make-build

# Build the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-install
