#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=dpkg
export SOURCE_PACKAGE_VERSION=1.20.5
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-bzip2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-tar-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-zlib-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd /sources
wget -c http://ftp.debian.org/debian/pool/main/d/${SOURCE_PACKAGE_NAME}/${SOURCE_PACKAGE_NAME}_${SOURCE_PACKAGE_VERSION}.tar.xz \
     -O ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.xz
tar -xf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.xz

if [ "${BUILD_TRIPLE}" != "${HOST_TRIPLE}" ]; then
    CROSS_COMPILING=yes
else
    CROSS_COMPILING=no
fi

if [ "${HOST_OS}" = "android" ]; then
    ADMIN_DIR=/data/local/tmp
    CONFIGURE_HOST_KERNEL=unknown
elif [ "${HOST_OS}" = "mingw32" ]; then
    ADMIN_DIR=/
    CONFIGURE_HOST_KERNEL=unknown
else
    ADMIN_DIR=/var/lib/dpkg
    CONFIGURE_HOST_KERNEL=${HOST_KERNEL}
fi

cd ${STAGE_ROOT}
CONFIGURE_HOST_TRIPLE=${HOST_PROCESSOR}-${CONFIGURE_HOST_KERNEL}-gnu \
CXXFLAGS="\
    -std=c++14 \
    ${CXXFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure \
    cross_compiling=${CROSS_COMPILING} \
    --disable-dselect \
    --prefix=${INSTALL_PREFIX} \
    --with-admindir=${ADMIN_DIR}

# Build the components
make-build

# Remove unnecessary dpkg var template folder.
rm -rf ${INSTALL_ROOT}${PACKAGE_PREFIX}/var

# Build the package
deb-package-build

# Install the package
deb-package-install
