#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=openssl
export SOURCE_PACKAGE_VERSION=1.1.1g
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_PROCESSOR}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_PROCESSOR}

rm -rf ${SOURCE_ROOT}
cd /sources
wget -c https://www.openssl.org/source/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
mkdir -p ${STAGE_ROOT}
cd ${STAGE_ROOT}

export AR=${PACKAGE_ROOT}/bin/llvm-ar \
       CC=${PACKAGE_ROOT}/bin/${PACKAGE_BASE_NAME}-platform-sdk-clang \
       RANLIB=${PACKAGE_ROOT}/bin/llvm-ranlib \
       RC=${PACKAGE_ROOT}/bin/${TARGET_PROCESSOR}-${TARGET_KERNEL}-${TARGET_OS}-windres
${SOURCE_ROOT}/Configure \
    --prefix=${STAGE_ROOT}/install${PACKAGE_PREFIX} \
    --openssldir=etc/ssl \
    mingw64

# Build the package
make -j${NUM_PROCESSORS}
make -j${NUM_PROCESSORS} install_sw
make -j${NUM_PROCESSORS} install_ssldirs

source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source /sources/${PACKAGE_BASE_NAME}-platform-sdk-package-install
