#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=autoconf
export SOURCE_PACKAGE_VERSION=2.69

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}

package-configure \
    ${SOURCE_ROOT}/configure \
    --prefix=${INSTALL_PREFIX}

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
