#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=icu4c
export SOURCE_PACKAGE_VERSION=9999-git

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/${SOURCE_PACKAGE_NAME}/source/configure \
    --disable-extras \
    --disable-samples \
    --disable-static \
    --disable-tests \
    --enable-shared \
    --prefix=${INSTALL_PREFIX} \
    --with-library-suffix=swift

# Build the components
TARGETS=" " \
make-build

make-build

# RPATH fixups
COMPONENTS="\
    ${INSTALL_PREFIX}/lib/libicudataswift.so \
    ${INSTALL_PREFIX}/lib/libicui18nswift.so \
    ${INSTALL_PREFIX}/lib/libicuioswift.so \
    ${INSTALL_PREFIX}/lib/libicutestswift.so \
    ${INSTALL_PREFIX}/lib/libicutuswift.so \
    ${INSTALL_PREFIX}/lib/libicuucswift.so \
" \
rpath-fixup

# Build the package
deb-package-build

# Build the package
deb-package-install
