#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=sqlite
export SOURCE_PACKAGE_VERSION=autoconf-3330000
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
cd /sources
wget -c https://sqlite.org/2020/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure

cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    lt_cv_deplibs_check_method=pass_all \
    --disable-static \
    --enable-shared \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX}

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
