#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=make
export SOURCE_PACKAGE_VERSION=4.3

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
sed -i \
    's/fcntl (intptr_t fd, int cmd, ...)/unused_fcntl (intptr_t fd, int cmd, ...)/g' \
    ${SOURCE_ROOT}/src/output.h \
    ${SOURCE_ROOT}/src/w32/compat/posixfcn.c

cd ${STAGE_ROOT}

SDK_PLATFORM_DIR=`echo ${SYSTEM_NAME} | tr '[:upper:]' '[:lower:]'`

if [ "${SDK_PLATFORM_DIR}" = "windows" ]; then
    MAKE_FS_CMD="--enable-case-insensitive-file-system"
fi

CFLAGS="\
    -U__MINGW32__ \
    ${CFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure \
    --prefix=${INSTALL_PREFIX} \
    "${MAKE_FS_CMD}"

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
