#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=bash
export SOURCE_PACKAGE_VERSION=5.1-rc3
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-acl-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-bzip2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd /sources
wget -c https://ftp.gnu.org/gnu/${SOURCE_PACKAGE_NAME}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz

cd ${STAGE_ROOT}

if [ "${HOST_OS}" = "musl" ]; then
    MALLOC_CMD="--without-bash-malloc"
fi

package-configure \
    ${SOURCE_ROOT}/configure \
    --prefix=${INSTALL_PREFIX} \
    ${MALLOC_CMD}

# Build the components
NUM_PROCESSORS=1 \
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
