#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_BASE_NAME=android-ndk
export SOURCE_PACKAGE_NAME=${SOURCE_PACKAGE_BASE_NAME}-headers
export SOURCE_PACKAGE_VERSION=${ANDROID_NDK_VERSION}
export ANDROID_NDK_STAGE_ROOT=${TEMPDIR}/org.${PACKAGE_BASE_NAME}/${SOURCE_PACKAGE_BASE_NAME}-${BUILD_OS}${BUILD_OS_API_LEVEL}-${BUILD_ARCH}
export QUALIFIED_PACKAGE_NAME=${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}
export INSTALL_ROOT=${TEMPDIR}/org.${PACKAGE_BASE_NAME}/${QUALIFIED_PACKAGE_NAME}
export TOOLCHAIN_ROOT=${ANDROID_NDK_STAGE_ROOT}/${BUILD_PACKAGE_PREFIX}/android-ndk-r21d/toolchains/llvm/prebuilt/${BUILD_KERNEL}-${BUILD_PROCESSOR}
export INCLUDES_PATH=${TOOLCHAIN_ROOT}/sysroot/usr/include

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

mkdir -p /sources/ndk-headers
mkdir -p ${INSTALL_ROOT}${PACKAGE_PREFIX}/include
rsync -aPx ${INCLUDES_PATH}/${HOST_TRIPLE}/asm \
           ${INCLUDES_PATH}/*.h \
           ${INCLUDES_PATH}/android \
           ${INCLUDES_PATH}/arpa \
           ${INCLUDES_PATH}/asm-generic \
           ${INCLUDES_PATH}/bits \
           ${INCLUDES_PATH}/c++ \
           ${INCLUDES_PATH}/linux \
           ${INCLUDES_PATH}/net \
           ${INCLUDES_PATH}/netinet \
           ${INCLUDES_PATH}/netpacket \
           ${INCLUDES_PATH}/sys \
           ${INSTALL_ROOT}${PACKAGE_PREFIX}/include

# Remove zlib components as they are rebuilt.
rm -f ${INSTALL_ROOT}${PACKAGE_PREFIX}/include/iconv.h \
      ${INSTALL_ROOT}${PACKAGE_PREFIX}/include/zconf.h \
      ${INSTALL_ROOT}${PACKAGE_PREFIX}/include/zlib.h

# Build the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-${PACKAGE_CLASS}-build

# Install the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-install
