#!/bin/bash

set -e

VERSION=${VERSION:='1.0.0'}
DEPENDS=${DEPENDS:=''}

function generate-control-file {
    # Template definition
    cd /sources/pkg-intermediates-${SOURCE_PACKAGE_NAME}/${PACKAGE_NAME}
    mkdir DEBIAN
    echo 10 > DEBIAN/compat
    sed "s|DEPENDS|${DEPENDS}|g; \
         s|PACKAGE_NAME|${PACKAGE_NAME}|g; \
         s|PACKAGE_BASE_NAME|${PACKAGE_BASE_NAME}|g; \
         s|SOURCE_PACKAGE_VERSION|${SOURCE_PACKAGE_VERSION}|g; \
         s|SYSTEM_ARCH|${PACKAGE_ARCH}|g; \
         s|VERSION|${VERSION}|g" \
         /usr/share/${VAL_VERDE_GH_TEAM}/control.in > DEBIAN/control
    sed "s|PACKAGE_NAME|${PACKAGE_NAME}|g" \
         /usr/share/${VAL_VERDE_GH_TEAM}/copyright.in > DEBIAN/copyright
    sed "s|CURRENT_DATE|`date`|g; \
         s|PACKAGE_NAME|${PACKAGE_NAME}|g; \
         s|SOURCE_PACKAGE_VERSION|${SOURCE_PACKAGE_VERSION}|g" \
         /usr/share/${VAL_VERDE_GH_TEAM}/changelog.in > DEBIAN/changelog
}

