#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=vim
export SOURCE_PACKAGE_VERSION=8.2.2057
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="${PACKAGE_BASE_NAME}-ncurses-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
cd /sources
wget -c https://github.com/${SOURCE_PACKAGE_NAME}/${SOURCE_PACKAGE_NAME}/archive/v${SOURCE_PACKAGE_VERSION}.tar.gz \
     -O ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz

cd ${STAGE_ROOT}
rsync -aPx ${SOURCE_ROOT}/ \
           ${STAGE_ROOT}

package-configure \
    ${STAGE_ROOT}/configure \
    vim_cv_getcwd_broken=no \
    vim_cv_memmove_handles_overlap=yes \
    vim_cv_stat_ignores_slash=no \
    vim_cv_terminfo=yes \
    vim_cv_tgetent=yes \
    vim_cv_toupper_broken=no \
    --prefix=${INSTALL_PREFIX} \
    --with-tlib=ncurses

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
