#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=winpthreads
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/mingw-w64/mingw-w64-libraries/${SOURCE_PACKAGE_NAME}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-mingw-w64-crt-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd ${STAGE_ROOT}
sed -i \
    "s/'auto-import'/'ld'/g" \
    ${SOURCE_ROOT}/configure
package-configure \
    ${SOURCE_ROOT}/configure \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX} \

# Build the components
make-build

rm -rf ${INSTALL_ROOT}${PACKAGE_PREFIX}/include/pthread_signal.h \
       ${INSTALL_ROOT}${PACKAGE_PREFIX}/include/pthread_time.h \
       ${INSTALL_ROOT}${PACKAGE_PREFIX}/include/pthread_unistd.h

# Build the package
deb-package-build

# Install the package
deb-package-install
