#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=elfutils
export SOURCE_PACKAGE_VERSION=0.181
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-curl-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-libarchive-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-libmicrohttpd-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

GIT_URL=https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git \
git-clone val-verde-mainline

cd ${STAGE_ROOT}

CFLAGS="\
    -Wno-implicit-function-declaration \
    -Wno-unknown-warning-option \
    -Wno-unused-command-line-argument \
    -Wno-unused-parameter \
    ${CFLAGS} \
" \
package-configure \
    ${SOURCE_ROOT}/configure \
    ac_cv_c99=yes \
    ac_cv_lib_argp_argp_parse=yes \
    ac_cv_implicit_fallthrough=no \
    --disable-debuginfod \
    --disable-static \
    --enable-shared \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX} \
    --with-zlib=yes

# Build the components
TARGETS="-C lib install" \
make-build

TARGETS="-C libelf install" \
make-build

# RPATH fixups
COMPONENTS="\
    ${INSTALL_ROOT}${PACKAGE_PREFIX}/lib/libelf.so \
" \
rpath-fixup

# Build the package
deb-package-build

# Install the package
deb-package-install
