#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=libedit
export SOURCE_PACKAGE_VERSION=20191231-3.1
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

rm -rf ${SOURCE_ROOT}
cd /sources
wget -c https://www.thrysoee.dk/editline/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
mkdir -p ${STAGE_ROOT}
cd ${STAGE_ROOT}
CFLAGS="\
    -D__STDC_ISO_10646__=201103L \
    -DNBBY=CHAR_BIT \
    -I${PACKAGE_PREFIX}/include \
    -I${PACKAGE_PREFIX}/include/ncurses \
    ${CFLAGS} \
" \
LDFLAGS="\
    -L${PACKAGE_PREFIX}/lib \
    ${LDFLAGS} \
" \
${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-configure \
    ${SOURCE_ROOT}/configure \
    --disable-static \
    --enable-shared \
    --prefix=${STAGE_ROOT}/install${PACKAGE_PREFIX}

# Build the components
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-make-build

# RPATH fixups
COMPONENTS="\
    ${STAGE_ROOT}/install${PACKAGE_PREFIX}/lib/libedit.so \
" \
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-rpath-fixup

# Build the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-install
