#!/bin/bash

set -e

# zlib build
CMAKE_BINDIR=/usr/bin \
MAKE_PROGRAM=/usr/bin/ninja \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-zlib-cross

# bzip2 build
MAKE_PROGRAM=/usr/bin/make \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bzip2-cross

# autoconf build
MAKE_PROGRAM=/usr/bin/make \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-autoconf-cross

# automake build
MAKE_PROGRAM=/usr/bin/make \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-automake-cross

# make build
MAKE_PROGRAM=/usr/bin/make \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-make-cross

# libiconv build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libiconv-cross

# pkg-config build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-pkg-config-cross

# pcre build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-pcre-cross

# icu build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-icu4c

# xz build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-xz-cross

# libxml2 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libxml2-cross

# libffi build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libffi-cross

# gdbm build
CFLAGS="\
    -fcommon \
    ${CFLAGS} \
" \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gdbm-cross

# ncurses build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-ncurses-cross

# libedit build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libedit-cross

# sqlite3 build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sqlite-cross

# openssl build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-openssl-cross

# libsecret build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libsecret-cross

# libcap build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libcap-cross

# libexpat build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-expat-cross

# libuv build
CMAKE_BINDIR=/usr/bin \
MAKE_PROGRAM=/usr/bin/ninja \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libuv-cross

# libssh2 build
CMAKE_BINDIR=/usr/bin \
MAKE_PROGRAM=/usr/bin/ninja \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libssh2-cross

# curl build
CMAKE_BINDIR=/usr/bin \
MAKE_PROGRAM=/usr/bin/ninja \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-curl-cross

# gettext build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gettext-cross

# attr build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-attr-cross

# acl build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-acl-cross

# bash build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bash-cross

# util-linux build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-util-linux-cross

# libarchive build
CMAKE_BINDIR=/usr/bin \
MAKE_PROGRAM=/usr/bin/ninja \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libarchive-cross

# libmicrohttpd build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-libmicrohttpd-cross

# elfutils build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-elfutils-cross

# sed build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-sed-cross

# bison build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-bison-cross

# gawk build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gawk-cross

# strace build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-strace-cross

# gperf build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-gperf-cross

# tar build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-tar-cross

# coreutils build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-coreutils-cross

# dpkg build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-dpkg-cross

# systemd build
MAKE_PROGRAM=/usr/bin/ninja \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-systemd

# wget build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-wget-cross

# python build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-python-cross

# lua build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-lua-cross

# swig build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-swig-cross

# z3 build
CMAKE_BINDIR=/usr/bin \
MAKE_PROGRAM=/usr/bin/ninja \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-z3-cross

# git build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-git-cross

# vim build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-vim-cross

# ninja build
CMAKE_BINDIR=/usr/bin \
MAKE_PROGRAM=/usr/bin/ninja \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-ninja-cross

# cmake build
CMAKE_BINDIR=/usr/bin \
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-cmake-cross

# android patch elf
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-android-patch-elf-cross

# jwasm (ml64) cross compiler build
bash ${VAL_VERDE_GH_TEAM}-platform-sdk-jwasm
