#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=binutils
export SOURCE_PACKAGE_VERSION=2.34
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd /sources
wget -c https://ftp.gnu.org/gnu/${SOURCE_PACKAGE_NAME}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz

cd ${STAGE_ROOT}

mkdir -p ${STAGE_ROOT}/bin
ln -sf /usr/bin/true \
       ${STAGE_ROOT}/bin/makeinfo

BINDIR=${BUILD_PACKAGE_PREFIX}/bin
OPTIMIZATION_FLAGS=${OPTIMIZATION_FLAGS:-"-DNDEBUG"}

AS_FOR_TARGET=${AS_FOR_TARGET:-${BINDIR}/llvm-as}
LD_FOR_TARGET=${LD_FOR_TARGET:-${BINDIR}/ld.lld}
RC_FOR_TARGET=${RC_FOR_TARGET:-${BINDIR}/llvm-rc}
TARGET_SYSROOT=${TARGET_SYSROOT:-${PACKAGE_PREFIX}}
TARGET_TRIPLE=${TARGET_TRIPLE:-${TARGET_PROCESSOR}-${TARGET_KERNEL}-${TARGET_OS}${TARGET_OS_API_LEVEL}}

CFLAGS_FOR_TARGET="${CFLAGS_FOR_TARGET} ${TARGET_ARCH_FLAGS} ${OPTIMIZATION_FLAGS} -O${OPTIMIZATION_LEVEL}"
CPPFLAGS_FOR_TARGET="${CFLAGS_FOR_TARGET} ${CPPFLAGS_FOR_TARGET}"
CXXFLAGS_FOR_TARGET="${CFLAGS_FOR_TARGET} ${CXXFLAGS_FOR_TARGET}"

export PATH=${PATH}:${STAGE_ROOT}/bin
package-configure \
    /sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}/configure \
    --disable-multilib \
    --disable-werror \
    --prefix=${STAGE_ROOT}/install${BUILD_PACKAGE_PREFIX} \
    --target=${TARGET_TRIPLE} \
    --with-sysroot=${TARGET_SYSROOT} \
    AR_FOR_TARGET=${BINDIR}/llvm-ar \
    AS_FOR_TARGET="${AS_FOR_TARGET}" \
    CFLAGS_FOR_TARGET="${CFLAGS_FOR_TARGET}" \
    CPPFLAGS_FOR_TARGET="${CPPFLAGS_FOR_TARGET}" \
    CXXFLAGS_FOR_TARGET="${CXXFLAGS_FOR_TARGET}" \
    DLLTOOL_FOR_TARGET=${BINDIR}/llvm-dlltool \
    GCC_FOR_TARGET="${CC_FOR_TARGET}" \
    LIPO_FOR_TARGET=${BINDIR}/llvm-lipo \
    LD_FOR_TARGET="${LD_FOR_TARGET}" \
    LDFLAGS_FOR_TARGET="${LDFLAGS_FOR_TARGET}" \
    NM_FOR_TARGET=${BINDIR}/llvm-nm \
    OBJCOPY_FOR_TARGET=${BINDIR}/llvm-objcopy \
    OBJDUMP_FOR_TARGET=${BINDIR}/llvm-objdump \
    RANLIB_FOR_TARGET=${BINDIR}/llvm-ranlib \
    READELF_FOR_TARGET=${BINDIR}/llvm-readelf \
    RC_FOR_TARGET="${RC_FOR_TARGET}" \
    SIZE_FOR_TARGET=${BINDIR}/llvm-size \
    STRIP_FOR_TARGET=${BINDIR}/llvm-strip \
    STRINGS_FOR_TARGET=${BINDIR}/llvm-strings

# Build the components
make -j${NUM_PROCESSORS}
make-build
deb-package-build

# Install the package
deb-package-install
