#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=vulkan-validation-layers
export SOURCE_PACKAGE_VERSION=9999-git
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="${PACKAGE_BASE_NAME}-vulkan-tools-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0)"

# Configure the build components
GIT_URL="https://github.com/${VAL_VERDE_GH_TEAM}/Vulkan-ValidationLayers.git" \
git-clone val-verde-mainline

cd ${STAGE_ROOT}

CMAKE_XCB_CMD="-DBUILD_WSI_XCB_SUPPORT=FALSE"

if [ "${HOST_OS}" = "gnu" ]; then
    CMAKE_XCB_CMD="-DBUILD_WSI_XCB_SUPPORT=TRUE"
fi

package-cmake \
    -DBUILD_LAYER_SUPPORT_FILES=TRUE \
    -DBUILD_WSI_DIRECTFB_SUPPORT=FALSE \
    -DBUILD_WSI_WAYLAND_SUPPORT=FALSE \
    -DBUILD_WSI_XLIB_SUPPORT=FALSE \
    -DGLSLANG_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DPKG_CONFIG_EXECUTABLE=${PKG_CONFIG} \
    -DSPIRV_HEADERS_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DSPIRV_TOOLS_INSTALL_DIR=${PACKAGE_PREFIX} \
    -DSPIRV_TOOLS_LIB=${PACKAGE_PREFIX}/lib/libSPIRV-Tools.a \
    -DSPIRV_TOOLS_OPT_SEARCH_PATH=${PACKAGE_PREFIX} \
    -DSPIRV_TOOLS_OPT_LIB=${PACKAGE_PREFIX}/lib/libSPIRV-Tools-opt.a \
    -DVulkanHeaders_INCLUDE_DIR=${PACKAGE_PREFIX}/include \
    -DVulkanRegistry_DIR=${PACKAGE_PREFIX}/share/vulkan/registry \
    "${CMAKE_XCB_CMD}" \
    ${SOURCE_ROOT}

# Build the components
ninja-build

# Build the package
deb-package-build

# Install the package
deb-package-install
