#!/bin/bash

set -e

SYSROOT=${SYSROOT:-${PACKAGE_ROOT}/${PACKAGE_BASE_NAME}-platform-sdk-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}/sysroot}

${BUILDER_SCRIPT_PATH}/clang++ \
    -stdlib=libc++ \
    --sysroot=${SYSROOT} \
    --target=${HOST_TRIPLE} \
    "$@"
