#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=libsecret
export SOURCE_PACKAGE_VERSION=0.20.4
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source ${BUILD_PACKAGE_PREFIX}/bin/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
GIT_URL=https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git \
git-clone val-verde-mainline

cd ${STAGE_ROOT}
package-configure \
    ${SOURCE_ROOT}/configure \
    --disable-gcrypt \
    --disable-static \
    --enable-gtk-doc=no \
    --enable-gtk-doc-html=no \
    --enable-gtk-doc-pdf=no \
    --enable-introspection=no \
    --enable-shared \
    --prefix=${INSTALL_ROOT}${PACKAGE_PREFIX}

# Build the components
TARGETS=" " \
make-build

make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
