#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=yautja-server
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export-compiler-environment

# Configure & build the package
GIT_URL="https://github.com/${VAL_VERDE_GH_TEAM}/${SOURCE_PACKAGE_NAME}.git" \
git-clone val-verde-mainline

rsync -aPx ${SOURCE_ROOT}/ \
           ${STAGE_ROOT}
cd ${STAGE_ROOT}

yarn-build

rsync -aPx ${STAGE_ROOT}/ \
           ${INSTALL_PREFIX}/

# Build the package
deb-package-build

# Install the package
deb-package-install
