#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=tar
export SOURCE_PACKAGE_VERSION=1.32

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

export DEPENDS="\
    ${PACKAGE_BASE_NAME}-acl-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-bzip2-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0), \
    ${PACKAGE_BASE_NAME}-xz-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH} (>=1.0.0) \
"

# Configure the build components
cd ${STAGE_ROOT}
FORCE_UNSAFE_CONFIGURE=1 \
package-configure \
    ${SOURCE_ROOT}/configure

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
