#!/bin/bash

set -e

# Set all environment vars
export SOURCE_PACKAGE_NAME=ncurses
export SOURCE_PACKAGE_VERSION=6.2
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}

# Source package build helper functions
source /sources/${VAL_VERDE_GH_TEAM}-platform-sdk-bash-source-scripts

# Configure the build components
cd /sources
wget -c https://ftp.gnu.org/gnu/ncurses/ncurses-6.2.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
sed -i "s/'auto-import'/'ld'/g" ${SOURCE_ROOT}/configure

cd ${STAGE_ROOT}
LDFLAGS=" \
    ${LDFLAGS} \
    ${LIBS} \
" \
OPTIMIZATION_LEVEL=3 \
package-configure \
    ${SOURCE_ROOT}/configure \
    --enable-ext-colors \
    --enable-mixed-case \
    --enable-pc-files \
    --enable-rpath \
    --enable-sp-funcs \
    --enable-term-driver \
    --prefix=${PACKAGE_PREFIX} \
    --with-curses-h \
    --with-cxx \
    --with-cxx-shared \
    --with-install-prefix=${INSTALL_ROOT}/ \
    --with-pkg-config=/usr/bin/pkg-config \
    --with-pkg-config-libdir=${PACKAGE_PREFIX}/lib/pkgconfig \
    --with-shared \
    --with-ticlib \
    --with-tic-path=/usr/bin/tic \
    --without-debug \
    --without-manpages \
    --without-progs \
    --without-tack \
    --without-tests

# Build the components
make-build

# Build the package
deb-package-build

# Install the package
deb-package-install
