#!/bin/bash

set -e

# Set all environment vars
export NUM_PROCESSORS="$(($(getconf _NPROCESSORS_ONLN) + 1))"
export SOURCE_PACKAGE_NAME=systemd
export SOURCE_PACKAGE_VERSION=246
export SOURCE_ROOT=/sources/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}
export STAGE_ROOT=/sources/build-staging/${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

export PACKAGE_NAME=${PACKAGE_BASE_NAME}-${SOURCE_PACKAGE_NAME}-${HOST_OS}${HOST_OS_API_LEVEL}-${HOST_ARCH}

rm -rf ${SOURCE_ROOT}
cd /sources
wget -c  https://github.com/${SOURCE_PACKAGE_NAME}/${SOURCE_PACKAGE_NAME}/archive/v${SOURCE_PACKAGE_VERSION}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
tar -zxf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz

cd ${SOURCE_ROOT}

CC=${CC:-${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-clang} \
CFLAGS="\
     -I${PACKAGE_PREFIX}/include \
     -L${PACKAGE_PREFIX}/lib \
     ${CFLAGS} \
" \
CPPFLAGS="\
     -I${PACKAGE_PREFIX}/include \
     -L${PACKAGE_PREFIX}/lib \
     ${CPPFLAGS} \
" \
LD=${LD:-${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-clang} \
LDFLAGS="\
     -L${PACKAGE_PREFIX}/lib \
     ${LDFLAGS} \
" \
PKG_CONFIG_PATH="${PACKAGE_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}" \
meson \
    -Dbuildtype=release \
    -Doptimization=${OPTIMIZATION_LEVEL} \
    -Dprefix=${STAGE_ROOT}/install${PACKAGE_PREFIX} \
    ${STAGE_ROOT}

cd ${STAGE_ROOT}

# Build the components
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-ninja-build

# Build the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-build

# Install the package
source ${BUILD_PACKAGE_PREFIX}/bin/${PACKAGE_BASE_NAME}-platform-sdk-package-install
