#!/bin/bash

set -e

if [ "${ENABLE_FLTO}" = "Full" ]; then
    FLTO_CFLAG=-flto
    FLTO_LDFLAG="-O2"
fi

BINDIR=${PACKAGE_ROOT}/bin
OPTIMIZATION_LEVEL=${OPTIMIZATION_LEVEL:-z}
FLTO_LDFLAG="${FLTO_LDFLAG} -s"
OPTIMIZATION_LEVEL=${OPTIMIZATION_LEVEL:-z}

AR=${AR:-${BINDIR}/llvm-ar}
CC=${CC:-${BINDIR}/clang}
CPP=${CPP:-"${CC} -E"}
CXX=${CXX:-${BINDIR}/clang++}
DLLTOOL=${DLLTOOL:-${BINDIR}/llvm-dlltool}
LD=${LD:-${BINDIR}/ld.lld}
MANIFEST_TOOL=${MANIFEST_TOOL:-${BINDIR}/llvm-mt}
NM=${NM:-${BINDIR}/llvm-nm}
OBJCOPY=${OBJCOPY:-${BINDIR}/llvm-objcopy}
OBJDUMP=${OBJDUMP:-${BINDIR}/llvm-objdump}
RANLIB=${RANLIB:-${BINDIR}/llvm-ranlib}
RC=${RC:-${BINDIR}/llvm-rc}
READELF=${READELF:-${BINDIR}/llvm-readelf}
SIZE=${SIZE:-${BINDIR}/llvm-size}
STRINGS=${STRINGS:-${BINDIR}/llvm-strings}
STRIP=${STRIP:-${BINDIR}/llvm-strip}

if [ -n "${LDFLAGS}" ]; then
    LDFLAGS_CMD="LDFLAGS=${LDFLAGS}"
fi

if [ -n "${LIBS}" ]; then
    LIBS_CMD="LIBS=${LIBS}"
fi

"$@" AR=${AR} \
     AS=${CC} \
     CC=${CC} \
     CFLAGS="${ARCH_FLAGS} ${FLTO_CFLAG} -O${OPTIMIZATION_LEVEL} ${CFLAGS}" \
     CPP="${CPP}" \
     CXX=${CXX} \
     CXXFLAGS="${ARCH_FLAGS} ${FLTO_CFLAG} -O${OPTIMIZATION_LEVEL} ${CXXFLAGS}" \
     DLLTOOL=${DLLTOOL} \
     LD=${LD} \
     LIBTOOLFLAGS="-avoid-version" \
     MANIFEST_TOOL=${MANIFEST_TOOL} \
     NM=${NM} \
     OBJCOPY=${OBJCOPY} \
     OBJDUMP=${OBJDUMP} \
     PKG_CONFIG_PATH=${PACKAGE_PREFIX}/lib/pkgconfig \
     RANLIB=${RANLIB} \
     RC=${RC} \
     READELF=${READELF} \
     SIZE=${SIZE} \
     STRIP=${STRIP} \
     STRINGS=${STRINGS} \
    --build=${BUILD_TRIPLE} \
    --host=${BUILD_TRIPLE} \
    ${CONFIGURE_FLAGS} \
    ${LDFLAGS_CMD} \
    ${LIBS_CMD}
