#!/bin/bash

"$@" \
    AR=${PACKAGE_ROOT}/bin/llvm-ar \
    AS=${PACKAGE_ROOT}/bin/llvm-as \
    CC=${PACKAGE_ROOT}/bin/clang \
    CFLAGS="-flto -march=haswell -mtune=haswell -Oz" \
    CXX=${PACKAGE_ROOT}/bin/clang++ \
    CXXFLAGS="-flto -march=haswell -mtune=haswell -Oz" \
    LD=${PACKAGE_ROOT}/bin/ld.lld \
    LDFLAGS="-flto -s -O2" \
    LIBTOOLFLAGS="-avoid-version" \
    NM=${PACKAGE_ROOT}/bin/llvm-nm \
    OBJCOPY=${PACKAGE_ROOT}/bin/llvm-objcopy \
    OBJDUMP=${PACKAGE_ROOT}/bin/llvm-objdump \
    RANLIB=${PACKAGE_ROOT}/bin/llvm-ranlib \
    READELF=${PACKAGE_ROOT}/bin/llvm-readelf \
    SIZE=${PACKAGE_ROOT}/bin/llvm-size \
    STRIP=${PACKAGE_ROOT}/bin/llvm-strip \
    STRINGS=${PACKAGE_ROOT}/bin/llvm-strings \
    --build=${BUILD_PROCESSOR}-${BUILD_KERNEL}-${BUILD_OS} \
    --host=${BUILD_PROCESSOR}-${BUILD_KERNEL}-${BUILD_OS}
