#!/bin/bash

set -e

function clean-up-root-gpg() {
    rm -rf ${HOME}/.gnupg
    gpg -k
}

function generate-gpg-key() {
    export GNUPGHOME="/sources"
    KEYFILE_NAME=${KEYFILE_NAME:-${VAL_VERDE_GH_TEAM}}
    cat >${KEYFILE_NAME} <<EOF
        %echo Generating a basic OpenPGP key
        Key-Type: DSA
        Key-Length: 1024
        Subkey-Type: ELG-E
        Subkey-Length: 1024
        Name-Real: Val Verde Inc.
        Name-Email: openvalverde@gmail.com
        Expire-Date: 0
        Passphrase: val-verde
        %commit
        %echo done
EOF
    gpg --batch --generate-key ${KEYFILE_NAME}
    gpg --armor --export openvalverde@gmail.com > ${KEYFILE_NAME}.gpg
}
