#!/bin/bash

set -e

# Source common variables and functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-common-variables

function derive-upstream-source-url() {
    export PACKAGE_NAME=${SOURCE_PACKAGE_NAME}-${PACKAGE_VERSION}        

    if [[ ${PACKAGE_BASE_URL} == *'${SOURCE_PACKAGE_NAME}'* || ${PACKAGE_BASE_URL} == *'${SOURCE_PACKAGE_VERSION}'* ]]; then
        PACKAGE_URL=${PACKAGE_BASE_URL//'${SOURCE_PACKAGE_NAME}'/${SOURCE_PACKAGE_NAME}}
        PACKAGE_URL=${PACKAGE_URL//'${SOURCE_PACKAGE_VERSION}'/${SOURCE_PACKAGE_VERSION}}
    else
        PACKAGE_URL=${PACKAGE_BASE_URL}
    fi
}

function determine-git-source-package() {
    if [[ ${SOURCE_BRANCH_IND} == "default" ]]; then
        SOURCE_BRANCH=val-verde-mainline
    elif [[ ${SOURCE_BRANCH_IND} == "default-next" ]]; then
        SOURCE_BRANCH=val-verde-mainline-next
    elif [[ ${SOURCE_BRANCH_IND} == "default-next-testing" ]]; then
        SOURCE_BRANCH=val-verde-mainline-next-testing
    elif [[ ${SOURCE_BRANCH_IND} == "android" ]]; then
        SOURCE_BRANCH=val-verde-android-mainline
        PACKAGE_NAME=${PACKAGE_NAME}-android
    elif [[ ${SOURCE_BRANCH_IND} == "android-next" ]]; then
        SOURCE_BRANCH=val-verde-android-mainline-next
        PACKAGE_NAME=${PACKAGE_NAME}-android
    elif [[ ${SOURCE_BRANCH_IND} == "android-next-testing" ]]; then
        SOURCE_BRANCH=val-verde-android-mainline-next
        PACKAGE_NAME=${PACKAGE_NAME}-android
    elif [[ ${SOURCE_BRANCH_IND} == "windows" ]]; then
        SOURCE_BRANCH=val-verde-windows-mainline
        PACKAGE_NAME=${PACKAGE_NAME}-windows
    else
        SOURCE_BRANCH=${SOURCE_BRANCH_IND}
    fi
}

function untar-tar-balls() {
    if [[ ${SOURCE_BRANCH_IND} == "wget" ]]; then
        package-wget -c ${PACKAGE_URL} \
                        -O ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
        package-tar -xzvf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz \
                    -C ${INSTALL_PREFIX} --strip 1
        ${RM} ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
    elif [[ ${SOURCE_BRANCH_IND} == "wget-xz" ]]; then
        package-wget -c ${PACKAGE_URL} \
                        -O ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.xz
        package-tar -xvf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.xz \
                    -C ${INSTALL_PREFIX} --strip 1
        ${RM} ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.xz
    elif [[ ${SOURCE_BRANCH_IND} == "wget-unzip" ]]; then
        ANDROID_NDK_URL=https://dl.google.com/android/repository

        package-wget -c ${ANDROID_NDK_URL}/${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}-${BUILD_KERNEL}-${BUILD_PROCESSOR}.zip \
                        -O ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.zip
        package-unzip ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.zip \
                        -d ${INSTALL_PREFIX}
        ${RM} ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.zip
    fi
}
