#!/bin/bash

set -e

# builder configuration defaults
BASE_DIRECTORY=${BASE_DIRECTORY:-$(${ECHO} "${PACKAGE_ROOT}" | ${CUT} -d "/" -f2)}
PACKAGE_INSTALL_BASE=${PACKAGE_INSTALL_BASE:-${BASE_DIRECTORY}}
RELEASE=${RELEASE:='1'}
TEMPLATE_ROOT_BASE=${TEMPLATE_ROOT_BASE:-/usr/share/${VAL_VERDE_GH_TEAM}}
VERSION=${VERSION:='1.0.0'}

function packaging-archive-build-install() {
    TEMPLATE_ROOT=${TEMPLATE_ROOT_BASE}/${PACKAGE_ARCHIVE_CLASS}

    # Build the package
    if [ -z "${DISABLE_BUILD_ARCHIVE}" ]; then
        ${PACKAGE_ARCHIVE_CLASS}-package-build
    fi

    # Install the package
    if [ -z "${DISABLE_INSTALL_ARCHIVE}" ]; then
        ${PACKAGE_ARCHIVE_CLASS}-package-install
    fi
}

function deb-package-build() {
    ARCHIVE_ROOT=${TEMP_ROOT_BASE}/archiving/${SOURCE_PACKAGE_NAME}/${PACKAGE_NAME}
    TEMPLATE_ROOT=${TEMPLATE_ROOT:-${TEMPLATE_ROOT_BASE}/deb}

    package-push-directory ${INSTALL_ROOT}
        ${RM} -rf ${ARCHIVE_ROOT}
        ${MKDIR} -p ${ARCHIVE_ROOT}
        package-rsync -ax \
                    ${BASE_DIRECTORY} \
                    ${ARCHIVE_ROOT}/

        TEMPLATE_ROOT=${TEMPLATE_ROOT} \
        generate-control-file "${PACKAGE_NAME}"
        package-dpkg-build ${ARCHIVE_ROOT}

        ${MV} ${ARCHIVE_ROOT}/../${PACKAGE_NAME}.deb \
                ${ARCHIVE_PATH}/${PACKAGE_NAME}.deb
        ${RM} -rf ${ARCHIVE_ROOT}
    package-pop-directory
}

function deb-package-install() {
    package-dpkg-install ${ARCHIVE_PATH}/${PACKAGE_NAME}.deb
}

function generate-control-file() {
    ARCHIVE_ROOT=${TEMP_ROOT_BASE}/archiving/${SOURCE_PACKAGE_NAME}/${PACKAGE_NAME}

    # Template definition
    DEBIAN_ROOT=${ARCHIVE_ROOT}/DEBIAN

    ${MKDIR} -p ${DEBIAN_ROOT}
    ${ECHO} 10 \
            > ${DEBIAN_ROOT}/compat
    ${SED} "s|DEPENDS|${DEPENDS}|g; \
            s|PACKAGE_NAME|${PACKAGE_NAME}|g; \
            s|PACKAGE_BASE_NAME|${PACKAGE_BASE_NAME}|g; \
            s|SOURCE_PACKAGE_VERSION|${SOURCE_PACKAGE_VERSION}|g; \
            s|SYSTEM_ARCH|${PACKAGE_ARCH}|g; \
            s|VERSION|${VERSION}|g" \
            ${TEMPLATE_ROOT}/control.in \
            > ${DEBIAN_ROOT}/control
    ${SED} "s|PACKAGE_NAME|${PACKAGE_NAME}|g" \
            ${TEMPLATE_ROOT}/copyright.in \
            > ${DEBIAN_ROOT}/copyright
    ${SED} "s|CURRENT_DATE|`date`|g; \
            s|PACKAGE_NAME|${PACKAGE_NAME}|g; \
            s|SOURCE_PACKAGE_VERSION|${SOURCE_PACKAGE_VERSION}|g" \
            ${TEMPLATE_ROOT}/changelog.in \
            > ${DEBIAN_ROOT}/changelog
}

function generate-spec-file() {
    ARCHIVE_ROOT=${TEMP_ROOT_BASE}/archiving/${SOURCE_PACKAGE_NAME}/${PACKAGE_NAME}

    ${SED} "s|ARCHIVE_ROOT|${ARCHIVE_ROOT}|g; \
            s|BUILD_PROCESSOR|${BUILD_PROCESSOR}|g; \
            s|PACKAGE_NAME|${PACKAGE_NAME}|g; \
            s|RELEASE|${RELEASE}|g; \
            s|SYSTEM_ARCH|${PACKAGE_ARCH}|g; \
            s|VERSION|${VERSION}|g" \
            ${TEMPLATE_ROOT}/spec.in \
            > ${ARCHIVE_ROOT}/SPECS/${SOURCE_PACKAGE_NAME}.spec
}

function rpm-package-build() {
    ARCHIVE_ROOT=${TEMP_ROOT_BASE}/archiving/${SOURCE_PACKAGE_NAME}/${PACKAGE_NAME}
    TEMPLATE_ROOT=${TEMPLATE_ROOT:-${TEMPLATE_ROOT_BASE}/rpm}

    package-push-directory ${INSTALL_ROOT}
        ${RM} -rf ${ARCHIVE_ROOT}
        ${MKDIR} -p ${ARCHIVE_ROOT} \
            ${ARCHIVE_ROOT}/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS} \
            ${ARCHIVE_ROOT}/SOURCES/${PACKAGE_NAME}

        package-rsync -ax \
                    ${BASE_DIRECTORY} \
                    ${ARCHIVE_ROOT}/SOURCES/${PACKAGE_NAME}
        
        package-tar zvcfP ${ARCHIVE_ROOT}/SOURCES/${PACKAGE_NAME}.tar.gz .

        generate-spec-file "${PACKAGE_NAME}"

        ${SED} -i "s|%files|%files\n/${PACKAGE_INSTALL_BASE}/*|g" ${ARCHIVE_ROOT}/SPECS/${SOURCE_PACKAGE_NAME}.spec

        package-rpm-build --quiet --define "_topdir ${ARCHIVE_ROOT}" -ba ${ARCHIVE_ROOT}/SPECS/${SOURCE_PACKAGE_NAME}.spec

        ${MV} ${ARCHIVE_ROOT}/RPMS/${BUILD_PROCESSOR}/${PACKAGE_NAME}.rpm \
                ${ARCHIVE_PATH}/${PACKAGE_NAME}.rpm
        ${RM} -rf ${ARCHIVE_ROOT}
    package-pop-directory
}

function rpm-package-install() {
    package-rpm-install ${ARCHIVE_PATH}/${PACKAGE_NAME}.rpm
}


function tar-package-build() {
    SOURCE_PACKAGE_NAME=$1
    SOURCE_PACKAGE_VERSION=${2:-'1.0.0'}
    PACKAGE_URL=$3

    PACKAGE_NAME=${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}
    INSTALL_ROOT=${TEMP_ROOT_BASE}/${PACKAGE_NAME}-tar-archives
    INSTALL_PREFIX=${INSTALL_ROOT}/${PACKAGE_NAME}

    ${MKDIR} -p ${INSTALL_PREFIX}

    package-push-directory ${INSTALL_ROOT}
        package-wget -c ${PACKAGE_URL} \
                     -O ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz
        package-tar -xzvf ${SOURCE_PACKAGE_NAME}-${SOURCE_PACKAGE_VERSION}.tar.gz \
                    -C ${INSTALL_PREFIX} \
                    --strip 1
        package-tar -cvf ${PACKAGE_NAME}.tar ${INSTALL_PREFIX}
        ${MV} ${PACKAGE_NAME}.tar ${TAR_ROOT_BASE}
        ${RM} ${PACKAGE_NAME}.tar.gz
    package-pop-directory

    ${RM} -r ${INSTALL_ROOT}
}

function trigger-source-package-install() {
    SOURCE_FILES=$( $(${FIND} -name ${SOURCE_ARCHIVE_PATH}/*.${PACKAGE_ARCHIVE_CLASS}) )

    for src_file in "${#SOURCE_FILES[@]}"; do
        ${ECHO} -e "Installing Source ${PACKAGE_ARCHIVE_CLASS} Package: ${src_file}"
        if [ "${PACKAGE_ARCHIVE_CLASS}" = "deb" ]; then
            package-dpkg-install ${src_file}
        elif [ "${PACKAGE_ARCHIVE_CLASS}" = "rpm" ]; then
            package-rpm-install ${src_file}
        fi
    done
}
