version: '3.5'

services: 
    builder:
        container_name: builder
        build: 
            context: ./
            dockerfile: dev.Dockerfile
        privileged: true
#Note: privileged flag here is needed to enable REPL mode.