#!/bin/bash

set -e

# Source package build helper functions
export PACKAGE_USR_PREFIX=.

source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-api

# mingw-w64-headers build
package-invoke-builder mingw-w64-headers 6

# mingw-w64-crt build
package-invoke-builder mingw-w64-crt 6

# compiler-rt build (for host)
package-invoke-builder compiler-rt-cross ${LLVM_VERSION}

# libcxx build
package-invoke-builder libcxx-bootstrap ${LLVM_VERSION}

# mingw-w64-winpthreads build
package-invoke-builder mingw-w64-winpthreads 6