#!/bin/bash

set -e

# Source package build helper functions
source /usr/libexec/${VAL_VERDE_GH_TEAM}-platform-sdk-builder-utils

export SOURCE_ROOT=${SOURCE_ROOT_BASE}/mingw-w64-${SOURCE_PACKAGE_VERSION}/${SOURCE_PACKAGE_NAME}

# Invoke one-shot template for configure/install
if [ "${HOST_PROCESSOR}" = "aarch64" ]; then
    ENABLE_OR_DISABLE_LIB32=disable
    ENABLE_OR_DISABLE_LIBARM32=disable
    ENABLE_OR_DISABLE_LIB64=disable
    ENABLE_OR_DISABLE_LIBARM64=enable
elif [ "${HOST_PROCESSOR}" = "armv7a" ]; then
    ENABLE_OR_DISABLE_LIB32=disable
    ENABLE_OR_DISABLE_LIBARM32=enable
    ENABLE_OR_DISABLE_LIB64=disable
    ENABLE_OR_DISABLE_LIBARM64=disable
elif [ "${HOST_PROCESSOR}" = "i386" ] ||
     [ "${HOST_PROCESSOR}" = "i486" ] ||
     [ "${HOST_PROCESSOR}" = "i586" ] ||
     [ "${HOST_PROCESSOR}" = "i686" ] ||
     [ "${HOST_PROCESSOR}" = "i786" ]; then
    ENABLE_OR_DISABLE_LIB32=enable
    ENABLE_OR_DISABLE_LIBARM32=disable
    ENABLE_OR_DISABLE_LIB64=disable
    ENABLE_OR_DISABLE_LIBARM64=disable
elif [ "${HOST_PROCESSOR}" = "x86_64" ]; then
    ENABLE_OR_DISABLE_LIB32=disable
    ENABLE_OR_DISABLE_LIBARM32=disable
    ENABLE_OR_DISABLE_LIB64=enable
    ENABLE_OR_DISABLE_LIBARM64=disable
fi

function package-install-completion-callback() {
    ${LN} -sf \
          `package-get-filename uuid STATIC` \
          ${INSTALL_PREFIX}/lib/`package-get-filename winuuid STATIC`
}

CONFIGURE_BUILD_ROOT=${STAGE_ROOT} \
DISABLE_AUTOUPDATE=TRUE \
PACKAGE_INSTALL_COMPLETION_CALLBACK=package-install-completion-callback \
package-stage-configure-install-archive \
    --${ENABLE_OR_DISABLE_LIBARM32}-libarm32 \
    --${ENABLE_OR_DISABLE_LIB32}-lib32 \
    --enable-experimental=registeredprintf,softmath \
    --enable-warnings=0 \
    --with-default-msvcrt=ucrt \
    --${ENABLE_OR_DISABLE_LIB64}-lib64 \
    --${ENABLE_OR_DISABLE_LIBARM64}-libarm64
